package org.fao.geonet.kernel.repository;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.fao.geonet.kernel.domain.Metadata;

/**
 * Implementation for all queries that cannot be automatically generated by Spring-data.
 * 
 * @author Jesse
 */
public class MetadataRepositoryImpl implements MetadataRepositoryCustom {

    @PersistenceContext
    EntityManager entityManager;

    @Override
    public Metadata findByIdString(String id) {
        try {
            return entityManager.find(Metadata.class, Integer.parseInt(id));
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("id parameter of findByIdString must be parsable to an integer.  It was '" + id + "'");
        }
    }

}
