package org.fao.geonet.datahub;

import org.springframework.core.io.ClassPathResource;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;

// Generated by ChatGPT & Claude3.7
public class FileUtils {
    private static final Path DATAHUB_TEMP_DIR;
    private static final Path METADATA_EDITOR_TEMP_DIR;

    static {
        try {
            DATAHUB_TEMP_DIR = Files.createTempDirectory("datahub_cache");
            METADATA_EDITOR_TEMP_DIR = Files.createTempDirectory("metadata_editor_cache");

            DATAHUB_TEMP_DIR.toFile().deleteOnExit();
            METADATA_EDITOR_TEMP_DIR.toFile().deleteOnExit();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public static boolean fileExistsInJar(String relativePath) {
        ClassPathResource resource = new ClassPathResource(relativePath);
        return resource.isReadable();
    }

    public static File getFileFromJar(String relativePath) throws IOException {
        Path tempDir;
        
        if (relativePath.startsWith("/datahub/") || relativePath.startsWith("datahub/")) {
            tempDir = DATAHUB_TEMP_DIR;
        } else if (relativePath.startsWith("/metadata-editor/") || relativePath.startsWith("metadata-editor/")) {
            tempDir = METADATA_EDITOR_TEMP_DIR;
        } else {
            tempDir = DATAHUB_TEMP_DIR;
        }
        
        File tempFile = new File(tempDir.toFile(), new File(relativePath).getName());
        if (tempFile.exists()) {
            return tempFile;
        }

        if (!FileUtils.fileExistsInJar(relativePath)) {
            throw new IOException("File not found: " + relativePath);
        }

        ClassPathResource resource = new ClassPathResource(relativePath);

        // Copy resource contents to temp file
        try (InputStream inputStream = resource.getInputStream();
             FileOutputStream outputStream = new FileOutputStream(tempFile)) {
            inputStream.transferTo(outputStream);
        }

        tempFile.deleteOnExit(); // Mark for deletion on JVM exit
        return tempFile;
    }

    public static String readFromInputStream(InputStream inputStream)
            throws IOException {
        StringBuilder resultStringBuilder = new StringBuilder();
        try (BufferedReader br
                     = new BufferedReader(new InputStreamReader(inputStream))) {
            String line;
            while ((line = br.readLine()) != null) {
                resultStringBuilder.append(line).append("\n");
            }
        }
        return resultStringBuilder.toString();
    }
}
