package org.fao.geonet.datahub;

import org.springframework.core.io.ClassPathResource;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;

// Generated by ChatGPT
public class FileUtils {
    private static final Path TEMP_DIR;

    static {
        try {
            TEMP_DIR = Files.createTempDirectory("plugin_cache");
            TEMP_DIR.toFile().deleteOnExit(); // Ensure temp directory is cleaned up
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public static boolean fileExistsInJar(String relativePath) {
        ClassPathResource resource = new ClassPathResource(relativePath);
        return resource.isReadable();
    }

    public static File getFileFromJar(String relativePath) throws IOException {
        File tempFile = new File(TEMP_DIR.toFile(), new File(relativePath).getName());
        if (tempFile.exists()) {
            return tempFile;
        }

        if (!FileUtils.fileExistsInJar(relativePath)) {
            throw new IOException("File not found: " + relativePath);
        }

        ClassPathResource resource = new ClassPathResource(relativePath);

        // Copy resource contents to temp file
        try (InputStream inputStream = resource.getInputStream();
             FileOutputStream outputStream = new FileOutputStream(tempFile)) {
            inputStream.transferTo(outputStream);
        }

        tempFile.deleteOnExit(); // Mark for deletion on JVM exit
        return tempFile;
    }

    public static String readFromInputStream(InputStream inputStream)
        throws IOException {
        StringBuilder resultStringBuilder = new StringBuilder();
        try (BufferedReader br
                 = new BufferedReader(new InputStreamReader(inputStream))) {
            String line;
            while ((line = br.readLine()) != null) {
                resultStringBuilder.append(line).append("\n");
            }
        }
        return resultStringBuilder.toString();
    }
}
