// This file was autogenerated by ../../../../../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../components/dv/GaugeDirective.js', ['gn_gauge_directive'], []);
goog.addDependency('../../components/dv/GaugeModule.js', ['gn_gauge'], ['gn_gauge_directive']);
goog.addDependency('../../components/translation/TranslationDirective.js', ['gn_translation_directive'], []);
goog.addDependency('../../components/translation/TranslationModule.js', ['gn_translation'], ['gn_translation_directive']);
goog.addDependency('../../js/AdminController.js', ['gn_admin_controller'], ['gn_cat_controller', 'gn_dashboard_controller', 'gn_usergroup_controller']);
goog.addDependency('../../js/CatController.js', ['gn_cat_controller'], []);
goog.addDependency('../../js/DashboardContentStatController.js', ['gn_dashboard_content_stat_controller'], []);
goog.addDependency('../../js/DashboardController.js', ['gn_dashboard_controller'], ['gn_dashboard_content_stat_controller', 'gn_dashboard_search_stat_controller', 'gn_dashboard_status_controller']);
goog.addDependency('../../js/DashboardSearchStatController.js', ['gn_dashboard_search_stat_controller'], []);
goog.addDependency('../../js/DashboardStatusController.js', ['gn_dashboard_status_controller'], ['gn_gauge']);
goog.addDependency('../../js/GnAdminModule.js', ['gn_admin'], ['gn', 'gn_admin_controller', 'gn_cat_controller', 'gn_dashboard_controller', 'gn_translation', 'gn_translation_controller']);
goog.addDependency('../../js/GnLoginModule.js', ['gn_login'], ['gn_cat_controller', 'gn_login_controller', 'gn_translation', 'gn_translation_controller']);
goog.addDependency('../../js/GnModule.js', ['gn'], ['gn_cat_controller', 'gn_translation', 'gn_translation_controller']);
goog.addDependency('../../js/LoginController.js', ['gn_login_controller'], []);
goog.addDependency('../../js/TranslationController.js', ['gn_translation_controller'], []);
goog.addDependency('../../js/UserGroupController.js', ['gn_usergroup_controller'], []);
