package org.fao.geonet.bean.statistic;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import org.fao.geonet.domain.ISODate;

/**
 * An entity representing a search request that was made by a user. This is part
 * of the statistics tracing.
 * <p/>
 * <p>
 * When creating a SearchRequest and its parameters all the parameters and the
 * search request must be saved individually because a limitation of JPA means
 * that SearchRequest can't cascade operations from SearchRequest to the params.
 * </p>
 * 
 * @author Jesse
 */
public class SearchRequest implements Serializable {
	private static final long serialVersionUID = -1294836123657513520L;
	private int _id;
	private ISODate _requestDate;
	private String _ipAddress;
	private String _luceneQuery;
	private int _hits;
	private String _lang;
	private String _sortBy;
	private String _spatialFilter;
	private String _metadataType;
	private boolean _simple;
	private boolean _autogenerated;
	private String _service;
	private List<SearchRequestParam> _params = new ArrayList<SearchRequestParam>();

	public int get_id() {
		return _id;
	}

	public void set_id(int _id) {
		this._id = _id;
	}

	public ISODate get_requestDate() {
		return _requestDate;
	}

	public void set_requestDate(ISODate _requestDate) {
		this._requestDate = _requestDate;
	}

	public String get_ipAddress() {
		return _ipAddress;
	}

	public void set_ipAddress(String _ipAddress) {
		this._ipAddress = _ipAddress;
	}

	public String get_luceneQuery() {
		return _luceneQuery;
	}

	public void set_luceneQuery(String _luceneQuery) {
		this._luceneQuery = _luceneQuery;
	}

	public int get_hits() {
		return _hits;
	}

	public void set_hits(int _hits) {
		this._hits = _hits;
	}

	public String get_lang() {
		return _lang;
	}

	public void set_lang(String _lang) {
		this._lang = _lang;
	}

	public String get_sortBy() {
		return _sortBy;
	}

	public void set_sortBy(String _sortBy) {
		this._sortBy = _sortBy;
	}

	public String get_spatialFilter() {
		return _spatialFilter;
	}

	public void set_spatialFilter(String _spatialFilter) {
		this._spatialFilter = _spatialFilter;
	}

	public String get_metadataType() {
		return _metadataType;
	}

	public void set_metadataType(String _metadataType) {
		this._metadataType = _metadataType;
	}

	public boolean is_simple() {
		return _simple;
	}

	public void set_simple(boolean _simple) {
		this._simple = _simple;
	}

	public boolean is_autogenerated() {
		return _autogenerated;
	}

	public void set_autogenerated(boolean _autogenerated) {
		this._autogenerated = _autogenerated;
	}

	public String get_service() {
		return _service;
	}

	public void set_service(String _service) {
		this._service = _service;
	}

	public List<SearchRequestParam> get_params() {
		return _params;
	}

	public void set_params(List<SearchRequestParam> _params) {
		this._params = _params;
	}

}
