# These are supported funding model platforms

github: [osgeo]
custom: ['https://github.com/geonetwork/core-geonetwork/wiki','https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=LDTWEL3XKUVU8&source=url']
