-- 2.6.4 changes
CREATE TABLE CustomElementSet
  (
    xpath  varchar(1000) not null
  );

UPDATE Languages SET isocode = 'spa' where id ='es';

ALTER TABLE Languages ADD isInspire char(1);
ALTER TABLE Languages ADD isDefault char(1);

UPDATE Languages SET isInspire = 'y', isDefault = 'y' where id ='en';
UPDATE Languages SET isInspire = 'y', isDefault = 'n' where id ='fr';
UPDATE Languages SET isInspire = 'y', isDefault = 'n' where id ='es';
UPDATE Languages SET isInspire = 'n', isDefault = 'n' where id ='ru';
UPDATE Languages SET isInspire = 'n', isDefault = 'n' where id ='cn';
UPDATE Languages SET isInspire = 'y', isDefault = 'n' where id ='de';
UPDATE Languages SET isInspire = 'y', isDefault = 'n' where id ='nl';
UPDATE Languages SET isInspire = 'y', isDefault = 'n' where id ='pt';
UPDATE Languages SET isInspire = 'n', isDefault = 'n' where id ='ca';
UPDATE Languages SET isInspire = 'n', isDefault = 'n' where id ='tr';

-- 2.6.5 changes

INSERT INTO Settings VALUES (23,20,'protocol','http');

INSERT INTO Settings VALUES (88,80,'defaultGroup', NULL);
INSERT INTO Settings VALUES (113,87,'group',NULL);
INSERT INTO Settings VALUES (178,173,'group',NULL);
INSERT INTO Settings VALUES (179,170,'defaultGroup', NULL);

INSERT INTO Languages VALUES ('fi','Finnish', 'fin', 'y', 'n');

INSERT INTO CswServerCapabilitiesInfo VALUES (41, 'fi', 'title', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (42, 'fi', 'abstract', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (43, 'fi', 'fees', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (44, 'fi', 'accessConstraints', '');

INSERT INTO CategoriesDes VALUES (1,'fi','Kartat & kuvat');
INSERT INTO CategoriesDes VALUES (2,'fi','Tietoaineistot');
INSERT INTO CategoriesDes VALUES (3,'fi','Vuorovaikutteiset resurssit');
INSERT INTO CategoriesDes VALUES (4,'fi','Sovellukset');
INSERT INTO CategoriesDes VALUES (5,'fi','Esimerkkitapaukset, parhaat käytännöt');
INSERT INTO CategoriesDes VALUES (6,'fi','Konferenssijulkaisut');
INSERT INTO CategoriesDes VALUES (7,'fi','Valokuvat');
INSERT INTO CategoriesDes VALUES (8,'fi','Äänitteet / Videot');
INSERT INTO CategoriesDes VALUES (9,'fi','Hakemistot');
INSERT INTO CategoriesDes VALUES (10,'fi','Other information resources');

INSERT INTO GroupsDes VALUES (-1,'fi','Vierailija');
INSERT INTO GroupsDes VALUES (0,'fi','Intranet');
INSERT INTO GroupsDes VALUES (1,'fi','Kaikki');
INSERT INTO GroupsDes VALUES (2,'fi','Ryhmä');

INSERT INTO Settings VALUES (722,720,'enableSearchPanel','false');

INSERT INTO Settings VALUES (910,1,'metadata',NULL);
INSERT INTO Settings VALUES (911,910,'enableSimpleView','true');
INSERT INTO Settings VALUES (912,910,'enableIsoView','true');
INSERT INTO Settings VALUES (913,910,'enableInspireView','false');
INSERT INTO Settings VALUES (914,910,'enableXmlView','true');
INSERT INTO Settings VALUES (915,910,'defaultView','simple');

UPDATE Settings SET value='2.6.5' WHERE name='version';
UPDATE Settings SET value='0' WHERE name='subVersion';

-- 2.6.5 changes - Adding Italian localization

INSERT INTO Languages VALUES ('it','Italiano', 'ita', 'y', 'n');

INSERT INTO CswServerCapabilitiesInfo VALUES (45, 'it', 'title', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (46, 'it', 'abstract', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (47, 'it', 'fees', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (48, 'it', 'accessConstraints', '');

INSERT INTO CategoriesDes VALUES (1,'it','Mappe e grafici');
INSERT INTO CategoriesDes VALUES (2,'it','Datasets');
INSERT INTO CategoriesDes VALUES (3,'it','Risorse interattive');
INSERT INTO CategoriesDes VALUES (4,'it','Applicazioni');
INSERT INTO CategoriesDes VALUES (5,'it','Casi di studio');
INSERT INTO CategoriesDes VALUES (6,'it','Atti di conferenze');
INSERT INTO CategoriesDes VALUES (7,'it','Fotografie');
INSERT INTO CategoriesDes VALUES (8,'it','Audio/Video');
INSERT INTO CategoriesDes VALUES (9,'it','Archivi');
INSERT INTO CategoriesDes VALUES (10,'it','Altre risorse di informazione');

INSERT INTO GroupsDes VALUES (-1,'it','Visitatore');
INSERT INTO GroupsDes VALUES (0,'it','Intranet');
INSERT INTO GroupsDes VALUES (1,'it','Tutti');
INSERT INTO GroupsDes VALUES (2,'it','Gruppo di esempio');

INSERT INTO IsoLanguagesDes VALUES (1,'it','Afar');
INSERT INTO IsoLanguagesDes VALUES (2,'it','Abkhazian');
INSERT INTO IsoLanguagesDes VALUES (3,'it','Achinese');
INSERT INTO IsoLanguagesDes VALUES (4,'it','Acioli');
INSERT INTO IsoLanguagesDes VALUES (5,'it','Adangme');
INSERT INTO IsoLanguagesDes VALUES (6,'it','Adyghe; Adygei');
INSERT INTO IsoLanguagesDes VALUES (7,'it','Afro-asiatiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (8,'it','Afrihili');
INSERT INTO IsoLanguagesDes VALUES (9,'it','Afrikaans');
INSERT INTO IsoLanguagesDes VALUES (10,'it','Ainu');
INSERT INTO IsoLanguagesDes VALUES (11,'it','Akan');
INSERT INTO IsoLanguagesDes VALUES (12,'it','Accadiano');
INSERT INTO IsoLanguagesDes VALUES (13,'it','Albanese');
INSERT INTO IsoLanguagesDes VALUES (14,'it','Aleut');
INSERT INTO IsoLanguagesDes VALUES (15,'it','Algonchine, Lingue');
INSERT INTO IsoLanguagesDes VALUES (16,'it','Altai del Sud');
INSERT INTO IsoLanguagesDes VALUES (17,'it','Amarico');
INSERT INTO IsoLanguagesDes VALUES (18,'it','Inglese antico (ca.450-1100)');
INSERT INTO IsoLanguagesDes VALUES (19,'it','Angika');
INSERT INTO IsoLanguagesDes VALUES (20,'it','Apache, Lingue');
INSERT INTO IsoLanguagesDes VALUES (21,'it','Arabo');
INSERT INTO IsoLanguagesDes VALUES (22,'it','Aramaico ufficiale (700-300 AC); Aramaico Imperiale (700-300 AC)');
INSERT INTO IsoLanguagesDes VALUES (23,'it','Aragonese');
INSERT INTO IsoLanguagesDes VALUES (24,'it','Armeno');
INSERT INTO IsoLanguagesDes VALUES (25,'it','Mapudungun; Mapuche');
INSERT INTO IsoLanguagesDes VALUES (26,'it','Arapaho');
INSERT INTO IsoLanguagesDes VALUES (27,'it','Lingue artificiali');
INSERT INTO IsoLanguagesDes VALUES (28,'it','Arawak');
INSERT INTO IsoLanguagesDes VALUES (29,'it','Assamese');
INSERT INTO IsoLanguagesDes VALUES (30,'it','Asturiano; Bable; Leonese; Asturiano-Leonese');
INSERT INTO IsoLanguagesDes VALUES (31,'it','Lingue Athapascan');
INSERT INTO IsoLanguagesDes VALUES (32,'it','Australi, Lingue');
INSERT INTO IsoLanguagesDes VALUES (33,'it','Avarico');
INSERT INTO IsoLanguagesDes VALUES (34,'it','Avestan');
INSERT INTO IsoLanguagesDes VALUES (35,'it','Awadhi');
INSERT INTO IsoLanguagesDes VALUES (36,'it','Aymara');
INSERT INTO IsoLanguagesDes VALUES (37,'it','Azero');
INSERT INTO IsoLanguagesDes VALUES (38,'it','Lingue Banda');
INSERT INTO IsoLanguagesDes VALUES (39,'it','Lingue Bamileke');
INSERT INTO IsoLanguagesDes VALUES (40,'it','Baschiro');
INSERT INTO IsoLanguagesDes VALUES (41,'it','Beluci');
INSERT INTO IsoLanguagesDes VALUES (42,'it','Bambara');
INSERT INTO IsoLanguagesDes VALUES (43,'it','Balinese');
INSERT INTO IsoLanguagesDes VALUES (44,'it','Basco');
INSERT INTO IsoLanguagesDes VALUES (45,'it','Basa');
INSERT INTO IsoLanguagesDes VALUES (46,'it','Baltiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (47,'it','Beja');
INSERT INTO IsoLanguagesDes VALUES (48,'it','Bielorusso');
INSERT INTO IsoLanguagesDes VALUES (49,'it','Bemba');
INSERT INTO IsoLanguagesDes VALUES (50,'it','Bengalese');
INSERT INTO IsoLanguagesDes VALUES (51,'it','Berbere, Lingue');
INSERT INTO IsoLanguagesDes VALUES (52,'it','Bhojpuri');
INSERT INTO IsoLanguagesDes VALUES (53,'it','Lingue bihari');
INSERT INTO IsoLanguagesDes VALUES (54,'it','Bikol');
INSERT INTO IsoLanguagesDes VALUES (55,'it','Bini; Edo');
INSERT INTO IsoLanguagesDes VALUES (56,'it','Bislama');
INSERT INTO IsoLanguagesDes VALUES (57,'it','Siksika');
INSERT INTO IsoLanguagesDes VALUES (58,'it','Lingue bantu');
INSERT INTO IsoLanguagesDes VALUES (59,'it','Bosniaco');
INSERT INTO IsoLanguagesDes VALUES (60,'it','Braj');
INSERT INTO IsoLanguagesDes VALUES (61,'it','Bretone');
INSERT INTO IsoLanguagesDes VALUES (62,'it','Lingue Batak');
INSERT INTO IsoLanguagesDes VALUES (63,'it','Buriat');
INSERT INTO IsoLanguagesDes VALUES (64,'it','Buginese');
INSERT INTO IsoLanguagesDes VALUES (65,'it','Bulgaro');
INSERT INTO IsoLanguagesDes VALUES (66,'it','Burmese');
INSERT INTO IsoLanguagesDes VALUES (67,'it','Blin; Bilin');
INSERT INTO IsoLanguagesDes VALUES (68,'it','Caddo');
INSERT INTO IsoLanguagesDes VALUES (69,'it','Lingue indiane dell''America Centrale');
INSERT INTO IsoLanguagesDes VALUES (70,'it','Galibi Carib');
INSERT INTO IsoLanguagesDes VALUES (71,'it','Catalano; Valenciano');
INSERT INTO IsoLanguagesDes VALUES (72,'it','Caucasiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (73,'it','Cebuano');
INSERT INTO IsoLanguagesDes VALUES (74,'it','Celtiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (75,'it','Chamorro');
INSERT INTO IsoLanguagesDes VALUES (76,'it','Chibcha');
INSERT INTO IsoLanguagesDes VALUES (77,'it','Ceceno');
INSERT INTO IsoLanguagesDes VALUES (78,'it','Ciagataica');
INSERT INTO IsoLanguagesDes VALUES (79,'it','Cinese (altro)');
INSERT INTO IsoLanguagesDes VALUES (80,'it','Chuukese');
INSERT INTO IsoLanguagesDes VALUES (81,'it','Mari');
INSERT INTO IsoLanguagesDes VALUES (82,'it','Gergo Chinook');
INSERT INTO IsoLanguagesDes VALUES (83,'it','Choctaw');
INSERT INTO IsoLanguagesDes VALUES (84,'it','Chipewyan');
INSERT INTO IsoLanguagesDes VALUES (85,'it','Cherokee');
INSERT INTO IsoLanguagesDes VALUES (86,'it','Slavo antico; Slavonico ecclesiastico; Bulgaro antico; Slavonico ecclesiastico antico');
INSERT INTO IsoLanguagesDes VALUES (87,'it','Chuvash');
INSERT INTO IsoLanguagesDes VALUES (88,'it','Cheyenne');
INSERT INTO IsoLanguagesDes VALUES (89,'it','Lingue chamic');
INSERT INTO IsoLanguagesDes VALUES (90,'it','Copto');
INSERT INTO IsoLanguagesDes VALUES (91,'it','Cornish');
INSERT INTO IsoLanguagesDes VALUES (92,'it','Corso');
INSERT INTO IsoLanguagesDes VALUES (93,'it','Creolo e pidgin, basate sull''inglese');
INSERT INTO IsoLanguagesDes VALUES (94,'it','Creolo e pidgin, basate sul francese');
INSERT INTO IsoLanguagesDes VALUES (95,'it','Creolo e pidgin, basate sul portoghese');
INSERT INTO IsoLanguagesDes VALUES (96,'it','Cree');
INSERT INTO IsoLanguagesDes VALUES (97,'it','Tatar crimeo; Turco crimeo');
INSERT INTO IsoLanguagesDes VALUES (98,'it','Creolo e pidgin');
INSERT INTO IsoLanguagesDes VALUES (99,'it','Kashubian');
INSERT INTO IsoLanguagesDes VALUES (100,'it','Cuscitiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (101,'it','Ceco');
INSERT INTO IsoLanguagesDes VALUES (102,'it','Dakota');
INSERT INTO IsoLanguagesDes VALUES (103,'it','Danese');
INSERT INTO IsoLanguagesDes VALUES (104,'it','Dargwa');
INSERT INTO IsoLanguagesDes VALUES (105,'it','Dayak, Lingue della terra di');
INSERT INTO IsoLanguagesDes VALUES (106,'it','Delaware');
INSERT INTO IsoLanguagesDes VALUES (107,'it','Slave (Athapascano)');
INSERT INTO IsoLanguagesDes VALUES (108,'it','Dogrib');
INSERT INTO IsoLanguagesDes VALUES (109,'it','Dinca');
INSERT INTO IsoLanguagesDes VALUES (110,'it','Divehi; Dhivehi; Maldiviano');
INSERT INTO IsoLanguagesDes VALUES (111,'it','Dogri');
INSERT INTO IsoLanguagesDes VALUES (112,'it','Lingue dravidiane');
INSERT INTO IsoLanguagesDes VALUES (113,'it','Sorabo inferiore');
INSERT INTO IsoLanguagesDes VALUES (114,'it','Duala');
INSERT INTO IsoLanguagesDes VALUES (115,'it','Olandese medio (ca.1050-1350)');
INSERT INTO IsoLanguagesDes VALUES (116,'it','Olandese; Fiammingo');
INSERT INTO IsoLanguagesDes VALUES (117,'it','Diula');
INSERT INTO IsoLanguagesDes VALUES (118,'it','Dzongkha');
INSERT INTO IsoLanguagesDes VALUES (119,'it','Efik');
INSERT INTO IsoLanguagesDes VALUES (120,'it','Egiziano (Antico)');
INSERT INTO IsoLanguagesDes VALUES (121,'it','Ekajuk');
INSERT INTO IsoLanguagesDes VALUES (122,'it','Elamitico');
INSERT INTO IsoLanguagesDes VALUES (123,'it','Inglese');
INSERT INTO IsoLanguagesDes VALUES (124,'it','Inglese medio (1100-1500)');
INSERT INTO IsoLanguagesDes VALUES (125,'it','Esperanto');
INSERT INTO IsoLanguagesDes VALUES (126,'it','Estone');
INSERT INTO IsoLanguagesDes VALUES (127,'it','Ewe');
INSERT INTO IsoLanguagesDes VALUES (128,'it','Ewondo');
INSERT INTO IsoLanguagesDes VALUES (129,'it','Fang');
INSERT INTO IsoLanguagesDes VALUES (130,'it','Faroese');
INSERT INTO IsoLanguagesDes VALUES (131,'it','Fanti');
INSERT INTO IsoLanguagesDes VALUES (132,'it','Figiano');
INSERT INTO IsoLanguagesDes VALUES (133,'it','Filippino');
INSERT INTO IsoLanguagesDes VALUES (134,'it','Finlandese');
INSERT INTO IsoLanguagesDes VALUES (135,'it','Finno-Ugriano, Lingue');
INSERT INTO IsoLanguagesDes VALUES (136,'it','Fon');
INSERT INTO IsoLanguagesDes VALUES (137,'it','Francese');
INSERT INTO IsoLanguagesDes VALUES (138,'it','Francese medio (ca.1400-1600)');
INSERT INTO IsoLanguagesDes VALUES (139,'it','Francese antico (842-ca.1400)');
INSERT INTO IsoLanguagesDes VALUES (140,'it','Frisone del Nord');
INSERT INTO IsoLanguagesDes VALUES (141,'it','Frisone orientale');
INSERT INTO IsoLanguagesDes VALUES (142,'it','Frisone occidentale');
INSERT INTO IsoLanguagesDes VALUES (143,'it','Fulah');
INSERT INTO IsoLanguagesDes VALUES (144,'it','Friulano');
INSERT INTO IsoLanguagesDes VALUES (145,'it','Ga');
INSERT INTO IsoLanguagesDes VALUES (146,'it','Gayo');
INSERT INTO IsoLanguagesDes VALUES (147,'it','Gbaya');
INSERT INTO IsoLanguagesDes VALUES (148,'it','Germaniche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (149,'it','Georgiano');
INSERT INTO IsoLanguagesDes VALUES (150,'it','Tedesco');
INSERT INTO IsoLanguagesDes VALUES (151,'it','Geez');
INSERT INTO IsoLanguagesDes VALUES (152,'it','Gilbertese');
INSERT INTO IsoLanguagesDes VALUES (153,'it','Gaelico; Gaelico Scozzese');
INSERT INTO IsoLanguagesDes VALUES (154,'it','Irlandese');
INSERT INTO IsoLanguagesDes VALUES (155,'it','Galiziano');
INSERT INTO IsoLanguagesDes VALUES (156,'it','Manx');
INSERT INTO IsoLanguagesDes VALUES (157,'it','Tedesco medio alto (ca. 1050-1500');
INSERT INTO IsoLanguagesDes VALUES (158,'it','Tedesco antico alto (ca. 750-1050)');
INSERT INTO IsoLanguagesDes VALUES (159,'it','Gondi');
INSERT INTO IsoLanguagesDes VALUES (160,'it','Gorontalo');
INSERT INTO IsoLanguagesDes VALUES (161,'it','Gothico, Lingua associata)');
INSERT INTO IsoLanguagesDes VALUES (162,'it','Grebo');
INSERT INTO IsoLanguagesDes VALUES (163,'it','Greco antico (fino al 1453)');
INSERT INTO IsoLanguagesDes VALUES (164,'it','Greco moderno (1453-)');
INSERT INTO IsoLanguagesDes VALUES (165,'it','Guarani');
INSERT INTO IsoLanguagesDes VALUES (166,'it','Svizzero tedesco; Alemanno; Alsaziano');
INSERT INTO IsoLanguagesDes VALUES (167,'it','Gujarati');
INSERT INTO IsoLanguagesDes VALUES (168,'it','Gwich''in');
INSERT INTO IsoLanguagesDes VALUES (169,'it','Haida');
INSERT INTO IsoLanguagesDes VALUES (170,'it','Haitiano; Haitiano Creolo');
INSERT INTO IsoLanguagesDes VALUES (171,'it','Hausa');
INSERT INTO IsoLanguagesDes VALUES (172,'it','Hawaiano');
INSERT INTO IsoLanguagesDes VALUES (173,'it','Ebraico');
INSERT INTO IsoLanguagesDes VALUES (174,'it','Herero');
INSERT INTO IsoLanguagesDes VALUES (175,'it','Himachali; Pahari occidentali, Lingue');
INSERT INTO IsoLanguagesDes VALUES (176,'it','Himachali');
INSERT INTO IsoLanguagesDes VALUES (177,'it','Hindi');
INSERT INTO IsoLanguagesDes VALUES (178,'it','Ittita');
INSERT INTO IsoLanguagesDes VALUES (179,'it','Hmong');
INSERT INTO IsoLanguagesDes VALUES (180,'it','Hiri Motu');
INSERT INTO IsoLanguagesDes VALUES (181,'it','Sorabo superiore');
INSERT INTO IsoLanguagesDes VALUES (182,'it','Ungherese');
INSERT INTO IsoLanguagesDes VALUES (183,'it','Hupa');
INSERT INTO IsoLanguagesDes VALUES (184,'it','Iban');
INSERT INTO IsoLanguagesDes VALUES (185,'it','Igbo');
INSERT INTO IsoLanguagesDes VALUES (186,'it','Islandese');
INSERT INTO IsoLanguagesDes VALUES (187,'it','Ido');
INSERT INTO IsoLanguagesDes VALUES (188,'it','Sichuan Yi');
INSERT INTO IsoLanguagesDes VALUES (189,'it','Ijo, lingua');
INSERT INTO IsoLanguagesDes VALUES (190,'it','Eschimese');
INSERT INTO IsoLanguagesDes VALUES (191,'it','Interlingue; Occidentale');
INSERT INTO IsoLanguagesDes VALUES (192,'it','Iloko');
INSERT INTO IsoLanguagesDes VALUES (193,'it','Interlingua (International Auxiliary Language Association)');
INSERT INTO IsoLanguagesDes VALUES (194,'it','Indic, Lingua');
INSERT INTO IsoLanguagesDes VALUES (195,'it','Indonesiano');
INSERT INTO IsoLanguagesDes VALUES (196,'it','Indo-Europee, Lingue');
INSERT INTO IsoLanguagesDes VALUES (197,'it','Ingush');
INSERT INTO IsoLanguagesDes VALUES (198,'it','Inupiaq');
INSERT INTO IsoLanguagesDes VALUES (199,'it','Iraniano, Lingue');
INSERT INTO IsoLanguagesDes VALUES (200,'it','Irochesi, Lingue');
INSERT INTO IsoLanguagesDes VALUES (201,'it','Italiano');
INSERT INTO IsoLanguagesDes VALUES (202,'it','Javanese');
INSERT INTO IsoLanguagesDes VALUES (203,'it','Lojban');
INSERT INTO IsoLanguagesDes VALUES (204,'it','Giapponese');
INSERT INTO IsoLanguagesDes VALUES (205,'it','Giudeo-Persiano');
INSERT INTO IsoLanguagesDes VALUES (206,'it','Giudeo-Arabo');
INSERT INTO IsoLanguagesDes VALUES (207,'it','Kara-Kalpak');
INSERT INTO IsoLanguagesDes VALUES (208,'it','Kabyle');
INSERT INTO IsoLanguagesDes VALUES (209,'it','Kachin; Jingpho');
INSERT INTO IsoLanguagesDes VALUES (210,'it','Kalaallisut; Groenlandese');
INSERT INTO IsoLanguagesDes VALUES (211,'it','Kamba');
INSERT INTO IsoLanguagesDes VALUES (212,'it','Kannada');
INSERT INTO IsoLanguagesDes VALUES (213,'it','Karen, Lingue');
INSERT INTO IsoLanguagesDes VALUES (214,'it','Kashmiri');
INSERT INTO IsoLanguagesDes VALUES (215,'it','Kanuri');
INSERT INTO IsoLanguagesDes VALUES (216,'it','Kawi');
INSERT INTO IsoLanguagesDes VALUES (217,'it','Kazako');
INSERT INTO IsoLanguagesDes VALUES (218,'it','Kabardian');
INSERT INTO IsoLanguagesDes VALUES (219,'it','Khasi');
INSERT INTO IsoLanguagesDes VALUES (220,'it','Khoisan, lingue');
INSERT INTO IsoLanguagesDes VALUES (221,'it','Khmer Centrale');
INSERT INTO IsoLanguagesDes VALUES (222,'it','Khotanese');
INSERT INTO IsoLanguagesDes VALUES (223,'it','Kikuyu; Gikuyu');
INSERT INTO IsoLanguagesDes VALUES (224,'it','Kinyarwanda');
INSERT INTO IsoLanguagesDes VALUES (225,'it','Kirghizo; Chirghiso');
INSERT INTO IsoLanguagesDes VALUES (226,'it','Kimbundu');
INSERT INTO IsoLanguagesDes VALUES (227,'it','Konkani');
INSERT INTO IsoLanguagesDes VALUES (228,'it','Komi');
INSERT INTO IsoLanguagesDes VALUES (229,'it','Kongo');
INSERT INTO IsoLanguagesDes VALUES (230,'it','Coreano');
INSERT INTO IsoLanguagesDes VALUES (231,'it','Kosraean');
INSERT INTO IsoLanguagesDes VALUES (232,'it','Kpelle');
INSERT INTO IsoLanguagesDes VALUES (233,'it','Karachay-Balkar');
INSERT INTO IsoLanguagesDes VALUES (234,'it','Karelian');
INSERT INTO IsoLanguagesDes VALUES (235,'it','Kru, Lingue');
INSERT INTO IsoLanguagesDes VALUES (236,'it','Kurukh');
INSERT INTO IsoLanguagesDes VALUES (237,'it','Kuanyama; Kwanyama');
INSERT INTO IsoLanguagesDes VALUES (238,'it','Kumyk');
INSERT INTO IsoLanguagesDes VALUES (239,'it','Curdo');
INSERT INTO IsoLanguagesDes VALUES (240,'it','Kutenai');
INSERT INTO IsoLanguagesDes VALUES (241,'it','Ladino');
INSERT INTO IsoLanguagesDes VALUES (242,'it','Lahnda');
INSERT INTO IsoLanguagesDes VALUES (243,'it','Lamba');
INSERT INTO IsoLanguagesDes VALUES (244,'it','Lao');
INSERT INTO IsoLanguagesDes VALUES (245,'it','Latino');
INSERT INTO IsoLanguagesDes VALUES (246,'it','Lettone');
INSERT INTO IsoLanguagesDes VALUES (247,'it','Lezghian');
INSERT INTO IsoLanguagesDes VALUES (248,'it','Limburgan; Limburger; Limburgish');
INSERT INTO IsoLanguagesDes VALUES (249,'it','Lingala');
INSERT INTO IsoLanguagesDes VALUES (250,'it','Lituano');
INSERT INTO IsoLanguagesDes VALUES (251,'it','Mongo');
INSERT INTO IsoLanguagesDes VALUES (252,'it','Lozi');
INSERT INTO IsoLanguagesDes VALUES (253,'it','Lussemburghese');
INSERT INTO IsoLanguagesDes VALUES (254,'it','Luba-Lulua');
INSERT INTO IsoLanguagesDes VALUES (255,'it','Luba-Katangaxon, Low');
INSERT INTO IsoLanguagesDes VALUES (256,'it','Ganda');
INSERT INTO IsoLanguagesDes VALUES (257,'it','Luiseno');
INSERT INTO IsoLanguagesDes VALUES (258,'it','Lunda');
INSERT INTO IsoLanguagesDes VALUES (259,'it','Luo (Kenya e Tanzania)');
INSERT INTO IsoLanguagesDes VALUES (260,'it','Lushai');
INSERT INTO IsoLanguagesDes VALUES (261,'it','Macedone');
INSERT INTO IsoLanguagesDes VALUES (262,'it','Madurese');
INSERT INTO IsoLanguagesDes VALUES (263,'it','Magahi');
INSERT INTO IsoLanguagesDes VALUES (264,'it','Marshallese');
INSERT INTO IsoLanguagesDes VALUES (265,'it','Maithili');
INSERT INTO IsoLanguagesDes VALUES (266,'it','Makasarl Nepal Bhasa');
INSERT INTO IsoLanguagesDes VALUES (267,'it','Malayalam');
INSERT INTO IsoLanguagesDes VALUES (268,'it','Mandingo');
INSERT INTO IsoLanguagesDes VALUES (269,'it','Maori');
INSERT INTO IsoLanguagesDes VALUES (270,'it','Austronesiane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (271,'it','Marathi');
INSERT INTO IsoLanguagesDes VALUES (272,'it','Masai');
INSERT INTO IsoLanguagesDes VALUES (273,'it','Malay');
INSERT INTO IsoLanguagesDes VALUES (274,'it','Moksha');
INSERT INTO IsoLanguagesDes VALUES (275,'it','Mandar');
INSERT INTO IsoLanguagesDes VALUES (276,'it','Mende');
INSERT INTO IsoLanguagesDes VALUES (277,'it','Irlandese medio (900-1200)');
INSERT INTO IsoLanguagesDes VALUES (278,'it','Mi''kmaq; Micmac');
INSERT INTO IsoLanguagesDes VALUES (279,'it','Minangkabau');
INSERT INTO IsoLanguagesDes VALUES (280,'it','Lingue non codificate');
INSERT INTO IsoLanguagesDes VALUES (281,'it','Mon-Khmer, Lingue');
INSERT INTO IsoLanguagesDes VALUES (282,'it','Malagasy');
INSERT INTO IsoLanguagesDes VALUES (283,'it','Maltese');
INSERT INTO IsoLanguagesDes VALUES (284,'it','Manchu');
INSERT INTO IsoLanguagesDes VALUES (285,'it','Manipuri');
INSERT INTO IsoLanguagesDes VALUES (286,'it','Manobo, Lingue');
INSERT INTO IsoLanguagesDes VALUES (287,'it','Mohawk');
INSERT INTO IsoLanguagesDes VALUES (288,'it','Moldavo');
INSERT INTO IsoLanguagesDes VALUES (289,'it','Mongolo');
INSERT INTO IsoLanguagesDes VALUES (290,'it','Mossi');
INSERT INTO IsoLanguagesDes VALUES (291,'it','Multiple, Lingue');
INSERT INTO IsoLanguagesDes VALUES (292,'it','Munda, Lingue');
INSERT INTO IsoLanguagesDes VALUES (293,'it','Creek');
INSERT INTO IsoLanguagesDes VALUES (294,'it','Mirandese');
INSERT INTO IsoLanguagesDes VALUES (295,'it','Marwari');
INSERT INTO IsoLanguagesDes VALUES (296,'it','Maya, Lingue');
INSERT INTO IsoLanguagesDes VALUES (297,'it','Erzya');
INSERT INTO IsoLanguagesDes VALUES (298,'it','Nahuatl,Lingue');
INSERT INTO IsoLanguagesDes VALUES (299,'it','Nord America, Lingue (indiane)');
INSERT INTO IsoLanguagesDes VALUES (300,'it','Napoletano');
INSERT INTO IsoLanguagesDes VALUES (301,'it','Nauru');
INSERT INTO IsoLanguagesDes VALUES (302,'it','Navajo; Navaho');
INSERT INTO IsoLanguagesDes VALUES (303,'it','Ndebele del Sud');
INSERT INTO IsoLanguagesDes VALUES (304,'it','Ndebele del Nord');
INSERT INTO IsoLanguagesDes VALUES (305,'it','Ndonga');
INSERT INTO IsoLanguagesDes VALUES (306,'it','Tedesco; Basso Sassone');
INSERT INTO IsoLanguagesDes VALUES (307,'it','Nepalese');
INSERT INTO IsoLanguagesDes VALUES (308,'it','Bhasa nepalese, Newari');
INSERT INTO IsoLanguagesDes VALUES (309,'it','Nias');
INSERT INTO IsoLanguagesDes VALUES (310,'it','Niger-Kordofanian, Lingue');
INSERT INTO IsoLanguagesDes VALUES (311,'it','Niuean');
INSERT INTO IsoLanguagesDes VALUES (312,'it','Nynorsk Norvegese');
INSERT INTO IsoLanguagesDes VALUES (313,'it','Bokmål, Norwegian; Norwegian Bokmål');
INSERT INTO IsoLanguagesDes VALUES (314,'it','Nogai');
INSERT INTO IsoLanguagesDes VALUES (315,'it','Norse antico');
INSERT INTO IsoLanguagesDes VALUES (316,'it','Norvegese');
INSERT INTO IsoLanguagesDes VALUES (317,'it','Pedi; Sepedi; Northern Sotho');
INSERT INTO IsoLanguagesDes VALUES (318,'it','Nubiane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (319,'it','Newari calssico; Newsari antico; Nepal Bhasa classico');
INSERT INTO IsoLanguagesDes VALUES (320,'it','Chichewa; Chewa; Nyanja');
INSERT INTO IsoLanguagesDes VALUES (321,'it','Nyamwezi');
INSERT INTO IsoLanguagesDes VALUES (322,'it','Nyankole');
INSERT INTO IsoLanguagesDes VALUES (323,'it','Nyoro');
INSERT INTO IsoLanguagesDes VALUES (324,'it','Nzima');
INSERT INTO IsoLanguagesDes VALUES (325,'it','Occitano (dopo 1500); Provenzale');
INSERT INTO IsoLanguagesDes VALUES (326,'it','Ojibwa');
INSERT INTO IsoLanguagesDes VALUES (327,'it','Oriya');
INSERT INTO IsoLanguagesDes VALUES (328,'it','Oromo');
INSERT INTO IsoLanguagesDes VALUES (329,'it','Osage');
INSERT INTO IsoLanguagesDes VALUES (330,'it','Osseto');
INSERT INTO IsoLanguagesDes VALUES (331,'it','Turco Ottomano (1500-1928)');
INSERT INTO IsoLanguagesDes VALUES (332,'it','Ottomane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (333,'it','Papuane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (334,'it','Pangasinan');
INSERT INTO IsoLanguagesDes VALUES (335,'it','Pahlavi');
INSERT INTO IsoLanguagesDes VALUES (336,'it','Pampanga');
INSERT INTO IsoLanguagesDes VALUES (337,'it','Panjabi; Punjabi');
INSERT INTO IsoLanguagesDes VALUES (338,'it','Papiamento');
INSERT INTO IsoLanguagesDes VALUES (339,'it','Palau');
INSERT INTO IsoLanguagesDes VALUES (340,'it','Persiano Antico (ca.600-400 B.C.)');
INSERT INTO IsoLanguagesDes VALUES (341,'it','Persiano');
INSERT INTO IsoLanguagesDes VALUES (342,'it','Filippine, Lingue');
INSERT INTO IsoLanguagesDes VALUES (343,'it','Fenicio');
INSERT INTO IsoLanguagesDes VALUES (344,'it','Pali');
INSERT INTO IsoLanguagesDes VALUES (345,'it','Polacco');
INSERT INTO IsoLanguagesDes VALUES (346,'it','Pohnpeian');
INSERT INTO IsoLanguagesDes VALUES (347,'it','Portoghese');
INSERT INTO IsoLanguagesDes VALUES (348,'it','Prakrit, Lingue');
INSERT INTO IsoLanguagesDes VALUES (349,'it','Provenzale Antico (fino al 1500); Occitano Antico (fino al 1500)');
INSERT INTO IsoLanguagesDes VALUES (350,'it','Pasthu; Afgano');
INSERT INTO IsoLanguagesDes VALUES (351,'it','Riservato per uso locale');
INSERT INTO IsoLanguagesDes VALUES (352,'it','Quechua');
INSERT INTO IsoLanguagesDes VALUES (353,'it','Rajasthani');
INSERT INTO IsoLanguagesDes VALUES (354,'it','Rapanui');
INSERT INTO IsoLanguagesDes VALUES (355,'it','Rarotongan; Maori dell''Isola di Cook');
INSERT INTO IsoLanguagesDes VALUES (356,'it','Romanze, Lingue');
INSERT INTO IsoLanguagesDes VALUES (357,'it','Romancio');
INSERT INTO IsoLanguagesDes VALUES (358,'it','Romany');
INSERT INTO IsoLanguagesDes VALUES (359,'it','Rumeno');
INSERT INTO IsoLanguagesDes VALUES (360,'it','Rundi');
INSERT INTO IsoLanguagesDes VALUES (361,'it','Aromeno; Arumeno; Macedone-Romeno');
INSERT INTO IsoLanguagesDes VALUES (362,'it','Russo');
INSERT INTO IsoLanguagesDes VALUES (363,'it','Sandawe');
INSERT INTO IsoLanguagesDes VALUES (364,'it','Sango');
INSERT INTO IsoLanguagesDes VALUES (365,'it','Yakut');
INSERT INTO IsoLanguagesDes VALUES (366,'it','Sud America, Lingue (indiane)');
INSERT INTO IsoLanguagesDes VALUES (367,'it','Salishan, Lingue');
INSERT INTO IsoLanguagesDes VALUES (368,'it','Aramaico Samaritano');
INSERT INTO IsoLanguagesDes VALUES (369,'it','Sanscrito');
INSERT INTO IsoLanguagesDes VALUES (370,'it','Sasak');
INSERT INTO IsoLanguagesDes VALUES (371,'it','Santali');
INSERT INTO IsoLanguagesDes VALUES (372,'it','Serbo');
INSERT INTO IsoLanguagesDes VALUES (373,'it','Siciliano');
INSERT INTO IsoLanguagesDes VALUES (374,'it','Scots');
INSERT INTO IsoLanguagesDes VALUES (375,'it','Croatian');
INSERT INTO IsoLanguagesDes VALUES (376,'it','Selkup');
INSERT INTO IsoLanguagesDes VALUES (377,'it','Semitiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (378,'it','Irlandese Antico (fino al 900)');
INSERT INTO IsoLanguagesDes VALUES (379,'it','Linguaggi dei Segni');
INSERT INTO IsoLanguagesDes VALUES (380,'it','Shan');
INSERT INTO IsoLanguagesDes VALUES (381,'it','Sidamo');
INSERT INTO IsoLanguagesDes VALUES (382,'it','Sinhala; Sinhalese');
INSERT INTO IsoLanguagesDes VALUES (383,'it','Siouan, Lingue');
INSERT INTO IsoLanguagesDes VALUES (384,'it','Sino-Tibetane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (385,'it','Slave, Lingue');
INSERT INTO IsoLanguagesDes VALUES (386,'it','Slovacco');
INSERT INTO IsoLanguagesDes VALUES (387,'it','Sloveno');
INSERT INTO IsoLanguagesDes VALUES (388,'it','Sami del Sud');
INSERT INTO IsoLanguagesDes VALUES (389,'it','Sami del Nord');
INSERT INTO IsoLanguagesDes VALUES (390,'it','Sami, Lingue');
INSERT INTO IsoLanguagesDes VALUES (391,'it','Sami Lule');
INSERT INTO IsoLanguagesDes VALUES (392,'it','Sami Inari');
INSERT INTO IsoLanguagesDes VALUES (393,'it','Samoano');
INSERT INTO IsoLanguagesDes VALUES (394,'it','Sami Skolt');
INSERT INTO IsoLanguagesDes VALUES (395,'it','Shona');
INSERT INTO IsoLanguagesDes VALUES (396,'it','Sindhi');
INSERT INTO IsoLanguagesDes VALUES (397,'it','Soninke');
INSERT INTO IsoLanguagesDes VALUES (398,'it','Sogdian');
INSERT INTO IsoLanguagesDes VALUES (399,'it','Somalo');
INSERT INTO IsoLanguagesDes VALUES (400,'it','Songhai, Lingue');
INSERT INTO IsoLanguagesDes VALUES (401,'it','Sotho del Sud');
INSERT INTO IsoLanguagesDes VALUES (402,'it','Spagnolo; Castigliano');
INSERT INTO IsoLanguagesDes VALUES (403,'it','Sardo; Zazaki');
INSERT INTO IsoLanguagesDes VALUES (404,'it','Sranan Tongo');
INSERT INTO IsoLanguagesDes VALUES (405,'it','Serer');
INSERT INTO IsoLanguagesDes VALUES (406,'it','Nilo-Sahariane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (407,'it','Swati');
INSERT INTO IsoLanguagesDes VALUES (408,'it','Sukuma');
INSERT INTO IsoLanguagesDes VALUES (409,'it','Sundanese');
INSERT INTO IsoLanguagesDes VALUES (410,'it','Susu');
INSERT INTO IsoLanguagesDes VALUES (411,'it','Sumero');
INSERT INTO IsoLanguagesDes VALUES (412,'it','Swahili');
INSERT INTO IsoLanguagesDes VALUES (413,'it','Svedese');
INSERT INTO IsoLanguagesDes VALUES (414,'it','Siriano');
INSERT INTO IsoLanguagesDes VALUES (415,'it','Thaitiano');
INSERT INTO IsoLanguagesDes VALUES (416,'it','Tai, Lingue');
INSERT INTO IsoLanguagesDes VALUES (417,'it','Tamil');
INSERT INTO IsoLanguagesDes VALUES (418,'it','Tatarico');
INSERT INTO IsoLanguagesDes VALUES (419,'it','Telugu');
INSERT INTO IsoLanguagesDes VALUES (420,'it','Timnendere)');
INSERT INTO IsoLanguagesDes VALUES (421,'it','Tereno');
INSERT INTO IsoLanguagesDes VALUES (422,'it','Tetum');
INSERT INTO IsoLanguagesDes VALUES (423,'it','Tajik');
INSERT INTO IsoLanguagesDes VALUES (424,'it','Tagalog');
INSERT INTO IsoLanguagesDes VALUES (425,'it','Thailandese');
INSERT INTO IsoLanguagesDes VALUES (426,'it','Tibetano');
INSERT INTO IsoLanguagesDes VALUES (427,'it','Tigre');
INSERT INTO IsoLanguagesDes VALUES (428,'it','Tigrinya');
INSERT INTO IsoLanguagesDes VALUES (429,'it','Tiv');
INSERT INTO IsoLanguagesDes VALUES (430,'it','Tokelau');
INSERT INTO IsoLanguagesDes VALUES (431,'it','Klingon; tlhIngan-Hol');
INSERT INTO IsoLanguagesDes VALUES (432,'it','Tlingit');
INSERT INTO IsoLanguagesDes VALUES (433,'it','Tamashek');
INSERT INTO IsoLanguagesDes VALUES (434,'it','Tonga (Nyasa)');
INSERT INTO IsoLanguagesDes VALUES (435,'it','Tonga (Isole Tonga)');
INSERT INTO IsoLanguagesDes VALUES (436,'it','Tok Pisin');
INSERT INTO IsoLanguagesDes VALUES (437,'it','Tsimshian');
INSERT INTO IsoLanguagesDes VALUES (438,'it','Tswana');
INSERT INTO IsoLanguagesDes VALUES (439,'it','Tsonga');
INSERT INTO IsoLanguagesDes VALUES (440,'it','Turcmeno');
INSERT INTO IsoLanguagesDes VALUES (441,'it','Tumbuka');
INSERT INTO IsoLanguagesDes VALUES (442,'it','Tupi, Lingue');
INSERT INTO IsoLanguagesDes VALUES (443,'it','Turco');
INSERT INTO IsoLanguagesDes VALUES (444,'it','Altaiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (445,'it','Tuvalu');
INSERT INTO IsoLanguagesDes VALUES (446,'it','Twi');
INSERT INTO IsoLanguagesDes VALUES (447,'it','Tuvinian');
INSERT INTO IsoLanguagesDes VALUES (448,'it','Udmurt');
INSERT INTO IsoLanguagesDes VALUES (449,'it','Ugaritico');
INSERT INTO IsoLanguagesDes VALUES (450,'it','Uighur; Uyghur');
INSERT INTO IsoLanguagesDes VALUES (451,'it','Ucraino');
INSERT INTO IsoLanguagesDes VALUES (452,'it','Umbundu');
INSERT INTO IsoLanguagesDes VALUES (453,'it','Non determinato');
INSERT INTO IsoLanguagesDes VALUES (454,'it','Urdu');
INSERT INTO IsoLanguagesDes VALUES (455,'it','Uzbeco');
INSERT INTO IsoLanguagesDes VALUES (456,'it','Vai');
INSERT INTO IsoLanguagesDes VALUES (457,'it','Venda');
INSERT INTO IsoLanguagesDes VALUES (458,'it','Vietnamita');
INSERT INTO IsoLanguagesDes VALUES (459,'it','Volapük');
INSERT INTO IsoLanguagesDes VALUES (460,'it','Votic');
INSERT INTO IsoLanguagesDes VALUES (461,'it','Wakashan, Lingue');
INSERT INTO IsoLanguagesDes VALUES (462,'it','Walamo');
INSERT INTO IsoLanguagesDes VALUES (463,'it','Waray');
INSERT INTO IsoLanguagesDes VALUES (464,'it','Washo');
INSERT INTO IsoLanguagesDes VALUES (465,'it','Gallese');
INSERT INTO IsoLanguagesDes VALUES (466,'it','Sorabe, Lingue');
INSERT INTO IsoLanguagesDes VALUES (467,'it','Vallone');
INSERT INTO IsoLanguagesDes VALUES (468,'it','Volof');
INSERT INTO IsoLanguagesDes VALUES (469,'it','Kalmyk; Oirat');
INSERT INTO IsoLanguagesDes VALUES (470,'it','Xhosa');
INSERT INTO IsoLanguagesDes VALUES (471,'it','Yao');
INSERT INTO IsoLanguagesDes VALUES (472,'it','Yapese');
INSERT INTO IsoLanguagesDes VALUES (473,'it','Yiddish');
INSERT INTO IsoLanguagesDes VALUES (474,'it','Yoruba');
INSERT INTO IsoLanguagesDes VALUES (475,'it','Yupik, Lingue');
INSERT INTO IsoLanguagesDes VALUES (476,'it','Zapotec');
INSERT INTO IsoLanguagesDes VALUES (477,'it','Zenaga');
INSERT INTO IsoLanguagesDes VALUES (478,'it','Zhuang; Chuang');
INSERT INTO IsoLanguagesDes VALUES (479,'it','Zande, Lingue');
INSERT INTO IsoLanguagesDes VALUES (480,'it','Zulu');
INSERT INTO IsoLanguagesDes VALUES (481,'it','Zuni');
INSERT INTO IsoLanguagesDes VALUES (482,'it','Nessun contenuto linguistico; non applicabile');
INSERT INTO IsoLanguagesDes VALUES (483,'it','N''Ko');
INSERT INTO IsoLanguagesDes VALUES (484,'it','Zaza; Dimili; Dimli; Kirdki; Kirmanjki');

INSERT INTO OperationsDes VALUES (0,'it','Pubblica');
INSERT INTO OperationsDes VALUES (1,'it','Scarica');
INSERT INTO OperationsDes VALUES (2,'it','Modifica');
INSERT INTO OperationsDes VALUES (3,'it','Notifica');
INSERT INTO OperationsDes VALUES (5,'it','Mappa interattiva');
INSERT INTO OperationsDes VALUES (6,'it','In rilievo');

INSERT INTO RegionsDes VALUES (1,'it','Armenia');
INSERT INTO RegionsDes VALUES (2,'it','Afghanistan');
INSERT INTO RegionsDes VALUES (3,'it','Albania');
INSERT INTO RegionsDes VALUES (4,'it','Algeria');
INSERT INTO RegionsDes VALUES (5,'it','Samoa Americane');
INSERT INTO RegionsDes VALUES (6,'it','Andorra');
INSERT INTO RegionsDes VALUES (7,'it','Angola');
INSERT INTO RegionsDes VALUES (8,'it','Antigua e Barbuda');
INSERT INTO RegionsDes VALUES (9,'it','Argentina');
INSERT INTO RegionsDes VALUES (10,'it','Australia');
INSERT INTO RegionsDes VALUES (11,'it','Austria');
INSERT INTO RegionsDes VALUES (12,'it','Bahamas');
INSERT INTO RegionsDes VALUES (13,'it','Bahrain');
INSERT INTO RegionsDes VALUES (14,'it','Barbados');
INSERT INTO RegionsDes VALUES (16,'it','Bangladesh');
INSERT INTO RegionsDes VALUES (17,'it','Bermuda');
INSERT INTO RegionsDes VALUES (18,'it','Bhutan');
INSERT INTO RegionsDes VALUES (19,'it','Bolivia');
INSERT INTO RegionsDes VALUES (20,'it','Botswana');
INSERT INTO RegionsDes VALUES (21,'it','Brasile');
INSERT INTO RegionsDes VALUES (22,'it','Aruba');
INSERT INTO RegionsDes VALUES (23,'it','Belize');
INSERT INTO RegionsDes VALUES (24,'it','Territorio britannico dell''oceano Indiano');
INSERT INTO RegionsDes VALUES (25,'it','Isole Salomone');
INSERT INTO RegionsDes VALUES (26,'it','Brunei Darussalam');
INSERT INTO RegionsDes VALUES (27,'it','Bulgaria');
INSERT INTO RegionsDes VALUES (28,'it','Birmania');
INSERT INTO RegionsDes VALUES (29,'it','Burundi');
INSERT INTO RegionsDes VALUES (30,'it','Antartide');
INSERT INTO RegionsDes VALUES (31,'it','Isola Bouvet');
INSERT INTO RegionsDes VALUES (32,'it','Camerun');
INSERT INTO RegionsDes VALUES (33,'it','Canada');
INSERT INTO RegionsDes VALUES (35,'it','Capo Verde');
INSERT INTO RegionsDes VALUES (36,'it','Isole Cayman');
INSERT INTO RegionsDes VALUES (37,'it','Repubblica Centrafricana');
INSERT INTO RegionsDes VALUES (38,'it','Sri Lanka');
INSERT INTO RegionsDes VALUES (39,'it','Ciad');
INSERT INTO RegionsDes VALUES (40,'it','Cile');
INSERT INTO RegionsDes VALUES (41,'it','Cina');
INSERT INTO RegionsDes VALUES (42,'it','Isola di Natale');
INSERT INTO RegionsDes VALUES (43,'it','Isole Cocos e Keeling');
INSERT INTO RegionsDes VALUES (44,'it','Colombia');
INSERT INTO RegionsDes VALUES (45,'it','Comore');
INSERT INTO RegionsDes VALUES (46,'it','Repubblica del Congo');
INSERT INTO RegionsDes VALUES (47,'it','Isole Cook');
INSERT INTO RegionsDes VALUES (48,'it','Costa Rica');
INSERT INTO RegionsDes VALUES (49,'it','Cuba');
INSERT INTO RegionsDes VALUES (50,'it','Cipro');
INSERT INTO RegionsDes VALUES (52,'it','Azerbaigian');
INSERT INTO RegionsDes VALUES (53,'it','Benin');
INSERT INTO RegionsDes VALUES (54,'it','Danimarca');
INSERT INTO RegionsDes VALUES (55,'it','Dominica');
INSERT INTO RegionsDes VALUES (56,'it','Repubblica Dominicana');
INSERT INTO RegionsDes VALUES (57,'it','Bielorussia');
INSERT INTO RegionsDes VALUES (58,'it','Ecuador');
INSERT INTO RegionsDes VALUES (59,'it','Egitto');
INSERT INTO RegionsDes VALUES (60,'it','El Salvador');
INSERT INTO RegionsDes VALUES (61,'it','Guinea Equatoriale');
INSERT INTO RegionsDes VALUES (63,'it','Estonia');
INSERT INTO RegionsDes VALUES (64,'it','Isole Faeroe');
INSERT INTO RegionsDes VALUES (65,'it','Isole Falkland');
INSERT INTO RegionsDes VALUES (66,'it','Figi');
INSERT INTO RegionsDes VALUES (67,'it','Finlandia');
INSERT INTO RegionsDes VALUES (68,'it','Francia');
INSERT INTO RegionsDes VALUES (69,'it','Guyana Francese');
INSERT INTO RegionsDes VALUES (70,'it','Polinesia Francese');
INSERT INTO RegionsDes VALUES (71,'it','Francia, Terre australi e antartiche');
INSERT INTO RegionsDes VALUES (72,'it','Gibuti');
INSERT INTO RegionsDes VALUES (73,'it','Georgia');
INSERT INTO RegionsDes VALUES (74,'it','Gabon');
INSERT INTO RegionsDes VALUES (75,'it','Gambia');
INSERT INTO RegionsDes VALUES (76,'it','Gaza, striscia di');
INSERT INTO RegionsDes VALUES (79,'it','Germania');
INSERT INTO RegionsDes VALUES (80,'it','Bosnia-Erzegovina');
INSERT INTO RegionsDes VALUES (81,'it','Ghana');
INSERT INTO RegionsDes VALUES (82,'it','Gibilterra');
INSERT INTO RegionsDes VALUES (83,'it','Kiribati');
INSERT INTO RegionsDes VALUES (84,'it','Grecia');
INSERT INTO RegionsDes VALUES (85,'it','Groenlandia');
INSERT INTO RegionsDes VALUES (86,'it','Grenada');
INSERT INTO RegionsDes VALUES (87,'it','Guadalupa');
INSERT INTO RegionsDes VALUES (88,'it','Guam');
INSERT INTO RegionsDes VALUES (89,'it','Guatemala');
INSERT INTO RegionsDes VALUES (90,'it','Guinea');
INSERT INTO RegionsDes VALUES (91,'it','Guyana');
INSERT INTO RegionsDes VALUES (92,'it','Isole Heard e McDonald');
INSERT INTO RegionsDes VALUES (93,'it','Haiti');
INSERT INTO RegionsDes VALUES (95,'it','Honduras');
INSERT INTO RegionsDes VALUES (97,'it','Ungheria');
INSERT INTO RegionsDes VALUES (98,'it','Croazia');
INSERT INTO RegionsDes VALUES (99,'it','Islanda');
INSERT INTO RegionsDes VALUES (100,'it','India');
INSERT INTO RegionsDes VALUES (101,'it','Indonesia');
INSERT INTO RegionsDes VALUES (102,'it','Iran');
INSERT INTO RegionsDes VALUES (103,'it','Iraq');
INSERT INTO RegionsDes VALUES (104,'it','Irlanda');
INSERT INTO RegionsDes VALUES (105,'it','Israele');
INSERT INTO RegionsDes VALUES (106,'it','Italia');
INSERT INTO RegionsDes VALUES (107,'it','Costa d''Avorio');
INSERT INTO RegionsDes VALUES (108,'it','Kazakistan');
INSERT INTO RegionsDes VALUES (109,'it','Giamaica');
INSERT INTO RegionsDes VALUES (110,'it','Giappone');
INSERT INTO RegionsDes VALUES (112,'it','Giordania');
INSERT INTO RegionsDes VALUES (113,'it','Kirghizistan');
INSERT INTO RegionsDes VALUES (114,'it','Kenia');
INSERT INTO RegionsDes VALUES (115,'it','Cambogia');
INSERT INTO RegionsDes VALUES (116,'it','Corea, Repubblica Democratica Popolare di');
INSERT INTO RegionsDes VALUES (117,'it','Corea, Repubblica di');
INSERT INTO RegionsDes VALUES (118,'it','Kuwait');
INSERT INTO RegionsDes VALUES (119,'it','Lettonia');
INSERT INTO RegionsDes VALUES (120,'it','Laos');
INSERT INTO RegionsDes VALUES (121,'it','Libano');
INSERT INTO RegionsDes VALUES (122,'it','Lesotho');
INSERT INTO RegionsDes VALUES (123,'it','Liberia');
INSERT INTO RegionsDes VALUES (124,'it','Libia');
INSERT INTO RegionsDes VALUES (125,'it','Liechtenstein');
INSERT INTO RegionsDes VALUES (126,'it','Lituania');
INSERT INTO RegionsDes VALUES (127,'it','Isole Marshall');
INSERT INTO RegionsDes VALUES (129,'it','Madagascar');
INSERT INTO RegionsDes VALUES (130,'it','Malawi');
INSERT INTO RegionsDes VALUES (131,'it','Malesia');
INSERT INTO RegionsDes VALUES (132,'it','Maldive');
INSERT INTO RegionsDes VALUES (133,'it','Mali');
INSERT INTO RegionsDes VALUES (134,'it','Malta');
INSERT INTO RegionsDes VALUES (135,'it','Martinica');
INSERT INTO RegionsDes VALUES (136,'it','Mauritania');
INSERT INTO RegionsDes VALUES (137,'it','Mauritius');
INSERT INTO RegionsDes VALUES (138,'it','Messico');
INSERT INTO RegionsDes VALUES (139,'it','Isole Midway');
INSERT INTO RegionsDes VALUES (140,'it','Monaco');
INSERT INTO RegionsDes VALUES (141,'it','Mongolia');
INSERT INTO RegionsDes VALUES (142,'it','Montserrat');
INSERT INTO RegionsDes VALUES (143,'it','Marocco');
INSERT INTO RegionsDes VALUES (144,'it','Mozambico');
INSERT INTO RegionsDes VALUES (145,'it','Micronesia, Stati Federati di');
INSERT INTO RegionsDes VALUES (146,'it','Moldavia');
INSERT INTO RegionsDes VALUES (147,'it','Namibia');
INSERT INTO RegionsDes VALUES (148,'it','Nauru');
INSERT INTO RegionsDes VALUES (149,'it','Nepal');
INSERT INTO RegionsDes VALUES (150,'it','Paesi Bassi');
INSERT INTO RegionsDes VALUES (151,'it','Antille Olandesi');
INSERT INTO RegionsDes VALUES (153,'it','Nuova Caledonia');
INSERT INTO RegionsDes VALUES (154,'it','Macedonia');
INSERT INTO RegionsDes VALUES (155,'it','Vanuatu');
INSERT INTO RegionsDes VALUES (156,'it','Nuova Zelanda');
INSERT INTO RegionsDes VALUES (157,'it','Nicaragua');
INSERT INTO RegionsDes VALUES (158,'it','Niger');
INSERT INTO RegionsDes VALUES (159,'it','Nigeria');
INSERT INTO RegionsDes VALUES (160,'it','Niue');
INSERT INTO RegionsDes VALUES (161,'it','Isola Norfolk');
INSERT INTO RegionsDes VALUES (162,'it','Norvegia');
INSERT INTO RegionsDes VALUES (163,'it','Isole Marianne Settentrionali');
INSERT INTO RegionsDes VALUES (165,'it','Pakistan');
INSERT INTO RegionsDes VALUES (166,'it','Panama');
INSERT INTO RegionsDes VALUES (167,'it','Ceca, Repubblica');
INSERT INTO RegionsDes VALUES (168,'it','Papua Nuova Guinea');
INSERT INTO RegionsDes VALUES (169,'it','Paraguay');
INSERT INTO RegionsDes VALUES (170,'it','Peru');
INSERT INTO RegionsDes VALUES (171,'it','Filippine');
INSERT INTO RegionsDes VALUES (172,'it','Isole Pitcairn');
INSERT INTO RegionsDes VALUES (173,'it','Polonia');
INSERT INTO RegionsDes VALUES (174,'it','Portogallo');
INSERT INTO RegionsDes VALUES (175,'it','Guinea-Bissau');
INSERT INTO RegionsDes VALUES (176,'it','Timor Est');
INSERT INTO RegionsDes VALUES (177,'it','Porto Rico');
INSERT INTO RegionsDes VALUES (178,'it','Eritrea');
INSERT INTO RegionsDes VALUES (179,'it','Qatar');
INSERT INTO RegionsDes VALUES (181,'it','Zimbabwe');
INSERT INTO RegionsDes VALUES (182,'it','Reunion');
INSERT INTO RegionsDes VALUES (183,'it','Romania');
INSERT INTO RegionsDes VALUES (184,'it','Ruanda');
INSERT INTO RegionsDes VALUES (185,'it','Russia');
INSERT INTO RegionsDes VALUES (187,'it','Sant''Elena');
INSERT INTO RegionsDes VALUES (188,'it','Saint Kitts e Nevis');
INSERT INTO RegionsDes VALUES (189,'it','Santa Lucia');
INSERT INTO RegionsDes VALUES (190,'it','Saint-Pierre e Miquelon');
INSERT INTO RegionsDes VALUES (191,'it','Saint Vincent e Grenadine');
INSERT INTO RegionsDes VALUES (192,'it','San Marino');
INSERT INTO RegionsDes VALUES (193,'it','Sao Tome e Principe');
INSERT INTO RegionsDes VALUES (194,'it','Arabia Saudita');
INSERT INTO RegionsDes VALUES (195,'it','Senegal');
INSERT INTO RegionsDes VALUES (196,'it','Seychelles');
INSERT INTO RegionsDes VALUES (197,'it','Sierra Leone');
INSERT INTO RegionsDes VALUES (198,'it','Slovenia');
INSERT INTO RegionsDes VALUES (199,'it','Slovacchia');
INSERT INTO RegionsDes VALUES (200,'it','Singapore');
INSERT INTO RegionsDes VALUES (201,'it','Somalia');
INSERT INTO RegionsDes VALUES (202,'it','Sudafrica');
INSERT INTO RegionsDes VALUES (203,'it','Spagna');
INSERT INTO RegionsDes VALUES (205,'it','Sahara Occidentale');
INSERT INTO RegionsDes VALUES (206,'it','Sudan');
INSERT INTO RegionsDes VALUES (207,'it','Suriname');
INSERT INTO RegionsDes VALUES (208,'it','Tagikistan');
INSERT INTO RegionsDes VALUES (209,'it','Swaziland');
INSERT INTO RegionsDes VALUES (210,'it','Svezia');
INSERT INTO RegionsDes VALUES (211,'it','Svizzera');
INSERT INTO RegionsDes VALUES (212,'it','Siria');
INSERT INTO RegionsDes VALUES (213,'it','Turkmenistan');
INSERT INTO RegionsDes VALUES (214,'it','Taiwan');
INSERT INTO RegionsDes VALUES (215,'it','Tanzania');
INSERT INTO RegionsDes VALUES (216,'it','Thailandia');
INSERT INTO RegionsDes VALUES (217,'it','Togo');
INSERT INTO RegionsDes VALUES (218,'it','Tokelau');
INSERT INTO RegionsDes VALUES (219,'it','Tonga');
INSERT INTO RegionsDes VALUES (220,'it','Trinidad e Tobago');
INSERT INTO RegionsDes VALUES (221,'it','Oman');
INSERT INTO RegionsDes VALUES (222,'it','Tunisia');
INSERT INTO RegionsDes VALUES (223,'it','Turchia');
INSERT INTO RegionsDes VALUES (224,'it','Turks and Caicos');
INSERT INTO RegionsDes VALUES (225,'it','Emirati Arabi Uniti');
INSERT INTO RegionsDes VALUES (226,'it','Uganda');
INSERT INTO RegionsDes VALUES (227,'it','Tuvalu');
INSERT INTO RegionsDes VALUES (229,'it','Regno Unito');
INSERT INTO RegionsDes VALUES (230,'it','Ucraina');
INSERT INTO RegionsDes VALUES (231,'it','Stati Uniti d''America');
INSERT INTO RegionsDes VALUES (232,'it','Stati Uniti d''America, Isole Minori Esterne ');
INSERT INTO RegionsDes VALUES (233,'it','Burkina Faso');
INSERT INTO RegionsDes VALUES (234,'it','Uruguay');
INSERT INTO RegionsDes VALUES (235,'it','Uzbekistan');
INSERT INTO RegionsDes VALUES (236,'it','Venezuela');
INSERT INTO RegionsDes VALUES (237,'it','Vietnam');
INSERT INTO RegionsDes VALUES (238,'it','Etiopia');
INSERT INTO RegionsDes VALUES (239,'it','Isole Vergini britanniche');
INSERT INTO RegionsDes VALUES (240,'it','Isole Vergini americane');
INSERT INTO RegionsDes VALUES (242,'it','Isola di Wake');
INSERT INTO RegionsDes VALUES (243,'it','Isole di Wallis e Futuna');
INSERT INTO RegionsDes VALUES (244,'it','Samoa');
INSERT INTO RegionsDes VALUES (245,'it','Cisgiordania');
INSERT INTO RegionsDes VALUES (249,'it','Yemen');
INSERT INTO RegionsDes VALUES (250,'it','Congo');
INSERT INTO RegionsDes VALUES (251,'it','Zambia');
INSERT INTO RegionsDes VALUES (255,'it','Belgio');
INSERT INTO RegionsDes VALUES (256,'it','Lussemburgo');
INSERT INTO RegionsDes VALUES (258,'it','Anguilla');
INSERT INTO RegionsDes VALUES (260,'it','Isola di Svalbard');
INSERT INTO RegionsDes VALUES (264,'it','Isole di Man');
INSERT INTO RegionsDes VALUES (270,'it','Mayotte');
INSERT INTO RegionsDes VALUES (271,'it','Georgia del Sud e isole Sandwich');
INSERT INTO RegionsDes VALUES (303,'it','Europa Occidentale');
INSERT INTO RegionsDes VALUES (307,'it','Autorità Intergovernativa per lo Sviluppo');
INSERT INTO RegionsDes VALUES (310,'it','Africa Occidentale del Nord');
INSERT INTO RegionsDes VALUES (311,'it','Africa Occidentale');
INSERT INTO RegionsDes VALUES (312,'it','Africa Centrale');
INSERT INTO RegionsDes VALUES (313,'it','Africa Orientale');
INSERT INTO RegionsDes VALUES (314,'it','Africa del Sud');
INSERT INTO RegionsDes VALUES (315,'it','America Latina');
INSERT INTO RegionsDes VALUES (316,'it','America Centrale');
INSERT INTO RegionsDes VALUES (317,'it','Caraibi');
INSERT INTO RegionsDes VALUES (318,'it','America del Sud');
INSERT INTO RegionsDes VALUES (319,'it','Vicino Oriente');
INSERT INTO RegionsDes VALUES (320,'it','Vicino Oriente in Africa');
INSERT INTO RegionsDes VALUES (321,'it','Vicino Oriente in Asia');
INSERT INTO RegionsDes VALUES (322,'it','Estremo Oriente');
INSERT INTO RegionsDes VALUES (323,'it','Asia Meridionale');
INSERT INTO RegionsDes VALUES (324,'it','Est e Sud-Est Asiatico');
INSERT INTO RegionsDes VALUES (325,'it','Vicino Oriente & Nord Africa');
INSERT INTO RegionsDes VALUES (334,'it','Europa Orientale');
INSERT INTO RegionsDes VALUES (335,'it','Europa');
INSERT INTO RegionsDes VALUES (337,'it','Asia');
INSERT INTO RegionsDes VALUES (338,'it','Africa');
INSERT INTO RegionsDes VALUES (348,'it','America Latina');
INSERT INTO RegionsDes VALUES (370,'it','Serbia');
INSERT INTO RegionsDes VALUES (371,'it','Montenegro');
INSERT INTO RegionsDes VALUES (390,'it','Sahara Meridionale');
INSERT INTO RegionsDes VALUES (421,'it','Nord Africa');
INSERT INTO RegionsDes VALUES (427,'it','Europa, Paesi non UE');
INSERT INTO RegionsDes VALUES (428,'it','Nord America');
INSERT INTO RegionsDes VALUES (469,'it','URSS, Area Ex');
INSERT INTO RegionsDes VALUES (1008,'it','Mar Glaciale Artico');
INSERT INTO RegionsDes VALUES (1009,'it','Atlantico, Nord-Occidentale');
INSERT INTO RegionsDes VALUES (1010,'it','Atlantico, Nord-Orientale');
INSERT INTO RegionsDes VALUES (1011,'it','Atlantico, Centro-Occidentale');
INSERT INTO RegionsDes VALUES (1012,'it','Atlantico, Centro-Orientale');
INSERT INTO RegionsDes VALUES (1013,'it','Mediterraneo e Mar Nero');
INSERT INTO RegionsDes VALUES (1014,'it','Atlantico, Sud-Occidentale');
INSERT INTO RegionsDes VALUES (1015,'it','Atlantico, Sud-Orientale');
INSERT INTO RegionsDes VALUES (1016,'it','Atlantico, Antartico');
INSERT INTO RegionsDes VALUES (1017,'it','Oceano Indiano, Occidentale');
INSERT INTO RegionsDes VALUES (1018,'it','Oceano Indiano, Orientale');
INSERT INTO RegionsDes VALUES (1019,'it','Oceano Indiano, Antartico');
INSERT INTO RegionsDes VALUES (1020,'it','Pacifico, Nord-Occidentale');
INSERT INTO RegionsDes VALUES (1021,'it','Pacifico, Nord-Orientale');
INSERT INTO RegionsDes VALUES (1022,'it','Pacifico, Centro-Occidentale');
INSERT INTO RegionsDes VALUES (1023,'it','Pacifico, Contro-Orientale');
INSERT INTO RegionsDes VALUES (1024,'it','Pacifico, Sud-Occidentale');
INSERT INTO RegionsDes VALUES (1025,'it','Pacifico, Sud-Orientale');
INSERT INTO RegionsDes VALUES (1026,'it','Pacifico, Antartico');
INSERT INTO RegionsDes VALUES (1220,'it','Tutte le zone di pesca');
INSERT INTO RegionsDes VALUES (9999,'it','Mondo');

