/*
 * Copyright (C) 2001-2016 Food and Agriculture Organization of the
 * United Nations (FAO-UN), United Nations World Food Programme (WFP)
 * and United Nations Environment Programme (UNEP)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 *
 * Contact: Jeroen Ticheler - FAO - Viale delle Terme di Caracalla 2,
 * Rome - Italy. email: geonetwork@osgeo.org
 */

package org.fao.geonet.repository;

import com.google.common.collect.Maps;

import org.fao.geonet.domain.ISODate;
import org.fao.geonet.domain.MetadataDraft;
import org.fao.geonet.domain.MetadataDraft_;
import org.fao.geonet.domain.MetadataDataInfo_;
import org.fao.geonet.domain.MetadataSourceInfo;
import org.fao.geonet.domain.Pair;
import org.fao.geonet.repository.reports.MetadataReportsQueries;
import org.jdom.Element;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.data.repository.NoRepositoryBean;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jakarta.persistence.Query;
import jakarta.persistence.Tuple;
import jakarta.persistence.TypedQuery;
import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.Order;
import jakarta.persistence.criteria.Path;
import jakarta.persistence.criteria.Root;

/**
 * Implementation for all {@link Metadata} queries that cannot be automatically generated by
 * Spring-data.
 *
 * @author Jesse
 */
public class MetadataDraftRepositoryCustomImpl implements MetadataDraftRepositoryCustom<MetadataDraft> {

    @PersistenceContext
    EntityManager _entityManager;

    @Override
    public MetadataReportsQueries getMetadataReports() {
        return new MetadataReportsQueries(_entityManager);
    }

    @Override
    public
    @Nonnull
    Page<Pair<Integer, ISODate>> findIdsAndChangeDates(@Nullable Pageable pageable) {
        CriteriaBuilder cb = _entityManager.getCriteriaBuilder();
        CriteriaQuery<Tuple> cbQuery = cb.createQuery(Tuple.class);
        Root<MetadataDraft> root = cbQuery.from(MetadataDraft.class);

        cbQuery.multiselect(cb.count(root));
        Long total = (Long) _entityManager.createQuery(cbQuery).getSingleResult().get(0);
        cbQuery.multiselect(root.get(MetadataDraft_.id), root.get(MetadataDraft_.dataInfo).get(MetadataDataInfo_.changeDate));

        if (pageable != null && pageable.getSort() != null) {
            final Sort sort = pageable.getSort();
            List<Order> orders = SortUtils.sortToJpaOrders(cb, sort, root);

            cbQuery.orderBy(orders);
        }

        TypedQuery<Tuple> query = _entityManager.createQuery(cbQuery);
        if (pageable != null) {
            query.setFirstResult(Math.toIntExact(pageable.getOffset()));
            query.setMaxResults(pageable.getPageSize());
        }

        ArrayList<Pair<Integer, ISODate>> finalResults = new ArrayList<Pair<Integer, ISODate>>();
        for (Tuple tuple : query.getResultList()) {
            final Integer mdId = (Integer) tuple.get(0);
            final ISODate changeDate = (ISODate) tuple.get(1);
            finalResults.add(Pair.read(mdId, changeDate));
        }
        return new PageImpl<Pair<Integer, ISODate>>(finalResults, pageable, total);
    }

    @Nonnull
    @Override
    public List<Integer> findIdsBy(@Nonnull Specification<MetadataDraft> spec) {
        CriteriaBuilder cb = _entityManager.getCriteriaBuilder();
        CriteriaQuery<Integer> cbQuery = cb.createQuery(Integer.class);
        Root<MetadataDraft> root = cbQuery.from(MetadataDraft.class);
        cbQuery.select(root.get(MetadataDraft_.id));

        cbQuery.where(spec.toPredicate(root, cbQuery, cb));
        return _entityManager.createQuery(cbQuery).getResultList();
    }

    @Override
    public Map<Integer, MetadataSourceInfo> findSourceInfo(Specification<MetadataDraft> spec) {
        CriteriaBuilder cb = _entityManager.getCriteriaBuilder();
        CriteriaQuery<Object[]> cbQuery = cb.createQuery(Object[].class);
        Root<MetadataDraft> root = cbQuery.from(MetadataDraft.class);
        cbQuery.select(cb.array(root.get(MetadataDraft_.id), root.get(MetadataDraft_.sourceInfo)));

        cbQuery.where(spec.toPredicate(root, cbQuery, cb));
        Map<Integer, MetadataSourceInfo> results = Maps.newHashMap();
        final List<Object[]> resultList = _entityManager.createQuery(cbQuery).getResultList();
        for (Object[] objects : resultList) {
            final Integer metadataId = (Integer) objects[0];
            final MetadataSourceInfo sourceInfo = (MetadataSourceInfo) objects[1];
            results.put(metadataId, sourceInfo);
        }

        return results;
    }

    /**
     * @see org.fao.geonet.repository.MetadataRepositoryCustom#findAllSimple(org.springframework.data.jpa.domain.Specification)
     */
    @Override
    public List<SimpleMetadata> findSimple(String id) {
        Query query = _entityManager.createQuery(
            "select new org.fao.geonet.repository.SimpleMetadata("
                + "id, uuid, dataInfo.changeDate, dataInfo.type_JPAWorkaround) "
                + "from Metadata where harvestInfo.uuid = :id").setParameter("id", id);

        //TODO paginate

        return query.getResultList();
    }


    @Override
    public Element findUuidsAndChangeDatesAndSchemaId(List<Integer> ids, @Nonnull Pageable pageable) {
        CriteriaBuilder cb = _entityManager.getCriteriaBuilder();
        CriteriaQuery<Tuple> cbQuery = cb.createQuery(Tuple.class);
        Root<MetadataDraft> root = cbQuery.from(MetadataDraft.class);

        cbQuery.multiselect(root.get(MetadataDraft_.uuid), root.get(MetadataDraft_.dataInfo).get(MetadataDataInfo_.changeDate), root.get(MetadataDraft_.dataInfo).get(MetadataDataInfo_.schemaId));

        cbQuery.where(root.get(MetadataDraft_.id).in(ids), cb.equal(root.get(MetadataDraft_.dataInfo).get(MetadataDataInfo_.type_JPAWorkaround), 'n'));

        if (pageable != null && pageable.getSort() != null) {
            final Sort sort = pageable.getSort();
            List<Order> orders = SortUtils.sortToJpaOrders(cb, sort, root);

            cbQuery.orderBy(orders);
        }

        TypedQuery<Tuple> query = _entityManager.createQuery(cbQuery);
        if (pageable != null) {
            query.setFirstResult(Math.toIntExact(pageable.getOffset()));
            query.setMaxResults(pageable.getPageSize());
        }

        Element result = new Element("metadata");
        for (Tuple tuple : query.getResultList()) {

            Element record = new Element("record");
            Element uuid = new Element("uuid");
            Element schemaid = new Element("schemaid");
            Element changedate = new Element("changedate");

            uuid.addContent((String) tuple.get(0));
            changedate.addContent(((ISODate) tuple.get(1)).toString());
            schemaid.addContent((String) tuple.get(2));

            record.addContent(uuid);
            record.addContent(changedate);
            record.addContent(schemaid);

            result.addContent(record);

        }
        return result;
    }

    @Override
    public Element findUuidsAndChangeDatesAndSchemaId(List<Integer> ids) {
        CriteriaBuilder cb = _entityManager.getCriteriaBuilder();
        CriteriaQuery<Tuple> cbQuery = cb.createQuery(Tuple.class);
        Root<MetadataDraft> root = cbQuery.from(MetadataDraft.class);

        cbQuery.multiselect(root.get(MetadataDraft_.uuid), root.get(MetadataDraft_.dataInfo).get(MetadataDataInfo_.changeDate), root.get(MetadataDraft_.dataInfo).get(MetadataDataInfo_.schemaId));

        cbQuery.where(root.get(MetadataDraft_.id).in(ids), cb.equal(root.get(MetadataDraft_.dataInfo).get(MetadataDataInfo_.type_JPAWorkaround), 'n'));

        TypedQuery<Tuple> query = _entityManager.createQuery(cbQuery);

        Element result = new Element("metadata");
        for (Tuple tuple : query.getResultList()) {

            Element record = new Element("record");
            Element uuid = new Element("uuid");
            Element schemaid = new Element("schemaid");
            Element changedate = new Element("changedate");

            uuid.addContent((String) tuple.get(0));
            changedate.addContent(((ISODate) tuple.get(1)).toString());
            schemaid.addContent((String) tuple.get(2));

            record.addContent(uuid);
            record.addContent(changedate);
            record.addContent(schemaid);

            result.addContent(record);

        }
        return result;
    }

}
