package org.fao.geonet.repository;

import org.fao.geonet.domain.Setting;
import org.fao.geonet.domain.Setting_;

/**
 * Implementation for all {@link Setting} queries that cannot be automatically generated by Spring-data.
 *
 * @author Jesse
 */
public class SettingRepositoryImpl extends AbstractSettingRepoImpl<Setting> implements SettingRepositoryCustom {

    public SettingRepositoryImpl() {
        super(Setting.class, Setting_.parent);
    }
}
