-- ISO 3 letter code migration
INSERT INTO Languages VALUES ('nor','Norsk', 'n', 'n');

UPDATE CategoriesDes             SET langid='nor' WHERE langid='no';
UPDATE IsoLanguagesDes           SET langid='nor' WHERE langid='no';
UPDATE RegionsDes                SET langid='nor' WHERE langid='no';
UPDATE GroupsDes                 SET langid='nor' WHERE langid='no';
UPDATE OperationsDes             SET langid='nor' WHERE langid='no';
UPDATE StatusValuesDes           SET langid='nor' WHERE langid='no';
UPDATE CswServerCapabilitiesInfo SET langid='nor' WHERE langid='no';
DELETE FROM Languages WHERE id='no';

-- Take care to table ID (related to other loc files)
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (1,'nor','Kart og grafikk');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (2,'nor','Datasett');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (3,'nor','Interakive ressurser');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (4,'nor','Applikasjoner');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (5,'nor','Studier og anbefalinger');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (6,'nor','Konferanseresultater');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (7,'nor','Fotografier');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (8,'nor','Audio/Video');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (9,'nor','Kataloger');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (10,'nor','Andre ressurser');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (11,'nor','Z3950 Servers');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (12,'nor','Registers');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (13,'nor','Physical Samples');

INSERT INTO GroupsDes (iddes, langid, label) VALUES (-1,'nor','Gjest');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (0,'nor','Intranett');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (1,'nor','Alle');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (2,'nor','Eksempelgruppe');

INSERT INTO IsoLanguagesDes VALUES (1,'nor','Afar');
INSERT INTO IsoLanguagesDes VALUES (2,'nor','Abkhazian');
INSERT INTO IsoLanguagesDes VALUES (3,'nor','Achinese');
INSERT INTO IsoLanguagesDes VALUES (4,'nor','Acoli');
INSERT INTO IsoLanguagesDes VALUES (5,'nor','Adangme');
INSERT INTO IsoLanguagesDes VALUES (6,'nor','Adyghe; Adygei');
INSERT INTO IsoLanguagesDes VALUES (7,'nor','Afro-Asiatic (Other)');
INSERT INTO IsoLanguagesDes VALUES (8,'nor','Afrihili');
INSERT INTO IsoLanguagesDes VALUES (9,'nor','Afrikaans');
INSERT INTO IsoLanguagesDes VALUES (10,'nor','Ainu');
INSERT INTO IsoLanguagesDes VALUES (11,'nor','Akan');
INSERT INTO IsoLanguagesDes VALUES (12,'nor','Akkadian');
INSERT INTO IsoLanguagesDes VALUES (13,'nor','Albanian');
INSERT INTO IsoLanguagesDes VALUES (14,'nor','Aleut');
INSERT INTO IsoLanguagesDes VALUES (15,'nor','Algonquian languages');
INSERT INTO IsoLanguagesDes VALUES (16,'nor','Southern Altai');
INSERT INTO IsoLanguagesDes VALUES (17,'nor','Amharic');
INSERT INTO IsoLanguagesDes VALUES (18,'nor','English, Old (ca.450-1100)');
INSERT INTO IsoLanguagesDes VALUES (19,'nor','Angika');
INSERT INTO IsoLanguagesDes VALUES (20,'nor','Apache languages');
INSERT INTO IsoLanguagesDes VALUES (21,'nor','Arabic');
INSERT INTO IsoLanguagesDes VALUES (22,'nor','Aramaic');
INSERT INTO IsoLanguagesDes VALUES (23,'nor','Aragonese');
INSERT INTO IsoLanguagesDes VALUES (24,'nor','Armenian');
INSERT INTO IsoLanguagesDes VALUES (25,'nor','Mapudungun; Mapuche');
INSERT INTO IsoLanguagesDes VALUES (26,'nor','Arapaho');
INSERT INTO IsoLanguagesDes VALUES (27,'nor','Artificial (Other)');
INSERT INTO IsoLanguagesDes VALUES (28,'nor','Arawak');
INSERT INTO IsoLanguagesDes VALUES (29,'nor','Assamese');
INSERT INTO IsoLanguagesDes VALUES (30,'nor','Asturian; Bable');
INSERT INTO IsoLanguagesDes VALUES (31,'nor','Athapascan languages');
INSERT INTO IsoLanguagesDes VALUES (32,'nor','Australian languages');
INSERT INTO IsoLanguagesDes VALUES (33,'nor','Avaric');
INSERT INTO IsoLanguagesDes VALUES (34,'nor','Avestan');
INSERT INTO IsoLanguagesDes VALUES (35,'nor','Awadhi');
INSERT INTO IsoLanguagesDes VALUES (36,'nor','Aymara');
INSERT INTO IsoLanguagesDes VALUES (37,'nor','Azerbaijani');
INSERT INTO IsoLanguagesDes VALUES (38,'nor','Banda languages');
INSERT INTO IsoLanguagesDes VALUES (39,'nor','Bamileke languages');
INSERT INTO IsoLanguagesDes VALUES (40,'nor','Bashkir');
INSERT INTO IsoLanguagesDes VALUES (41,'nor','Baluchi');
INSERT INTO IsoLanguagesDes VALUES (42,'nor','Bambara');
INSERT INTO IsoLanguagesDes VALUES (43,'nor','Balinese');
INSERT INTO IsoLanguagesDes VALUES (44,'nor','Basque');
INSERT INTO IsoLanguagesDes VALUES (45,'nor','Basa');
INSERT INTO IsoLanguagesDes VALUES (46,'nor','Baltic (Other)');
INSERT INTO IsoLanguagesDes VALUES (47,'nor','Beja');
INSERT INTO IsoLanguagesDes VALUES (48,'nor','Belarusian');
INSERT INTO IsoLanguagesDes VALUES (49,'nor','Bemba');
INSERT INTO IsoLanguagesDes VALUES (50,'nor','Bengali');
INSERT INTO IsoLanguagesDes VALUES (51,'nor','Berber (Other)');
INSERT INTO IsoLanguagesDes VALUES (52,'nor','Bhojpuri');
INSERT INTO IsoLanguagesDes VALUES (53,'nor','Bihari');
INSERT INTO IsoLanguagesDes VALUES (54,'nor','Bikol');
INSERT INTO IsoLanguagesDes VALUES (55,'nor','Bini; Edo');
INSERT INTO IsoLanguagesDes VALUES (56,'nor','Bislama');
INSERT INTO IsoLanguagesDes VALUES (57,'nor','Siksika');
INSERT INTO IsoLanguagesDes VALUES (58,'nor','Bantu (Other)');
INSERT INTO IsoLanguagesDes VALUES (59,'nor','Bosnian');
INSERT INTO IsoLanguagesDes VALUES (60,'nor','Braj');
INSERT INTO IsoLanguagesDes VALUES (61,'nor','Breton');
INSERT INTO IsoLanguagesDes VALUES (62,'nor','Batak languages');
INSERT INTO IsoLanguagesDes VALUES (63,'nor','Buriat');
INSERT INTO IsoLanguagesDes VALUES (64,'nor','Buginese');
INSERT INTO IsoLanguagesDes VALUES (65,'nor','Bulgarian');
INSERT INTO IsoLanguagesDes VALUES (66,'nor','Burmese');
INSERT INTO IsoLanguagesDes VALUES (67,'nor','Blin; Bilin');
INSERT INTO IsoLanguagesDes VALUES (68,'nor','Caddo');
INSERT INTO IsoLanguagesDes VALUES (69,'nor','Central American Indian (Other)');
INSERT INTO IsoLanguagesDes VALUES (70,'nor','Galibi Carib');
INSERT INTO IsoLanguagesDes VALUES (71,'nor','Catalan; Valencian');
INSERT INTO IsoLanguagesDes VALUES (72,'nor','Caucasian (Other)on liturgique; vieux bulgare');
INSERT INTO IsoLanguagesDes VALUES (73,'nor','Cebuano');
INSERT INTO IsoLanguagesDes VALUES (74,'nor','Celtic (Other)');
INSERT INTO IsoLanguagesDes VALUES (75,'nor','Chamorro');
INSERT INTO IsoLanguagesDes VALUES (76,'nor','Chibcha');
INSERT INTO IsoLanguagesDes VALUES (77,'nor','Chechen');
INSERT INTO IsoLanguagesDes VALUES (78,'nor','Chagataier)');
INSERT INTO IsoLanguagesDes VALUES (79,'nor','Chinese(Other)');
INSERT INTO IsoLanguagesDes VALUES (80,'nor','Chuukese');
INSERT INTO IsoLanguagesDes VALUES (81,'nor','Mari');
INSERT INTO IsoLanguagesDes VALUES (82,'nor','Chinook jargon');
INSERT INTO IsoLanguagesDes VALUES (83,'nor','Choctaw');
INSERT INTO IsoLanguagesDes VALUES (84,'nor','Chipewyan');
INSERT INTO IsoLanguagesDes VALUES (85,'nor','Cherokee');
INSERT INTO IsoLanguagesDes VALUES (86,'nor','Church Slavic; Old Slavonic; Church Sl');
INSERT INTO IsoLanguagesDes VALUES (87,'nor','Chuvash');
INSERT INTO IsoLanguagesDes VALUES (88,'nor','Cheyenne');
INSERT INTO IsoLanguagesDes VALUES (89,'nor','Chamic languages');
INSERT INTO IsoLanguagesDes VALUES (90,'nor','Coptic');
INSERT INTO IsoLanguagesDes VALUES (91,'nor','Cornish');
INSERT INTO IsoLanguagesDes VALUES (92,'nor','Corsican');
INSERT INTO IsoLanguagesDes VALUES (93,'nor','Creoles and pidgins, English based (Ot');
INSERT INTO IsoLanguagesDes VALUES (94,'nor','Creoles and pidgins, French-based (Oth');
INSERT INTO IsoLanguagesDes VALUES (95,'nor','Creoles and pidgins, Portuguese-based ');
INSERT INTO IsoLanguagesDes VALUES (96,'nor','Cree');
INSERT INTO IsoLanguagesDes VALUES (97,'nor','Crimean Tatar; Crimean Turkish');
INSERT INTO IsoLanguagesDes VALUES (98,'nor','Creoles and pidgins (Other)');
INSERT INTO IsoLanguagesDes VALUES (99,'nor','Kashubian');
INSERT INTO IsoLanguagesDes VALUES (100,'nor','Cushitic (Other)');
INSERT INTO IsoLanguagesDes VALUES (101,'nor','Czech');
INSERT INTO IsoLanguagesDes VALUES (102,'nor','Dakota');
INSERT INTO IsoLanguagesDes VALUES (103,'nor','Danish');
INSERT INTO IsoLanguagesDes VALUES (104,'nor','Dargwa');
INSERT INTO IsoLanguagesDes VALUES (105,'nor','Land Dayak languages');
INSERT INTO IsoLanguagesDes VALUES (106,'nor','Delaware');
INSERT INTO IsoLanguagesDes VALUES (107,'nor','Slave (Athapascan)');
INSERT INTO IsoLanguagesDes VALUES (108,'nor','Dogrib');
INSERT INTO IsoLanguagesDes VALUES (109,'nor','Dinka');
INSERT INTO IsoLanguagesDes VALUES (110,'nor','Divehi; Dhivehi; Maldivian');
INSERT INTO IsoLanguagesDes VALUES (111,'nor','Dogri');
INSERT INTO IsoLanguagesDes VALUES (112,'nor','Dravidian (Other)');
INSERT INTO IsoLanguagesDes VALUES (113,'nor','Lower Sorbian');
INSERT INTO IsoLanguagesDes VALUES (114,'nor','Duala');
INSERT INTO IsoLanguagesDes VALUES (115,'nor','Dutch, Middle (ca.1050-1350)');
INSERT INTO IsoLanguagesDes VALUES (116,'nor','Dutch; Flemish');
INSERT INTO IsoLanguagesDes VALUES (117,'nor','Dyula');
INSERT INTO IsoLanguagesDes VALUES (118,'nor','Dzongkha');
INSERT INTO IsoLanguagesDes VALUES (119,'nor','Efik');
INSERT INTO IsoLanguagesDes VALUES (120,'nor','Egyptian (Ancient)');
INSERT INTO IsoLanguagesDes VALUES (121,'nor','Ekajuk');
INSERT INTO IsoLanguagesDes VALUES (122,'nor','Elamite');
INSERT INTO IsoLanguagesDes VALUES (123,'nor','English');
INSERT INTO IsoLanguagesDes VALUES (124,'nor','English, Middle (1100-1500)');
INSERT INTO IsoLanguagesDes VALUES (125,'nor','Esperanto');
INSERT INTO IsoLanguagesDes VALUES (126,'nor','Estonian');
INSERT INTO IsoLanguagesDes VALUES (127,'nor','Ewe');
INSERT INTO IsoLanguagesDes VALUES (128,'nor','Ewondo');
INSERT INTO IsoLanguagesDes VALUES (129,'nor','Fang');
INSERT INTO IsoLanguagesDes VALUES (130,'nor','Faroese');
INSERT INTO IsoLanguagesDes VALUES (131,'nor','Fanti');
INSERT INTO IsoLanguagesDes VALUES (132,'nor','Fijian');
INSERT INTO IsoLanguagesDes VALUES (133,'nor','Filipino; Pilipino');
INSERT INTO IsoLanguagesDes VALUES (134,'nor','Finnish');
INSERT INTO IsoLanguagesDes VALUES (135,'nor','Finno-Ugrian (Other)');
INSERT INTO IsoLanguagesDes VALUES (136,'nor','Fon');
INSERT INTO IsoLanguagesDes VALUES (137,'nor','French');
INSERT INTO IsoLanguagesDes VALUES (138,'nor','French, Middle (ca.1400-1600)');
INSERT INTO IsoLanguagesDes VALUES (139,'nor','French, Old (842-ca.1400)');
INSERT INTO IsoLanguagesDes VALUES (140,'nor','Northern Frisian');
INSERT INTO IsoLanguagesDes VALUES (141,'nor','Eastern Frisian');
INSERT INTO IsoLanguagesDes VALUES (142,'nor','Western Frisian');
INSERT INTO IsoLanguagesDes VALUES (143,'nor','Fulah');
INSERT INTO IsoLanguagesDes VALUES (144,'nor','Friulian');
INSERT INTO IsoLanguagesDes VALUES (145,'nor','Ga');
INSERT INTO IsoLanguagesDes VALUES (146,'nor','Gayo');
INSERT INTO IsoLanguagesDes VALUES (147,'nor','Gbaya');
INSERT INTO IsoLanguagesDes VALUES (148,'nor','Germanic (Other)');
INSERT INTO IsoLanguagesDes VALUES (149,'nor','Georgian');
INSERT INTO IsoLanguagesDes VALUES (150,'nor','German');
INSERT INTO IsoLanguagesDes VALUES (151,'nor','Geez');
INSERT INTO IsoLanguagesDes VALUES (152,'nor','Gilbertese');
INSERT INTO IsoLanguagesDes VALUES (153,'nor','Gaelic; Scottish Gaelic');
INSERT INTO IsoLanguagesDes VALUES (154,'nor','Irish');
INSERT INTO IsoLanguagesDes VALUES (155,'nor','Galician');
INSERT INTO IsoLanguagesDes VALUES (156,'nor','Manx');
INSERT INTO IsoLanguagesDes VALUES (157,'nor','German, Middle High (ca.1050-1500)');
INSERT INTO IsoLanguagesDes VALUES (158,'nor','German, Old High (ca.750-1050)');
INSERT INTO IsoLanguagesDes VALUES (159,'nor','Gondi');
INSERT INTO IsoLanguagesDes VALUES (160,'nor','Gorontalo');
INSERT INTO IsoLanguagesDes VALUES (161,'nor','Gothicanguage Association)');
INSERT INTO IsoLanguagesDes VALUES (162,'nor','Grebo');
INSERT INTO IsoLanguagesDes VALUES (163,'nor','Greek, Ancient (to 1453)');
INSERT INTO IsoLanguagesDes VALUES (164,'nor','Greek, Modern (1453-)');
INSERT INTO IsoLanguagesDes VALUES (165,'nor','Guarani');
INSERT INTO IsoLanguagesDes VALUES (166,'nor','Swiss German; Alemannic');
INSERT INTO IsoLanguagesDes VALUES (167,'nor','Gujarati');
INSERT INTO IsoLanguagesDes VALUES (168,'nor','Gwich''in');
INSERT INTO IsoLanguagesDes VALUES (169,'nor','Haida');
INSERT INTO IsoLanguagesDes VALUES (170,'nor','Haitian; Haitian Creole');
INSERT INTO IsoLanguagesDes VALUES (171,'nor','Hausa');
INSERT INTO IsoLanguagesDes VALUES (172,'nor','Hawaiian');
INSERT INTO IsoLanguagesDes VALUES (173,'nor','Hebrew');
INSERT INTO IsoLanguagesDes VALUES (174,'nor','Herero');
INSERT INTO IsoLanguagesDes VALUES (175,'nor','Hiligaynon');
INSERT INTO IsoLanguagesDes VALUES (176,'nor','Himachali');
INSERT INTO IsoLanguagesDes VALUES (177,'nor','Hindi');
INSERT INTO IsoLanguagesDes VALUES (178,'nor','Hittite');
INSERT INTO IsoLanguagesDes VALUES (179,'nor','Hmong');
INSERT INTO IsoLanguagesDes VALUES (180,'nor','Hiri Motu');
INSERT INTO IsoLanguagesDes VALUES (181,'nor','Upper Sorbian');
INSERT INTO IsoLanguagesDes VALUES (182,'nor','Hungarian');
INSERT INTO IsoLanguagesDes VALUES (183,'nor','Hupa');
INSERT INTO IsoLanguagesDes VALUES (184,'nor','Iban');
INSERT INTO IsoLanguagesDes VALUES (185,'nor','Igbo');
INSERT INTO IsoLanguagesDes VALUES (186,'nor','Icelandic');
INSERT INTO IsoLanguagesDes VALUES (187,'nor','Ido');
INSERT INTO IsoLanguagesDes VALUES (188,'nor','Sichuan Yi');
INSERT INTO IsoLanguagesDes VALUES (189,'nor','Ijo languages');
INSERT INTO IsoLanguagesDes VALUES (190,'nor','Inuktitut');
INSERT INTO IsoLanguagesDes VALUES (191,'nor','Interlingue');
INSERT INTO IsoLanguagesDes VALUES (192,'nor','Iloko');
INSERT INTO IsoLanguagesDes VALUES (193,'nor','Interlingua (International Auxiliary L');
INSERT INTO IsoLanguagesDes VALUES (194,'nor','Indic (Other)');
INSERT INTO IsoLanguagesDes VALUES (195,'nor','Indonesian');
INSERT INTO IsoLanguagesDes VALUES (196,'nor','Indo-European (Other)');
INSERT INTO IsoLanguagesDes VALUES (197,'nor','Ingush');
INSERT INTO IsoLanguagesDes VALUES (198,'nor','Inupiaq');
INSERT INTO IsoLanguagesDes VALUES (199,'nor','Iranian (Other)');
INSERT INTO IsoLanguagesDes VALUES (200,'nor','Iroquoian languages');
INSERT INTO IsoLanguagesDes VALUES (201,'nor','Italian');
INSERT INTO IsoLanguagesDes VALUES (202,'nor','Javanese');
INSERT INTO IsoLanguagesDes VALUES (203,'nor','Lojban');
INSERT INTO IsoLanguagesDes VALUES (204,'nor','Japanese');
INSERT INTO IsoLanguagesDes VALUES (205,'nor','Judeo-Persian');
INSERT INTO IsoLanguagesDes VALUES (206,'nor','Judeo-Arabic');
INSERT INTO IsoLanguagesDes VALUES (207,'nor','Kara-Kalpak');
INSERT INTO IsoLanguagesDes VALUES (208,'nor','Kabyle');
INSERT INTO IsoLanguagesDes VALUES (209,'nor','Kachin; Jingpho');
INSERT INTO IsoLanguagesDes VALUES (210,'nor','Kalaallisut; Greenlandic');
INSERT INTO IsoLanguagesDes VALUES (211,'nor','Kamba');
INSERT INTO IsoLanguagesDes VALUES (212,'nor','Kannada');
INSERT INTO IsoLanguagesDes VALUES (213,'nor','Karen languages');
INSERT INTO IsoLanguagesDes VALUES (214,'nor','Kashmiri');
INSERT INTO IsoLanguagesDes VALUES (215,'nor','Kanuri');
INSERT INTO IsoLanguagesDes VALUES (216,'nor','Kawi');
INSERT INTO IsoLanguagesDes VALUES (217,'nor','Kazakh');
INSERT INTO IsoLanguagesDes VALUES (218,'nor','Kabardian');
INSERT INTO IsoLanguagesDes VALUES (219,'nor','Khasi');
INSERT INTO IsoLanguagesDes VALUES (220,'nor','Khoisan (Other)');
INSERT INTO IsoLanguagesDes VALUES (221,'nor','Central Khmer');
INSERT INTO IsoLanguagesDes VALUES (222,'nor','Khotanese');
INSERT INTO IsoLanguagesDes VALUES (223,'nor','Kikuyu; Gikuyu');
INSERT INTO IsoLanguagesDes VALUES (224,'nor','Kinyarwanda');
INSERT INTO IsoLanguagesDes VALUES (225,'nor','Kirghiz; Kyrgyz');
INSERT INTO IsoLanguagesDes VALUES (226,'nor','Kimbundu');
INSERT INTO IsoLanguagesDes VALUES (227,'nor','Konkani');
INSERT INTO IsoLanguagesDes VALUES (228,'nor','Komi');
INSERT INTO IsoLanguagesDes VALUES (229,'nor','Kongo');
INSERT INTO IsoLanguagesDes VALUES (230,'nor','Korean');
INSERT INTO IsoLanguagesDes VALUES (231,'nor','Kosraean');
INSERT INTO IsoLanguagesDes VALUES (232,'nor','Kpelle');
INSERT INTO IsoLanguagesDes VALUES (233,'nor','Karachay-Balkar');
INSERT INTO IsoLanguagesDes VALUES (234,'nor','Karelian');
INSERT INTO IsoLanguagesDes VALUES (235,'nor','Kru languages');
INSERT INTO IsoLanguagesDes VALUES (236,'nor','Kurukh');
INSERT INTO IsoLanguagesDes VALUES (237,'nor','Kuanyama; Kwanyama');
INSERT INTO IsoLanguagesDes VALUES (238,'nor','Kumyk');
INSERT INTO IsoLanguagesDes VALUES (239,'nor','Kurdish');
INSERT INTO IsoLanguagesDes VALUES (240,'nor','Kutenai');
INSERT INTO IsoLanguagesDes VALUES (241,'nor','Ladino');
INSERT INTO IsoLanguagesDes VALUES (242,'nor','Lahnda');
INSERT INTO IsoLanguagesDes VALUES (243,'nor','Lamba');
INSERT INTO IsoLanguagesDes VALUES (244,'nor','Lao');
INSERT INTO IsoLanguagesDes VALUES (245,'nor','Latin');
INSERT INTO IsoLanguagesDes VALUES (246,'nor','Latvian');
INSERT INTO IsoLanguagesDes VALUES (247,'nor','Lezghian');
INSERT INTO IsoLanguagesDes VALUES (248,'nor','Limburgan; Limburger; Limburgish');
INSERT INTO IsoLanguagesDes VALUES (249,'nor','Lingala');
INSERT INTO IsoLanguagesDes VALUES (250,'nor','Lithuanian');
INSERT INTO IsoLanguagesDes VALUES (251,'nor','Mongo');
INSERT INTO IsoLanguagesDes VALUES (252,'nor','Lozi');
INSERT INTO IsoLanguagesDes VALUES (253,'nor','Luxembourgish; Letzeburgesch');
INSERT INTO IsoLanguagesDes VALUES (254,'nor','Luba-Lulua');
INSERT INTO IsoLanguagesDes VALUES (255,'nor','Luba-Katangaxon, Low');
INSERT INTO IsoLanguagesDes VALUES (256,'nor','Ganda');
INSERT INTO IsoLanguagesDes VALUES (257,'nor','Luiseno');
INSERT INTO IsoLanguagesDes VALUES (258,'nor','Lunda');
INSERT INTO IsoLanguagesDes VALUES (259,'nor','Luo (Kenya and Tanzania)');
INSERT INTO IsoLanguagesDes VALUES (260,'nor','Lushai');
INSERT INTO IsoLanguagesDes VALUES (261,'nor','Macedonian00E5l');
INSERT INTO IsoLanguagesDes VALUES (262,'nor','Madurese');
INSERT INTO IsoLanguagesDes VALUES (263,'nor','Magahi');
INSERT INTO IsoLanguagesDes VALUES (264,'nor','Marshallese');
INSERT INTO IsoLanguagesDes VALUES (265,'nor','Maithili');
INSERT INTO IsoLanguagesDes VALUES (266,'nor','Makasarl Nepal Bhasa');
INSERT INTO IsoLanguagesDes VALUES (267,'nor','Malayalam');
INSERT INTO IsoLanguagesDes VALUES (268,'nor','Mandingo');
INSERT INTO IsoLanguagesDes VALUES (269,'nor','Maori');
INSERT INTO IsoLanguagesDes VALUES (270,'nor','Austronesian (Other)');
INSERT INTO IsoLanguagesDes VALUES (271,'nor','Marathi');
INSERT INTO IsoLanguagesDes VALUES (272,'nor','Masai');
INSERT INTO IsoLanguagesDes VALUES (273,'nor','Malay');
INSERT INTO IsoLanguagesDes VALUES (274,'nor','Moksha');
INSERT INTO IsoLanguagesDes VALUES (275,'nor','Mandar');
INSERT INTO IsoLanguagesDes VALUES (276,'nor','Mende');
INSERT INTO IsoLanguagesDes VALUES (277,'nor','Irish, Middle (900-1200)');
INSERT INTO IsoLanguagesDes VALUES (278,'nor','Mi''kmaq; Micmac');
INSERT INTO IsoLanguagesDes VALUES (279,'nor','Minangkabau');
INSERT INTO IsoLanguagesDes VALUES (280,'nor','Miscellaneous languages');
INSERT INTO IsoLanguagesDes VALUES (281,'nor','Mon-Khmer (Other)');
INSERT INTO IsoLanguagesDes VALUES (282,'nor','Malagasy');
INSERT INTO IsoLanguagesDes VALUES (283,'nor','Maltese');
INSERT INTO IsoLanguagesDes VALUES (284,'nor','Manchu');
INSERT INTO IsoLanguagesDes VALUES (285,'nor','Manipuri');
INSERT INTO IsoLanguagesDes VALUES (286,'nor','Manobo languages');
INSERT INTO IsoLanguagesDes VALUES (287,'nor','Mohawk');
INSERT INTO IsoLanguagesDes VALUES (288,'nor','Moldavian');
INSERT INTO IsoLanguagesDes VALUES (289,'nor','Mongolian');
INSERT INTO IsoLanguagesDes VALUES (290,'nor','Mossi');
INSERT INTO IsoLanguagesDes VALUES (291,'nor','Multiple languages');
INSERT INTO IsoLanguagesDes VALUES (292,'nor','Munda languages');
INSERT INTO IsoLanguagesDes VALUES (293,'nor','Creek');
INSERT INTO IsoLanguagesDes VALUES (294,'nor','Mirandese');
INSERT INTO IsoLanguagesDes VALUES (295,'nor','Marwari');
INSERT INTO IsoLanguagesDes VALUES (296,'nor','Mayan languages');
INSERT INTO IsoLanguagesDes VALUES (297,'nor','Erzya');
INSERT INTO IsoLanguagesDes VALUES (298,'nor','Nahuatl languages');
INSERT INTO IsoLanguagesDes VALUES (299,'nor','North American Indian');
INSERT INTO IsoLanguagesDes VALUES (300,'nor','Neapolitan');
INSERT INTO IsoLanguagesDes VALUES (301,'nor','Nauru');
INSERT INTO IsoLanguagesDes VALUES (302,'nor','Navajo; Navaho');
INSERT INTO IsoLanguagesDes VALUES (303,'nor','Ndebele, South; South Ndebele');
INSERT INTO IsoLanguagesDes VALUES (304,'nor','Ndebele, North; North Ndebele');
INSERT INTO IsoLanguagesDes VALUES (305,'nor','Ndonga');
INSERT INTO IsoLanguagesDes VALUES (306,'nor','Low German; Low Saxon; German, Low; Sa');
INSERT INTO IsoLanguagesDes VALUES (307,'nor','Nepali');
INSERT INTO IsoLanguagesDes VALUES (308,'nor','Nepal Bhasa; Newari');
INSERT INTO IsoLanguagesDes VALUES (309,'nor','Nias');
INSERT INTO IsoLanguagesDes VALUES (310,'nor','Niger-Kordofanian (Other)');
INSERT INTO IsoLanguagesDes VALUES (311,'nor','Niuean');
INSERT INTO IsoLanguagesDes VALUES (312,'nor','Norwegian Nynorsk; Nynorsk, Norwegian');
INSERT INTO IsoLanguagesDes VALUES (313,'nor','Bokmål, Norwegian; Norwegian Bokmål');
INSERT INTO IsoLanguagesDes VALUES (314,'nor','Nogai');
INSERT INTO IsoLanguagesDes VALUES (315,'nor','Norse, Old');
INSERT INTO IsoLanguagesDes VALUES (316,'nor','Norwegian');
INSERT INTO IsoLanguagesDes VALUES (317,'nor','Pedi; Sepedi; Northern Sotho');
INSERT INTO IsoLanguagesDes VALUES (318,'nor','Nubian languages');
INSERT INTO IsoLanguagesDes VALUES (319,'nor','Classical Newari; Old Newari; Classica');
INSERT INTO IsoLanguagesDes VALUES (320,'nor','Chichewa; Chewa; Nyanja');
INSERT INTO IsoLanguagesDes VALUES (321,'nor','Nyamwezi');
INSERT INTO IsoLanguagesDes VALUES (322,'nor','Nyankole');
INSERT INTO IsoLanguagesDes VALUES (323,'nor','Nyoro');
INSERT INTO IsoLanguagesDes VALUES (324,'nor','Nzima');
INSERT INTO IsoLanguagesDes VALUES (325,'nor','Occitan (post 1500); Provençal');
INSERT INTO IsoLanguagesDes VALUES (326,'nor','Ojibwa');
INSERT INTO IsoLanguagesDes VALUES (327,'nor','Oriya');
INSERT INTO IsoLanguagesDes VALUES (328,'nor','Oromo');
INSERT INTO IsoLanguagesDes VALUES (329,'nor','Osage');
INSERT INTO IsoLanguagesDes VALUES (330,'nor','Ossetian; Ossetic');
INSERT INTO IsoLanguagesDes VALUES (331,'nor','Turkish, Ottoman (1500-1928)');
INSERT INTO IsoLanguagesDes VALUES (332,'nor','Otomian languages');
INSERT INTO IsoLanguagesDes VALUES (333,'nor','Papuan (Other)');
INSERT INTO IsoLanguagesDes VALUES (334,'nor','Pangasinan');
INSERT INTO IsoLanguagesDes VALUES (335,'nor','Pahlavi');
INSERT INTO IsoLanguagesDes VALUES (336,'nor','Pampanga');
INSERT INTO IsoLanguagesDes VALUES (337,'nor','Panjabi; Punjabi');
INSERT INTO IsoLanguagesDes VALUES (338,'nor','Papiamento');
INSERT INTO IsoLanguagesDes VALUES (339,'nor','Palauan');
INSERT INTO IsoLanguagesDes VALUES (340,'nor','Persian, Old (ca.600-400 B.C.)');
INSERT INTO IsoLanguagesDes VALUES (341,'nor','Persian');
INSERT INTO IsoLanguagesDes VALUES (342,'nor','Philippine (Other)');
INSERT INTO IsoLanguagesDes VALUES (343,'nor','Phoenician');
INSERT INTO IsoLanguagesDes VALUES (344,'nor','Pali');
INSERT INTO IsoLanguagesDes VALUES (345,'nor','Polish');
INSERT INTO IsoLanguagesDes VALUES (346,'nor','Pohnpeian');
INSERT INTO IsoLanguagesDes VALUES (347,'nor','Portuguese');
INSERT INTO IsoLanguagesDes VALUES (348,'nor','Prakrit languages');
INSERT INTO IsoLanguagesDes VALUES (349,'nor','Provençal, Old (to 1500)');
INSERT INTO IsoLanguagesDes VALUES (350,'nor','Pushto');
INSERT INTO IsoLanguagesDes VALUES (351,'nor','Reserved for local use');
INSERT INTO IsoLanguagesDes VALUES (352,'nor','Quechua');
INSERT INTO IsoLanguagesDes VALUES (353,'nor','Rajasthani');
INSERT INTO IsoLanguagesDes VALUES (354,'nor','Rapanui');
INSERT INTO IsoLanguagesDes VALUES (355,'nor','Rarotongan; Cook Islands Maori');
INSERT INTO IsoLanguagesDes VALUES (356,'nor','Romance (Other)');
INSERT INTO IsoLanguagesDes VALUES (357,'nor','Romansh');
INSERT INTO IsoLanguagesDes VALUES (358,'nor','Romany');
INSERT INTO IsoLanguagesDes VALUES (359,'nor','Romanian');
INSERT INTO IsoLanguagesDes VALUES (360,'nor','Rundi');
INSERT INTO IsoLanguagesDes VALUES (361,'nor','Aromanian; Arumanian; Macedo-Romanian');
INSERT INTO IsoLanguagesDes VALUES (362,'nor','Russian');
INSERT INTO IsoLanguagesDes VALUES (363,'nor','Sandawe');
INSERT INTO IsoLanguagesDes VALUES (364,'nor','Sango');
INSERT INTO IsoLanguagesDes VALUES (365,'nor','Yakut');
INSERT INTO IsoLanguagesDes VALUES (366,'nor','South American Indian (Other)');
INSERT INTO IsoLanguagesDes VALUES (367,'nor','Salishan languages');
INSERT INTO IsoLanguagesDes VALUES (368,'nor','Samaritan Aramaic');
INSERT INTO IsoLanguagesDes VALUES (369,'nor','Sanskrit');
INSERT INTO IsoLanguagesDes VALUES (370,'nor','Sasak');
INSERT INTO IsoLanguagesDes VALUES (371,'nor','Santali');
INSERT INTO IsoLanguagesDes VALUES (372,'nor','Serbian');
INSERT INTO IsoLanguagesDes VALUES (373,'nor','Sicilian');
INSERT INTO IsoLanguagesDes VALUES (374,'nor','Scots');
INSERT INTO IsoLanguagesDes VALUES (375,'nor','Croatian');
INSERT INTO IsoLanguagesDes VALUES (376,'nor','Selkup');
INSERT INTO IsoLanguagesDes VALUES (377,'nor','Semitic (Other)');
INSERT INTO IsoLanguagesDes VALUES (378,'nor','Irish, Old (to 900)');
INSERT INTO IsoLanguagesDes VALUES (379,'nor','Sign Languages');
INSERT INTO IsoLanguagesDes VALUES (380,'nor','Shan');
INSERT INTO IsoLanguagesDes VALUES (381,'nor','Sidamo');
INSERT INTO IsoLanguagesDes VALUES (382,'nor','Sinhala; Sinhalese');
INSERT INTO IsoLanguagesDes VALUES (383,'nor','Siouan languages');
INSERT INTO IsoLanguagesDes VALUES (384,'nor','Sino-Tibetan (Other)');
INSERT INTO IsoLanguagesDes VALUES (385,'nor','Slavic (Other)');
INSERT INTO IsoLanguagesDes VALUES (386,'nor','Slovak');
INSERT INTO IsoLanguagesDes VALUES (387,'nor','Slovenian');
INSERT INTO IsoLanguagesDes VALUES (388,'nor','Southern Sami');
INSERT INTO IsoLanguagesDes VALUES (389,'nor','Northern Sami');
INSERT INTO IsoLanguagesDes VALUES (390,'nor','Sami languages (Other)');
INSERT INTO IsoLanguagesDes VALUES (391,'nor','Lule Sami');
INSERT INTO IsoLanguagesDes VALUES (392,'nor','Inari Sami');
INSERT INTO IsoLanguagesDes VALUES (393,'nor','Samoan');
INSERT INTO IsoLanguagesDes VALUES (394,'nor','Skolt Sami');
INSERT INTO IsoLanguagesDes VALUES (395,'nor','Shona');
INSERT INTO IsoLanguagesDes VALUES (396,'nor','Sindhi');
INSERT INTO IsoLanguagesDes VALUES (397,'nor','Soninke');
INSERT INTO IsoLanguagesDes VALUES (398,'nor','Sogdian');
INSERT INTO IsoLanguagesDes VALUES (399,'nor','Somali');
INSERT INTO IsoLanguagesDes VALUES (400,'nor','Songhai languages');
INSERT INTO IsoLanguagesDes VALUES (401,'nor','Sotho, Southern');
INSERT INTO IsoLanguagesDes VALUES (402,'nor','Spanish; Castilian');
INSERT INTO IsoLanguagesDes VALUES (403,'nor','Sardinian; Zazaki');
INSERT INTO IsoLanguagesDes VALUES (404,'nor','Sranan Tongo');
INSERT INTO IsoLanguagesDes VALUES (405,'nor','Serer');
INSERT INTO IsoLanguagesDes VALUES (406,'nor','Nilo-Saharan (Other)');
INSERT INTO IsoLanguagesDes VALUES (407,'nor','Swati');
INSERT INTO IsoLanguagesDes VALUES (408,'nor','Sukuma');
INSERT INTO IsoLanguagesDes VALUES (409,'nor','Sundanese');
INSERT INTO IsoLanguagesDes VALUES (410,'nor','Susu');
INSERT INTO IsoLanguagesDes VALUES (411,'nor','Sumerian');
INSERT INTO IsoLanguagesDes VALUES (412,'nor','Swahili');
INSERT INTO IsoLanguagesDes VALUES (413,'nor','Swedish');
INSERT INTO IsoLanguagesDes VALUES (414,'nor','Syriac');
INSERT INTO IsoLanguagesDes VALUES (415,'nor','Tahitian');
INSERT INTO IsoLanguagesDes VALUES (416,'nor','Tai (Other)');
INSERT INTO IsoLanguagesDes VALUES (417,'nor','Tamil');
INSERT INTO IsoLanguagesDes VALUES (418,'nor','Tatar');
INSERT INTO IsoLanguagesDes VALUES (419,'nor','Telugu');
INSERT INTO IsoLanguagesDes VALUES (420,'nor','Timnendere)');
INSERT INTO IsoLanguagesDes VALUES (421,'nor','Tereno');
INSERT INTO IsoLanguagesDes VALUES (422,'nor','Tetum');
INSERT INTO IsoLanguagesDes VALUES (423,'nor','Tajik');
INSERT INTO IsoLanguagesDes VALUES (424,'nor','Tagalog');
INSERT INTO IsoLanguagesDes VALUES (425,'nor','Thai');
INSERT INTO IsoLanguagesDes VALUES (426,'nor','Tibetan');
INSERT INTO IsoLanguagesDes VALUES (427,'nor','Tigre');
INSERT INTO IsoLanguagesDes VALUES (428,'nor','Tigrinya');
INSERT INTO IsoLanguagesDes VALUES (429,'nor','Tiv');
INSERT INTO IsoLanguagesDes VALUES (430,'nor','Tokelau');
INSERT INTO IsoLanguagesDes VALUES (431,'nor','Klingon; tlhIngan-Hol');
INSERT INTO IsoLanguagesDes VALUES (432,'nor','Tlingit');
INSERT INTO IsoLanguagesDes VALUES (433,'nor','Tamashek');
INSERT INTO IsoLanguagesDes VALUES (434,'nor','Tonga (Nyasa)');
INSERT INTO IsoLanguagesDes VALUES (435,'nor','Tonga (Tonga Islands)');
INSERT INTO IsoLanguagesDes VALUES (436,'nor','Tok Pisin');
INSERT INTO IsoLanguagesDes VALUES (437,'nor','Tsimshian');
INSERT INTO IsoLanguagesDes VALUES (438,'nor','Tswana');
INSERT INTO IsoLanguagesDes VALUES (439,'nor','Tsonga');
INSERT INTO IsoLanguagesDes VALUES (440,'nor','Turkmen');
INSERT INTO IsoLanguagesDes VALUES (441,'nor','Tumbuka');
INSERT INTO IsoLanguagesDes VALUES (442,'nor','Tupi languages');
INSERT INTO IsoLanguagesDes VALUES (443,'nor','Turkish');
INSERT INTO IsoLanguagesDes VALUES (444,'nor','Altaic (Other)');
INSERT INTO IsoLanguagesDes VALUES (445,'nor','Tuvalu');
INSERT INTO IsoLanguagesDes VALUES (446,'nor','Twi');
INSERT INTO IsoLanguagesDes VALUES (447,'nor','Tuvinian');
INSERT INTO IsoLanguagesDes VALUES (448,'nor','Udmurt');
INSERT INTO IsoLanguagesDes VALUES (449,'nor','Ugaritic');
INSERT INTO IsoLanguagesDes VALUES (450,'nor','Uighur; Uyghur');
INSERT INTO IsoLanguagesDes VALUES (451,'nor','Ukrainian');
INSERT INTO IsoLanguagesDes VALUES (452,'nor','Umbundu');
INSERT INTO IsoLanguagesDes VALUES (453,'nor','Undetermined');
INSERT INTO IsoLanguagesDes VALUES (454,'nor','Urdu');
INSERT INTO IsoLanguagesDes VALUES (455,'nor','Uzbek');
INSERT INTO IsoLanguagesDes VALUES (456,'nor','Vai');
INSERT INTO IsoLanguagesDes VALUES (457,'nor','Venda');
INSERT INTO IsoLanguagesDes VALUES (458,'nor','Vietnamese');
INSERT INTO IsoLanguagesDes VALUES (459,'nor','Volapük');
INSERT INTO IsoLanguagesDes VALUES (460,'nor','Votic');
INSERT INTO IsoLanguagesDes VALUES (461,'nor','Wakashan languages');
INSERT INTO IsoLanguagesDes VALUES (462,'nor','Walamo');
INSERT INTO IsoLanguagesDes VALUES (463,'nor','Waray');
INSERT INTO IsoLanguagesDes VALUES (464,'nor','Washo');
INSERT INTO IsoLanguagesDes VALUES (465,'nor','Welsh');
INSERT INTO IsoLanguagesDes VALUES (466,'nor','Sorbian languages');
INSERT INTO IsoLanguagesDes VALUES (467,'nor','Walloon');
INSERT INTO IsoLanguagesDes VALUES (468,'nor','Wolof');
INSERT INTO IsoLanguagesDes VALUES (469,'nor','Kalmyk; Oirat');
INSERT INTO IsoLanguagesDes VALUES (470,'nor','Xhosa');
INSERT INTO IsoLanguagesDes VALUES (471,'nor','Yao');
INSERT INTO IsoLanguagesDes VALUES (472,'nor','Yapese');
INSERT INTO IsoLanguagesDes VALUES (473,'nor','Yiddish');
INSERT INTO IsoLanguagesDes VALUES (474,'nor','Yoruba');
INSERT INTO IsoLanguagesDes VALUES (475,'nor','Yupik languages');
INSERT INTO IsoLanguagesDes VALUES (476,'nor','Zapotec');
INSERT INTO IsoLanguagesDes VALUES (477,'nor','Zenaga');
INSERT INTO IsoLanguagesDes VALUES (478,'nor','Zhuang; Chuang');
INSERT INTO IsoLanguagesDes VALUES (479,'nor','Zande languages');
INSERT INTO IsoLanguagesDes VALUES (480,'nor','Zulu');
INSERT INTO IsoLanguagesDes VALUES (481,'nor','Zuni');
INSERT INTO IsoLanguagesDes VALUES (482,'nor','No linguistic content');
INSERT INTO IsoLanguagesDes VALUES (483,'nor','N''Ko');
INSERT INTO IsoLanguagesDes VALUES (484,'nor','Zaza; Dimili; Dimli; Kirdki; Kirmanjki');

INSERT INTO OperationsDes VALUES (0,'nor','Publisér');
INSERT INTO OperationsDes VALUES (1,'nor','Nedlasting');
INSERT INTO OperationsDes VALUES (2,'nor','Oppdatering');
INSERT INTO OperationsDes VALUES (3,'nor','Varsle');
INSERT INTO OperationsDes VALUES (5,'nor','Interaktivt kart');
INSERT INTO OperationsDes VALUES (6,'nor','Aktuelt');

INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (0,'nor','Unknown');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (1,'nor','Draft');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (2,'nor','Approved');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (3,'nor','Retired');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (4,'nor','Submitted');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (5,'nor','Rejected');

INSERT INTO RegionsDes VALUES (1,'nor','Armenia');
INSERT INTO RegionsDes VALUES (2,'nor','Afghanistan');
INSERT INTO RegionsDes VALUES (3,'nor','Albania');
INSERT INTO RegionsDes VALUES (4,'nor','Algeria');
INSERT INTO RegionsDes VALUES (5,'nor','American Samoa');
INSERT INTO RegionsDes VALUES (6,'nor','Andorra');
INSERT INTO RegionsDes VALUES (7,'nor','Angola');
INSERT INTO RegionsDes VALUES (8,'nor','Antigua and Barbuda');
INSERT INTO RegionsDes VALUES (9,'nor','Argentina');
INSERT INTO RegionsDes VALUES (10,'nor','Australia');
INSERT INTO RegionsDes VALUES (11,'nor','Austria');
INSERT INTO RegionsDes VALUES (12,'nor','Bahamas');
INSERT INTO RegionsDes VALUES (13,'nor','Bahrain');
INSERT INTO RegionsDes VALUES (14,'nor','Barbados');
INSERT INTO RegionsDes VALUES (16,'nor','Bangladesh');
INSERT INTO RegionsDes VALUES (17,'nor','Bermuda');
INSERT INTO RegionsDes VALUES (18,'nor','Bhutan');
INSERT INTO RegionsDes VALUES (19,'nor','Bolivia');
INSERT INTO RegionsDes VALUES (20,'nor','Botswana');
INSERT INTO RegionsDes VALUES (21,'nor','Brazil');
INSERT INTO RegionsDes VALUES (22,'nor','Aruba');
INSERT INTO RegionsDes VALUES (23,'nor','Belize');
INSERT INTO RegionsDes VALUES (24,'nor','British Indian Ocean Ter');
INSERT INTO RegionsDes VALUES (25,'nor','Solomon Islands');
INSERT INTO RegionsDes VALUES (26,'nor','Brunei Darussalam');
INSERT INTO RegionsDes VALUES (27,'nor','Bulgaria');
INSERT INTO RegionsDes VALUES (28,'nor','Myanmar');
INSERT INTO RegionsDes VALUES (29,'nor','Burundi');
INSERT INTO RegionsDes VALUES (30,'nor','Antarctica');
INSERT INTO RegionsDes VALUES (31,'nor','Bouvet Island');
INSERT INTO RegionsDes VALUES (32,'nor','Cameroon');
INSERT INTO RegionsDes VALUES (33,'nor','Canada');
INSERT INTO RegionsDes VALUES (35,'nor','Cape Verde');
INSERT INTO RegionsDes VALUES (36,'nor','Cayman Island');
INSERT INTO RegionsDes VALUES (37,'nor','Central African Republic');
INSERT INTO RegionsDes VALUES (38,'nor','Sri Lanka');
INSERT INTO RegionsDes VALUES (39,'nor','Chad');
INSERT INTO RegionsDes VALUES (40,'nor','Chile');
INSERT INTO RegionsDes VALUES (41,'nor','China, Mainland');
INSERT INTO RegionsDes VALUES (42,'nor','Christmas Island');
INSERT INTO RegionsDes VALUES (43,'nor','Cocos Islands');
INSERT INTO RegionsDes VALUES (44,'nor','Colombia');
INSERT INTO RegionsDes VALUES (45,'nor','Comoros');
INSERT INTO RegionsDes VALUES (46,'nor','Congo, Republic of');
INSERT INTO RegionsDes VALUES (47,'nor','Cook Islands');
INSERT INTO RegionsDes VALUES (48,'nor','Costa Rica');
INSERT INTO RegionsDes VALUES (49,'nor','Cuba');
INSERT INTO RegionsDes VALUES (50,'nor','Cyprus');
INSERT INTO RegionsDes VALUES (52,'nor','Azerbaijan, Republic of');
INSERT INTO RegionsDes VALUES (53,'nor','Benin');
INSERT INTO RegionsDes VALUES (54,'nor','Denmark');
INSERT INTO RegionsDes VALUES (55,'nor','Dominica');
INSERT INTO RegionsDes VALUES (56,'nor','Dominican Republic');
INSERT INTO RegionsDes VALUES (57,'nor','Belarus');
INSERT INTO RegionsDes VALUES (58,'nor','Ecuador');
INSERT INTO RegionsDes VALUES (59,'nor','Egypt');
INSERT INTO RegionsDes VALUES (60,'nor','El Salvador');
INSERT INTO RegionsDes VALUES (61,'nor','Equatorial Guinea');
INSERT INTO RegionsDes VALUES (63,'nor','Estonia');
INSERT INTO RegionsDes VALUES (64,'nor','Faeroe Islands');
INSERT INTO RegionsDes VALUES (65,'nor','Falkland Islands');
INSERT INTO RegionsDes VALUES (66,'nor','Fiji Islands');
INSERT INTO RegionsDes VALUES (67,'nor','Finland');
INSERT INTO RegionsDes VALUES (68,'nor','France');
INSERT INTO RegionsDes VALUES (69,'nor','French Guiana');
INSERT INTO RegionsDes VALUES (70,'nor','French Polynesia');
INSERT INTO RegionsDes VALUES (71,'nor','French South Terr');
INSERT INTO RegionsDes VALUES (72,'nor','Djibouti');
INSERT INTO RegionsDes VALUES (73,'nor','Georgia');
INSERT INTO RegionsDes VALUES (74,'nor','Gabon');
INSERT INTO RegionsDes VALUES (75,'nor','Gambia');
INSERT INTO RegionsDes VALUES (76,'nor','Gaza Strip');
INSERT INTO RegionsDes VALUES (79,'nor','Germany');
INSERT INTO RegionsDes VALUES (80,'nor','Bosnia and Herzegovina');
INSERT INTO RegionsDes VALUES (81,'nor','Ghana');
INSERT INTO RegionsDes VALUES (82,'nor','Gibraltar');
INSERT INTO RegionsDes VALUES (83,'nor','Kiribati');
INSERT INTO RegionsDes VALUES (84,'nor','Greece');
INSERT INTO RegionsDes VALUES (85,'nor','Greenland');
INSERT INTO RegionsDes VALUES (86,'nor','Grenada');
INSERT INTO RegionsDes VALUES (87,'nor','Guadeloupe');
INSERT INTO RegionsDes VALUES (88,'nor','Guam');
INSERT INTO RegionsDes VALUES (89,'nor','Guatemala');
INSERT INTO RegionsDes VALUES (90,'nor','Guinea');
INSERT INTO RegionsDes VALUES (91,'nor','Guyana');
INSERT INTO RegionsDes VALUES (92,'nor','Heard and McDonald Is');
INSERT INTO RegionsDes VALUES (93,'nor','Haiti');
INSERT INTO RegionsDes VALUES (95,'nor','Honduras');
INSERT INTO RegionsDes VALUES (97,'nor','Hungary');
INSERT INTO RegionsDes VALUES (98,'nor','Croatia');
INSERT INTO RegionsDes VALUES (99,'nor','Iceland');
INSERT INTO RegionsDes VALUES (100,'nor','India');
INSERT INTO RegionsDes VALUES (101,'nor','Indonesia');
INSERT INTO RegionsDes VALUES (102,'nor','Iran, Islamic Rep of');
INSERT INTO RegionsDes VALUES (103,'nor','Iraq');
INSERT INTO RegionsDes VALUES (104,'nor','Ireland');
INSERT INTO RegionsDes VALUES (105,'nor','Israel');
INSERT INTO RegionsDes VALUES (106,'nor','Italy');
INSERT INTO RegionsDes VALUES (107,'nor','Ivory Coast');
INSERT INTO RegionsDes VALUES (108,'nor','Kazakhstan');
INSERT INTO RegionsDes VALUES (109,'nor','Jamaica');
INSERT INTO RegionsDes VALUES (110,'nor','Japan');
INSERT INTO RegionsDes VALUES (112,'nor','Jordan');
INSERT INTO RegionsDes VALUES (113,'nor','Kyrgyzstan');
INSERT INTO RegionsDes VALUES (114,'nor','Kenya');
INSERT INTO RegionsDes VALUES (115,'nor','Cambodia');
INSERT INTO RegionsDes VALUES (116,'nor','Korea, Dem People''s Rep');
INSERT INTO RegionsDes VALUES (117,'nor','Korea, Republic of');
INSERT INTO RegionsDes VALUES (118,'nor','Kuwait');
INSERT INTO RegionsDes VALUES (119,'nor','Latvia');
INSERT INTO RegionsDes VALUES (120,'nor','Laos');
INSERT INTO RegionsDes VALUES (121,'nor','Lebanon');
INSERT INTO RegionsDes VALUES (122,'nor','Lesotho');
INSERT INTO RegionsDes VALUES (123,'nor','Liberia');
INSERT INTO RegionsDes VALUES (124,'nor','Libyan Arab Jamahiriya');
INSERT INTO RegionsDes VALUES (125,'nor','Liechtensten');
INSERT INTO RegionsDes VALUES (126,'nor','Lithuania');
INSERT INTO RegionsDes VALUES (127,'nor','Marshall Island');
INSERT INTO RegionsDes VALUES (129,'nor','Madagascar');
INSERT INTO RegionsDes VALUES (130,'nor','Malawi');
INSERT INTO RegionsDes VALUES (131,'nor','Malaysia');
INSERT INTO RegionsDes VALUES (132,'nor','Maldives');
INSERT INTO RegionsDes VALUES (133,'nor','Mali');
INSERT INTO RegionsDes VALUES (134,'nor','Malta');
INSERT INTO RegionsDes VALUES (135,'nor','Martinique');
INSERT INTO RegionsDes VALUES (136,'nor','Mauritania');
INSERT INTO RegionsDes VALUES (137,'nor','Mauritius');
INSERT INTO RegionsDes VALUES (138,'nor','Mexico');
INSERT INTO RegionsDes VALUES (139,'nor','Midway Islands');
INSERT INTO RegionsDes VALUES (140,'nor','Monaco');
INSERT INTO RegionsDes VALUES (141,'nor','Mongolia');
INSERT INTO RegionsDes VALUES (142,'nor','Montserrat');
INSERT INTO RegionsDes VALUES (143,'nor','Morocco');
INSERT INTO RegionsDes VALUES (144,'nor','Mozambique');
INSERT INTO RegionsDes VALUES (145,'nor','Micronesia,Fed States of');
INSERT INTO RegionsDes VALUES (146,'nor','Moldova, Republic of');
INSERT INTO RegionsDes VALUES (147,'nor','Namibia');
INSERT INTO RegionsDes VALUES (148,'nor','Nauru');
INSERT INTO RegionsDes VALUES (149,'nor','Nepal');
INSERT INTO RegionsDes VALUES (150,'nor','Netherlands');
INSERT INTO RegionsDes VALUES (151,'nor','Neth Antilles');
INSERT INTO RegionsDes VALUES (153,'nor','NewCaledonia');
INSERT INTO RegionsDes VALUES (154,'nor','Macedonia');
INSERT INTO RegionsDes VALUES (155,'nor','Vanuatu');
INSERT INTO RegionsDes VALUES (156,'nor','New Zealand');
INSERT INTO RegionsDes VALUES (157,'nor','Nicaragua');
INSERT INTO RegionsDes VALUES (158,'nor','Niger');
INSERT INTO RegionsDes VALUES (159,'nor','Nigeria');
INSERT INTO RegionsDes VALUES (160,'nor','Niue');
INSERT INTO RegionsDes VALUES (161,'nor','Norfolk Island');
INSERT INTO RegionsDes VALUES (162,'nor','Norway');
INSERT INTO RegionsDes VALUES (163,'nor','Northern Mariana Is');
INSERT INTO RegionsDes VALUES (165,'nor','Pakistan');
INSERT INTO RegionsDes VALUES (166,'nor','Panama');
INSERT INTO RegionsDes VALUES (167,'nor','Czech Republic');
INSERT INTO RegionsDes VALUES (168,'nor','Papua New Guinea');
INSERT INTO RegionsDes VALUES (169,'nor','Paraguay');
INSERT INTO RegionsDes VALUES (170,'nor','Peru');
INSERT INTO RegionsDes VALUES (171,'nor','Philippines');
INSERT INTO RegionsDes VALUES (172,'nor','Pitcairn Islands');
INSERT INTO RegionsDes VALUES (173,'nor','Poland');
INSERT INTO RegionsDes VALUES (174,'nor','Portugal');
INSERT INTO RegionsDes VALUES (175,'nor','Guinea-Bissau');
INSERT INTO RegionsDes VALUES (176,'nor','East Timor');
INSERT INTO RegionsDes VALUES (177,'nor','Puerto Rico');
INSERT INTO RegionsDes VALUES (178,'nor','Eritrea');
INSERT INTO RegionsDes VALUES (179,'nor','Qatar');
INSERT INTO RegionsDes VALUES (181,'nor','Zimbabwe');
INSERT INTO RegionsDes VALUES (182,'nor','Reunion');
INSERT INTO RegionsDes VALUES (183,'nor','Romania');
INSERT INTO RegionsDes VALUES (184,'nor','Rwanda');
INSERT INTO RegionsDes VALUES (185,'nor','Russian Federation');
INSERT INTO RegionsDes VALUES (187,'nor','Saint Helena');
INSERT INTO RegionsDes VALUES (188,'nor','Saint Kitts and Nevis');
INSERT INTO RegionsDes VALUES (189,'nor','Saint Lucia');
INSERT INTO RegionsDes VALUES (190,'nor','Saint Pierre & Miquelon');
INSERT INTO RegionsDes VALUES (191,'nor','Saint Vincent/Grenadines');
INSERT INTO RegionsDes VALUES (192,'nor','San Marino');
INSERT INTO RegionsDes VALUES (193,'nor','Sao Tome and Principe');
INSERT INTO RegionsDes VALUES (194,'nor','Saudi Arabia');
INSERT INTO RegionsDes VALUES (195,'nor','Senegal');
INSERT INTO RegionsDes VALUES (196,'nor','Seychelles');
INSERT INTO RegionsDes VALUES (197,'nor','Sierra Leone');
INSERT INTO RegionsDes VALUES (198,'nor','Slovenia');
INSERT INTO RegionsDes VALUES (199,'nor','Slovakia');
INSERT INTO RegionsDes VALUES (200,'nor','Singapore');
INSERT INTO RegionsDes VALUES (201,'nor','Somalia');
INSERT INTO RegionsDes VALUES (202,'nor','South Africa');
INSERT INTO RegionsDes VALUES (203,'nor','Spain');
INSERT INTO RegionsDes VALUES (205,'nor','Western Sahara');
INSERT INTO RegionsDes VALUES (206,'nor','Sudan');
INSERT INTO RegionsDes VALUES (207,'nor','Suriname');
INSERT INTO RegionsDes VALUES (208,'nor','Tajikistan');
INSERT INTO RegionsDes VALUES (209,'nor','Swaziland');
INSERT INTO RegionsDes VALUES (210,'nor','Sweden');
INSERT INTO RegionsDes VALUES (211,'nor','Switzerland');
INSERT INTO RegionsDes VALUES (212,'nor','Syrian Arab Republic');
INSERT INTO RegionsDes VALUES (213,'nor','Turkmenistan');
INSERT INTO RegionsDes VALUES (214,'nor','China, Taiwan Prov of');
INSERT INTO RegionsDes VALUES (215,'nor','Tanzania, United Rep of');
INSERT INTO RegionsDes VALUES (216,'nor','Thailand');
INSERT INTO RegionsDes VALUES (217,'nor','Togo');
INSERT INTO RegionsDes VALUES (218,'nor','Tokelau');
INSERT INTO RegionsDes VALUES (219,'nor','Tonga');
INSERT INTO RegionsDes VALUES (220,'nor','Trinidad and Tobago');
INSERT INTO RegionsDes VALUES (221,'nor','Oman');
INSERT INTO RegionsDes VALUES (222,'nor','Tunisia');
INSERT INTO RegionsDes VALUES (223,'nor','Turkey');
INSERT INTO RegionsDes VALUES (224,'nor','Turks and Caicos Is');
INSERT INTO RegionsDes VALUES (225,'nor','United Arab Emirates');
INSERT INTO RegionsDes VALUES (226,'nor','Uganda');
INSERT INTO RegionsDes VALUES (227,'nor','Tuvalu');
INSERT INTO RegionsDes VALUES (229,'nor','United Kingdom');
INSERT INTO RegionsDes VALUES (230,'nor','Ukraine');
INSERT INTO RegionsDes VALUES (231,'nor','United States of America');
INSERT INTO RegionsDes VALUES (232,'nor','US Minor Outlying Is');
INSERT INTO RegionsDes VALUES (233,'nor','Burkina Faso');
INSERT INTO RegionsDes VALUES (234,'nor','Uruguay');
INSERT INTO RegionsDes VALUES (235,'nor','Uzbekistan');
INSERT INTO RegionsDes VALUES (236,'nor','Venezuela');
INSERT INTO RegionsDes VALUES (237,'nor','Viet Nam');
INSERT INTO RegionsDes VALUES (238,'nor','Ethiopia');
INSERT INTO RegionsDes VALUES (239,'nor','British Virgin Island');
INSERT INTO RegionsDes VALUES (240,'nor','US Virgin Islands');
INSERT INTO RegionsDes VALUES (242,'nor','Wake Island');
INSERT INTO RegionsDes VALUES (243,'nor','Wallis and Futuna Is');
INSERT INTO RegionsDes VALUES (244,'nor','Samoa');
INSERT INTO RegionsDes VALUES (245,'nor','West Bank');
INSERT INTO RegionsDes VALUES (249,'nor','Yemen');
INSERT INTO RegionsDes VALUES (250,'nor','Congo, Dem Republic of');
INSERT INTO RegionsDes VALUES (251,'nor','Zambia');
INSERT INTO RegionsDes VALUES (255,'nor','Belgium');
INSERT INTO RegionsDes VALUES (256,'nor','Luxembourg');
INSERT INTO RegionsDes VALUES (258,'nor','Anguilla');
INSERT INTO RegionsDes VALUES (260,'nor','Svalbard Is');
INSERT INTO RegionsDes VALUES (264,'nor','Isle of Man');
INSERT INTO RegionsDes VALUES (270,'nor','Mayotte');
INSERT INTO RegionsDes VALUES (271,'nor','SouthGeorgia/Sandwich Is');
INSERT INTO RegionsDes VALUES (303,'nor','Western Europe');
INSERT INTO RegionsDes VALUES (307,'nor','Intergvt Author Devpment');
INSERT INTO RegionsDes VALUES (310,'nor','North Western Africa');
INSERT INTO RegionsDes VALUES (311,'nor','Western Africa');
INSERT INTO RegionsDes VALUES (312,'nor','Central Africa');
INSERT INTO RegionsDes VALUES (313,'nor','Eastern Africa');
INSERT INTO RegionsDes VALUES (314,'nor','Southern Africa');
INSERT INTO RegionsDes VALUES (315,'nor','Latin Amer & Caribbean');
INSERT INTO RegionsDes VALUES (316,'nor','Central America');
INSERT INTO RegionsDes VALUES (317,'nor','Caribbean');
INSERT INTO RegionsDes VALUES (318,'nor','South America');
INSERT INTO RegionsDes VALUES (319,'nor','Near East');
INSERT INTO RegionsDes VALUES (320,'nor','Near East in Africa');
INSERT INTO RegionsDes VALUES (321,'nor','Near East in Asia');
INSERT INTO RegionsDes VALUES (322,'nor','Far East');
INSERT INTO RegionsDes VALUES (323,'nor','South Asia');
INSERT INTO RegionsDes VALUES (324,'nor','East & South East Asia');
INSERT INTO RegionsDes VALUES (325,'nor','Near East and North Africa');
INSERT INTO RegionsDes VALUES (334,'nor','Eastern Europe');
INSERT INTO RegionsDes VALUES (335,'nor','Europe');
INSERT INTO RegionsDes VALUES (337,'nor','Asia');
INSERT INTO RegionsDes VALUES (338,'nor','Africa');
INSERT INTO RegionsDes VALUES (348,'nor','Latin America');
INSERT INTO RegionsDes VALUES (370,'nor','Serbia');
INSERT INTO RegionsDes VALUES (371,'nor','Montenegro');
INSERT INTO RegionsDes VALUES (390,'nor','South of Sahara');
INSERT INTO RegionsDes VALUES (421,'nor','North Africa');
INSERT INTO RegionsDes VALUES (427,'nor','Europe, Non-EU Countries');
INSERT INTO RegionsDes VALUES (428,'nor','North America');
INSERT INTO RegionsDes VALUES (469,'nor','USSR, Former Area of');
INSERT INTO RegionsDes VALUES (1008,'nor','Arctic Sea');
INSERT INTO RegionsDes VALUES (1009,'nor','Atlantic, Northwest');
INSERT INTO RegionsDes VALUES (1010,'nor','Atlantic, Northeast');
INSERT INTO RegionsDes VALUES (1011,'nor','Atlantic, Western Central');
INSERT INTO RegionsDes VALUES (1012,'nor','Atlantic, Eastern Central');
INSERT INTO RegionsDes VALUES (1013,'nor','Mediterran and Black Sea');
INSERT INTO RegionsDes VALUES (1014,'nor','Atlantic, Southwest');
INSERT INTO RegionsDes VALUES (1015,'nor','Atlantic, Southeast');
INSERT INTO RegionsDes VALUES (1016,'nor','Atlantic, Antarctic');
INSERT INTO RegionsDes VALUES (1017,'nor','Indian Ocean, Western');
INSERT INTO RegionsDes VALUES (1018,'nor','Indian Ocean, Eastern');
INSERT INTO RegionsDes VALUES (1019,'nor','Indian Ocean, Antarctic');
INSERT INTO RegionsDes VALUES (1020,'nor','Pacific, Northwest');
INSERT INTO RegionsDes VALUES (1021,'nor','Pacific, Northeast');
INSERT INTO RegionsDes VALUES (1022,'nor','Pacific, Western Central');
INSERT INTO RegionsDes VALUES (1023,'nor','Pacific, Eastern Central');
INSERT INTO RegionsDes VALUES (1024,'nor','Pacific, Southwest');
INSERT INTO RegionsDes VALUES (1025,'nor','Pacific, Southeast');
INSERT INTO RegionsDes VALUES (1026,'nor','Pacific, Antarctic');
INSERT INTO RegionsDes VALUES (1220,'nor','All fishing areas');
INSERT INTO RegionsDes VALUES (9999,'nor','World');
