-- New for 2.8
INSERT INTO Languages VALUES ('pol','Polski', 'n', 'n');

-- Take care to table ID (related to other loc files)
INSERT INTO CswServerCapabilitiesInfo VALUES (61, 'pol', 'title', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (62, 'pol', 'abstract', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (63, 'pol', 'fees', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (64, 'pol', 'accessConstraints', '');

INSERT INTO CategoriesDes (iddes, langid, label) VALUES (1,'pol','Mapy i grafika');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (2,'pol','Zbiory danych');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (3,'pol','Źródła interaktywne');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (4,'pol','Aplikacje');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (5,'pol','Badania, najlepsze praktyki');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (6,'pol','Materiały konferencyjne');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (7,'pol','Zdjęcia');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (8,'pol','Audio/Wideo');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (9,'pol','Katalogi');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (10,'pol','Inne źródła informacji');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (11,'pol','Serwery Z3950');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (12,'pol','Rejestry');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (13,'pol','Physical Samples');

INSERT INTO GroupsDes (iddes, langid, label) VALUES (-1,'pol','Gość');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (0,'pol','Intranet');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (1,'pol','Wszyscy');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (2,'pol','Przykładowa grupa');

INSERT INTO IsoLanguagesDes VALUES (1,'pol','Afar');
INSERT INTO IsoLanguagesDes VALUES (2,'pol','Abkhazian');
INSERT INTO IsoLanguagesDes VALUES (3,'pol','Achinese');
INSERT INTO IsoLanguagesDes VALUES (4,'pol','Acoli');
INSERT INTO IsoLanguagesDes VALUES (5,'pol','Adangme');
INSERT INTO IsoLanguagesDes VALUES (6,'pol','Adyghe; Adygei');
INSERT INTO IsoLanguagesDes VALUES (7,'pol','Afro-Asiatic (Other)');
INSERT INTO IsoLanguagesDes VALUES (8,'pol','Afrihili');
INSERT INTO IsoLanguagesDes VALUES (9,'pol','Afrikaans');
INSERT INTO IsoLanguagesDes VALUES (10,'pol','Ainu');
INSERT INTO IsoLanguagesDes VALUES (11,'pol','Akan');
INSERT INTO IsoLanguagesDes VALUES (12,'pol','Akkadian');
INSERT INTO IsoLanguagesDes VALUES (13,'pol','Albanian');
INSERT INTO IsoLanguagesDes VALUES (14,'pol','Aleut');
INSERT INTO IsoLanguagesDes VALUES (15,'pol','Algonquian languages');
INSERT INTO IsoLanguagesDes VALUES (16,'pol','Southern Altai');
INSERT INTO IsoLanguagesDes VALUES (17,'pol','Amharic');
INSERT INTO IsoLanguagesDes VALUES (18,'pol','English, Old (ca.450-1100)');
INSERT INTO IsoLanguagesDes VALUES (19,'pol','Angika');
INSERT INTO IsoLanguagesDes VALUES (20,'pol','Apache languages');
INSERT INTO IsoLanguagesDes VALUES (21,'pol','Arabic');
INSERT INTO IsoLanguagesDes VALUES (22,'pol','Aramaic');
INSERT INTO IsoLanguagesDes VALUES (23,'pol','Aragonese');
INSERT INTO IsoLanguagesDes VALUES (24,'pol','Armenian');
INSERT INTO IsoLanguagesDes VALUES (25,'pol','Mapudungun; Mapuche');
INSERT INTO IsoLanguagesDes VALUES (26,'pol','Arapaho');
INSERT INTO IsoLanguagesDes VALUES (27,'pol','Artificial (Other)');
INSERT INTO IsoLanguagesDes VALUES (28,'pol','Arawak');
INSERT INTO IsoLanguagesDes VALUES (29,'pol','Assamese');
INSERT INTO IsoLanguagesDes VALUES (30,'pol','Asturian; Bable');
INSERT INTO IsoLanguagesDes VALUES (31,'pol','Athapascan languages');
INSERT INTO IsoLanguagesDes VALUES (32,'pol','Australian languages');
INSERT INTO IsoLanguagesDes VALUES (33,'pol','Avaric');
INSERT INTO IsoLanguagesDes VALUES (34,'pol','Avestan');
INSERT INTO IsoLanguagesDes VALUES (35,'pol','Awadhi');
INSERT INTO IsoLanguagesDes VALUES (36,'pol','Aymara');
INSERT INTO IsoLanguagesDes VALUES (37,'pol','Azerbaijani');
INSERT INTO IsoLanguagesDes VALUES (38,'pol','Banda languages');
INSERT INTO IsoLanguagesDes VALUES (39,'pol','Bamileke languages');
INSERT INTO IsoLanguagesDes VALUES (40,'pol','Bashkir');
INSERT INTO IsoLanguagesDes VALUES (41,'pol','Baluchi');
INSERT INTO IsoLanguagesDes VALUES (42,'pol','Bambara');
INSERT INTO IsoLanguagesDes VALUES (43,'pol','Balinese');
INSERT INTO IsoLanguagesDes VALUES (44,'pol','Basque');
INSERT INTO IsoLanguagesDes VALUES (45,'pol','Basa');
INSERT INTO IsoLanguagesDes VALUES (46,'pol','Baltic (Other)');
INSERT INTO IsoLanguagesDes VALUES (47,'pol','Beja');
INSERT INTO IsoLanguagesDes VALUES (48,'pol','Belarusian');
INSERT INTO IsoLanguagesDes VALUES (49,'pol','Bemba');
INSERT INTO IsoLanguagesDes VALUES (50,'pol','Bengali');
INSERT INTO IsoLanguagesDes VALUES (51,'pol','Berber (Other)');
INSERT INTO IsoLanguagesDes VALUES (52,'pol','Bhojpuri');
INSERT INTO IsoLanguagesDes VALUES (53,'pol','Bihari');
INSERT INTO IsoLanguagesDes VALUES (54,'pol','Bikol');
INSERT INTO IsoLanguagesDes VALUES (55,'pol','Bini; Edo');
INSERT INTO IsoLanguagesDes VALUES (56,'pol','Bislama');
INSERT INTO IsoLanguagesDes VALUES (57,'pol','Siksika');
INSERT INTO IsoLanguagesDes VALUES (58,'pol','Bantu (Other)');
INSERT INTO IsoLanguagesDes VALUES (59,'pol','Bosnian');
INSERT INTO IsoLanguagesDes VALUES (60,'pol','Braj');
INSERT INTO IsoLanguagesDes VALUES (61,'pol','Breton');
INSERT INTO IsoLanguagesDes VALUES (62,'pol','Batak languages');
INSERT INTO IsoLanguagesDes VALUES (63,'pol','Buriat');
INSERT INTO IsoLanguagesDes VALUES (64,'pol','Buginese');
INSERT INTO IsoLanguagesDes VALUES (65,'pol','Bulgarian');
INSERT INTO IsoLanguagesDes VALUES (66,'pol','Burmese');
INSERT INTO IsoLanguagesDes VALUES (67,'pol','Blin; Bilin');
INSERT INTO IsoLanguagesDes VALUES (68,'pol','Caddo');
INSERT INTO IsoLanguagesDes VALUES (69,'pol','Central American Indian (Other)');
INSERT INTO IsoLanguagesDes VALUES (70,'pol','Galibi Carib');
INSERT INTO IsoLanguagesDes VALUES (71,'pol','Catalan; Valencian');
INSERT INTO IsoLanguagesDes VALUES (72,'pol','Caucasian (Other)on liturgique; vieux bulgare');
INSERT INTO IsoLanguagesDes VALUES (73,'pol','Cebuano');
INSERT INTO IsoLanguagesDes VALUES (74,'pol','Celtic (Other)');
INSERT INTO IsoLanguagesDes VALUES (75,'pol','Chamorro');
INSERT INTO IsoLanguagesDes VALUES (76,'pol','Chibcha');
INSERT INTO IsoLanguagesDes VALUES (77,'pol','Chechen');
INSERT INTO IsoLanguagesDes VALUES (78,'pol','Chagataier)');
INSERT INTO IsoLanguagesDes VALUES (79,'pol','Chinese(Other)');
INSERT INTO IsoLanguagesDes VALUES (80,'pol','Chuukese');
INSERT INTO IsoLanguagesDes VALUES (81,'pol','Mari');
INSERT INTO IsoLanguagesDes VALUES (82,'pol','Chinook jargon');
INSERT INTO IsoLanguagesDes VALUES (83,'pol','Choctaw');
INSERT INTO IsoLanguagesDes VALUES (84,'pol','Chipewyan');
INSERT INTO IsoLanguagesDes VALUES (85,'pol','Cherokee');
INSERT INTO IsoLanguagesDes VALUES (86,'pol','Church Slavic; Old Slavonic; Church Sl');
INSERT INTO IsoLanguagesDes VALUES (87,'pol','Chuvash');
INSERT INTO IsoLanguagesDes VALUES (88,'pol','Cheyenne');
INSERT INTO IsoLanguagesDes VALUES (89,'pol','Chamic languages');
INSERT INTO IsoLanguagesDes VALUES (90,'pol','Coptic');
INSERT INTO IsoLanguagesDes VALUES (91,'pol','Cornish');
INSERT INTO IsoLanguagesDes VALUES (92,'pol','Corsican');
INSERT INTO IsoLanguagesDes VALUES (93,'pol','Creoles and pidgins, English based (Ot');
INSERT INTO IsoLanguagesDes VALUES (94,'pol','Creoles and pidgins, French-based (Oth');
INSERT INTO IsoLanguagesDes VALUES (95,'pol','Creoles and pidgins, Portuguese-based ');
INSERT INTO IsoLanguagesDes VALUES (96,'pol','Cree');
INSERT INTO IsoLanguagesDes VALUES (97,'pol','Crimean Tatar; Crimean Turkish');
INSERT INTO IsoLanguagesDes VALUES (98,'pol','Creoles and pidgins (Other)');
INSERT INTO IsoLanguagesDes VALUES (99,'pol','Kashubian');
INSERT INTO IsoLanguagesDes VALUES (100,'pol','Cushitic (Other)');
INSERT INTO IsoLanguagesDes VALUES (101,'pol','Czech');
INSERT INTO IsoLanguagesDes VALUES (102,'pol','Dakota');
INSERT INTO IsoLanguagesDes VALUES (103,'pol','Danish');
INSERT INTO IsoLanguagesDes VALUES (104,'pol','Dargwa');
INSERT INTO IsoLanguagesDes VALUES (105,'pol','Land Dayak languages');
INSERT INTO IsoLanguagesDes VALUES (106,'pol','Delaware');
INSERT INTO IsoLanguagesDes VALUES (107,'pol','Slave (Athapascan)');
INSERT INTO IsoLanguagesDes VALUES (108,'pol','Dogrib');
INSERT INTO IsoLanguagesDes VALUES (109,'pol','Dinka');
INSERT INTO IsoLanguagesDes VALUES (110,'pol','Divehi; Dhivehi; Maldivian');
INSERT INTO IsoLanguagesDes VALUES (111,'pol','Dogri');
INSERT INTO IsoLanguagesDes VALUES (112,'pol','Dravidian (Other)');
INSERT INTO IsoLanguagesDes VALUES (113,'pol','Lower Sorbian');
INSERT INTO IsoLanguagesDes VALUES (114,'pol','Duala');
INSERT INTO IsoLanguagesDes VALUES (115,'pol','Dutch, Middle (ca.1050-1350)');
INSERT INTO IsoLanguagesDes VALUES (116,'pol','Dutch; Flemish');
INSERT INTO IsoLanguagesDes VALUES (117,'pol','Dyula');
INSERT INTO IsoLanguagesDes VALUES (118,'pol','Dzongkha');
INSERT INTO IsoLanguagesDes VALUES (119,'pol','Efik');
INSERT INTO IsoLanguagesDes VALUES (120,'pol','Egyptian (Ancient)');
INSERT INTO IsoLanguagesDes VALUES (121,'pol','Ekajuk');
INSERT INTO IsoLanguagesDes VALUES (122,'pol','Elamite');
INSERT INTO IsoLanguagesDes VALUES (123,'pol','English');
INSERT INTO IsoLanguagesDes VALUES (124,'pol','English, Middle (1100-1500)');
INSERT INTO IsoLanguagesDes VALUES (125,'pol','Esperanto');
INSERT INTO IsoLanguagesDes VALUES (126,'pol','Estonian');
INSERT INTO IsoLanguagesDes VALUES (127,'pol','Ewe');
INSERT INTO IsoLanguagesDes VALUES (128,'pol','Ewondo');
INSERT INTO IsoLanguagesDes VALUES (129,'pol','Fang');
INSERT INTO IsoLanguagesDes VALUES (130,'pol','Faroese');
INSERT INTO IsoLanguagesDes VALUES (131,'pol','Fanti');
INSERT INTO IsoLanguagesDes VALUES (132,'pol','Fijian');
INSERT INTO IsoLanguagesDes VALUES (133,'pol','Filipino; Pilipino');
INSERT INTO IsoLanguagesDes VALUES (134,'pol','Finnish');
INSERT INTO IsoLanguagesDes VALUES (135,'pol','Finno-Ugrian (Other)');
INSERT INTO IsoLanguagesDes VALUES (136,'pol','Fon');
INSERT INTO IsoLanguagesDes VALUES (137,'pol','French');
INSERT INTO IsoLanguagesDes VALUES (138,'pol','French, Middle (ca.1400-1600)');
INSERT INTO IsoLanguagesDes VALUES (139,'pol','French, Old (842-ca.1400)');
INSERT INTO IsoLanguagesDes VALUES (140,'pol','Northern Frisian');
INSERT INTO IsoLanguagesDes VALUES (141,'pol','Eastern Frisian');
INSERT INTO IsoLanguagesDes VALUES (142,'pol','Western Frisian');
INSERT INTO IsoLanguagesDes VALUES (143,'pol','Fulah');
INSERT INTO IsoLanguagesDes VALUES (144,'pol','Friulian');
INSERT INTO IsoLanguagesDes VALUES (145,'pol','Ga');
INSERT INTO IsoLanguagesDes VALUES (146,'pol','Gayo');
INSERT INTO IsoLanguagesDes VALUES (147,'pol','Gbaya');
INSERT INTO IsoLanguagesDes VALUES (148,'pol','Germanic (Other)');
INSERT INTO IsoLanguagesDes VALUES (149,'pol','Georgian');
INSERT INTO IsoLanguagesDes VALUES (150,'pol','German');
INSERT INTO IsoLanguagesDes VALUES (151,'pol','Geez');
INSERT INTO IsoLanguagesDes VALUES (152,'pol','Gilbertese');
INSERT INTO IsoLanguagesDes VALUES (153,'pol','Gaelic; Scottish Gaelic');
INSERT INTO IsoLanguagesDes VALUES (154,'pol','Irish');
INSERT INTO IsoLanguagesDes VALUES (155,'pol','Galician');
INSERT INTO IsoLanguagesDes VALUES (156,'pol','Manx');
INSERT INTO IsoLanguagesDes VALUES (157,'pol','German, Middle High (ca.1050-1500)');
INSERT INTO IsoLanguagesDes VALUES (158,'pol','German, Old High (ca.750-1050)');
INSERT INTO IsoLanguagesDes VALUES (159,'pol','Gondi');
INSERT INTO IsoLanguagesDes VALUES (160,'pol','Gorontalo');
INSERT INTO IsoLanguagesDes VALUES (161,'pol','Gothicanguage Association)');
INSERT INTO IsoLanguagesDes VALUES (162,'pol','Grebo');
INSERT INTO IsoLanguagesDes VALUES (163,'pol','Greek, Ancient (to 1453)');
INSERT INTO IsoLanguagesDes VALUES (164,'pol','Greek, Modern (1453-)');
INSERT INTO IsoLanguagesDes VALUES (165,'pol','Guarani');
INSERT INTO IsoLanguagesDes VALUES (166,'pol','Swiss German; Alemannic');
INSERT INTO IsoLanguagesDes VALUES (167,'pol','Gujarati');
INSERT INTO IsoLanguagesDes VALUES (168,'pol','Gwich''in');
INSERT INTO IsoLanguagesDes VALUES (169,'pol','Haida');
INSERT INTO IsoLanguagesDes VALUES (170,'pol','Haitian; Haitian Creole');
INSERT INTO IsoLanguagesDes VALUES (171,'pol','Hausa');
INSERT INTO IsoLanguagesDes VALUES (172,'pol','Hawaiian');
INSERT INTO IsoLanguagesDes VALUES (173,'pol','Hebrew');
INSERT INTO IsoLanguagesDes VALUES (174,'pol','Herero');
INSERT INTO IsoLanguagesDes VALUES (175,'pol','Hiligaynon');
INSERT INTO IsoLanguagesDes VALUES (176,'pol','Himachali');
INSERT INTO IsoLanguagesDes VALUES (177,'pol','Hindi');
INSERT INTO IsoLanguagesDes VALUES (178,'pol','Hittite');
INSERT INTO IsoLanguagesDes VALUES (179,'pol','Hmong');
INSERT INTO IsoLanguagesDes VALUES (180,'pol','Hiri Motu');
INSERT INTO IsoLanguagesDes VALUES (181,'pol','Upper Sorbian');
INSERT INTO IsoLanguagesDes VALUES (182,'pol','Hungarian');
INSERT INTO IsoLanguagesDes VALUES (183,'pol','Hupa');
INSERT INTO IsoLanguagesDes VALUES (184,'pol','Iban');
INSERT INTO IsoLanguagesDes VALUES (185,'pol','Igbo');
INSERT INTO IsoLanguagesDes VALUES (186,'pol','Icelandic');
INSERT INTO IsoLanguagesDes VALUES (187,'pol','Ido');
INSERT INTO IsoLanguagesDes VALUES (188,'pol','Sichuan Yi');
INSERT INTO IsoLanguagesDes VALUES (189,'pol','Ijo languages');
INSERT INTO IsoLanguagesDes VALUES (190,'pol','Inuktitut');
INSERT INTO IsoLanguagesDes VALUES (191,'pol','Interlingue');
INSERT INTO IsoLanguagesDes VALUES (192,'pol','Iloko');
INSERT INTO IsoLanguagesDes VALUES (193,'pol','Interlingua (International Auxiliary L');
INSERT INTO IsoLanguagesDes VALUES (194,'pol','Indic (Other)');
INSERT INTO IsoLanguagesDes VALUES (195,'pol','Indonesian');
INSERT INTO IsoLanguagesDes VALUES (196,'pol','Indo-European (Other)');
INSERT INTO IsoLanguagesDes VALUES (197,'pol','Ingush');
INSERT INTO IsoLanguagesDes VALUES (198,'pol','Inupiaq');
INSERT INTO IsoLanguagesDes VALUES (199,'pol','Iranian (Other)');
INSERT INTO IsoLanguagesDes VALUES (200,'pol','Iroquoian languages');
INSERT INTO IsoLanguagesDes VALUES (201,'pol','Italian');
INSERT INTO IsoLanguagesDes VALUES (202,'pol','Javanese');
INSERT INTO IsoLanguagesDes VALUES (203,'pol','Lojban');
INSERT INTO IsoLanguagesDes VALUES (204,'pol','Japanese');
INSERT INTO IsoLanguagesDes VALUES (205,'pol','Judeo-Persian');
INSERT INTO IsoLanguagesDes VALUES (206,'pol','Judeo-Arabic');
INSERT INTO IsoLanguagesDes VALUES (207,'pol','Kara-Kalpak');
INSERT INTO IsoLanguagesDes VALUES (208,'pol','Kabyle');
INSERT INTO IsoLanguagesDes VALUES (209,'pol','Kachin; Jingpho');
INSERT INTO IsoLanguagesDes VALUES (210,'pol','Kalaallisut; Greenlandic');
INSERT INTO IsoLanguagesDes VALUES (211,'pol','Kamba');
INSERT INTO IsoLanguagesDes VALUES (212,'pol','Kannada');
INSERT INTO IsoLanguagesDes VALUES (213,'pol','Karen languages');
INSERT INTO IsoLanguagesDes VALUES (214,'pol','Kashmiri');
INSERT INTO IsoLanguagesDes VALUES (215,'pol','Kanuri');
INSERT INTO IsoLanguagesDes VALUES (216,'pol','Kawi');
INSERT INTO IsoLanguagesDes VALUES (217,'pol','Kazakh');
INSERT INTO IsoLanguagesDes VALUES (218,'pol','Kabardian');
INSERT INTO IsoLanguagesDes VALUES (219,'pol','Khasi');
INSERT INTO IsoLanguagesDes VALUES (220,'pol','Khoisan (Other)');
INSERT INTO IsoLanguagesDes VALUES (221,'pol','Central Khmer');
INSERT INTO IsoLanguagesDes VALUES (222,'pol','Khotanese');
INSERT INTO IsoLanguagesDes VALUES (223,'pol','Kikuyu; Gikuyu');
INSERT INTO IsoLanguagesDes VALUES (224,'pol','Kinyarwanda');
INSERT INTO IsoLanguagesDes VALUES (225,'pol','Kirghiz; Kyrgyz');
INSERT INTO IsoLanguagesDes VALUES (226,'pol','Kimbundu');
INSERT INTO IsoLanguagesDes VALUES (227,'pol','Konkani');
INSERT INTO IsoLanguagesDes VALUES (228,'pol','Komi');
INSERT INTO IsoLanguagesDes VALUES (229,'pol','Kongo');
INSERT INTO IsoLanguagesDes VALUES (230,'pol','Korean');
INSERT INTO IsoLanguagesDes VALUES (231,'pol','Kosraean');
INSERT INTO IsoLanguagesDes VALUES (232,'pol','Kpelle');
INSERT INTO IsoLanguagesDes VALUES (233,'pol','Karachay-Balkar');
INSERT INTO IsoLanguagesDes VALUES (234,'pol','Karelian');
INSERT INTO IsoLanguagesDes VALUES (235,'pol','Kru languages');
INSERT INTO IsoLanguagesDes VALUES (236,'pol','Kurukh');
INSERT INTO IsoLanguagesDes VALUES (237,'pol','Kuanyama; Kwanyama');
INSERT INTO IsoLanguagesDes VALUES (238,'pol','Kumyk');
INSERT INTO IsoLanguagesDes VALUES (239,'pol','Kurdish');
INSERT INTO IsoLanguagesDes VALUES (240,'pol','Kutenai');
INSERT INTO IsoLanguagesDes VALUES (241,'pol','Ladino');
INSERT INTO IsoLanguagesDes VALUES (242,'pol','Lahnda');
INSERT INTO IsoLanguagesDes VALUES (243,'pol','Lamba');
INSERT INTO IsoLanguagesDes VALUES (244,'pol','Lao');
INSERT INTO IsoLanguagesDes VALUES (245,'pol','Latin');
INSERT INTO IsoLanguagesDes VALUES (246,'pol','Latvian');
INSERT INTO IsoLanguagesDes VALUES (247,'pol','Lezghian');
INSERT INTO IsoLanguagesDes VALUES (248,'pol','Limburgan; Limburger; Limburgish');
INSERT INTO IsoLanguagesDes VALUES (249,'pol','Lingala');
INSERT INTO IsoLanguagesDes VALUES (250,'pol','Lithuanian');
INSERT INTO IsoLanguagesDes VALUES (251,'pol','Mongo');
INSERT INTO IsoLanguagesDes VALUES (252,'pol','Lozi');
INSERT INTO IsoLanguagesDes VALUES (253,'pol','Luxembourgish; Letzeburgesch');
INSERT INTO IsoLanguagesDes VALUES (254,'pol','Luba-Lulua');
INSERT INTO IsoLanguagesDes VALUES (255,'pol','Luba-Katangaxon, Low');
INSERT INTO IsoLanguagesDes VALUES (256,'pol','Ganda');
INSERT INTO IsoLanguagesDes VALUES (257,'pol','Luiseno');
INSERT INTO IsoLanguagesDes VALUES (258,'pol','Lunda');
INSERT INTO IsoLanguagesDes VALUES (259,'pol','Luo (Kenya and Tanzania)');
INSERT INTO IsoLanguagesDes VALUES (260,'pol','Lushai');
INSERT INTO IsoLanguagesDes VALUES (261,'pol','Macedonian00E5l');
INSERT INTO IsoLanguagesDes VALUES (262,'pol','Madurese');
INSERT INTO IsoLanguagesDes VALUES (263,'pol','Magahi');
INSERT INTO IsoLanguagesDes VALUES (264,'pol','Marshallese');
INSERT INTO IsoLanguagesDes VALUES (265,'pol','Maithili');
INSERT INTO IsoLanguagesDes VALUES (266,'pol','Makasarl Nepal Bhasa');
INSERT INTO IsoLanguagesDes VALUES (267,'pol','Malayalam');
INSERT INTO IsoLanguagesDes VALUES (268,'pol','Mandingo');
INSERT INTO IsoLanguagesDes VALUES (269,'pol','Maori');
INSERT INTO IsoLanguagesDes VALUES (270,'pol','Austronesian (Other)');
INSERT INTO IsoLanguagesDes VALUES (271,'pol','Marathi');
INSERT INTO IsoLanguagesDes VALUES (272,'pol','Masai');
INSERT INTO IsoLanguagesDes VALUES (273,'pol','Malay');
INSERT INTO IsoLanguagesDes VALUES (274,'pol','Moksha');
INSERT INTO IsoLanguagesDes VALUES (275,'pol','Mandar');
INSERT INTO IsoLanguagesDes VALUES (276,'pol','Mende');
INSERT INTO IsoLanguagesDes VALUES (277,'pol','Irish, Middle (900-1200)');
INSERT INTO IsoLanguagesDes VALUES (278,'pol','Mi''kmaq; Micmac');
INSERT INTO IsoLanguagesDes VALUES (279,'pol','Minangkabau');
INSERT INTO IsoLanguagesDes VALUES (280,'pol','Miscellaneous languages');
INSERT INTO IsoLanguagesDes VALUES (281,'pol','Mon-Khmer (Other)');
INSERT INTO IsoLanguagesDes VALUES (282,'pol','Malagasy');
INSERT INTO IsoLanguagesDes VALUES (283,'pol','Maltese');
INSERT INTO IsoLanguagesDes VALUES (284,'pol','Manchu');
INSERT INTO IsoLanguagesDes VALUES (285,'pol','Manipuri');
INSERT INTO IsoLanguagesDes VALUES (286,'pol','Manobo languages');
INSERT INTO IsoLanguagesDes VALUES (287,'pol','Mohawk');
INSERT INTO IsoLanguagesDes VALUES (288,'pol','Moldavian');
INSERT INTO IsoLanguagesDes VALUES (289,'pol','Mongolian');
INSERT INTO IsoLanguagesDes VALUES (290,'pol','Mossi');
INSERT INTO IsoLanguagesDes VALUES (291,'pol','Multiple languages');
INSERT INTO IsoLanguagesDes VALUES (292,'pol','Munda languages');
INSERT INTO IsoLanguagesDes VALUES (293,'pol','Creek');
INSERT INTO IsoLanguagesDes VALUES (294,'pol','Mirandese');
INSERT INTO IsoLanguagesDes VALUES (295,'pol','Marwari');
INSERT INTO IsoLanguagesDes VALUES (296,'pol','Mayan languages');
INSERT INTO IsoLanguagesDes VALUES (297,'pol','Erzya');
INSERT INTO IsoLanguagesDes VALUES (298,'pol','Nahuatl languages');
INSERT INTO IsoLanguagesDes VALUES (299,'pol','North American Indian');
INSERT INTO IsoLanguagesDes VALUES (300,'pol','Neapolitan');
INSERT INTO IsoLanguagesDes VALUES (301,'pol','Nauru');
INSERT INTO IsoLanguagesDes VALUES (302,'pol','Navajo; Navaho');
INSERT INTO IsoLanguagesDes VALUES (303,'pol','Ndebele, South; South Ndebele');
INSERT INTO IsoLanguagesDes VALUES (304,'pol','Ndebele, North; North Ndebele');
INSERT INTO IsoLanguagesDes VALUES (305,'pol','Ndonga');
INSERT INTO IsoLanguagesDes VALUES (306,'pol','Low German; Low Saxon; German, Low; Sa');
INSERT INTO IsoLanguagesDes VALUES (307,'pol','Nepali');
INSERT INTO IsoLanguagesDes VALUES (308,'pol','Nepal Bhasa; Newari');
INSERT INTO IsoLanguagesDes VALUES (309,'pol','Nias');
INSERT INTO IsoLanguagesDes VALUES (310,'pol','Niger-Kordofanian (Other)');
INSERT INTO IsoLanguagesDes VALUES (311,'pol','Niuean');
INSERT INTO IsoLanguagesDes VALUES (312,'pol','Norwegian Nynorsk; Nynorsk, Norwegian');
INSERT INTO IsoLanguagesDes VALUES (313,'pol','Bokmål, Norwegian; Norwegian Bokmål');
INSERT INTO IsoLanguagesDes VALUES (314,'pol','Nogai');
INSERT INTO IsoLanguagesDes VALUES (315,'pol','Norse, Old');
INSERT INTO IsoLanguagesDes VALUES (316,'pol','Norwegian');
INSERT INTO IsoLanguagesDes VALUES (317,'pol','Pedi; Sepedi; Northern Sotho');
INSERT INTO IsoLanguagesDes VALUES (318,'pol','Nubian languages');
INSERT INTO IsoLanguagesDes VALUES (319,'pol','Classical Newari; Old Newari; Classica');
INSERT INTO IsoLanguagesDes VALUES (320,'pol','Chichewa; Chewa; Nyanja');
INSERT INTO IsoLanguagesDes VALUES (321,'pol','Nyamwezi');
INSERT INTO IsoLanguagesDes VALUES (322,'pol','Nyankole');
INSERT INTO IsoLanguagesDes VALUES (323,'pol','Nyoro');
INSERT INTO IsoLanguagesDes VALUES (324,'pol','Nzima');
INSERT INTO IsoLanguagesDes VALUES (325,'pol','Occitan (post 1500); Provençal');
INSERT INTO IsoLanguagesDes VALUES (326,'pol','Ojibwa');
INSERT INTO IsoLanguagesDes VALUES (327,'pol','Oriya');
INSERT INTO IsoLanguagesDes VALUES (328,'pol','Oromo');
INSERT INTO IsoLanguagesDes VALUES (329,'pol','Osage');
INSERT INTO IsoLanguagesDes VALUES (330,'pol','Ossetian; Ossetic');
INSERT INTO IsoLanguagesDes VALUES (331,'pol','Turkish, Ottoman (1500-1928)');
INSERT INTO IsoLanguagesDes VALUES (332,'pol','Otomian languages');
INSERT INTO IsoLanguagesDes VALUES (333,'pol','Papuan (Other)');
INSERT INTO IsoLanguagesDes VALUES (334,'pol','Pangasinan');
INSERT INTO IsoLanguagesDes VALUES (335,'pol','Pahlavi');
INSERT INTO IsoLanguagesDes VALUES (336,'pol','Pampanga');
INSERT INTO IsoLanguagesDes VALUES (337,'pol','Panjabi; Punjabi');
INSERT INTO IsoLanguagesDes VALUES (338,'pol','Papiamento');
INSERT INTO IsoLanguagesDes VALUES (339,'pol','Palauan');
INSERT INTO IsoLanguagesDes VALUES (340,'pol','Persian, Old (ca.600-400 B.C.)');
INSERT INTO IsoLanguagesDes VALUES (341,'pol','Persian');
INSERT INTO IsoLanguagesDes VALUES (342,'pol','Philippine (Other)');
INSERT INTO IsoLanguagesDes VALUES (343,'pol','Phoenician');
INSERT INTO IsoLanguagesDes VALUES (344,'pol','Pali');
INSERT INTO IsoLanguagesDes VALUES (345,'pol','Polish');
INSERT INTO IsoLanguagesDes VALUES (346,'pol','Pohnpeian');
INSERT INTO IsoLanguagesDes VALUES (347,'pol','Portuguese');
INSERT INTO IsoLanguagesDes VALUES (348,'pol','Prakrit languages');
INSERT INTO IsoLanguagesDes VALUES (349,'pol','Provençal, Old (to 1500)');
INSERT INTO IsoLanguagesDes VALUES (350,'pol','Pushto');
INSERT INTO IsoLanguagesDes VALUES (351,'pol','Reserved for local use');
INSERT INTO IsoLanguagesDes VALUES (352,'pol','Quechua');
INSERT INTO IsoLanguagesDes VALUES (353,'pol','Rajasthani');
INSERT INTO IsoLanguagesDes VALUES (354,'pol','Rapanui');
INSERT INTO IsoLanguagesDes VALUES (355,'pol','Rarotongan; Cook Islands Maori');
INSERT INTO IsoLanguagesDes VALUES (356,'pol','Romance (Other)');
INSERT INTO IsoLanguagesDes VALUES (357,'pol','Romansh');
INSERT INTO IsoLanguagesDes VALUES (358,'pol','Romany');
INSERT INTO IsoLanguagesDes VALUES (359,'pol','Romanian');
INSERT INTO IsoLanguagesDes VALUES (360,'pol','Rundi');
INSERT INTO IsoLanguagesDes VALUES (361,'pol','Aromanian; Arumanian; Macedo-Romanian');
INSERT INTO IsoLanguagesDes VALUES (362,'pol','Russian');
INSERT INTO IsoLanguagesDes VALUES (363,'pol','Sandawe');
INSERT INTO IsoLanguagesDes VALUES (364,'pol','Sango');
INSERT INTO IsoLanguagesDes VALUES (365,'pol','Yakut');
INSERT INTO IsoLanguagesDes VALUES (366,'pol','South American Indian (Other)');
INSERT INTO IsoLanguagesDes VALUES (367,'pol','Salishan languages');
INSERT INTO IsoLanguagesDes VALUES (368,'pol','Samaritan Aramaic');
INSERT INTO IsoLanguagesDes VALUES (369,'pol','Sanskrit');
INSERT INTO IsoLanguagesDes VALUES (370,'pol','Sasak');
INSERT INTO IsoLanguagesDes VALUES (371,'pol','Santali');
INSERT INTO IsoLanguagesDes VALUES (372,'pol','Serbian');
INSERT INTO IsoLanguagesDes VALUES (373,'pol','Sicilian');
INSERT INTO IsoLanguagesDes VALUES (374,'pol','Scots');
INSERT INTO IsoLanguagesDes VALUES (375,'pol','Croatian');
INSERT INTO IsoLanguagesDes VALUES (376,'pol','Selkup');
INSERT INTO IsoLanguagesDes VALUES (377,'pol','Semitic (Other)');
INSERT INTO IsoLanguagesDes VALUES (378,'pol','Irish, Old (to 900)');
INSERT INTO IsoLanguagesDes VALUES (379,'pol','Sign Languages');
INSERT INTO IsoLanguagesDes VALUES (380,'pol','Shan');
INSERT INTO IsoLanguagesDes VALUES (381,'pol','Sidamo');
INSERT INTO IsoLanguagesDes VALUES (382,'pol','Sinhala; Sinhalese');
INSERT INTO IsoLanguagesDes VALUES (383,'pol','Siouan languages');
INSERT INTO IsoLanguagesDes VALUES (384,'pol','Sino-Tibetan (Other)');
INSERT INTO IsoLanguagesDes VALUES (385,'pol','Slavic (Other)');
INSERT INTO IsoLanguagesDes VALUES (386,'pol','Slovak');
INSERT INTO IsoLanguagesDes VALUES (387,'pol','Slovenian');
INSERT INTO IsoLanguagesDes VALUES (388,'pol','Southern Sami');
INSERT INTO IsoLanguagesDes VALUES (389,'pol','Northern Sami');
INSERT INTO IsoLanguagesDes VALUES (390,'pol','Sami languages (Other)');
INSERT INTO IsoLanguagesDes VALUES (391,'pol','Lule Sami');
INSERT INTO IsoLanguagesDes VALUES (392,'pol','Inari Sami');
INSERT INTO IsoLanguagesDes VALUES (393,'pol','Samoan');
INSERT INTO IsoLanguagesDes VALUES (394,'pol','Skolt Sami');
INSERT INTO IsoLanguagesDes VALUES (395,'pol','Shona');
INSERT INTO IsoLanguagesDes VALUES (396,'pol','Sindhi');
INSERT INTO IsoLanguagesDes VALUES (397,'pol','Soninke');
INSERT INTO IsoLanguagesDes VALUES (398,'pol','Sogdian');
INSERT INTO IsoLanguagesDes VALUES (399,'pol','Somali');
INSERT INTO IsoLanguagesDes VALUES (400,'pol','Songhai languages');
INSERT INTO IsoLanguagesDes VALUES (401,'pol','Sotho, Southern');
INSERT INTO IsoLanguagesDes VALUES (402,'pol','Spanish; Castilian');
INSERT INTO IsoLanguagesDes VALUES (403,'pol','Sardinian; Zazaki');
INSERT INTO IsoLanguagesDes VALUES (404,'pol','Sranan Tongo');
INSERT INTO IsoLanguagesDes VALUES (405,'pol','Serer');
INSERT INTO IsoLanguagesDes VALUES (406,'pol','Nilo-Saharan (Other)');
INSERT INTO IsoLanguagesDes VALUES (407,'pol','Swati');
INSERT INTO IsoLanguagesDes VALUES (408,'pol','Sukuma');
INSERT INTO IsoLanguagesDes VALUES (409,'pol','Sundanese');
INSERT INTO IsoLanguagesDes VALUES (410,'pol','Susu');
INSERT INTO IsoLanguagesDes VALUES (411,'pol','Sumerian');
INSERT INTO IsoLanguagesDes VALUES (412,'pol','Swahili');
INSERT INTO IsoLanguagesDes VALUES (413,'pol','Swedish');
INSERT INTO IsoLanguagesDes VALUES (414,'pol','Syriac');
INSERT INTO IsoLanguagesDes VALUES (415,'pol','Tahitian');
INSERT INTO IsoLanguagesDes VALUES (416,'pol','Tai (Other)');
INSERT INTO IsoLanguagesDes VALUES (417,'pol','Tamil');
INSERT INTO IsoLanguagesDes VALUES (418,'pol','Tatar');
INSERT INTO IsoLanguagesDes VALUES (419,'pol','Telugu');
INSERT INTO IsoLanguagesDes VALUES (420,'pol','Timnendere)');
INSERT INTO IsoLanguagesDes VALUES (421,'pol','Tereno');
INSERT INTO IsoLanguagesDes VALUES (422,'pol','Tetum');
INSERT INTO IsoLanguagesDes VALUES (423,'pol','Tajik');
INSERT INTO IsoLanguagesDes VALUES (424,'pol','Tagalog');
INSERT INTO IsoLanguagesDes VALUES (425,'pol','Thai');
INSERT INTO IsoLanguagesDes VALUES (426,'pol','Tibetan');
INSERT INTO IsoLanguagesDes VALUES (427,'pol','Tigre');
INSERT INTO IsoLanguagesDes VALUES (428,'pol','Tigrinya');
INSERT INTO IsoLanguagesDes VALUES (429,'pol','Tiv');
INSERT INTO IsoLanguagesDes VALUES (430,'pol','Tokelau');
INSERT INTO IsoLanguagesDes VALUES (431,'pol','Klingon; tlhIngan-Hol');
INSERT INTO IsoLanguagesDes VALUES (432,'pol','Tlingit');
INSERT INTO IsoLanguagesDes VALUES (433,'pol','Tamashek');
INSERT INTO IsoLanguagesDes VALUES (434,'pol','Tonga (Nyasa)');
INSERT INTO IsoLanguagesDes VALUES (435,'pol','Tonga (Tonga Islands)');
INSERT INTO IsoLanguagesDes VALUES (436,'pol','Tok Pisin');
INSERT INTO IsoLanguagesDes VALUES (437,'pol','Tsimshian');
INSERT INTO IsoLanguagesDes VALUES (438,'pol','Tswana');
INSERT INTO IsoLanguagesDes VALUES (439,'pol','Tsonga');
INSERT INTO IsoLanguagesDes VALUES (440,'pol','Turkmen');
INSERT INTO IsoLanguagesDes VALUES (441,'pol','Tumbuka');
INSERT INTO IsoLanguagesDes VALUES (442,'pol','Tupi languages');
INSERT INTO IsoLanguagesDes VALUES (443,'pol','Turkish');
INSERT INTO IsoLanguagesDes VALUES (444,'pol','Altaic (Other)');
INSERT INTO IsoLanguagesDes VALUES (445,'pol','Tuvalu');
INSERT INTO IsoLanguagesDes VALUES (446,'pol','Twi');
INSERT INTO IsoLanguagesDes VALUES (447,'pol','Tuvinian');
INSERT INTO IsoLanguagesDes VALUES (448,'pol','Udmurt');
INSERT INTO IsoLanguagesDes VALUES (449,'pol','Ugaritic');
INSERT INTO IsoLanguagesDes VALUES (450,'pol','Uighur; Uyghur');
INSERT INTO IsoLanguagesDes VALUES (451,'pol','Ukrainian');
INSERT INTO IsoLanguagesDes VALUES (452,'pol','Umbundu');
INSERT INTO IsoLanguagesDes VALUES (453,'pol','Undetermined');
INSERT INTO IsoLanguagesDes VALUES (454,'pol','Urdu');
INSERT INTO IsoLanguagesDes VALUES (455,'pol','Uzbek');
INSERT INTO IsoLanguagesDes VALUES (456,'pol','Vai');
INSERT INTO IsoLanguagesDes VALUES (457,'pol','Venda');
INSERT INTO IsoLanguagesDes VALUES (458,'pol','Vietnamese');
INSERT INTO IsoLanguagesDes VALUES (459,'pol','Volapük');
INSERT INTO IsoLanguagesDes VALUES (460,'pol','Votic');
INSERT INTO IsoLanguagesDes VALUES (461,'pol','Wakashan languages');
INSERT INTO IsoLanguagesDes VALUES (462,'pol','Walamo');
INSERT INTO IsoLanguagesDes VALUES (463,'pol','Waray');
INSERT INTO IsoLanguagesDes VALUES (464,'pol','Washo');
INSERT INTO IsoLanguagesDes VALUES (465,'pol','Welsh');
INSERT INTO IsoLanguagesDes VALUES (466,'pol','Sorbian languages');
INSERT INTO IsoLanguagesDes VALUES (467,'pol','Walloon');
INSERT INTO IsoLanguagesDes VALUES (468,'pol','Wolof');
INSERT INTO IsoLanguagesDes VALUES (469,'pol','Kalmyk; Oirat');
INSERT INTO IsoLanguagesDes VALUES (470,'pol','Xhosa');
INSERT INTO IsoLanguagesDes VALUES (471,'pol','Yao');
INSERT INTO IsoLanguagesDes VALUES (472,'pol','Yapese');
INSERT INTO IsoLanguagesDes VALUES (473,'pol','Yiddish');
INSERT INTO IsoLanguagesDes VALUES (474,'pol','Yoruba');
INSERT INTO IsoLanguagesDes VALUES (475,'pol','Yupik languages');
INSERT INTO IsoLanguagesDes VALUES (476,'pol','Zapotec');
INSERT INTO IsoLanguagesDes VALUES (477,'pol','Zenaga');
INSERT INTO IsoLanguagesDes VALUES (478,'pol','Zhuang; Chuang');
INSERT INTO IsoLanguagesDes VALUES (479,'pol','Zande languages');
INSERT INTO IsoLanguagesDes VALUES (480,'pol','Zulu');
INSERT INTO IsoLanguagesDes VALUES (481,'pol','Zuni');
INSERT INTO IsoLanguagesDes VALUES (482,'pol','No linguistic content');
INSERT INTO IsoLanguagesDes VALUES (483,'pol','N''Ko');
INSERT INTO IsoLanguagesDes VALUES (484,'pol','Zaza; Dimili; Dimli; Kirdki; Kirmanjki');

INSERT INTO OperationsDes VALUES (0,'pol','Publikacja');
INSERT INTO OperationsDes VALUES (1,'pol','Pobieranie');
INSERT INTO OperationsDes VALUES (2,'pol','Edycja');
INSERT INTO OperationsDes VALUES (3,'pol','Powiadamianie');
INSERT INTO OperationsDes VALUES (5,'pol','Mapy interaktywne');
INSERT INTO OperationsDes VALUES (6,'pol','Wyróżnione');

INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (0,'pol','Nieznany');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (1,'pol','Draft');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (2,'pol','Zaaprobowana');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (3,'pol','Porzucone');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (4,'pol','Załadowane');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (5,'pol','Odrzucone');

INSERT INTO RegionsDes VALUES (1,'pol','Armenia');
INSERT INTO RegionsDes VALUES (2,'pol','Afghanistan');
INSERT INTO RegionsDes VALUES (3,'pol','Albania');
INSERT INTO RegionsDes VALUES (4,'pol','Algeria');
INSERT INTO RegionsDes VALUES (5,'pol','American Samoa');
INSERT INTO RegionsDes VALUES (6,'pol','Andorra');
INSERT INTO RegionsDes VALUES (7,'pol','Angola');
INSERT INTO RegionsDes VALUES (8,'pol','Antigua and Barbuda');
INSERT INTO RegionsDes VALUES (9,'pol','Argentina');
INSERT INTO RegionsDes VALUES (10,'pol','Australia');
INSERT INTO RegionsDes VALUES (11,'pol','Austria');
INSERT INTO RegionsDes VALUES (12,'pol','Bahamas');
INSERT INTO RegionsDes VALUES (13,'pol','Bahrain');
INSERT INTO RegionsDes VALUES (14,'pol','Barbados');
INSERT INTO RegionsDes VALUES (16,'pol','Bangladesh');
INSERT INTO RegionsDes VALUES (17,'pol','Bermuda');
INSERT INTO RegionsDes VALUES (18,'pol','Bhutan');
INSERT INTO RegionsDes VALUES (19,'pol','Bolivia');
INSERT INTO RegionsDes VALUES (20,'pol','Botswana');
INSERT INTO RegionsDes VALUES (21,'pol','Brazil');
INSERT INTO RegionsDes VALUES (22,'pol','Aruba');
INSERT INTO RegionsDes VALUES (23,'pol','Belize');
INSERT INTO RegionsDes VALUES (24,'pol','British Indian Ocean Ter');
INSERT INTO RegionsDes VALUES (25,'pol','Solomon Islands');
INSERT INTO RegionsDes VALUES (26,'pol','Brunei Darussalam');
INSERT INTO RegionsDes VALUES (27,'pol','Bulgaria');
INSERT INTO RegionsDes VALUES (28,'pol','Myanmar');
INSERT INTO RegionsDes VALUES (29,'pol','Burundi');
INSERT INTO RegionsDes VALUES (30,'pol','Antarctica');
INSERT INTO RegionsDes VALUES (31,'pol','Bouvet Island');
INSERT INTO RegionsDes VALUES (32,'pol','Cameroon');
INSERT INTO RegionsDes VALUES (33,'pol','Canada');
INSERT INTO RegionsDes VALUES (35,'pol','Cape Verde');
INSERT INTO RegionsDes VALUES (36,'pol','Cayman Island');
INSERT INTO RegionsDes VALUES (37,'pol','Central African Republic');
INSERT INTO RegionsDes VALUES (38,'pol','Sri Lanka');
INSERT INTO RegionsDes VALUES (39,'pol','Chad');
INSERT INTO RegionsDes VALUES (40,'pol','Chile');
INSERT INTO RegionsDes VALUES (41,'pol','China, Mainland');
INSERT INTO RegionsDes VALUES (42,'pol','Christmas Island');
INSERT INTO RegionsDes VALUES (43,'pol','Cocos Islands');
INSERT INTO RegionsDes VALUES (44,'pol','Colombia');
INSERT INTO RegionsDes VALUES (45,'pol','Comoros');
INSERT INTO RegionsDes VALUES (46,'pol','Congo, Republic of');
INSERT INTO RegionsDes VALUES (47,'pol','Cook Islands');
INSERT INTO RegionsDes VALUES (48,'pol','Costa Rica');
INSERT INTO RegionsDes VALUES (49,'pol','Cuba');
INSERT INTO RegionsDes VALUES (50,'pol','Cyprus');
INSERT INTO RegionsDes VALUES (52,'pol','Azerbaijan, Republic of');
INSERT INTO RegionsDes VALUES (53,'pol','Benin');
INSERT INTO RegionsDes VALUES (54,'pol','Denmark');
INSERT INTO RegionsDes VALUES (55,'pol','Dominica');
INSERT INTO RegionsDes VALUES (56,'pol','Dominican Republic');
INSERT INTO RegionsDes VALUES (57,'pol','Belarus');
INSERT INTO RegionsDes VALUES (58,'pol','Ecuador');
INSERT INTO RegionsDes VALUES (59,'pol','Egypt');
INSERT INTO RegionsDes VALUES (60,'pol','El Salvador');
INSERT INTO RegionsDes VALUES (61,'pol','Equatorial Guinea');
INSERT INTO RegionsDes VALUES (63,'pol','Estonia');
INSERT INTO RegionsDes VALUES (64,'pol','Faeroe Islands');
INSERT INTO RegionsDes VALUES (65,'pol','Falkland Islands');
INSERT INTO RegionsDes VALUES (66,'pol','Fiji Islands');
INSERT INTO RegionsDes VALUES (67,'pol','Finland');
INSERT INTO RegionsDes VALUES (68,'pol','France');
INSERT INTO RegionsDes VALUES (69,'pol','French Guiana');
INSERT INTO RegionsDes VALUES (70,'pol','French Polynesia');
INSERT INTO RegionsDes VALUES (71,'pol','French South Terr');
INSERT INTO RegionsDes VALUES (72,'pol','Djibouti');
INSERT INTO RegionsDes VALUES (73,'pol','Georgia');
INSERT INTO RegionsDes VALUES (74,'pol','Gabon');
INSERT INTO RegionsDes VALUES (75,'pol','Gambia');
INSERT INTO RegionsDes VALUES (76,'pol','Gaza Strip');
INSERT INTO RegionsDes VALUES (79,'pol','Germany');
INSERT INTO RegionsDes VALUES (80,'pol','Bosnia and Herzegovina');
INSERT INTO RegionsDes VALUES (81,'pol','Ghana');
INSERT INTO RegionsDes VALUES (82,'pol','Gibraltar');
INSERT INTO RegionsDes VALUES (83,'pol','Kiribati');
INSERT INTO RegionsDes VALUES (84,'pol','Greece');
INSERT INTO RegionsDes VALUES (85,'pol','Greenland');
INSERT INTO RegionsDes VALUES (86,'pol','Grenada');
INSERT INTO RegionsDes VALUES (87,'pol','Guadeloupe');
INSERT INTO RegionsDes VALUES (88,'pol','Guam');
INSERT INTO RegionsDes VALUES (89,'pol','Guatemala');
INSERT INTO RegionsDes VALUES (90,'pol','Guinea');
INSERT INTO RegionsDes VALUES (91,'pol','Guyana');
INSERT INTO RegionsDes VALUES (92,'pol','Heard and McDonald Is');
INSERT INTO RegionsDes VALUES (93,'pol','Haiti');
INSERT INTO RegionsDes VALUES (95,'pol','Honduras');
INSERT INTO RegionsDes VALUES (97,'pol','Hungary');
INSERT INTO RegionsDes VALUES (98,'pol','Croatia');
INSERT INTO RegionsDes VALUES (99,'pol','Iceland');
INSERT INTO RegionsDes VALUES (100,'pol','India');
INSERT INTO RegionsDes VALUES (101,'pol','Indonesia');
INSERT INTO RegionsDes VALUES (102,'pol','Iran, Islamic Rep of');
INSERT INTO RegionsDes VALUES (103,'pol','Iraq');
INSERT INTO RegionsDes VALUES (104,'pol','Ireland');
INSERT INTO RegionsDes VALUES (105,'pol','Israel');
INSERT INTO RegionsDes VALUES (106,'pol','Italy');
INSERT INTO RegionsDes VALUES (107,'pol','Ivory Coast');
INSERT INTO RegionsDes VALUES (108,'pol','Kazakhstan');
INSERT INTO RegionsDes VALUES (109,'pol','Jamaica');
INSERT INTO RegionsDes VALUES (110,'pol','Japan');
INSERT INTO RegionsDes VALUES (112,'pol','Jordan');
INSERT INTO RegionsDes VALUES (113,'pol','Kyrgyzstan');
INSERT INTO RegionsDes VALUES (114,'pol','Kenya');
INSERT INTO RegionsDes VALUES (115,'pol','Cambodia');
INSERT INTO RegionsDes VALUES (116,'pol','Korea, Dem People''s Rep');
INSERT INTO RegionsDes VALUES (117,'pol','Korea, Republic of');
INSERT INTO RegionsDes VALUES (118,'pol','Kuwait');
INSERT INTO RegionsDes VALUES (119,'pol','Latvia');
INSERT INTO RegionsDes VALUES (120,'pol','Laos');
INSERT INTO RegionsDes VALUES (121,'pol','Lebanon');
INSERT INTO RegionsDes VALUES (122,'pol','Lesotho');
INSERT INTO RegionsDes VALUES (123,'pol','Liberia');
INSERT INTO RegionsDes VALUES (124,'pol','Libyan Arab Jamahiriya');
INSERT INTO RegionsDes VALUES (125,'pol','Liechtensten');
INSERT INTO RegionsDes VALUES (126,'pol','Lithuania');
INSERT INTO RegionsDes VALUES (127,'pol','Marshall Island');
INSERT INTO RegionsDes VALUES (129,'pol','Madagascar');
INSERT INTO RegionsDes VALUES (130,'pol','Malawi');
INSERT INTO RegionsDes VALUES (131,'pol','Malaysia');
INSERT INTO RegionsDes VALUES (132,'pol','Maldives');
INSERT INTO RegionsDes VALUES (133,'pol','Mali');
INSERT INTO RegionsDes VALUES (134,'pol','Malta');
INSERT INTO RegionsDes VALUES (135,'pol','Martinique');
INSERT INTO RegionsDes VALUES (136,'pol','Mauritania');
INSERT INTO RegionsDes VALUES (137,'pol','Mauritius');
INSERT INTO RegionsDes VALUES (138,'pol','Mexico');
INSERT INTO RegionsDes VALUES (139,'pol','Midway Islands');
INSERT INTO RegionsDes VALUES (140,'pol','Monaco');
INSERT INTO RegionsDes VALUES (141,'pol','Mongolia');
INSERT INTO RegionsDes VALUES (142,'pol','Montserrat');
INSERT INTO RegionsDes VALUES (143,'pol','Morocco');
INSERT INTO RegionsDes VALUES (144,'pol','Mozambique');
INSERT INTO RegionsDes VALUES (145,'pol','Micronesia,Fed States of');
INSERT INTO RegionsDes VALUES (146,'pol','Moldova, Republic of');
INSERT INTO RegionsDes VALUES (147,'pol','Namibia');
INSERT INTO RegionsDes VALUES (148,'pol','Nauru');
INSERT INTO RegionsDes VALUES (149,'pol','Nepal');
INSERT INTO RegionsDes VALUES (150,'pol','Netherlands');
INSERT INTO RegionsDes VALUES (151,'pol','Neth Antilles');
INSERT INTO RegionsDes VALUES (153,'pol','NewCaledonia');
INSERT INTO RegionsDes VALUES (154,'pol','Macedonia');
INSERT INTO RegionsDes VALUES (155,'pol','Vanuatu');
INSERT INTO RegionsDes VALUES (156,'pol','New Zealand');
INSERT INTO RegionsDes VALUES (157,'pol','Nicaragua');
INSERT INTO RegionsDes VALUES (158,'pol','Niger');
INSERT INTO RegionsDes VALUES (159,'pol','Nigeria');
INSERT INTO RegionsDes VALUES (160,'pol','Niue');
INSERT INTO RegionsDes VALUES (161,'pol','Norfolk Island');
INSERT INTO RegionsDes VALUES (162,'pol','Norway');
INSERT INTO RegionsDes VALUES (163,'pol','Northern Mariana Is');
INSERT INTO RegionsDes VALUES (165,'pol','Pakistan');
INSERT INTO RegionsDes VALUES (166,'pol','Panama');
INSERT INTO RegionsDes VALUES (167,'pol','Czech Republic');
INSERT INTO RegionsDes VALUES (168,'pol','Papua New Guinea');
INSERT INTO RegionsDes VALUES (169,'pol','Paraguay');
INSERT INTO RegionsDes VALUES (170,'pol','Peru');
INSERT INTO RegionsDes VALUES (171,'pol','Philippines');
INSERT INTO RegionsDes VALUES (172,'pol','Pitcairn Islands');
INSERT INTO RegionsDes VALUES (173,'pol','Poland');
INSERT INTO RegionsDes VALUES (174,'pol','Portugal');
INSERT INTO RegionsDes VALUES (175,'pol','Guinea-Bissau');
INSERT INTO RegionsDes VALUES (176,'pol','East Timor');
INSERT INTO RegionsDes VALUES (177,'pol','Puerto Rico');
INSERT INTO RegionsDes VALUES (178,'pol','Eritrea');
INSERT INTO RegionsDes VALUES (179,'pol','Qatar');
INSERT INTO RegionsDes VALUES (181,'pol','Zimbabwe');
INSERT INTO RegionsDes VALUES (182,'pol','Reunion');
INSERT INTO RegionsDes VALUES (183,'pol','Romania');
INSERT INTO RegionsDes VALUES (184,'pol','Rwanda');
INSERT INTO RegionsDes VALUES (185,'pol','Russian Federation');
INSERT INTO RegionsDes VALUES (187,'pol','Saint Helena');
INSERT INTO RegionsDes VALUES (188,'pol','Saint Kitts and Nevis');
INSERT INTO RegionsDes VALUES (189,'pol','Saint Lucia');
INSERT INTO RegionsDes VALUES (190,'pol','Saint Pierre & Miquelon');
INSERT INTO RegionsDes VALUES (191,'pol','Saint Vincent/Grenadines');
INSERT INTO RegionsDes VALUES (192,'pol','San Marino');
INSERT INTO RegionsDes VALUES (193,'pol','Sao Tome and Principe');
INSERT INTO RegionsDes VALUES (194,'pol','Saudi Arabia');
INSERT INTO RegionsDes VALUES (195,'pol','Senegal');
INSERT INTO RegionsDes VALUES (196,'pol','Seychelles');
INSERT INTO RegionsDes VALUES (197,'pol','Sierra Leone');
INSERT INTO RegionsDes VALUES (198,'pol','Slovenia');
INSERT INTO RegionsDes VALUES (199,'pol','Slovakia');
INSERT INTO RegionsDes VALUES (200,'pol','Singapore');
INSERT INTO RegionsDes VALUES (201,'pol','Somalia');
INSERT INTO RegionsDes VALUES (202,'pol','South Africa');
INSERT INTO RegionsDes VALUES (203,'pol','Spain');
INSERT INTO RegionsDes VALUES (205,'pol','Western Sahara');
INSERT INTO RegionsDes VALUES (206,'pol','Sudan');
INSERT INTO RegionsDes VALUES (207,'pol','Suriname');
INSERT INTO RegionsDes VALUES (208,'pol','Tajikistan');
INSERT INTO RegionsDes VALUES (209,'pol','Swaziland');
INSERT INTO RegionsDes VALUES (210,'pol','Sweden');
INSERT INTO RegionsDes VALUES (211,'pol','Switzerland');
INSERT INTO RegionsDes VALUES (212,'pol','Syrian Arab Republic');
INSERT INTO RegionsDes VALUES (213,'pol','Turkmenistan');
INSERT INTO RegionsDes VALUES (214,'pol','China, Taiwan Prov of');
INSERT INTO RegionsDes VALUES (215,'pol','Tanzania, United Rep of');
INSERT INTO RegionsDes VALUES (216,'pol','Thailand');
INSERT INTO RegionsDes VALUES (217,'pol','Togo');
INSERT INTO RegionsDes VALUES (218,'pol','Tokelau');
INSERT INTO RegionsDes VALUES (219,'pol','Tonga');
INSERT INTO RegionsDes VALUES (220,'pol','Trinidad and Tobago');
INSERT INTO RegionsDes VALUES (221,'pol','Oman');
INSERT INTO RegionsDes VALUES (222,'pol','Tunisia');
INSERT INTO RegionsDes VALUES (223,'pol','Turkey');
INSERT INTO RegionsDes VALUES (224,'pol','Turks and Caicos Is');
INSERT INTO RegionsDes VALUES (225,'pol','United Arab Emirates');
INSERT INTO RegionsDes VALUES (226,'pol','Uganda');
INSERT INTO RegionsDes VALUES (227,'pol','Tuvalu');
INSERT INTO RegionsDes VALUES (229,'pol','United Kingdom');
INSERT INTO RegionsDes VALUES (230,'pol','Ukraine');
INSERT INTO RegionsDes VALUES (231,'pol','United States of America');
INSERT INTO RegionsDes VALUES (232,'pol','US Minor Outlying Is');
INSERT INTO RegionsDes VALUES (233,'pol','Burkina Faso');
INSERT INTO RegionsDes VALUES (234,'pol','Uruguay');
INSERT INTO RegionsDes VALUES (235,'pol','Uzbekistan');
INSERT INTO RegionsDes VALUES (236,'pol','Venezuela');
INSERT INTO RegionsDes VALUES (237,'pol','Viet Nam');
INSERT INTO RegionsDes VALUES (238,'pol','Ethiopia');
INSERT INTO RegionsDes VALUES (239,'pol','British Virgin Island');
INSERT INTO RegionsDes VALUES (240,'pol','US Virgin Islands');
INSERT INTO RegionsDes VALUES (242,'pol','Wake Island');
INSERT INTO RegionsDes VALUES (243,'pol','Wallis and Futuna Is');
INSERT INTO RegionsDes VALUES (244,'pol','Samoa');
INSERT INTO RegionsDes VALUES (245,'pol','West Bank');
INSERT INTO RegionsDes VALUES (249,'pol','Yemen');
INSERT INTO RegionsDes VALUES (250,'pol','Congo, Dem Republic of');
INSERT INTO RegionsDes VALUES (251,'pol','Zambia');
INSERT INTO RegionsDes VALUES (255,'pol','Belgium');
INSERT INTO RegionsDes VALUES (256,'pol','Luxembourg');
INSERT INTO RegionsDes VALUES (258,'pol','Anguilla');
INSERT INTO RegionsDes VALUES (260,'pol','Svalbard Is');
INSERT INTO RegionsDes VALUES (264,'pol','Isle of Man');
INSERT INTO RegionsDes VALUES (270,'pol','Mayotte');
INSERT INTO RegionsDes VALUES (271,'pol','SouthGeorgia/Sandwich Is');
INSERT INTO RegionsDes VALUES (303,'pol','Western Europe');
INSERT INTO RegionsDes VALUES (307,'pol','Intergvt Author Devpment');
INSERT INTO RegionsDes VALUES (310,'pol','North Western Africa');
INSERT INTO RegionsDes VALUES (311,'pol','Western Africa');
INSERT INTO RegionsDes VALUES (312,'pol','Central Africa');
INSERT INTO RegionsDes VALUES (313,'pol','Eastern Africa');
INSERT INTO RegionsDes VALUES (314,'pol','Southern Africa');
INSERT INTO RegionsDes VALUES (315,'pol','Latin Amer & Caribbean');
INSERT INTO RegionsDes VALUES (316,'pol','Central America');
INSERT INTO RegionsDes VALUES (317,'pol','Caribbean');
INSERT INTO RegionsDes VALUES (318,'pol','South America');
INSERT INTO RegionsDes VALUES (319,'pol','Near East');
INSERT INTO RegionsDes VALUES (320,'pol','Near East in Africa');
INSERT INTO RegionsDes VALUES (321,'pol','Near East in Asia');
INSERT INTO RegionsDes VALUES (322,'pol','Far East');
INSERT INTO RegionsDes VALUES (323,'pol','South Asia');
INSERT INTO RegionsDes VALUES (324,'pol','East & South East Asia');
INSERT INTO RegionsDes VALUES (325,'pol','Near East and North Africa');
INSERT INTO RegionsDes VALUES (334,'pol','Eastern Europe');
INSERT INTO RegionsDes VALUES (335,'pol','Europe');
INSERT INTO RegionsDes VALUES (337,'pol','Asia');
INSERT INTO RegionsDes VALUES (338,'pol','Africa');
INSERT INTO RegionsDes VALUES (348,'pol','Latin America');
INSERT INTO RegionsDes VALUES (370,'pol','Serbia');
INSERT INTO RegionsDes VALUES (371,'pol','Montenegro');
INSERT INTO RegionsDes VALUES (390,'pol','South of Sahara');
INSERT INTO RegionsDes VALUES (421,'pol','North Africa');
INSERT INTO RegionsDes VALUES (427,'pol','Europe, Non-EU Countries');
INSERT INTO RegionsDes VALUES (428,'pol','North America');
INSERT INTO RegionsDes VALUES (469,'pol','USSR, Former Area of');
INSERT INTO RegionsDes VALUES (1008,'pol','Arctic Sea');
INSERT INTO RegionsDes VALUES (1009,'pol','Atlantic, Northwest');
INSERT INTO RegionsDes VALUES (1010,'pol','Atlantic, Northeast');
INSERT INTO RegionsDes VALUES (1011,'pol','Atlantic, Western Central');
INSERT INTO RegionsDes VALUES (1012,'pol','Atlantic, Eastern Central');
INSERT INTO RegionsDes VALUES (1013,'pol','Mediterran and Black Sea');
INSERT INTO RegionsDes VALUES (1014,'pol','Atlantic, Southwest');
INSERT INTO RegionsDes VALUES (1015,'pol','Atlantic, Southeast');
INSERT INTO RegionsDes VALUES (1016,'pol','Atlantic, Antarctic');
INSERT INTO RegionsDes VALUES (1017,'pol','Indian Ocean, Western');
INSERT INTO RegionsDes VALUES (1018,'pol','Indian Ocean, Eastern');
INSERT INTO RegionsDes VALUES (1019,'pol','Indian Ocean, Antarctic');
INSERT INTO RegionsDes VALUES (1020,'pol','Pacific, Northwest');
INSERT INTO RegionsDes VALUES (1021,'pol','Pacific, Northeast');
INSERT INTO RegionsDes VALUES (1022,'pol','Pacific, Western Central');
INSERT INTO RegionsDes VALUES (1023,'pol','Pacific, Eastern Central');
INSERT INTO RegionsDes VALUES (1024,'pol','Pacific, Southwest');
INSERT INTO RegionsDes VALUES (1025,'pol','Pacific, Southeast');
INSERT INTO RegionsDes VALUES (1026,'pol','Pacific, Antarctic');
INSERT INTO RegionsDes VALUES (1220,'pol','All fishing areas');
INSERT INTO RegionsDes VALUES (9999,'pol','World');
