-- ISO 3 letter code migration
INSERT INTO Languages VALUES ('ita','Italiano', 'y', 'n');

UPDATE CategoriesDes             SET langid='ita' WHERE langid='it';
UPDATE IsoLanguagesDes           SET langid='ita' WHERE langid='it';
UPDATE RegionsDes                SET langid='ita' WHERE langid='it';
UPDATE GroupsDes                 SET langid='ita' WHERE langid='it';
UPDATE OperationsDes             SET langid='ita' WHERE langid='it';
UPDATE StatusValuesDes           SET langid='ita' WHERE langid='it';
UPDATE CswServerCapabilitiesInfo SET langid='ita' WHERE langid='it';
DELETE FROM Languages WHERE id='it';

-- Take care to table ID (related to other loc files)
INSERT INTO CswServerCapabilitiesInfo VALUES (49, 'ita', 'title', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (50, 'ita', 'abstract', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (51, 'ita', 'fees', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (52, 'ita', 'accessConstraints', '');

INSERT INTO CategoriesDes (iddes, langid, label) VALUES (1,'ita','Mappe e grafici');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (2,'ita','Datasets');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (3,'ita','Risorse interattive');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (4,'ita','Applicazioni');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (5,'ita','Casi di studio');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (6,'ita','Atti di conferenze');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (7,'ita','Fotografie');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (8,'ita','Audio/Video');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (9,'ita','Archivi');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (10,'ita','Altre risorse di informazione');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (11,'ita','Z3950 Servers');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (12,'ita','Registri');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (13,'ita','campioni fisici');

INSERT INTO GroupsDes (iddes, langid, label) VALUES (-1,'ita','Visitatore');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (0,'ita','Intranet');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (1,'ita','Tutti');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (2,'ita','Gruppo di esempio');

INSERT INTO IsoLanguagesDes VALUES (1,'ita','Afar');
INSERT INTO IsoLanguagesDes VALUES (2,'ita','Abkhazian');
INSERT INTO IsoLanguagesDes VALUES (3,'ita','Achinese');
INSERT INTO IsoLanguagesDes VALUES (4,'ita','Acioli');
INSERT INTO IsoLanguagesDes VALUES (5,'ita','Adangme');
INSERT INTO IsoLanguagesDes VALUES (6,'ita','Adyghe; Adygei');
INSERT INTO IsoLanguagesDes VALUES (7,'ita','Afro-asiatiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (8,'ita','Afrihili');
INSERT INTO IsoLanguagesDes VALUES (9,'ita','Afrikaans');
INSERT INTO IsoLanguagesDes VALUES (10,'ita','Ainu');
INSERT INTO IsoLanguagesDes VALUES (11,'ita','Akan');
INSERT INTO IsoLanguagesDes VALUES (12,'ita','Accadiano');
INSERT INTO IsoLanguagesDes VALUES (13,'ita','Albanese');
INSERT INTO IsoLanguagesDes VALUES (14,'ita','Aleut');
INSERT INTO IsoLanguagesDes VALUES (15,'ita','Algonchine, Lingue');
INSERT INTO IsoLanguagesDes VALUES (16,'ita','Altai del Sud');
INSERT INTO IsoLanguagesDes VALUES (17,'ita','Amarico');
INSERT INTO IsoLanguagesDes VALUES (18,'ita','Inglese antico (ca.450-1100)');
INSERT INTO IsoLanguagesDes VALUES (19,'ita','Angika');
INSERT INTO IsoLanguagesDes VALUES (20,'ita','Apache, Lingue');
INSERT INTO IsoLanguagesDes VALUES (21,'ita','Arabo');
INSERT INTO IsoLanguagesDes VALUES (22,'ita','Aramaico ufficiale (700-300 AC); Aramaico Imperiale (700-300 AC)');
INSERT INTO IsoLanguagesDes VALUES (23,'ita','Aragonese');
INSERT INTO IsoLanguagesDes VALUES (24,'ita','Armeno');
INSERT INTO IsoLanguagesDes VALUES (25,'ita','Mapudungun; Mapuche');
INSERT INTO IsoLanguagesDes VALUES (26,'ita','Arapaho');
INSERT INTO IsoLanguagesDes VALUES (27,'ita','Lingue artificiali');
INSERT INTO IsoLanguagesDes VALUES (28,'ita','Arawak');
INSERT INTO IsoLanguagesDes VALUES (29,'ita','Assamese');
INSERT INTO IsoLanguagesDes VALUES (30,'ita','Asturiano; Bable; Leonese; Asturiano-Leonese');
INSERT INTO IsoLanguagesDes VALUES (31,'ita','Lingue Athapascan');
INSERT INTO IsoLanguagesDes VALUES (32,'ita','Australi, Lingue');
INSERT INTO IsoLanguagesDes VALUES (33,'ita','Avarico');
INSERT INTO IsoLanguagesDes VALUES (34,'ita','Avestan');
INSERT INTO IsoLanguagesDes VALUES (35,'ita','Awadhi');
INSERT INTO IsoLanguagesDes VALUES (36,'ita','Aymara');
INSERT INTO IsoLanguagesDes VALUES (37,'ita','Azero');
INSERT INTO IsoLanguagesDes VALUES (38,'ita','Lingue Banda');
INSERT INTO IsoLanguagesDes VALUES (39,'ita','Lingue Bamileke');
INSERT INTO IsoLanguagesDes VALUES (40,'ita','Baschiro');
INSERT INTO IsoLanguagesDes VALUES (41,'ita','Beluci');
INSERT INTO IsoLanguagesDes VALUES (42,'ita','Bambara');
INSERT INTO IsoLanguagesDes VALUES (43,'ita','Balinese');
INSERT INTO IsoLanguagesDes VALUES (44,'ita','Basco');
INSERT INTO IsoLanguagesDes VALUES (45,'ita','Basa');
INSERT INTO IsoLanguagesDes VALUES (46,'ita','Baltiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (47,'ita','Beja');
INSERT INTO IsoLanguagesDes VALUES (48,'ita','Bielorusso');
INSERT INTO IsoLanguagesDes VALUES (49,'ita','Bemba');
INSERT INTO IsoLanguagesDes VALUES (50,'ita','Bengalese');
INSERT INTO IsoLanguagesDes VALUES (51,'ita','Berbere, Lingue');
INSERT INTO IsoLanguagesDes VALUES (52,'ita','Bhojpuri');
INSERT INTO IsoLanguagesDes VALUES (53,'ita','Lingue bihari');
INSERT INTO IsoLanguagesDes VALUES (54,'ita','Bikol');
INSERT INTO IsoLanguagesDes VALUES (55,'ita','Bini; Edo');
INSERT INTO IsoLanguagesDes VALUES (56,'ita','Bislama');
INSERT INTO IsoLanguagesDes VALUES (57,'ita','Siksika');
INSERT INTO IsoLanguagesDes VALUES (58,'ita','Lingue bantu');
INSERT INTO IsoLanguagesDes VALUES (59,'ita','Bosniaco');
INSERT INTO IsoLanguagesDes VALUES (60,'ita','Braj');
INSERT INTO IsoLanguagesDes VALUES (61,'ita','Bretone');
INSERT INTO IsoLanguagesDes VALUES (62,'ita','Lingue Batak');
INSERT INTO IsoLanguagesDes VALUES (63,'ita','Buriat');
INSERT INTO IsoLanguagesDes VALUES (64,'ita','Buginese');
INSERT INTO IsoLanguagesDes VALUES (65,'ita','Bulgaro');
INSERT INTO IsoLanguagesDes VALUES (66,'ita','Burmese');
INSERT INTO IsoLanguagesDes VALUES (67,'ita','Blin; Bilin');
INSERT INTO IsoLanguagesDes VALUES (68,'ita','Caddo');
INSERT INTO IsoLanguagesDes VALUES (69,'ita','Lingue indiane dell''America Centrale');
INSERT INTO IsoLanguagesDes VALUES (70,'ita','Galibi Carib');
INSERT INTO IsoLanguagesDes VALUES (71,'ita','Catalano; Valenciano');
INSERT INTO IsoLanguagesDes VALUES (72,'ita','Caucasiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (73,'ita','Cebuano');
INSERT INTO IsoLanguagesDes VALUES (74,'ita','Celtiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (75,'ita','Chamorro');
INSERT INTO IsoLanguagesDes VALUES (76,'ita','Chibcha');
INSERT INTO IsoLanguagesDes VALUES (77,'ita','Ceceno');
INSERT INTO IsoLanguagesDes VALUES (78,'ita','Ciagataica');
INSERT INTO IsoLanguagesDes VALUES (79,'ita','Cinese (altro)');
INSERT INTO IsoLanguagesDes VALUES (80,'ita','Chuukese');
INSERT INTO IsoLanguagesDes VALUES (81,'ita','Mari');
INSERT INTO IsoLanguagesDes VALUES (82,'ita','Gergo Chinook');
INSERT INTO IsoLanguagesDes VALUES (83,'ita','Choctaw');
INSERT INTO IsoLanguagesDes VALUES (84,'ita','Chipewyan');
INSERT INTO IsoLanguagesDes VALUES (85,'ita','Cherokee');
INSERT INTO IsoLanguagesDes VALUES (86,'ita','Slavo antico; Slavonico ecclesiastico; Bulgaro antico; Slavonico ecclesiastico antico');
INSERT INTO IsoLanguagesDes VALUES (87,'ita','Chuvash');
INSERT INTO IsoLanguagesDes VALUES (88,'ita','Cheyenne');
INSERT INTO IsoLanguagesDes VALUES (89,'ita','Lingue chamic');
INSERT INTO IsoLanguagesDes VALUES (90,'ita','Copto');
INSERT INTO IsoLanguagesDes VALUES (91,'ita','Cornish');
INSERT INTO IsoLanguagesDes VALUES (92,'ita','Corso');
INSERT INTO IsoLanguagesDes VALUES (93,'ita','Creolo e pidgin, basate sull''inglese');
INSERT INTO IsoLanguagesDes VALUES (94,'ita','Creolo e pidgin, basate sul francese');
INSERT INTO IsoLanguagesDes VALUES (95,'ita','Creolo e pidgin, basate sul portoghese');
INSERT INTO IsoLanguagesDes VALUES (96,'ita','Cree');
INSERT INTO IsoLanguagesDes VALUES (97,'ita','Tatar crimeo; Turco crimeo');
INSERT INTO IsoLanguagesDes VALUES (98,'ita','Creolo e pidgin');
INSERT INTO IsoLanguagesDes VALUES (99,'ita','Kashubian');
INSERT INTO IsoLanguagesDes VALUES (100,'ita','Cuscitiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (101,'ita','Ceco');
INSERT INTO IsoLanguagesDes VALUES (102,'ita','Dakota');
INSERT INTO IsoLanguagesDes VALUES (103,'ita','Danese');
INSERT INTO IsoLanguagesDes VALUES (104,'ita','Dargwa');
INSERT INTO IsoLanguagesDes VALUES (105,'ita','Dayak, Lingue della terra di');
INSERT INTO IsoLanguagesDes VALUES (106,'ita','Delaware');
INSERT INTO IsoLanguagesDes VALUES (107,'ita','Slave (Athapascano)');
INSERT INTO IsoLanguagesDes VALUES (108,'ita','Dogrib');
INSERT INTO IsoLanguagesDes VALUES (109,'ita','Dinca');
INSERT INTO IsoLanguagesDes VALUES (110,'ita','Divehi; Dhivehi; Maldiviano');
INSERT INTO IsoLanguagesDes VALUES (111,'ita','Dogri');
INSERT INTO IsoLanguagesDes VALUES (112,'ita','Lingue dravidiane');
INSERT INTO IsoLanguagesDes VALUES (113,'ita','Sorabo inferiore');
INSERT INTO IsoLanguagesDes VALUES (114,'ita','Duala');
INSERT INTO IsoLanguagesDes VALUES (115,'ita','Olandese medio (ca.1050-1350)');
INSERT INTO IsoLanguagesDes VALUES (116,'ita','Olandese; Fiammingo');
INSERT INTO IsoLanguagesDes VALUES (117,'ita','Diula');
INSERT INTO IsoLanguagesDes VALUES (118,'ita','Dzongkha');
INSERT INTO IsoLanguagesDes VALUES (119,'ita','Efik');
INSERT INTO IsoLanguagesDes VALUES (120,'ita','Egiziano (Antico)');
INSERT INTO IsoLanguagesDes VALUES (121,'ita','Ekajuk');
INSERT INTO IsoLanguagesDes VALUES (122,'ita','Elamitico');
INSERT INTO IsoLanguagesDes VALUES (123,'ita','Inglese');
INSERT INTO IsoLanguagesDes VALUES (124,'ita','Inglese medio (1100-1500)');
INSERT INTO IsoLanguagesDes VALUES (125,'ita','Esperanto');
INSERT INTO IsoLanguagesDes VALUES (126,'ita','Estone');
INSERT INTO IsoLanguagesDes VALUES (127,'ita','Ewe');
INSERT INTO IsoLanguagesDes VALUES (128,'ita','Ewondo');
INSERT INTO IsoLanguagesDes VALUES (129,'ita','Fang');
INSERT INTO IsoLanguagesDes VALUES (130,'ita','Faroese');
INSERT INTO IsoLanguagesDes VALUES (131,'ita','Fanti');
INSERT INTO IsoLanguagesDes VALUES (132,'ita','Figiano');
INSERT INTO IsoLanguagesDes VALUES (133,'ita','Filippino');
INSERT INTO IsoLanguagesDes VALUES (134,'ita','Finlandese');
INSERT INTO IsoLanguagesDes VALUES (135,'ita','Finno-Ugriano, Lingue');
INSERT INTO IsoLanguagesDes VALUES (136,'ita','Fon');
INSERT INTO IsoLanguagesDes VALUES (137,'ita','Francese');
INSERT INTO IsoLanguagesDes VALUES (138,'ita','Francese medio (ca.1400-1600)');
INSERT INTO IsoLanguagesDes VALUES (139,'ita','Francese antico (842-ca.1400)');
INSERT INTO IsoLanguagesDes VALUES (140,'ita','Frisone del Nord');
INSERT INTO IsoLanguagesDes VALUES (141,'ita','Frisone orientale');
INSERT INTO IsoLanguagesDes VALUES (142,'ita','Frisone occidentale');
INSERT INTO IsoLanguagesDes VALUES (143,'ita','Fulah');
INSERT INTO IsoLanguagesDes VALUES (144,'ita','Friulano');
INSERT INTO IsoLanguagesDes VALUES (145,'ita','Ga');
INSERT INTO IsoLanguagesDes VALUES (146,'ita','Gayo');
INSERT INTO IsoLanguagesDes VALUES (147,'ita','Gbaya');
INSERT INTO IsoLanguagesDes VALUES (148,'ita','Germaniche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (149,'ita','Georgiano');
INSERT INTO IsoLanguagesDes VALUES (150,'ita','Tedesco');
INSERT INTO IsoLanguagesDes VALUES (151,'ita','Geez');
INSERT INTO IsoLanguagesDes VALUES (152,'ita','Gilbertese');
INSERT INTO IsoLanguagesDes VALUES (153,'ita','Gaelico; Gaelico Scozzese');
INSERT INTO IsoLanguagesDes VALUES (154,'ita','Irlandese');
INSERT INTO IsoLanguagesDes VALUES (155,'ita','Galiziano');
INSERT INTO IsoLanguagesDes VALUES (156,'ita','Manx');
INSERT INTO IsoLanguagesDes VALUES (157,'ita','Tedesco medio alto (ca. 1050-1500');
INSERT INTO IsoLanguagesDes VALUES (158,'ita','Tedesco antico alto (ca. 750-1050)');
INSERT INTO IsoLanguagesDes VALUES (159,'ita','Gondi');
INSERT INTO IsoLanguagesDes VALUES (160,'ita','Gorontalo');
INSERT INTO IsoLanguagesDes VALUES (161,'ita','Gothico, Lingua associata)');
INSERT INTO IsoLanguagesDes VALUES (162,'ita','Grebo');
INSERT INTO IsoLanguagesDes VALUES (163,'ita','Greco antico (fino al 1453)');
INSERT INTO IsoLanguagesDes VALUES (164,'ita','Greco moderno (1453-)');
INSERT INTO IsoLanguagesDes VALUES (165,'ita','Guarani');
INSERT INTO IsoLanguagesDes VALUES (166,'ita','Svizzero tedesco; Alemanno; Alsaziano');
INSERT INTO IsoLanguagesDes VALUES (167,'ita','Gujarati');
INSERT INTO IsoLanguagesDes VALUES (168,'ita','Gwich''in');
INSERT INTO IsoLanguagesDes VALUES (169,'ita','Haida');
INSERT INTO IsoLanguagesDes VALUES (170,'ita','Haitiano; Haitiano Creolo');
INSERT INTO IsoLanguagesDes VALUES (171,'ita','Hausa');
INSERT INTO IsoLanguagesDes VALUES (172,'ita','Hawaiano');
INSERT INTO IsoLanguagesDes VALUES (173,'ita','Ebraico');
INSERT INTO IsoLanguagesDes VALUES (174,'ita','Herero');
INSERT INTO IsoLanguagesDes VALUES (175,'ita','Himachali; Pahari occidentali, Lingue');
INSERT INTO IsoLanguagesDes VALUES (176,'ita','Himachali');
INSERT INTO IsoLanguagesDes VALUES (177,'ita','Hindi');
INSERT INTO IsoLanguagesDes VALUES (178,'ita','Ittita');
INSERT INTO IsoLanguagesDes VALUES (179,'ita','Hmong');
INSERT INTO IsoLanguagesDes VALUES (180,'ita','Hiri Motu');
INSERT INTO IsoLanguagesDes VALUES (181,'ita','Sorabo superiore');
INSERT INTO IsoLanguagesDes VALUES (182,'ita','Ungherese');
INSERT INTO IsoLanguagesDes VALUES (183,'ita','Hupa');
INSERT INTO IsoLanguagesDes VALUES (184,'ita','Iban');
INSERT INTO IsoLanguagesDes VALUES (185,'ita','Igbo');
INSERT INTO IsoLanguagesDes VALUES (186,'ita','Islandese');
INSERT INTO IsoLanguagesDes VALUES (187,'ita','Ido');
INSERT INTO IsoLanguagesDes VALUES (188,'ita','Sichuan Yi');
INSERT INTO IsoLanguagesDes VALUES (189,'ita','Ijo, lingua');
INSERT INTO IsoLanguagesDes VALUES (190,'ita','Eschimese');
INSERT INTO IsoLanguagesDes VALUES (191,'ita','Interlingue; Occidentale');
INSERT INTO IsoLanguagesDes VALUES (192,'ita','Iloko');
INSERT INTO IsoLanguagesDes VALUES (193,'ita','Interlingua (International Auxiliary Language Association)');
INSERT INTO IsoLanguagesDes VALUES (194,'ita','Indic, Lingua');
INSERT INTO IsoLanguagesDes VALUES (195,'ita','Indonesiano');
INSERT INTO IsoLanguagesDes VALUES (196,'ita','Indo-Europee, Lingue');
INSERT INTO IsoLanguagesDes VALUES (197,'ita','Ingush');
INSERT INTO IsoLanguagesDes VALUES (198,'ita','Inupiaq');
INSERT INTO IsoLanguagesDes VALUES (199,'ita','Iraniano, Lingue');
INSERT INTO IsoLanguagesDes VALUES (200,'ita','Irochesi, Lingue');
INSERT INTO IsoLanguagesDes VALUES (201,'ita','Italiano');
INSERT INTO IsoLanguagesDes VALUES (202,'ita','Javanese');
INSERT INTO IsoLanguagesDes VALUES (203,'ita','Lojban');
INSERT INTO IsoLanguagesDes VALUES (204,'ita','Giapponese');
INSERT INTO IsoLanguagesDes VALUES (205,'ita','Giudeo-Persiano');
INSERT INTO IsoLanguagesDes VALUES (206,'ita','Giudeo-Arabo');
INSERT INTO IsoLanguagesDes VALUES (207,'ita','Kara-Kalpak');
INSERT INTO IsoLanguagesDes VALUES (208,'ita','Kabyle');
INSERT INTO IsoLanguagesDes VALUES (209,'ita','Kachin; Jingpho');
INSERT INTO IsoLanguagesDes VALUES (210,'ita','Kalaallisut; Groenlandese');
INSERT INTO IsoLanguagesDes VALUES (211,'ita','Kamba');
INSERT INTO IsoLanguagesDes VALUES (212,'ita','Kannada');
INSERT INTO IsoLanguagesDes VALUES (213,'ita','Karen, Lingue');
INSERT INTO IsoLanguagesDes VALUES (214,'ita','Kashmiri');
INSERT INTO IsoLanguagesDes VALUES (215,'ita','Kanuri');
INSERT INTO IsoLanguagesDes VALUES (216,'ita','Kawi');
INSERT INTO IsoLanguagesDes VALUES (217,'ita','Kazako');
INSERT INTO IsoLanguagesDes VALUES (218,'ita','Kabardian');
INSERT INTO IsoLanguagesDes VALUES (219,'ita','Khasi');
INSERT INTO IsoLanguagesDes VALUES (220,'ita','Khoisan, lingue');
INSERT INTO IsoLanguagesDes VALUES (221,'ita','Khmer Centrale');
INSERT INTO IsoLanguagesDes VALUES (222,'ita','Khotanese');
INSERT INTO IsoLanguagesDes VALUES (223,'ita','Kikuyu; Gikuyu');
INSERT INTO IsoLanguagesDes VALUES (224,'ita','Kinyarwanda');
INSERT INTO IsoLanguagesDes VALUES (225,'ita','Kirghizo; Chirghiso');
INSERT INTO IsoLanguagesDes VALUES (226,'ita','Kimbundu');
INSERT INTO IsoLanguagesDes VALUES (227,'ita','Konkani');
INSERT INTO IsoLanguagesDes VALUES (228,'ita','Komi');
INSERT INTO IsoLanguagesDes VALUES (229,'ita','Kongo');
INSERT INTO IsoLanguagesDes VALUES (230,'ita','Coreano');
INSERT INTO IsoLanguagesDes VALUES (231,'ita','Kosraean');
INSERT INTO IsoLanguagesDes VALUES (232,'ita','Kpelle');
INSERT INTO IsoLanguagesDes VALUES (233,'ita','Karachay-Balkar');
INSERT INTO IsoLanguagesDes VALUES (234,'ita','Karelian');
INSERT INTO IsoLanguagesDes VALUES (235,'ita','Kru, Lingue');
INSERT INTO IsoLanguagesDes VALUES (236,'ita','Kurukh');
INSERT INTO IsoLanguagesDes VALUES (237,'ita','Kuanyama; Kwanyama');
INSERT INTO IsoLanguagesDes VALUES (238,'ita','Kumyk');
INSERT INTO IsoLanguagesDes VALUES (239,'ita','Curdo');
INSERT INTO IsoLanguagesDes VALUES (240,'ita','Kutenai');
INSERT INTO IsoLanguagesDes VALUES (241,'ita','Ladino');
INSERT INTO IsoLanguagesDes VALUES (242,'ita','Lahnda');
INSERT INTO IsoLanguagesDes VALUES (243,'ita','Lamba');
INSERT INTO IsoLanguagesDes VALUES (244,'ita','Lao');
INSERT INTO IsoLanguagesDes VALUES (245,'ita','Latino');
INSERT INTO IsoLanguagesDes VALUES (246,'ita','Lettone');
INSERT INTO IsoLanguagesDes VALUES (247,'ita','Lezghian');
INSERT INTO IsoLanguagesDes VALUES (248,'ita','Limburgan; Limburger; Limburgish');
INSERT INTO IsoLanguagesDes VALUES (249,'ita','Lingala');
INSERT INTO IsoLanguagesDes VALUES (250,'ita','Lituano');
INSERT INTO IsoLanguagesDes VALUES (251,'ita','Mongo');
INSERT INTO IsoLanguagesDes VALUES (252,'ita','Lozi');
INSERT INTO IsoLanguagesDes VALUES (253,'ita','Lussemburghese');
INSERT INTO IsoLanguagesDes VALUES (254,'ita','Luba-Lulua');
INSERT INTO IsoLanguagesDes VALUES (255,'ita','Luba-Katangaxon, Low');
INSERT INTO IsoLanguagesDes VALUES (256,'ita','Ganda');
INSERT INTO IsoLanguagesDes VALUES (257,'ita','Luiseno');
INSERT INTO IsoLanguagesDes VALUES (258,'ita','Lunda');
INSERT INTO IsoLanguagesDes VALUES (259,'ita','Luo (Kenya e Tanzania)');
INSERT INTO IsoLanguagesDes VALUES (260,'ita','Lushai');
INSERT INTO IsoLanguagesDes VALUES (261,'ita','Macedone');
INSERT INTO IsoLanguagesDes VALUES (262,'ita','Madurese');
INSERT INTO IsoLanguagesDes VALUES (263,'ita','Magahi');
INSERT INTO IsoLanguagesDes VALUES (264,'ita','Marshallese');
INSERT INTO IsoLanguagesDes VALUES (265,'ita','Maithili');
INSERT INTO IsoLanguagesDes VALUES (266,'ita','Makasarl Nepal Bhasa');
INSERT INTO IsoLanguagesDes VALUES (267,'ita','Malayalam');
INSERT INTO IsoLanguagesDes VALUES (268,'ita','Mandingo');
INSERT INTO IsoLanguagesDes VALUES (269,'ita','Maori');
INSERT INTO IsoLanguagesDes VALUES (270,'ita','Austronesiane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (271,'ita','Marathi');
INSERT INTO IsoLanguagesDes VALUES (272,'ita','Masai');
INSERT INTO IsoLanguagesDes VALUES (273,'ita','Malay');
INSERT INTO IsoLanguagesDes VALUES (274,'ita','Moksha');
INSERT INTO IsoLanguagesDes VALUES (275,'ita','Mandar');
INSERT INTO IsoLanguagesDes VALUES (276,'ita','Mende');
INSERT INTO IsoLanguagesDes VALUES (277,'ita','Irlandese medio (900-1200)');
INSERT INTO IsoLanguagesDes VALUES (278,'ita','Mi''kmaq; Micmac');
INSERT INTO IsoLanguagesDes VALUES (279,'ita','Minangkabau');
INSERT INTO IsoLanguagesDes VALUES (280,'ita','Lingue non codificate');
INSERT INTO IsoLanguagesDes VALUES (281,'ita','Mon-Khmer, Lingue');
INSERT INTO IsoLanguagesDes VALUES (282,'ita','Malagasy');
INSERT INTO IsoLanguagesDes VALUES (283,'ita','Maltese');
INSERT INTO IsoLanguagesDes VALUES (284,'ita','Manchu');
INSERT INTO IsoLanguagesDes VALUES (285,'ita','Manipuri');
INSERT INTO IsoLanguagesDes VALUES (286,'ita','Manobo, Lingue');
INSERT INTO IsoLanguagesDes VALUES (287,'ita','Mohawk');
INSERT INTO IsoLanguagesDes VALUES (288,'ita','Moldavo');
INSERT INTO IsoLanguagesDes VALUES (289,'ita','Mongolo');
INSERT INTO IsoLanguagesDes VALUES (290,'ita','Mossi');
INSERT INTO IsoLanguagesDes VALUES (291,'ita','Multiple, Lingue');
INSERT INTO IsoLanguagesDes VALUES (292,'ita','Munda, Lingue');
INSERT INTO IsoLanguagesDes VALUES (293,'ita','Creek');
INSERT INTO IsoLanguagesDes VALUES (294,'ita','Mirandese');
INSERT INTO IsoLanguagesDes VALUES (295,'ita','Marwari');
INSERT INTO IsoLanguagesDes VALUES (296,'ita','Maya, Lingue');
INSERT INTO IsoLanguagesDes VALUES (297,'ita','Erzya');
INSERT INTO IsoLanguagesDes VALUES (298,'ita','Nahuatl,Lingue');
INSERT INTO IsoLanguagesDes VALUES (299,'ita','Nord America, Lingue (indiane)');
INSERT INTO IsoLanguagesDes VALUES (300,'ita','Napoletano');
INSERT INTO IsoLanguagesDes VALUES (301,'ita','Nauru');
INSERT INTO IsoLanguagesDes VALUES (302,'ita','Navajo; Navaho');
INSERT INTO IsoLanguagesDes VALUES (303,'ita','Ndebele del Sud');
INSERT INTO IsoLanguagesDes VALUES (304,'ita','Ndebele del Nord');
INSERT INTO IsoLanguagesDes VALUES (305,'ita','Ndonga');
INSERT INTO IsoLanguagesDes VALUES (306,'ita','Tedesco; Basso Sassone');
INSERT INTO IsoLanguagesDes VALUES (307,'ita','Nepalese');
INSERT INTO IsoLanguagesDes VALUES (308,'ita','Bhasa nepalese, Newari');
INSERT INTO IsoLanguagesDes VALUES (309,'ita','Nias');
INSERT INTO IsoLanguagesDes VALUES (310,'ita','Niger-Kordofanian, Lingue');
INSERT INTO IsoLanguagesDes VALUES (311,'ita','Niuean');
INSERT INTO IsoLanguagesDes VALUES (312,'ita','Nynorsk Norvegese');
INSERT INTO IsoLanguagesDes VALUES (313,'ita','Bokmål, Norwegian; Norwegian Bokmål');
INSERT INTO IsoLanguagesDes VALUES (314,'ita','Nogai');
INSERT INTO IsoLanguagesDes VALUES (315,'ita','Norse antico');
INSERT INTO IsoLanguagesDes VALUES (316,'ita','Norvegese');
INSERT INTO IsoLanguagesDes VALUES (317,'ita','Pedi; Sepedi; Northern Sotho');
INSERT INTO IsoLanguagesDes VALUES (318,'ita','Nubiane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (319,'ita','Newari calssico; Newsari antico; Nepal Bhasa classico');
INSERT INTO IsoLanguagesDes VALUES (320,'ita','Chichewa; Chewa; Nyanja');
INSERT INTO IsoLanguagesDes VALUES (321,'ita','Nyamwezi');
INSERT INTO IsoLanguagesDes VALUES (322,'ita','Nyankole');
INSERT INTO IsoLanguagesDes VALUES (323,'ita','Nyoro');
INSERT INTO IsoLanguagesDes VALUES (324,'ita','Nzima');
INSERT INTO IsoLanguagesDes VALUES (325,'ita','Occitano (dopo 1500); Provenzale');
INSERT INTO IsoLanguagesDes VALUES (326,'ita','Ojibwa');
INSERT INTO IsoLanguagesDes VALUES (327,'ita','Oriya');
INSERT INTO IsoLanguagesDes VALUES (328,'ita','Oromo');
INSERT INTO IsoLanguagesDes VALUES (329,'ita','Osage');
INSERT INTO IsoLanguagesDes VALUES (330,'ita','Osseto');
INSERT INTO IsoLanguagesDes VALUES (331,'ita','Turco Ottomano (1500-1928)');
INSERT INTO IsoLanguagesDes VALUES (332,'ita','Ottomane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (333,'ita','Papuane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (334,'ita','Pangasinan');
INSERT INTO IsoLanguagesDes VALUES (335,'ita','Pahlavi');
INSERT INTO IsoLanguagesDes VALUES (336,'ita','Pampanga');
INSERT INTO IsoLanguagesDes VALUES (337,'ita','Panjabi; Punjabi');
INSERT INTO IsoLanguagesDes VALUES (338,'ita','Papiamento');
INSERT INTO IsoLanguagesDes VALUES (339,'ita','Palau');
INSERT INTO IsoLanguagesDes VALUES (340,'ita','Persiano Antico (ca.600-400 B.C.)');
INSERT INTO IsoLanguagesDes VALUES (341,'ita','Persiano');
INSERT INTO IsoLanguagesDes VALUES (342,'ita','Filippine, Lingue');
INSERT INTO IsoLanguagesDes VALUES (343,'ita','Fenicio');
INSERT INTO IsoLanguagesDes VALUES (344,'ita','Pali');
INSERT INTO IsoLanguagesDes VALUES (345,'ita','Polacco');
INSERT INTO IsoLanguagesDes VALUES (346,'ita','Pohnpeian');
INSERT INTO IsoLanguagesDes VALUES (347,'ita','Portoghese');
INSERT INTO IsoLanguagesDes VALUES (348,'ita','Prakrit, Lingue');
INSERT INTO IsoLanguagesDes VALUES (349,'ita','Provenzale Antico (fino al 1500); Occitano Antico (fino al 1500)');
INSERT INTO IsoLanguagesDes VALUES (350,'ita','Pasthu; Afgano');
INSERT INTO IsoLanguagesDes VALUES (351,'ita','Riservato per uso locale');
INSERT INTO IsoLanguagesDes VALUES (352,'ita','Quechua');
INSERT INTO IsoLanguagesDes VALUES (353,'ita','Rajasthani');
INSERT INTO IsoLanguagesDes VALUES (354,'ita','Rapanui');
INSERT INTO IsoLanguagesDes VALUES (355,'ita','Rarotongan; Maori dell''Isola di Cook');
INSERT INTO IsoLanguagesDes VALUES (356,'ita','Romanze, Lingue');
INSERT INTO IsoLanguagesDes VALUES (357,'ita','Romancio');
INSERT INTO IsoLanguagesDes VALUES (358,'ita','Romany');
INSERT INTO IsoLanguagesDes VALUES (359,'ita','Rumeno');
INSERT INTO IsoLanguagesDes VALUES (360,'ita','Rundi');
INSERT INTO IsoLanguagesDes VALUES (361,'ita','Aromeno; Arumeno; Macedone-Romeno');
INSERT INTO IsoLanguagesDes VALUES (362,'ita','Russo');
INSERT INTO IsoLanguagesDes VALUES (363,'ita','Sandawe');
INSERT INTO IsoLanguagesDes VALUES (364,'ita','Sango');
INSERT INTO IsoLanguagesDes VALUES (365,'ita','Yakut');
INSERT INTO IsoLanguagesDes VALUES (366,'ita','Sud America, Lingue (indiane)');
INSERT INTO IsoLanguagesDes VALUES (367,'ita','Salishan, Lingue');
INSERT INTO IsoLanguagesDes VALUES (368,'ita','Aramaico Samaritano');
INSERT INTO IsoLanguagesDes VALUES (369,'ita','Sanscrito');
INSERT INTO IsoLanguagesDes VALUES (370,'ita','Sasak');
INSERT INTO IsoLanguagesDes VALUES (371,'ita','Santali');
INSERT INTO IsoLanguagesDes VALUES (372,'ita','Serbo');
INSERT INTO IsoLanguagesDes VALUES (373,'ita','Siciliano');
INSERT INTO IsoLanguagesDes VALUES (374,'ita','Scots');
INSERT INTO IsoLanguagesDes VALUES (375,'ita','Croatian');
INSERT INTO IsoLanguagesDes VALUES (376,'ita','Selkup');
INSERT INTO IsoLanguagesDes VALUES (377,'ita','Semitiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (378,'ita','Irlandese Antico (fino al 900)');
INSERT INTO IsoLanguagesDes VALUES (379,'ita','Linguaggi dei Segni');
INSERT INTO IsoLanguagesDes VALUES (380,'ita','Shan');
INSERT INTO IsoLanguagesDes VALUES (381,'ita','Sidamo');
INSERT INTO IsoLanguagesDes VALUES (382,'ita','Sinhala; Sinhalese');
INSERT INTO IsoLanguagesDes VALUES (383,'ita','Siouan, Lingue');
INSERT INTO IsoLanguagesDes VALUES (384,'ita','Sino-Tibetane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (385,'ita','Slave, Lingue');
INSERT INTO IsoLanguagesDes VALUES (386,'ita','Slovacco');
INSERT INTO IsoLanguagesDes VALUES (387,'ita','Sloveno');
INSERT INTO IsoLanguagesDes VALUES (388,'ita','Sami del Sud');
INSERT INTO IsoLanguagesDes VALUES (389,'ita','Sami del Nord');
INSERT INTO IsoLanguagesDes VALUES (390,'ita','Sami, Lingue');
INSERT INTO IsoLanguagesDes VALUES (391,'ita','Sami Lule');
INSERT INTO IsoLanguagesDes VALUES (392,'ita','Sami Inari');
INSERT INTO IsoLanguagesDes VALUES (393,'ita','Samoano');
INSERT INTO IsoLanguagesDes VALUES (394,'ita','Sami Skolt');
INSERT INTO IsoLanguagesDes VALUES (395,'ita','Shona');
INSERT INTO IsoLanguagesDes VALUES (396,'ita','Sindhi');
INSERT INTO IsoLanguagesDes VALUES (397,'ita','Soninke');
INSERT INTO IsoLanguagesDes VALUES (398,'ita','Sogdian');
INSERT INTO IsoLanguagesDes VALUES (399,'ita','Somalo');
INSERT INTO IsoLanguagesDes VALUES (400,'ita','Songhai, Lingue');
INSERT INTO IsoLanguagesDes VALUES (401,'ita','Sotho del Sud');
INSERT INTO IsoLanguagesDes VALUES (402,'ita','Spagnolo; Castigliano');
INSERT INTO IsoLanguagesDes VALUES (403,'ita','Sardo; Zazaki');
INSERT INTO IsoLanguagesDes VALUES (404,'ita','Sranan Tongo');
INSERT INTO IsoLanguagesDes VALUES (405,'ita','Serer');
INSERT INTO IsoLanguagesDes VALUES (406,'ita','Nilo-Sahariane, Lingue');
INSERT INTO IsoLanguagesDes VALUES (407,'ita','Swati');
INSERT INTO IsoLanguagesDes VALUES (408,'ita','Sukuma');
INSERT INTO IsoLanguagesDes VALUES (409,'ita','Sundanese');
INSERT INTO IsoLanguagesDes VALUES (410,'ita','Susu');
INSERT INTO IsoLanguagesDes VALUES (411,'ita','Sumero');
INSERT INTO IsoLanguagesDes VALUES (412,'ita','Swahili');
INSERT INTO IsoLanguagesDes VALUES (413,'ita','Svedese');
INSERT INTO IsoLanguagesDes VALUES (414,'ita','Siriano');
INSERT INTO IsoLanguagesDes VALUES (415,'ita','Thaitiano');
INSERT INTO IsoLanguagesDes VALUES (416,'ita','Tai, Lingue');
INSERT INTO IsoLanguagesDes VALUES (417,'ita','Tamil');
INSERT INTO IsoLanguagesDes VALUES (418,'ita','Tatarico');
INSERT INTO IsoLanguagesDes VALUES (419,'ita','Telugu');
INSERT INTO IsoLanguagesDes VALUES (420,'ita','Timnendere)');
INSERT INTO IsoLanguagesDes VALUES (421,'ita','Tereno');
INSERT INTO IsoLanguagesDes VALUES (422,'ita','Tetum');
INSERT INTO IsoLanguagesDes VALUES (423,'ita','Tajik');
INSERT INTO IsoLanguagesDes VALUES (424,'ita','Tagalog');
INSERT INTO IsoLanguagesDes VALUES (425,'ita','Thailandese');
INSERT INTO IsoLanguagesDes VALUES (426,'ita','Tibetano');
INSERT INTO IsoLanguagesDes VALUES (427,'ita','Tigre');
INSERT INTO IsoLanguagesDes VALUES (428,'ita','Tigrinya');
INSERT INTO IsoLanguagesDes VALUES (429,'ita','Tiv');
INSERT INTO IsoLanguagesDes VALUES (430,'ita','Tokelau');
INSERT INTO IsoLanguagesDes VALUES (431,'ita','Klingon; tlhIngan-Hol');
INSERT INTO IsoLanguagesDes VALUES (432,'ita','Tlingit');
INSERT INTO IsoLanguagesDes VALUES (433,'ita','Tamashek');
INSERT INTO IsoLanguagesDes VALUES (434,'ita','Tonga (Nyasa)');
INSERT INTO IsoLanguagesDes VALUES (435,'ita','Tonga (Isole Tonga)');
INSERT INTO IsoLanguagesDes VALUES (436,'ita','Tok Pisin');
INSERT INTO IsoLanguagesDes VALUES (437,'ita','Tsimshian');
INSERT INTO IsoLanguagesDes VALUES (438,'ita','Tswana');
INSERT INTO IsoLanguagesDes VALUES (439,'ita','Tsonga');
INSERT INTO IsoLanguagesDes VALUES (440,'ita','Turcmeno');
INSERT INTO IsoLanguagesDes VALUES (441,'ita','Tumbuka');
INSERT INTO IsoLanguagesDes VALUES (442,'ita','Tupi, Lingue');
INSERT INTO IsoLanguagesDes VALUES (443,'ita','Turco');
INSERT INTO IsoLanguagesDes VALUES (444,'ita','Altaiche, Lingue');
INSERT INTO IsoLanguagesDes VALUES (445,'ita','Tuvalu');
INSERT INTO IsoLanguagesDes VALUES (446,'ita','Twi');
INSERT INTO IsoLanguagesDes VALUES (447,'ita','Tuvinian');
INSERT INTO IsoLanguagesDes VALUES (448,'ita','Udmurt');
INSERT INTO IsoLanguagesDes VALUES (449,'ita','Ugaritico');
INSERT INTO IsoLanguagesDes VALUES (450,'ita','Uighur; Uyghur');
INSERT INTO IsoLanguagesDes VALUES (451,'ita','Ucraino');
INSERT INTO IsoLanguagesDes VALUES (452,'ita','Umbundu');
INSERT INTO IsoLanguagesDes VALUES (453,'ita','Non determinato');
INSERT INTO IsoLanguagesDes VALUES (454,'ita','Urdu');
INSERT INTO IsoLanguagesDes VALUES (455,'ita','Uzbeco');
INSERT INTO IsoLanguagesDes VALUES (456,'ita','Vai');
INSERT INTO IsoLanguagesDes VALUES (457,'ita','Venda');
INSERT INTO IsoLanguagesDes VALUES (458,'ita','Vietnamita');
INSERT INTO IsoLanguagesDes VALUES (459,'ita','Volapük');
INSERT INTO IsoLanguagesDes VALUES (460,'ita','Votic');
INSERT INTO IsoLanguagesDes VALUES (461,'ita','Wakashan, Lingue');
INSERT INTO IsoLanguagesDes VALUES (462,'ita','Walamo');
INSERT INTO IsoLanguagesDes VALUES (463,'ita','Waray');
INSERT INTO IsoLanguagesDes VALUES (464,'ita','Washo');
INSERT INTO IsoLanguagesDes VALUES (465,'ita','Gallese');
INSERT INTO IsoLanguagesDes VALUES (466,'ita','Sorabe, Lingue');
INSERT INTO IsoLanguagesDes VALUES (467,'ita','Vallone');
INSERT INTO IsoLanguagesDes VALUES (468,'ita','Volof');
INSERT INTO IsoLanguagesDes VALUES (469,'ita','Kalmyk; Oirat');
INSERT INTO IsoLanguagesDes VALUES (470,'ita','Xhosa');
INSERT INTO IsoLanguagesDes VALUES (471,'ita','Yao');
INSERT INTO IsoLanguagesDes VALUES (472,'ita','Yapese');
INSERT INTO IsoLanguagesDes VALUES (473,'ita','Yiddish');
INSERT INTO IsoLanguagesDes VALUES (474,'ita','Yoruba');
INSERT INTO IsoLanguagesDes VALUES (475,'ita','Yupik, Lingue');
INSERT INTO IsoLanguagesDes VALUES (476,'ita','Zapotec');
INSERT INTO IsoLanguagesDes VALUES (477,'ita','Zenaga');
INSERT INTO IsoLanguagesDes VALUES (478,'ita','Zhuang; Chuang');
INSERT INTO IsoLanguagesDes VALUES (479,'ita','Zande, Lingue');
INSERT INTO IsoLanguagesDes VALUES (480,'ita','Zulu');
INSERT INTO IsoLanguagesDes VALUES (481,'ita','Zuni');
INSERT INTO IsoLanguagesDes VALUES (482,'ita','Nessun contenuto linguistico; non applicabile');
INSERT INTO IsoLanguagesDes VALUES (483,'ita','N''Ko');
INSERT INTO IsoLanguagesDes VALUES (484,'ita','Zaza; Dimili; Dimli; Kirdki; Kirmanjki');

INSERT INTO OperationsDes VALUES (0,'ita','Pubblica');
INSERT INTO OperationsDes VALUES (1,'ita','Scarica');
INSERT INTO OperationsDes VALUES (2,'ita','Modifica');
INSERT INTO OperationsDes VALUES (3,'ita','Notifica');
INSERT INTO OperationsDes VALUES (5,'ita','Mappa interattiva');
INSERT INTO OperationsDes VALUES (6,'ita','In rilievo');

INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (0,'ita','Sconosciuto');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (1,'ita','Bozza');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (2,'ita','Approvato');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (3,'ita','Ritirato');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (4,'ita','Proposto');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (5,'ita','Respinto');

INSERT INTO RegionsDes VALUES (1,'ita','Armenia');
INSERT INTO RegionsDes VALUES (2,'ita','Afghanistan');
INSERT INTO RegionsDes VALUES (3,'ita','Albania');
INSERT INTO RegionsDes VALUES (4,'ita','Algeria');
INSERT INTO RegionsDes VALUES (5,'ita','Samoa Americane');
INSERT INTO RegionsDes VALUES (6,'ita','Andorra');
INSERT INTO RegionsDes VALUES (7,'ita','Angola');
INSERT INTO RegionsDes VALUES (8,'ita','Antigua e Barbuda');
INSERT INTO RegionsDes VALUES (9,'ita','Argentina');
INSERT INTO RegionsDes VALUES (10,'ita','Australia');
INSERT INTO RegionsDes VALUES (11,'ita','Austria');
INSERT INTO RegionsDes VALUES (12,'ita','Bahamas');
INSERT INTO RegionsDes VALUES (13,'ita','Bahrain');
INSERT INTO RegionsDes VALUES (14,'ita','Barbados');
INSERT INTO RegionsDes VALUES (16,'ita','Bangladesh');
INSERT INTO RegionsDes VALUES (17,'ita','Bermuda');
INSERT INTO RegionsDes VALUES (18,'ita','Bhutan');
INSERT INTO RegionsDes VALUES (19,'ita','Bolivia');
INSERT INTO RegionsDes VALUES (20,'ita','Botswana');
INSERT INTO RegionsDes VALUES (21,'ita','Brasile');
INSERT INTO RegionsDes VALUES (22,'ita','Aruba');
INSERT INTO RegionsDes VALUES (23,'ita','Belize');
INSERT INTO RegionsDes VALUES (24,'ita','Territorio britannico dell''oceano Indiano');
INSERT INTO RegionsDes VALUES (25,'ita','Isole Salomone');
INSERT INTO RegionsDes VALUES (26,'ita','Brunei Darussalam');
INSERT INTO RegionsDes VALUES (27,'ita','Bulgaria');
INSERT INTO RegionsDes VALUES (28,'ita','Birmania');
INSERT INTO RegionsDes VALUES (29,'ita','Burundi');
INSERT INTO RegionsDes VALUES (30,'ita','Antartide');
INSERT INTO RegionsDes VALUES (31,'ita','Isola Bouvet');
INSERT INTO RegionsDes VALUES (32,'ita','Camerun');
INSERT INTO RegionsDes VALUES (33,'ita','Canada');
INSERT INTO RegionsDes VALUES (35,'ita','Capo Verde');
INSERT INTO RegionsDes VALUES (36,'ita','Isole Cayman');
INSERT INTO RegionsDes VALUES (37,'ita','Repubblica Centrafricana');
INSERT INTO RegionsDes VALUES (38,'ita','Sri Lanka');
INSERT INTO RegionsDes VALUES (39,'ita','Ciad');
INSERT INTO RegionsDes VALUES (40,'ita','Cile');
INSERT INTO RegionsDes VALUES (41,'ita','Cina');
INSERT INTO RegionsDes VALUES (42,'ita','Isola di Natale');
INSERT INTO RegionsDes VALUES (43,'ita','Isole Cocos e Keeling');
INSERT INTO RegionsDes VALUES (44,'ita','Colombia');
INSERT INTO RegionsDes VALUES (45,'ita','Comore');
INSERT INTO RegionsDes VALUES (46,'ita','Repubblica del Congo');
INSERT INTO RegionsDes VALUES (47,'ita','Isole Cook');
INSERT INTO RegionsDes VALUES (48,'ita','Costa Rica');
INSERT INTO RegionsDes VALUES (49,'ita','Cuba');
INSERT INTO RegionsDes VALUES (50,'ita','Cipro');
INSERT INTO RegionsDes VALUES (52,'ita','Azerbaigian');
INSERT INTO RegionsDes VALUES (53,'ita','Benin');
INSERT INTO RegionsDes VALUES (54,'ita','Danimarca');
INSERT INTO RegionsDes VALUES (55,'ita','Dominica');
INSERT INTO RegionsDes VALUES (56,'ita','Repubblica Dominicana');
INSERT INTO RegionsDes VALUES (57,'ita','Bielorussia');
INSERT INTO RegionsDes VALUES (58,'ita','Ecuador');
INSERT INTO RegionsDes VALUES (59,'ita','Egitto');
INSERT INTO RegionsDes VALUES (60,'ita','El Salvador');
INSERT INTO RegionsDes VALUES (61,'ita','Guinea Equatoriale');
INSERT INTO RegionsDes VALUES (63,'ita','Estonia');
INSERT INTO RegionsDes VALUES (64,'ita','Isole Faeroe');
INSERT INTO RegionsDes VALUES (65,'ita','Isole Falkland');
INSERT INTO RegionsDes VALUES (66,'ita','Figi');
INSERT INTO RegionsDes VALUES (67,'ita','Finlandia');
INSERT INTO RegionsDes VALUES (68,'ita','Francia');
INSERT INTO RegionsDes VALUES (69,'ita','Guyana Francese');
INSERT INTO RegionsDes VALUES (70,'ita','Polinesia Francese');
INSERT INTO RegionsDes VALUES (71,'ita','Francia, Terre australi e antartiche');
INSERT INTO RegionsDes VALUES (72,'ita','Gibuti');
INSERT INTO RegionsDes VALUES (73,'ita','Georgia');
INSERT INTO RegionsDes VALUES (74,'ita','Gabon');
INSERT INTO RegionsDes VALUES (75,'ita','Gambia');
INSERT INTO RegionsDes VALUES (76,'ita','Gaza, striscia di');
INSERT INTO RegionsDes VALUES (79,'ita','Germania');
INSERT INTO RegionsDes VALUES (80,'ita','Bosnia-Erzegovina');
INSERT INTO RegionsDes VALUES (81,'ita','Ghana');
INSERT INTO RegionsDes VALUES (82,'ita','Gibilterra');
INSERT INTO RegionsDes VALUES (83,'ita','Kiribati');
INSERT INTO RegionsDes VALUES (84,'ita','Grecia');
INSERT INTO RegionsDes VALUES (85,'ita','Groenlandia');
INSERT INTO RegionsDes VALUES (86,'ita','Grenada');
INSERT INTO RegionsDes VALUES (87,'ita','Guadalupa');
INSERT INTO RegionsDes VALUES (88,'ita','Guam');
INSERT INTO RegionsDes VALUES (89,'ita','Guatemala');
INSERT INTO RegionsDes VALUES (90,'ita','Guinea');
INSERT INTO RegionsDes VALUES (91,'ita','Guyana');
INSERT INTO RegionsDes VALUES (92,'ita','Isole Heard e McDonald');
INSERT INTO RegionsDes VALUES (93,'ita','Haiti');
INSERT INTO RegionsDes VALUES (95,'ita','Honduras');
INSERT INTO RegionsDes VALUES (97,'ita','Ungheria');
INSERT INTO RegionsDes VALUES (98,'ita','Croazia');
INSERT INTO RegionsDes VALUES (99,'ita','Islanda');
INSERT INTO RegionsDes VALUES (100,'ita','India');
INSERT INTO RegionsDes VALUES (101,'ita','Indonesia');
INSERT INTO RegionsDes VALUES (102,'ita','Iran');
INSERT INTO RegionsDes VALUES (103,'ita','Iraq');
INSERT INTO RegionsDes VALUES (104,'ita','Irlanda');
INSERT INTO RegionsDes VALUES (105,'ita','Israele');
INSERT INTO RegionsDes VALUES (106,'ita','Italia');
INSERT INTO RegionsDes VALUES (107,'ita','Costa d''Avorio');
INSERT INTO RegionsDes VALUES (108,'ita','Kazakistan');
INSERT INTO RegionsDes VALUES (109,'ita','Giamaica');
INSERT INTO RegionsDes VALUES (110,'ita','Giappone');
INSERT INTO RegionsDes VALUES (112,'ita','Giordania');
INSERT INTO RegionsDes VALUES (113,'ita','Kirghizistan');
INSERT INTO RegionsDes VALUES (114,'ita','Kenia');
INSERT INTO RegionsDes VALUES (115,'ita','Cambogia');
INSERT INTO RegionsDes VALUES (116,'ita','Corea, Repubblica Democratica Popolare di');
INSERT INTO RegionsDes VALUES (117,'ita','Corea, Repubblica di');
INSERT INTO RegionsDes VALUES (118,'ita','Kuwait');
INSERT INTO RegionsDes VALUES (119,'ita','Lettonia');
INSERT INTO RegionsDes VALUES (120,'ita','Laos');
INSERT INTO RegionsDes VALUES (121,'ita','Libano');
INSERT INTO RegionsDes VALUES (122,'ita','Lesotho');
INSERT INTO RegionsDes VALUES (123,'ita','Liberia');
INSERT INTO RegionsDes VALUES (124,'ita','Libia');
INSERT INTO RegionsDes VALUES (125,'ita','Liechtenstein');
INSERT INTO RegionsDes VALUES (126,'ita','Lituania');
INSERT INTO RegionsDes VALUES (127,'ita','Isole Marshall');
INSERT INTO RegionsDes VALUES (129,'ita','Madagascar');
INSERT INTO RegionsDes VALUES (130,'ita','Malawi');
INSERT INTO RegionsDes VALUES (131,'ita','Malesia');
INSERT INTO RegionsDes VALUES (132,'ita','Maldive');
INSERT INTO RegionsDes VALUES (133,'ita','Mali');
INSERT INTO RegionsDes VALUES (134,'ita','Malta');
INSERT INTO RegionsDes VALUES (135,'ita','Martinica');
INSERT INTO RegionsDes VALUES (136,'ita','Mauritania');
INSERT INTO RegionsDes VALUES (137,'ita','Mauritius');
INSERT INTO RegionsDes VALUES (138,'ita','Messico');
INSERT INTO RegionsDes VALUES (139,'ita','Isole Midway');
INSERT INTO RegionsDes VALUES (140,'ita','Monaco');
INSERT INTO RegionsDes VALUES (141,'ita','Mongolia');
INSERT INTO RegionsDes VALUES (142,'ita','Montserrat');
INSERT INTO RegionsDes VALUES (143,'ita','Marocco');
INSERT INTO RegionsDes VALUES (144,'ita','Mozambico');
INSERT INTO RegionsDes VALUES (145,'ita','Micronesia, Stati Federati di');
INSERT INTO RegionsDes VALUES (146,'ita','Moldavia');
INSERT INTO RegionsDes VALUES (147,'ita','Namibia');
INSERT INTO RegionsDes VALUES (148,'ita','Nauru');
INSERT INTO RegionsDes VALUES (149,'ita','Nepal');
INSERT INTO RegionsDes VALUES (150,'ita','Paesi Bassi');
INSERT INTO RegionsDes VALUES (151,'ita','Antille Olandesi');
INSERT INTO RegionsDes VALUES (153,'ita','Nuova Caledonia');
INSERT INTO RegionsDes VALUES (154,'ita','Macedonia');
INSERT INTO RegionsDes VALUES (155,'ita','Vanuatu');
INSERT INTO RegionsDes VALUES (156,'ita','Nuova Zelanda');
INSERT INTO RegionsDes VALUES (157,'ita','Nicaragua');
INSERT INTO RegionsDes VALUES (158,'ita','Niger');
INSERT INTO RegionsDes VALUES (159,'ita','Nigeria');
INSERT INTO RegionsDes VALUES (160,'ita','Niue');
INSERT INTO RegionsDes VALUES (161,'ita','Isola Norfolk');
INSERT INTO RegionsDes VALUES (162,'ita','Norvegia');
INSERT INTO RegionsDes VALUES (163,'ita','Isole Marianne Settentrionali');
INSERT INTO RegionsDes VALUES (165,'ita','Pakistan');
INSERT INTO RegionsDes VALUES (166,'ita','Panama');
INSERT INTO RegionsDes VALUES (167,'ita','Ceca, Repubblica');
INSERT INTO RegionsDes VALUES (168,'ita','Papua Nuova Guinea');
INSERT INTO RegionsDes VALUES (169,'ita','Paraguay');
INSERT INTO RegionsDes VALUES (170,'ita','Peru');
INSERT INTO RegionsDes VALUES (171,'ita','Filippine');
INSERT INTO RegionsDes VALUES (172,'ita','Isole Pitcairn');
INSERT INTO RegionsDes VALUES (173,'ita','Polonia');
INSERT INTO RegionsDes VALUES (174,'ita','Portogallo');
INSERT INTO RegionsDes VALUES (175,'ita','Guinea-Bissau');
INSERT INTO RegionsDes VALUES (176,'ita','Timor Est');
INSERT INTO RegionsDes VALUES (177,'ita','Porto Rico');
INSERT INTO RegionsDes VALUES (178,'ita','Eritrea');
INSERT INTO RegionsDes VALUES (179,'ita','Qatar');
INSERT INTO RegionsDes VALUES (181,'ita','Zimbabwe');
INSERT INTO RegionsDes VALUES (182,'ita','Reunion');
INSERT INTO RegionsDes VALUES (183,'ita','Romania');
INSERT INTO RegionsDes VALUES (184,'ita','Ruanda');
INSERT INTO RegionsDes VALUES (185,'ita','Russia');
INSERT INTO RegionsDes VALUES (187,'ita','Sant''Elena');
INSERT INTO RegionsDes VALUES (188,'ita','Saint Kitts e Nevis');
INSERT INTO RegionsDes VALUES (189,'ita','Santa Lucia');
INSERT INTO RegionsDes VALUES (190,'ita','Saint-Pierre e Miquelon');
INSERT INTO RegionsDes VALUES (191,'ita','Saint Vincent e Grenadine');
INSERT INTO RegionsDes VALUES (192,'ita','San Marino');
INSERT INTO RegionsDes VALUES (193,'ita','Sao Tome e Principe');
INSERT INTO RegionsDes VALUES (194,'ita','Arabia Saudita');
INSERT INTO RegionsDes VALUES (195,'ita','Senegal');
INSERT INTO RegionsDes VALUES (196,'ita','Seychelles');
INSERT INTO RegionsDes VALUES (197,'ita','Sierra Leone');
INSERT INTO RegionsDes VALUES (198,'ita','Slovenia');
INSERT INTO RegionsDes VALUES (199,'ita','Slovacchia');
INSERT INTO RegionsDes VALUES (200,'ita','Singapore');
INSERT INTO RegionsDes VALUES (201,'ita','Somalia');
INSERT INTO RegionsDes VALUES (202,'ita','Sudafrica');
INSERT INTO RegionsDes VALUES (203,'ita','Spagna');
INSERT INTO RegionsDes VALUES (205,'ita','Sahara Occidentale');
INSERT INTO RegionsDes VALUES (206,'ita','Sudan');
INSERT INTO RegionsDes VALUES (207,'ita','Suriname');
INSERT INTO RegionsDes VALUES (208,'ita','Tagikistan');
INSERT INTO RegionsDes VALUES (209,'ita','Swaziland');
INSERT INTO RegionsDes VALUES (210,'ita','Svezia');
INSERT INTO RegionsDes VALUES (211,'ita','Svizzera');
INSERT INTO RegionsDes VALUES (212,'ita','Siria');
INSERT INTO RegionsDes VALUES (213,'ita','Turkmenistan');
INSERT INTO RegionsDes VALUES (214,'ita','Taiwan');
INSERT INTO RegionsDes VALUES (215,'ita','Tanzania');
INSERT INTO RegionsDes VALUES (216,'ita','Thailandia');
INSERT INTO RegionsDes VALUES (217,'ita','Togo');
INSERT INTO RegionsDes VALUES (218,'ita','Tokelau');
INSERT INTO RegionsDes VALUES (219,'ita','Tonga');
INSERT INTO RegionsDes VALUES (220,'ita','Trinidad e Tobago');
INSERT INTO RegionsDes VALUES (221,'ita','Oman');
INSERT INTO RegionsDes VALUES (222,'ita','Tunisia');
INSERT INTO RegionsDes VALUES (223,'ita','Turchia');
INSERT INTO RegionsDes VALUES (224,'ita','Turks and Caicos');
INSERT INTO RegionsDes VALUES (225,'ita','Emirati Arabi Uniti');
INSERT INTO RegionsDes VALUES (226,'ita','Uganda');
INSERT INTO RegionsDes VALUES (227,'ita','Tuvalu');
INSERT INTO RegionsDes VALUES (229,'ita','Regno Unito');
INSERT INTO RegionsDes VALUES (230,'ita','Ucraina');
INSERT INTO RegionsDes VALUES (231,'ita','Stati Uniti d''America');
INSERT INTO RegionsDes VALUES (232,'ita','Stati Uniti d''America, Isole Minori Esterne ');
INSERT INTO RegionsDes VALUES (233,'ita','Burkina Faso');
INSERT INTO RegionsDes VALUES (234,'ita','Uruguay');
INSERT INTO RegionsDes VALUES (235,'ita','Uzbekistan');
INSERT INTO RegionsDes VALUES (236,'ita','Venezuela');
INSERT INTO RegionsDes VALUES (237,'ita','Vietnam');
INSERT INTO RegionsDes VALUES (238,'ita','Etiopia');
INSERT INTO RegionsDes VALUES (239,'ita','Isole Vergini britanniche');
INSERT INTO RegionsDes VALUES (240,'ita','Isole Vergini americane');
INSERT INTO RegionsDes VALUES (242,'ita','Isola di Wake');
INSERT INTO RegionsDes VALUES (243,'ita','Isole di Wallis e Futuna');
INSERT INTO RegionsDes VALUES (244,'ita','Samoa');
INSERT INTO RegionsDes VALUES (245,'ita','Cisgiordania');
INSERT INTO RegionsDes VALUES (249,'ita','Yemen');
INSERT INTO RegionsDes VALUES (250,'ita','Congo');
INSERT INTO RegionsDes VALUES (251,'ita','Zambia');
INSERT INTO RegionsDes VALUES (255,'ita','Belgio');
INSERT INTO RegionsDes VALUES (256,'ita','Lussemburgo');
INSERT INTO RegionsDes VALUES (258,'ita','Anguilla');
INSERT INTO RegionsDes VALUES (260,'ita','Isola di Svalbard');
INSERT INTO RegionsDes VALUES (264,'ita','Isole di Man');
INSERT INTO RegionsDes VALUES (270,'ita','Mayotte');
INSERT INTO RegionsDes VALUES (271,'ita','Georgia del Sud e isole Sandwich');
INSERT INTO RegionsDes VALUES (303,'ita','Europa Occidentale');
INSERT INTO RegionsDes VALUES (307,'ita','Autorità Intergovernativa per lo Sviluppo');
INSERT INTO RegionsDes VALUES (310,'ita','Africa Occidentale del Nord');
INSERT INTO RegionsDes VALUES (311,'ita','Africa Occidentale');
INSERT INTO RegionsDes VALUES (312,'ita','Africa Centrale');
INSERT INTO RegionsDes VALUES (313,'ita','Africa Orientale');
INSERT INTO RegionsDes VALUES (314,'ita','Africa del Sud');
INSERT INTO RegionsDes VALUES (315,'ita','America Latina');
INSERT INTO RegionsDes VALUES (316,'ita','America Centrale');
INSERT INTO RegionsDes VALUES (317,'ita','Caraibi');
INSERT INTO RegionsDes VALUES (318,'ita','America del Sud');
INSERT INTO RegionsDes VALUES (319,'ita','Vicino Oriente');
INSERT INTO RegionsDes VALUES (320,'ita','Vicino Oriente in Africa');
INSERT INTO RegionsDes VALUES (321,'ita','Vicino Oriente in Asia');
INSERT INTO RegionsDes VALUES (322,'ita','Estremo Oriente');
INSERT INTO RegionsDes VALUES (323,'ita','Asia Meridionale');
INSERT INTO RegionsDes VALUES (324,'ita','Est e Sud-Est Asiatico');
INSERT INTO RegionsDes VALUES (325,'ita','Vicino Oriente & Nord Africa');
INSERT INTO RegionsDes VALUES (334,'ita','Europa Orientale');
INSERT INTO RegionsDes VALUES (335,'ita','Europa');
INSERT INTO RegionsDes VALUES (337,'ita','Asia');
INSERT INTO RegionsDes VALUES (338,'ita','Africa');
INSERT INTO RegionsDes VALUES (348,'ita','America Latina');
INSERT INTO RegionsDes VALUES (370,'ita','Serbia');
INSERT INTO RegionsDes VALUES (371,'ita','Montenegro');
INSERT INTO RegionsDes VALUES (390,'ita','Sahara Meridionale');
INSERT INTO RegionsDes VALUES (421,'ita','Nord Africa');
INSERT INTO RegionsDes VALUES (427,'ita','Europa, Paesi non UE');
INSERT INTO RegionsDes VALUES (428,'ita','Nord America');
INSERT INTO RegionsDes VALUES (469,'ita','URSS, Area Ex');
INSERT INTO RegionsDes VALUES (1008,'ita','Mar Glaciale Artico');
INSERT INTO RegionsDes VALUES (1009,'ita','Atlantico, Nord-Occidentale');
INSERT INTO RegionsDes VALUES (1010,'ita','Atlantico, Nord-Orientale');
INSERT INTO RegionsDes VALUES (1011,'ita','Atlantico, Centro-Occidentale');
INSERT INTO RegionsDes VALUES (1012,'ita','Atlantico, Centro-Orientale');
INSERT INTO RegionsDes VALUES (1013,'ita','Mediterraneo e Mar Nero');
INSERT INTO RegionsDes VALUES (1014,'ita','Atlantico, Sud-Occidentale');
INSERT INTO RegionsDes VALUES (1015,'ita','Atlantico, Sud-Orientale');
INSERT INTO RegionsDes VALUES (1016,'ita','Atlantico, Antartico');
INSERT INTO RegionsDes VALUES (1017,'ita','Oceano Indiano, Occidentale');
INSERT INTO RegionsDes VALUES (1018,'ita','Oceano Indiano, Orientale');
INSERT INTO RegionsDes VALUES (1019,'ita','Oceano Indiano, Antartico');
INSERT INTO RegionsDes VALUES (1020,'ita','Pacifico, Nord-Occidentale');
INSERT INTO RegionsDes VALUES (1021,'ita','Pacifico, Nord-Orientale');
INSERT INTO RegionsDes VALUES (1022,'ita','Pacifico, Centro-Occidentale');
INSERT INTO RegionsDes VALUES (1023,'ita','Pacifico, Contro-Orientale');
INSERT INTO RegionsDes VALUES (1024,'ita','Pacifico, Sud-Occidentale');
INSERT INTO RegionsDes VALUES (1025,'ita','Pacifico, Sud-Orientale');
INSERT INTO RegionsDes VALUES (1026,'ita','Pacifico, Antartico');
INSERT INTO RegionsDes VALUES (1220,'ita','Tutte le zone di pesca');
INSERT INTO RegionsDes VALUES (9999,'ita','Mondo');
