package org.fao.geonet.domain.statistic;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.fao.geonet.domain.Constants;

/**
 * An entity representing a request that was made by a user.  
 * This is part of the statistics tracing
 *
 * @author Jesse
 */
@Entity
@Access(AccessType.PROPERTY)
@Table(name="requests")
public class Request {
    private int _id;
    private String _requestDate;
    private String _ipAddress;
    private String _query;
    private int _hits;
    private String _lang;
    private String _sortBy;
    private String _spatialFilter;
    private String _type;
    private boolean _simple;
    private boolean _autogenerated;
    private String _service;
    private RequestParams _params;

    @Id
    public int getId() {
        return _id;
    }

    public void setId(int id) {
        this._id = id;
    }
    @OneToOne(cascade=CascadeType.ALL, mappedBy = "request" ,orphanRemoval=true, fetch=FetchType.LAZY)
    public RequestParams getParams() {
        return _params;
    }
    public void setParams(RequestParams params) {
        this._params = params;
    }
    @Column(name = "requestdate", length=30)
    public String getRequestDate() {
        return _requestDate;
    }

    public void setRequestDate(String requestDate) {
        this._requestDate = requestDate;
    }

    @Column(name = "ip", length=Constants.IP_ADDRESS_COLUMN_LENGTH)
    public String getIpAddress() {
        return _ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this._ipAddress = ipAddress;
    }

    @Column(length=4000)
    public String getQuery() {
        return _query;
    }

    public void setQuery(String query) {
        this._query = query;
    }

    @Column(nullable=false)
    public int getHits() {
        return _hits;
    }

    public void setHits(int hits) {
        this._hits = hits;
    }
    @Column(length=16)
    public String getLang() {
        return _lang;
    }

    public void setLang(String lang) {
        this._lang = lang;
    }

    @Column(name = "sortby")
    public String getSortBy() {
        return _sortBy;
    }

    public void setSortBy(String sortBy) {
        this._sortBy = sortBy;
    }

    @Column(name = "spatialfilter", length=4000)
    public String getSpatialFilter() {
        return _spatialFilter;
    }

    public void setSpatialFilter(String spatialFilter) {
        this._spatialFilter = spatialFilter;
    }

    @Column(length=4000)
    public String getType() {
        return _type;
    }

    public void setType(String type) {
        this._type = type;
    }

    public String getService() {
        return _service;
    }

    public void setService(String service) {
        this._service = service;
    }

    public boolean isSimple() {
        return _simple;
    }

    public void setSimple(boolean simple) {
        this._simple = simple;
    }

    public boolean isAutogenerated() {
        return _autogenerated;
    }

    public void setAutogenerated(boolean autogenerated) {
        this._autogenerated = autogenerated;
    }

}
