version: '3.1'
volumes:
  geonetwork:

services:
  frontend:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      #      - cas
      - geonetwork

  ldap:
    build:
      context: ../core/src/test/docker/ldap
    image: sextant-ldap:latest

      #  cas:
      #    build:
      #      context: ./cas
      #      dockerfile: Dockerfile
      #    image: sextant-cas:latest
      #    environment:
      #      JAVA_OPTS: -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
      #    volumes:
      #      - ./cas/cas-overlay-template-6.2/etc/cas:/etc/cas
      #    ports:
      #      - 5005:5005
      #    depends_on:
      #      - ldap

  geonetwork:
    build: .
    image: sextant-geonetwork:elastic
    restart: always
    env_file:
      - ./.env
    environment:
      # configure the tomcat connector
      # Needed for GN to send a service
      # URL to CAS which would be coherent
      # with what CAS expects
      CONNECTOR_PROXY_NAME: ${DOCKER_HOST_ADDRESS}
      CONNECTOR_PROXY_PORT: 8080
      DATA_DIR: /var/lib/geonetwork_data
      ES_HOST: elasticsearch
      ES_PROTOCOL: http
      ES_PORT: 9200
      ES_INDEX_SEARCHLOGS: geo-searchlogs
      ES_INDEX_RECORDS: geo-records
      ES_INDEX_FEATURES: geo-features
      KB_URL: ""
      POSTGRES_DB_HOST: database
      POSTGRES_DB_NAME: sextant
      POSTGRES_DB_USERNAME: sxt
      POSTGRES_DB_PASSWORD: sxt
      # To be set in accordance with the ldap container
      LDAP_URL: "ldap://ldap:389"
      LDAP_ADMIN_DN: cn=admin,dc=ifremer,dc=fr
      LDAP_ADMIN_PASSWORD: secret
      CAS_URL: "https://users.marine-id.org"
      GN_URL: "http://${DOCKER_HOST_ADDRESS}:8080/geonetwork"
      CAS_TICKET_VALIDATION_URL: "https://users.marine-id.org"
      PANIER_XML_PATH_LOGGED: "/export/home/tomcat/instances_data/sextant-test/panier/folders/aTraiter/intranet"
      PANIER_XML_PATH_ANONYMOUS: "/export/home/tomcat/instances_data/sextant-test/panier/folders/aTraiter/anonymous"
      JAVA_OPTS: -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    volumes:
      - geonetwork:/var/lib/geonetwork_data
    depends_on:
      - elasticsearch
      - database
    ports:
      - 5006:5005

  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      discovery.type: single-node

  database:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: sxt
      POSTGRES_PASSWORD: sxt
      POSTGRES_DB: sextant
