url=jdbc:postgresql://localhost:5432/geonetwork-dev
username=www-data
password=www-data
driver=org.postgresql.Driver
changeLogFile=src/main/resources/db/changelog.xml
referenceUrl=jdbc:postgresql://localhost:5432/geonetwork-prod
referenceUsername=www-data
referencePassword=www-data
