--
-- DB migration script for Sextant from v5.0 to 5.1

--SET search_path = geonetwork;

CREATE TABLE CustomElementSet
  (
    xpath  varchar(1000) not null
  );
  
  
ALTER TABLE Metadata ALTER COLUMN harvestUri TYPE varchar(455);

ALTER TABLE HarvestHistory ADD elapsedTime int;

INSERT INTO Settings VALUES (960,1,'wiki',NULL);
INSERT INTO Settings VALUES (961,960,'markup','none');
INSERT INTO Settings VALUES (962,960,'output','strip');
INSERT INTO Settings VALUES (963,960,'mefoutput','strip');

INSERT INTO Settings VALUES (964,1,'wysiwyg',NULL);
INSERT INTO Settings VALUES (965,964,'enable','false');

CREATE TABLE Requests
  (
    id             int,
    requestDate    varchar(30),
    ip             varchar(128),
    query          varchar(4000),
    hits           int,
    lang           varchar(16),
    sortBy         varchar(128),
    spatialFilter  varchar(4000),
    type           varchar(4000),
    simple         int             default 1,
    autogenerated  int             default 0,
    service        varchar(128),

    primary key(id)
  );

CREATE INDEX RequestsNDX1 ON Requests(requestDate);
CREATE INDEX RequestsNDX2 ON Requests(ip);
CREATE INDEX RequestsNDX3 ON Requests(hits);
CREATE INDEX RequestsNDX4 ON Requests(lang);

-- ======================================================================

CREATE TABLE Params
  (
    id          int,
    requestId   int,
    queryType   varchar(128),
    termField   varchar(128),
    termText    varchar(128),
    similarity  float,
    lowerText   varchar(128),
    upperText   varchar(128),
    inclusive   char(1),

    primary key(id),

    foreign key(requestId) references Requests(id)
  );

CREATE INDEX ParamsNDX1 ON Params(requestId);
CREATE INDEX ParamsNDX2 ON Params(queryType);
CREATE INDEX ParamsNDX3 ON Params(termField);
CREATE INDEX ParamsNDX4 ON Params(termText);
