package org.fao.geonet.domain;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.fao.geonet.entitylistener.MetadataIndicatorEntityListenerManager;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import java.io.Serializable;

@Entity
@Access(AccessType.PROPERTY)
@Cacheable
@Table(name = MetadataIndicator.TABLE_NAME)
@EntityListeners(MetadataIndicatorEntityListenerManager.class)
@SequenceGenerator(name = MetadataIndicator.ID_SEQ_NAME, initialValue = 100, allocationSize = 1)
public class MetadataIndicator implements Serializable {
    static final String ID_SEQ_NAME = "metadataindicator_id_seq";

    public static final String TABLE_NAME = "MetadataIndicator";
    public static final String ID_COLUMN_NAME = "id";

    private int id;
    private String name;
    private String value;

    /**
     * Get the id of the metadata indicator.
     * <p>
     * This is autogenerated and when a new link is created the metadata indicator will be
     * assigned a new value.
     *
     * @return the id of the metadata indicator.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = ID_SEQ_NAME)
    @Column(name = ID_COLUMN_NAME, nullable = false)
    public int getId() {
        return id;
    }

    public MetadataIndicator setId(int id) {
        this.id = id;
        return this;
    }

    /**
     * Metadata indicator name.
     */
    @Column(nullable = false)
    public String getName() {
        return name;
    }

    public MetadataIndicator setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Metadata indicator value.
     */
    @Column(nullable = false)
    public String getValue() {
        return value;
    }

    public MetadataIndicator setValue(String value) {
        this.value = value;
        return this;
    }
}
