-- ISO 3 letter code migration
INSERT INTO Languages VALUES ('fin','Suomi', 'y', 'n');

UPDATE CategoriesDes             SET langid='fin' WHERE langid='fi';
UPDATE IsoLanguagesDes           SET langid='fin' WHERE langid='fi';
UPDATE RegionsDes                SET langid='fin' WHERE langid='fi';
UPDATE GroupsDes                 SET langid='fin' WHERE langid='fi';
UPDATE OperationsDes             SET langid='fin' WHERE langid='fi';
UPDATE StatusValuesDes           SET langid='fin' WHERE langid='fi';
UPDATE CswServerCapabilitiesInfo SET langid='fin' WHERE langid='fi';
DELETE FROM Languages WHERE id='fi';

-- Take care to table ID (related to other loc files)
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (1,'fin','Kartat & kuvat');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (2,'fin','Tietoaineistot');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (3,'fin','Vuorovaikutteiset resurssit');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (4,'fin','Sovellukset');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (5,'fin','Esimerkkitapaukset, parhaat käytännöt');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (6,'fin','Konferenssijulkaisut');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (7,'fin','Valokuvat');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (8,'fin','Äänitteet / Videot');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (9,'fin','Hakemistot');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (10,'fin','Other information resources');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (11,'fin','Z3950 Servers');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (12,'fin','Registers');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (13,'fin','Fyysisiä näytteitä');

INSERT INTO GroupsDes (iddes, langid, label) VALUES (-1,'fin','Vierailija');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (0,'fin','Intranet');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (1,'fin','Kaikki');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (2,'fin','Ryhmä');

INSERT INTO IsoLanguagesDes VALUES (1,'fin','Afar');
INSERT INTO IsoLanguagesDes VALUES (2,'fin','Abkhazian');
INSERT INTO IsoLanguagesDes VALUES (3,'fin','Achinese');
INSERT INTO IsoLanguagesDes VALUES (4,'fin','Acoli');
INSERT INTO IsoLanguagesDes VALUES (5,'fin','Adangme');
INSERT INTO IsoLanguagesDes VALUES (6,'fin','Adyghe; Adygei');
INSERT INTO IsoLanguagesDes VALUES (7,'fin','Afro-Asiatic (Other)');
INSERT INTO IsoLanguagesDes VALUES (8,'fin','Afrihili');
INSERT INTO IsoLanguagesDes VALUES (9,'fin','Afrikaans');
INSERT INTO IsoLanguagesDes VALUES (10,'fin','Ainu');
INSERT INTO IsoLanguagesDes VALUES (11,'fin','Akan');
INSERT INTO IsoLanguagesDes VALUES (12,'fin','Akkadian');
INSERT INTO IsoLanguagesDes VALUES (13,'fin','Albanian');
INSERT INTO IsoLanguagesDes VALUES (14,'fin','Aleut');
INSERT INTO IsoLanguagesDes VALUES (15,'fin','Algonquian languages');
INSERT INTO IsoLanguagesDes VALUES (16,'fin','Southern Altai');
INSERT INTO IsoLanguagesDes VALUES (17,'fin','Amharic');
INSERT INTO IsoLanguagesDes VALUES (18,'fin','English, Old (ca.450-1100)');
INSERT INTO IsoLanguagesDes VALUES (19,'fin','Angika');
INSERT INTO IsoLanguagesDes VALUES (20,'fin','Apache languages');
INSERT INTO IsoLanguagesDes VALUES (21,'fin','Arabic');
INSERT INTO IsoLanguagesDes VALUES (22,'fin','Aramaic');
INSERT INTO IsoLanguagesDes VALUES (23,'fin','Aragonese');
INSERT INTO IsoLanguagesDes VALUES (24,'fin','Armenian');
INSERT INTO IsoLanguagesDes VALUES (25,'fin','Mapudungun; Mapuche');
INSERT INTO IsoLanguagesDes VALUES (26,'fin','Arapaho');
INSERT INTO IsoLanguagesDes VALUES (27,'fin','Artificial (Other)');
INSERT INTO IsoLanguagesDes VALUES (28,'fin','Arawak');
INSERT INTO IsoLanguagesDes VALUES (29,'fin','Assamese');
INSERT INTO IsoLanguagesDes VALUES (30,'fin','Asturian; Bable');
INSERT INTO IsoLanguagesDes VALUES (31,'fin','Athapascan languages');
INSERT INTO IsoLanguagesDes VALUES (32,'fin','Australian languages');
INSERT INTO IsoLanguagesDes VALUES (33,'fin','Avaric');
INSERT INTO IsoLanguagesDes VALUES (34,'fin','Avestan');
INSERT INTO IsoLanguagesDes VALUES (35,'fin','Awadhi');
INSERT INTO IsoLanguagesDes VALUES (36,'fin','Aymara');
INSERT INTO IsoLanguagesDes VALUES (37,'fin','Azerbaijani');
INSERT INTO IsoLanguagesDes VALUES (38,'fin','Banda languages');
INSERT INTO IsoLanguagesDes VALUES (39,'fin','Bamileke languages');
INSERT INTO IsoLanguagesDes VALUES (40,'fin','Bashkir');
INSERT INTO IsoLanguagesDes VALUES (41,'fin','Baluchi');
INSERT INTO IsoLanguagesDes VALUES (42,'fin','Bambara');
INSERT INTO IsoLanguagesDes VALUES (43,'fin','Balinese');
INSERT INTO IsoLanguagesDes VALUES (44,'fin','Basque');
INSERT INTO IsoLanguagesDes VALUES (45,'fin','Basa');
INSERT INTO IsoLanguagesDes VALUES (46,'fin','Baltic (Other)');
INSERT INTO IsoLanguagesDes VALUES (47,'fin','Beja');
INSERT INTO IsoLanguagesDes VALUES (48,'fin','Belarusian');
INSERT INTO IsoLanguagesDes VALUES (49,'fin','Bemba');
INSERT INTO IsoLanguagesDes VALUES (50,'fin','Bengali');
INSERT INTO IsoLanguagesDes VALUES (51,'fin','Berber (Other)');
INSERT INTO IsoLanguagesDes VALUES (52,'fin','Bhojpuri');
INSERT INTO IsoLanguagesDes VALUES (53,'fin','Bihari');
INSERT INTO IsoLanguagesDes VALUES (54,'fin','Bikol');
INSERT INTO IsoLanguagesDes VALUES (55,'fin','Bini; Edo');
INSERT INTO IsoLanguagesDes VALUES (56,'fin','Bislama');
INSERT INTO IsoLanguagesDes VALUES (57,'fin','Siksika');
INSERT INTO IsoLanguagesDes VALUES (58,'fin','Bantu (Other)');
INSERT INTO IsoLanguagesDes VALUES (59,'fin','Bosnian');
INSERT INTO IsoLanguagesDes VALUES (60,'fin','Braj');
INSERT INTO IsoLanguagesDes VALUES (61,'fin','Breton');
INSERT INTO IsoLanguagesDes VALUES (62,'fin','Batak languages');
INSERT INTO IsoLanguagesDes VALUES (63,'fin','Buriat');
INSERT INTO IsoLanguagesDes VALUES (64,'fin','Buginese');
INSERT INTO IsoLanguagesDes VALUES (65,'fin','Bulgarian');
INSERT INTO IsoLanguagesDes VALUES (66,'fin','Burmese');
INSERT INTO IsoLanguagesDes VALUES (67,'fin','Blin; Bilin');
INSERT INTO IsoLanguagesDes VALUES (68,'fin','Caddo');
INSERT INTO IsoLanguagesDes VALUES (69,'fin','Central American Indian (Other)');
INSERT INTO IsoLanguagesDes VALUES (70,'fin','Galibi Carib');
INSERT INTO IsoLanguagesDes VALUES (71,'fin','Catalan; Valencian');
INSERT INTO IsoLanguagesDes VALUES (72,'fin','Caucasian (Other)on liturgique; vieux bulgare');
INSERT INTO IsoLanguagesDes VALUES (73,'fin','Cebuano');
INSERT INTO IsoLanguagesDes VALUES (74,'fin','Celtic (Other)');
INSERT INTO IsoLanguagesDes VALUES (75,'fin','Chamorro');
INSERT INTO IsoLanguagesDes VALUES (76,'fin','Chibcha');
INSERT INTO IsoLanguagesDes VALUES (77,'fin','Chechen');
INSERT INTO IsoLanguagesDes VALUES (78,'fin','Chagataier)');
INSERT INTO IsoLanguagesDes VALUES (79,'fin','Chinese(Other)');
INSERT INTO IsoLanguagesDes VALUES (80,'fin','Chuukese');
INSERT INTO IsoLanguagesDes VALUES (81,'fin','Mari');
INSERT INTO IsoLanguagesDes VALUES (82,'fin','Chinook jargon');
INSERT INTO IsoLanguagesDes VALUES (83,'fin','Choctaw');
INSERT INTO IsoLanguagesDes VALUES (84,'fin','Chipewyan');
INSERT INTO IsoLanguagesDes VALUES (85,'fin','Cherokee');
INSERT INTO IsoLanguagesDes VALUES (86,'fin','Church Slavic; Old Slavonic; Church Sl');
INSERT INTO IsoLanguagesDes VALUES (87,'fin','Chuvash');
INSERT INTO IsoLanguagesDes VALUES (88,'fin','Cheyenne');
INSERT INTO IsoLanguagesDes VALUES (89,'fin','Chamic languages');
INSERT INTO IsoLanguagesDes VALUES (90,'fin','Coptic');
INSERT INTO IsoLanguagesDes VALUES (91,'fin','Cornish');
INSERT INTO IsoLanguagesDes VALUES (92,'fin','Corsican');
INSERT INTO IsoLanguagesDes VALUES (93,'fin','Creoles and pidgins, English based (Ot');
INSERT INTO IsoLanguagesDes VALUES (94,'fin','Creoles and pidgins, French-based (Oth');
INSERT INTO IsoLanguagesDes VALUES (95,'fin','Creoles and pidgins, Portuguese-based ');
INSERT INTO IsoLanguagesDes VALUES (96,'fin','Cree');
INSERT INTO IsoLanguagesDes VALUES (97,'fin','Crimean Tatar; Crimean Turkish');
INSERT INTO IsoLanguagesDes VALUES (98,'fin','Creoles and pidgins (Other)');
INSERT INTO IsoLanguagesDes VALUES (99,'fin','Kashubian');
INSERT INTO IsoLanguagesDes VALUES (100,'fin','Cushitic (Other)');
INSERT INTO IsoLanguagesDes VALUES (101,'fin','Czech');
INSERT INTO IsoLanguagesDes VALUES (102,'fin','Dakota');
INSERT INTO IsoLanguagesDes VALUES (103,'fin','Danish');
INSERT INTO IsoLanguagesDes VALUES (104,'fin','Dargwa');
INSERT INTO IsoLanguagesDes VALUES (105,'fin','Land Dayak languages');
INSERT INTO IsoLanguagesDes VALUES (106,'fin','Delaware');
INSERT INTO IsoLanguagesDes VALUES (107,'fin','Slave (Athapascan)');
INSERT INTO IsoLanguagesDes VALUES (108,'fin','Dogrib');
INSERT INTO IsoLanguagesDes VALUES (109,'fin','Dinka');
INSERT INTO IsoLanguagesDes VALUES (110,'fin','Divehi; Dhivehi; Maldivian');
INSERT INTO IsoLanguagesDes VALUES (111,'fin','Dogri');
INSERT INTO IsoLanguagesDes VALUES (112,'fin','Dravidian (Other)');
INSERT INTO IsoLanguagesDes VALUES (113,'fin','Lower Sorbian');
INSERT INTO IsoLanguagesDes VALUES (114,'fin','Duala');
INSERT INTO IsoLanguagesDes VALUES (115,'fin','Dutch, Middle (ca.1050-1350)');
INSERT INTO IsoLanguagesDes VALUES (116,'fin','Dutch; Flemish');
INSERT INTO IsoLanguagesDes VALUES (117,'fin','Dyula');
INSERT INTO IsoLanguagesDes VALUES (118,'fin','Dzongkha');
INSERT INTO IsoLanguagesDes VALUES (119,'fin','Efik');
INSERT INTO IsoLanguagesDes VALUES (120,'fin','Egyptian (Ancient)');
INSERT INTO IsoLanguagesDes VALUES (121,'fin','Ekajuk');
INSERT INTO IsoLanguagesDes VALUES (122,'fin','Elamite');
INSERT INTO IsoLanguagesDes VALUES (123,'fin','English');
INSERT INTO IsoLanguagesDes VALUES (124,'fin','English, Middle (1100-1500)');
INSERT INTO IsoLanguagesDes VALUES (125,'fin','Esperanto');
INSERT INTO IsoLanguagesDes VALUES (126,'fin','Estonian');
INSERT INTO IsoLanguagesDes VALUES (127,'fin','Ewe');
INSERT INTO IsoLanguagesDes VALUES (128,'fin','Ewondo');
INSERT INTO IsoLanguagesDes VALUES (129,'fin','Fang');
INSERT INTO IsoLanguagesDes VALUES (130,'fin','Faroese');
INSERT INTO IsoLanguagesDes VALUES (131,'fin','Fanti');
INSERT INTO IsoLanguagesDes VALUES (132,'fin','Fijian');
INSERT INTO IsoLanguagesDes VALUES (133,'fin','Filipino; Pilipino');
INSERT INTO IsoLanguagesDes VALUES (134,'fin','Finnish');
INSERT INTO IsoLanguagesDes VALUES (135,'fin','Finno-Ugrian (Other)');
INSERT INTO IsoLanguagesDes VALUES (136,'fin','Fon');
INSERT INTO IsoLanguagesDes VALUES (137,'fin','French');
INSERT INTO IsoLanguagesDes VALUES (138,'fin','French, Middle (ca.1400-1600)');
INSERT INTO IsoLanguagesDes VALUES (139,'fin','French, Old (842-ca.1400)');
INSERT INTO IsoLanguagesDes VALUES (140,'fin','Northern Frisian');
INSERT INTO IsoLanguagesDes VALUES (141,'fin','Eastern Frisian');
INSERT INTO IsoLanguagesDes VALUES (142,'fin','Western Frisian');
INSERT INTO IsoLanguagesDes VALUES (143,'fin','Fulah');
INSERT INTO IsoLanguagesDes VALUES (144,'fin','Friulian');
INSERT INTO IsoLanguagesDes VALUES (145,'fin','Ga');
INSERT INTO IsoLanguagesDes VALUES (146,'fin','Gayo');
INSERT INTO IsoLanguagesDes VALUES (147,'fin','Gbaya');
INSERT INTO IsoLanguagesDes VALUES (148,'fin','Germanic (Other)');
INSERT INTO IsoLanguagesDes VALUES (149,'fin','Georgian');
INSERT INTO IsoLanguagesDes VALUES (150,'fin','German');
INSERT INTO IsoLanguagesDes VALUES (151,'fin','Geez');
INSERT INTO IsoLanguagesDes VALUES (152,'fin','Gilbertese');
INSERT INTO IsoLanguagesDes VALUES (153,'fin','Gaelic; Scottish Gaelic');
INSERT INTO IsoLanguagesDes VALUES (154,'fin','Irish');
INSERT INTO IsoLanguagesDes VALUES (155,'fin','Galician');
INSERT INTO IsoLanguagesDes VALUES (156,'fin','Manx');
INSERT INTO IsoLanguagesDes VALUES (157,'fin','German, Middle High (ca.1050-1500)');
INSERT INTO IsoLanguagesDes VALUES (158,'fin','German, Old High (ca.750-1050)');
INSERT INTO IsoLanguagesDes VALUES (159,'fin','Gondi');
INSERT INTO IsoLanguagesDes VALUES (160,'fin','Gorontalo');
INSERT INTO IsoLanguagesDes VALUES (161,'fin','Gothicanguage Association)');
INSERT INTO IsoLanguagesDes VALUES (162,'fin','Grebo');
INSERT INTO IsoLanguagesDes VALUES (163,'fin','Greek, Ancient (to 1453)');
INSERT INTO IsoLanguagesDes VALUES (164,'fin','Greek, Modern (1453-)');
INSERT INTO IsoLanguagesDes VALUES (165,'fin','Guarani');
INSERT INTO IsoLanguagesDes VALUES (166,'fin','Swiss German; Alemannic');
INSERT INTO IsoLanguagesDes VALUES (167,'fin','Gujarati');
INSERT INTO IsoLanguagesDes VALUES (168,'fin','Gwich''in');
INSERT INTO IsoLanguagesDes VALUES (169,'fin','Haida');
INSERT INTO IsoLanguagesDes VALUES (170,'fin','Haitian; Haitian Creole');
INSERT INTO IsoLanguagesDes VALUES (171,'fin','Hausa');
INSERT INTO IsoLanguagesDes VALUES (172,'fin','Hawaiian');
INSERT INTO IsoLanguagesDes VALUES (173,'fin','Hebrew');
INSERT INTO IsoLanguagesDes VALUES (174,'fin','Herero');
INSERT INTO IsoLanguagesDes VALUES (175,'fin','Hiligaynon');
INSERT INTO IsoLanguagesDes VALUES (176,'fin','Himachali');
INSERT INTO IsoLanguagesDes VALUES (177,'fin','Hindi');
INSERT INTO IsoLanguagesDes VALUES (178,'fin','Hittite');
INSERT INTO IsoLanguagesDes VALUES (179,'fin','Hmong');
INSERT INTO IsoLanguagesDes VALUES (180,'fin','Hiri Motu');
INSERT INTO IsoLanguagesDes VALUES (181,'fin','Upper Sorbian');
INSERT INTO IsoLanguagesDes VALUES (182,'fin','Hungarian');
INSERT INTO IsoLanguagesDes VALUES (183,'fin','Hupa');
INSERT INTO IsoLanguagesDes VALUES (184,'fin','Iban');
INSERT INTO IsoLanguagesDes VALUES (185,'fin','Igbo');
INSERT INTO IsoLanguagesDes VALUES (186,'fin','Icelandic');
INSERT INTO IsoLanguagesDes VALUES (187,'fin','Ido');
INSERT INTO IsoLanguagesDes VALUES (188,'fin','Sichuan Yi');
INSERT INTO IsoLanguagesDes VALUES (189,'fin','Ijo languages');
INSERT INTO IsoLanguagesDes VALUES (190,'fin','Inuktitut');
INSERT INTO IsoLanguagesDes VALUES (191,'fin','Interlingue');
INSERT INTO IsoLanguagesDes VALUES (192,'fin','Iloko');
INSERT INTO IsoLanguagesDes VALUES (193,'fin','Interlingua (International Auxiliary L');
INSERT INTO IsoLanguagesDes VALUES (194,'fin','Indic (Other)');
INSERT INTO IsoLanguagesDes VALUES (195,'fin','Indonesian');
INSERT INTO IsoLanguagesDes VALUES (196,'fin','Indo-European (Other)');
INSERT INTO IsoLanguagesDes VALUES (197,'fin','Ingush');
INSERT INTO IsoLanguagesDes VALUES (198,'fin','Inupiaq');
INSERT INTO IsoLanguagesDes VALUES (199,'fin','Iranian (Other)');
INSERT INTO IsoLanguagesDes VALUES (200,'fin','Iroquoian languages');
INSERT INTO IsoLanguagesDes VALUES (201,'fin','Italian');
INSERT INTO IsoLanguagesDes VALUES (202,'fin','Javanese');
INSERT INTO IsoLanguagesDes VALUES (203,'fin','Lojban');
INSERT INTO IsoLanguagesDes VALUES (204,'fin','Japanese');
INSERT INTO IsoLanguagesDes VALUES (205,'fin','Judeo-Persian');
INSERT INTO IsoLanguagesDes VALUES (206,'fin','Judeo-Arabic');
INSERT INTO IsoLanguagesDes VALUES (207,'fin','Kara-Kalpak');
INSERT INTO IsoLanguagesDes VALUES (208,'fin','Kabyle');
INSERT INTO IsoLanguagesDes VALUES (209,'fin','Kachin; Jingpho');
INSERT INTO IsoLanguagesDes VALUES (210,'fin','Kalaallisut; Greenlandic');
INSERT INTO IsoLanguagesDes VALUES (211,'fin','Kamba');
INSERT INTO IsoLanguagesDes VALUES (212,'fin','Kannada');
INSERT INTO IsoLanguagesDes VALUES (213,'fin','Karen languages');
INSERT INTO IsoLanguagesDes VALUES (214,'fin','Kashmiri');
INSERT INTO IsoLanguagesDes VALUES (215,'fin','Kanuri');
INSERT INTO IsoLanguagesDes VALUES (216,'fin','Kawi');
INSERT INTO IsoLanguagesDes VALUES (217,'fin','Kazakh');
INSERT INTO IsoLanguagesDes VALUES (218,'fin','Kabardian');
INSERT INTO IsoLanguagesDes VALUES (219,'fin','Khasi');
INSERT INTO IsoLanguagesDes VALUES (220,'fin','Khoisan (Other)');
INSERT INTO IsoLanguagesDes VALUES (221,'fin','Central Khmer');
INSERT INTO IsoLanguagesDes VALUES (222,'fin','Khotanese');
INSERT INTO IsoLanguagesDes VALUES (223,'fin','Kikuyu; Gikuyu');
INSERT INTO IsoLanguagesDes VALUES (224,'fin','Kinyarwanda');
INSERT INTO IsoLanguagesDes VALUES (225,'fin','Kirghiz; Kyrgyz');
INSERT INTO IsoLanguagesDes VALUES (226,'fin','Kimbundu');
INSERT INTO IsoLanguagesDes VALUES (227,'fin','Konkani');
INSERT INTO IsoLanguagesDes VALUES (228,'fin','Komi');
INSERT INTO IsoLanguagesDes VALUES (229,'fin','Kongo');
INSERT INTO IsoLanguagesDes VALUES (230,'fin','Korean');
INSERT INTO IsoLanguagesDes VALUES (231,'fin','Kosraean');
INSERT INTO IsoLanguagesDes VALUES (232,'fin','Kpelle');
INSERT INTO IsoLanguagesDes VALUES (233,'fin','Karachay-Balkar');
INSERT INTO IsoLanguagesDes VALUES (234,'fin','Karelian');
INSERT INTO IsoLanguagesDes VALUES (235,'fin','Kru languages');
INSERT INTO IsoLanguagesDes VALUES (236,'fin','Kurukh');
INSERT INTO IsoLanguagesDes VALUES (237,'fin','Kuanyama; Kwanyama');
INSERT INTO IsoLanguagesDes VALUES (238,'fin','Kumyk');
INSERT INTO IsoLanguagesDes VALUES (239,'fin','Kurdish');
INSERT INTO IsoLanguagesDes VALUES (240,'fin','Kutenai');
INSERT INTO IsoLanguagesDes VALUES (241,'fin','Ladino');
INSERT INTO IsoLanguagesDes VALUES (242,'fin','Lahnda');
INSERT INTO IsoLanguagesDes VALUES (243,'fin','Lamba');
INSERT INTO IsoLanguagesDes VALUES (244,'fin','Lao');
INSERT INTO IsoLanguagesDes VALUES (245,'fin','Latin');
INSERT INTO IsoLanguagesDes VALUES (246,'fin','Latvian');
INSERT INTO IsoLanguagesDes VALUES (247,'fin','Lezghian');
INSERT INTO IsoLanguagesDes VALUES (248,'fin','Limburgan; Limburger; Limburgish');
INSERT INTO IsoLanguagesDes VALUES (249,'fin','Lingala');
INSERT INTO IsoLanguagesDes VALUES (250,'fin','Lithuanian');
INSERT INTO IsoLanguagesDes VALUES (251,'fin','Mongo');
INSERT INTO IsoLanguagesDes VALUES (252,'fin','Lozi');
INSERT INTO IsoLanguagesDes VALUES (253,'fin','Luxembourgish; Letzeburgesch');
INSERT INTO IsoLanguagesDes VALUES (254,'fin','Luba-Lulua');
INSERT INTO IsoLanguagesDes VALUES (255,'fin','Luba-Katangaxon, Low');
INSERT INTO IsoLanguagesDes VALUES (256,'fin','Ganda');
INSERT INTO IsoLanguagesDes VALUES (257,'fin','Luiseno');
INSERT INTO IsoLanguagesDes VALUES (258,'fin','Lunda');
INSERT INTO IsoLanguagesDes VALUES (259,'fin','Luo (Kenya and Tanzania)');
INSERT INTO IsoLanguagesDes VALUES (260,'fin','Lushai');
INSERT INTO IsoLanguagesDes VALUES (261,'fin','Macedonian00E5l');
INSERT INTO IsoLanguagesDes VALUES (262,'fin','Madurese');
INSERT INTO IsoLanguagesDes VALUES (263,'fin','Magahi');
INSERT INTO IsoLanguagesDes VALUES (264,'fin','Marshallese');
INSERT INTO IsoLanguagesDes VALUES (265,'fin','Maithili');
INSERT INTO IsoLanguagesDes VALUES (266,'fin','Makasarl Nepal Bhasa');
INSERT INTO IsoLanguagesDes VALUES (267,'fin','Malayalam');
INSERT INTO IsoLanguagesDes VALUES (268,'fin','Mandingo');
INSERT INTO IsoLanguagesDes VALUES (269,'fin','Maori');
INSERT INTO IsoLanguagesDes VALUES (270,'fin','Austronesian (Other)');
INSERT INTO IsoLanguagesDes VALUES (271,'fin','Marathi');
INSERT INTO IsoLanguagesDes VALUES (272,'fin','Masai');
INSERT INTO IsoLanguagesDes VALUES (273,'fin','Malay');
INSERT INTO IsoLanguagesDes VALUES (274,'fin','Moksha');
INSERT INTO IsoLanguagesDes VALUES (275,'fin','Mandar');
INSERT INTO IsoLanguagesDes VALUES (276,'fin','Mende');
INSERT INTO IsoLanguagesDes VALUES (277,'fin','Irish, Middle (900-1200)');
INSERT INTO IsoLanguagesDes VALUES (278,'fin','Mi''kmaq; Micmac');
INSERT INTO IsoLanguagesDes VALUES (279,'fin','Minangkabau');
INSERT INTO IsoLanguagesDes VALUES (280,'fin','Miscellaneous languages');
INSERT INTO IsoLanguagesDes VALUES (281,'fin','Mon-Khmer (Other)');
INSERT INTO IsoLanguagesDes VALUES (282,'fin','Malagasy');
INSERT INTO IsoLanguagesDes VALUES (283,'fin','Maltese');
INSERT INTO IsoLanguagesDes VALUES (284,'fin','Manchu');
INSERT INTO IsoLanguagesDes VALUES (285,'fin','Manipuri');
INSERT INTO IsoLanguagesDes VALUES (286,'fin','Manobo languages');
INSERT INTO IsoLanguagesDes VALUES (287,'fin','Mohawk');
INSERT INTO IsoLanguagesDes VALUES (288,'fin','Moldavian');
INSERT INTO IsoLanguagesDes VALUES (289,'fin','Mongolian');
INSERT INTO IsoLanguagesDes VALUES (290,'fin','Mossi');
INSERT INTO IsoLanguagesDes VALUES (291,'fin','Multiple languages');
INSERT INTO IsoLanguagesDes VALUES (292,'fin','Munda languages');
INSERT INTO IsoLanguagesDes VALUES (293,'fin','Creek');
INSERT INTO IsoLanguagesDes VALUES (294,'fin','Mirandese');
INSERT INTO IsoLanguagesDes VALUES (295,'fin','Marwari');
INSERT INTO IsoLanguagesDes VALUES (296,'fin','Mayan languages');
INSERT INTO IsoLanguagesDes VALUES (297,'fin','Erzya');
INSERT INTO IsoLanguagesDes VALUES (298,'fin','Nahuatl languages');
INSERT INTO IsoLanguagesDes VALUES (299,'fin','North American Indian');
INSERT INTO IsoLanguagesDes VALUES (300,'fin','Neapolitan');
INSERT INTO IsoLanguagesDes VALUES (301,'fin','Nauru');
INSERT INTO IsoLanguagesDes VALUES (302,'fin','Navajo; Navaho');
INSERT INTO IsoLanguagesDes VALUES (303,'fin','Ndebele, South; South Ndebele');
INSERT INTO IsoLanguagesDes VALUES (304,'fin','Ndebele, North; North Ndebele');
INSERT INTO IsoLanguagesDes VALUES (305,'fin','Ndonga');
INSERT INTO IsoLanguagesDes VALUES (306,'fin','Low German; Low Saxon; German, Low; Sa');
INSERT INTO IsoLanguagesDes VALUES (307,'fin','Nepali');
INSERT INTO IsoLanguagesDes VALUES (308,'fin','Nepal Bhasa; Newari');
INSERT INTO IsoLanguagesDes VALUES (309,'fin','Nias');
INSERT INTO IsoLanguagesDes VALUES (310,'fin','Niger-Kordofanian (Other)');
INSERT INTO IsoLanguagesDes VALUES (311,'fin','Niuean');
INSERT INTO IsoLanguagesDes VALUES (312,'fin','Norwegian Nynorsk; Nynorsk, Norwegian');
INSERT INTO IsoLanguagesDes VALUES (313,'fin','Bokmål, Norwegian; Norwegian Bokmål');
INSERT INTO IsoLanguagesDes VALUES (314,'fin','Nogai');
INSERT INTO IsoLanguagesDes VALUES (315,'fin','Norse, Old');
INSERT INTO IsoLanguagesDes VALUES (316,'fin','Norwegian');
INSERT INTO IsoLanguagesDes VALUES (317,'fin','Pedi; Sepedi; Northern Sotho');
INSERT INTO IsoLanguagesDes VALUES (318,'fin','Nubian languages');
INSERT INTO IsoLanguagesDes VALUES (319,'fin','Classical Newari; Old Newari; Classica');
INSERT INTO IsoLanguagesDes VALUES (320,'fin','Chichewa; Chewa; Nyanja');
INSERT INTO IsoLanguagesDes VALUES (321,'fin','Nyamwezi');
INSERT INTO IsoLanguagesDes VALUES (322,'fin','Nyankole');
INSERT INTO IsoLanguagesDes VALUES (323,'fin','Nyoro');
INSERT INTO IsoLanguagesDes VALUES (324,'fin','Nzima');
INSERT INTO IsoLanguagesDes VALUES (325,'fin','Occitan (post 1500); Provençal');
INSERT INTO IsoLanguagesDes VALUES (326,'fin','Ojibwa');
INSERT INTO IsoLanguagesDes VALUES (327,'fin','Oriya');
INSERT INTO IsoLanguagesDes VALUES (328,'fin','Oromo');
INSERT INTO IsoLanguagesDes VALUES (329,'fin','Osage');
INSERT INTO IsoLanguagesDes VALUES (330,'fin','Ossetian; Ossetic');
INSERT INTO IsoLanguagesDes VALUES (331,'fin','Turkish, Ottoman (1500-1928)');
INSERT INTO IsoLanguagesDes VALUES (332,'fin','Otomian languages');
INSERT INTO IsoLanguagesDes VALUES (333,'fin','Papuan (Other)');
INSERT INTO IsoLanguagesDes VALUES (334,'fin','Pangasinan');
INSERT INTO IsoLanguagesDes VALUES (335,'fin','Pahlavi');
INSERT INTO IsoLanguagesDes VALUES (336,'fin','Pampanga');
INSERT INTO IsoLanguagesDes VALUES (337,'fin','Panjabi; Punjabi');
INSERT INTO IsoLanguagesDes VALUES (338,'fin','Papiamento');
INSERT INTO IsoLanguagesDes VALUES (339,'fin','Palauan');
INSERT INTO IsoLanguagesDes VALUES (340,'fin','Persian, Old (ca.600-400 B.C.)');
INSERT INTO IsoLanguagesDes VALUES (341,'fin','Persian');
INSERT INTO IsoLanguagesDes VALUES (342,'fin','Philippine (Other)');
INSERT INTO IsoLanguagesDes VALUES (343,'fin','Phoenician');
INSERT INTO IsoLanguagesDes VALUES (344,'fin','Pali');
INSERT INTO IsoLanguagesDes VALUES (345,'fin','Polish');
INSERT INTO IsoLanguagesDes VALUES (346,'fin','Pohnpeian');
INSERT INTO IsoLanguagesDes VALUES (347,'fin','Portuguese');
INSERT INTO IsoLanguagesDes VALUES (348,'fin','Prakrit languages');
INSERT INTO IsoLanguagesDes VALUES (349,'fin','Provençal, Old (to 1500)');
INSERT INTO IsoLanguagesDes VALUES (350,'fin','Pushto');
INSERT INTO IsoLanguagesDes VALUES (351,'fin','Reserved for local use');
INSERT INTO IsoLanguagesDes VALUES (352,'fin','Quechua');
INSERT INTO IsoLanguagesDes VALUES (353,'fin','Rajasthani');
INSERT INTO IsoLanguagesDes VALUES (354,'fin','Rapanui');
INSERT INTO IsoLanguagesDes VALUES (355,'fin','Rarotongan; Cook Islands Maori');
INSERT INTO IsoLanguagesDes VALUES (356,'fin','Romance (Other)');
INSERT INTO IsoLanguagesDes VALUES (357,'fin','Romansh');
INSERT INTO IsoLanguagesDes VALUES (358,'fin','Romany');
INSERT INTO IsoLanguagesDes VALUES (359,'fin','Romanian');
INSERT INTO IsoLanguagesDes VALUES (360,'fin','Rundi');
INSERT INTO IsoLanguagesDes VALUES (361,'fin','Aromanian; Arumanian; Macedo-Romanian');
INSERT INTO IsoLanguagesDes VALUES (362,'fin','Russian');
INSERT INTO IsoLanguagesDes VALUES (363,'fin','Sandawe');
INSERT INTO IsoLanguagesDes VALUES (364,'fin','Sango');
INSERT INTO IsoLanguagesDes VALUES (365,'fin','Yakut');
INSERT INTO IsoLanguagesDes VALUES (366,'fin','South American Indian (Other)');
INSERT INTO IsoLanguagesDes VALUES (367,'fin','Salishan languages');
INSERT INTO IsoLanguagesDes VALUES (368,'fin','Samaritan Aramaic');
INSERT INTO IsoLanguagesDes VALUES (369,'fin','Sanskrit');
INSERT INTO IsoLanguagesDes VALUES (370,'fin','Sasak');
INSERT INTO IsoLanguagesDes VALUES (371,'fin','Santali');
INSERT INTO IsoLanguagesDes VALUES (372,'fin','Serbian');
INSERT INTO IsoLanguagesDes VALUES (373,'fin','Sicilian');
INSERT INTO IsoLanguagesDes VALUES (374,'fin','Scots');
INSERT INTO IsoLanguagesDes VALUES (375,'fin','Croatian');
INSERT INTO IsoLanguagesDes VALUES (376,'fin','Selkup');
INSERT INTO IsoLanguagesDes VALUES (377,'fin','Semitic (Other)');
INSERT INTO IsoLanguagesDes VALUES (378,'fin','Irish, Old (to 900)');
INSERT INTO IsoLanguagesDes VALUES (379,'fin','Sign Languages');
INSERT INTO IsoLanguagesDes VALUES (380,'fin','Shan');
INSERT INTO IsoLanguagesDes VALUES (381,'fin','Sidamo');
INSERT INTO IsoLanguagesDes VALUES (382,'fin','Sinhala; Sinhalese');
INSERT INTO IsoLanguagesDes VALUES (383,'fin','Siouan languages');
INSERT INTO IsoLanguagesDes VALUES (384,'fin','Sino-Tibetan (Other)');
INSERT INTO IsoLanguagesDes VALUES (385,'fin','Slavic (Other)');
INSERT INTO IsoLanguagesDes VALUES (386,'fin','Slovak');
INSERT INTO IsoLanguagesDes VALUES (387,'fin','Slovenian');
INSERT INTO IsoLanguagesDes VALUES (388,'fin','Southern Sami');
INSERT INTO IsoLanguagesDes VALUES (389,'fin','Northern Sami');
INSERT INTO IsoLanguagesDes VALUES (390,'fin','Sami languages (Other)');
INSERT INTO IsoLanguagesDes VALUES (391,'fin','Lule Sami');
INSERT INTO IsoLanguagesDes VALUES (392,'fin','Inari Sami');
INSERT INTO IsoLanguagesDes VALUES (393,'fin','Samoan');
INSERT INTO IsoLanguagesDes VALUES (394,'fin','Skolt Sami');
INSERT INTO IsoLanguagesDes VALUES (395,'fin','Shona');
INSERT INTO IsoLanguagesDes VALUES (396,'fin','Sindhi');
INSERT INTO IsoLanguagesDes VALUES (397,'fin','Soninke');
INSERT INTO IsoLanguagesDes VALUES (398,'fin','Sogdian');
INSERT INTO IsoLanguagesDes VALUES (399,'fin','Somali');
INSERT INTO IsoLanguagesDes VALUES (400,'fin','Songhai languages');
INSERT INTO IsoLanguagesDes VALUES (401,'fin','Sotho, Southern');
INSERT INTO IsoLanguagesDes VALUES (402,'fin','Spanish; Castilian');
INSERT INTO IsoLanguagesDes VALUES (403,'fin','Sardinian; Zazaki');
INSERT INTO IsoLanguagesDes VALUES (404,'fin','Sranan Tongo');
INSERT INTO IsoLanguagesDes VALUES (405,'fin','Serer');
INSERT INTO IsoLanguagesDes VALUES (406,'fin','Nilo-Saharan (Other)');
INSERT INTO IsoLanguagesDes VALUES (407,'fin','Swati');
INSERT INTO IsoLanguagesDes VALUES (408,'fin','Sukuma');
INSERT INTO IsoLanguagesDes VALUES (409,'fin','Sundanese');
INSERT INTO IsoLanguagesDes VALUES (410,'fin','Susu');
INSERT INTO IsoLanguagesDes VALUES (411,'fin','Sumerian');
INSERT INTO IsoLanguagesDes VALUES (412,'fin','Swahili');
INSERT INTO IsoLanguagesDes VALUES (413,'fin','Swedish');
INSERT INTO IsoLanguagesDes VALUES (414,'fin','Syriac');
INSERT INTO IsoLanguagesDes VALUES (415,'fin','Tahitian');
INSERT INTO IsoLanguagesDes VALUES (416,'fin','Tai (Other)');
INSERT INTO IsoLanguagesDes VALUES (417,'fin','Tamil');
INSERT INTO IsoLanguagesDes VALUES (418,'fin','Tatar');
INSERT INTO IsoLanguagesDes VALUES (419,'fin','Telugu');
INSERT INTO IsoLanguagesDes VALUES (420,'fin','Timnendere)');
INSERT INTO IsoLanguagesDes VALUES (421,'fin','Tereno');
INSERT INTO IsoLanguagesDes VALUES (422,'fin','Tetum');
INSERT INTO IsoLanguagesDes VALUES (423,'fin','Tajik');
INSERT INTO IsoLanguagesDes VALUES (424,'fin','Tagalog');
INSERT INTO IsoLanguagesDes VALUES (425,'fin','Thai');
INSERT INTO IsoLanguagesDes VALUES (426,'fin','Tibetan');
INSERT INTO IsoLanguagesDes VALUES (427,'fin','Tigre');
INSERT INTO IsoLanguagesDes VALUES (428,'fin','Tigrinya');
INSERT INTO IsoLanguagesDes VALUES (429,'fin','Tiv');
INSERT INTO IsoLanguagesDes VALUES (430,'fin','Tokelau');
INSERT INTO IsoLanguagesDes VALUES (431,'fin','Klingon; tlhIngan-Hol');
INSERT INTO IsoLanguagesDes VALUES (432,'fin','Tlingit');
INSERT INTO IsoLanguagesDes VALUES (433,'fin','Tamashek');
INSERT INTO IsoLanguagesDes VALUES (434,'fin','Tonga (Nyasa)');
INSERT INTO IsoLanguagesDes VALUES (435,'fin','Tonga (Tonga Islands)');
INSERT INTO IsoLanguagesDes VALUES (436,'fin','Tok Pisin');
INSERT INTO IsoLanguagesDes VALUES (437,'fin','Tsimshian');
INSERT INTO IsoLanguagesDes VALUES (438,'fin','Tswana');
INSERT INTO IsoLanguagesDes VALUES (439,'fin','Tsonga');
INSERT INTO IsoLanguagesDes VALUES (440,'fin','Turkmen');
INSERT INTO IsoLanguagesDes VALUES (441,'fin','Tumbuka');
INSERT INTO IsoLanguagesDes VALUES (442,'fin','Tupi languages');
INSERT INTO IsoLanguagesDes VALUES (443,'fin','Turkish');
INSERT INTO IsoLanguagesDes VALUES (444,'fin','Altaic (Other)');
INSERT INTO IsoLanguagesDes VALUES (445,'fin','Tuvalu');
INSERT INTO IsoLanguagesDes VALUES (446,'fin','Twi');
INSERT INTO IsoLanguagesDes VALUES (447,'fin','Tuvinian');
INSERT INTO IsoLanguagesDes VALUES (448,'fin','Udmurt');
INSERT INTO IsoLanguagesDes VALUES (449,'fin','Ugaritic');
INSERT INTO IsoLanguagesDes VALUES (450,'fin','Uighur; Uyghur');
INSERT INTO IsoLanguagesDes VALUES (451,'fin','Ukrainian');
INSERT INTO IsoLanguagesDes VALUES (452,'fin','Umbundu');
INSERT INTO IsoLanguagesDes VALUES (453,'fin','Undetermined');
INSERT INTO IsoLanguagesDes VALUES (454,'fin','Urdu');
INSERT INTO IsoLanguagesDes VALUES (455,'fin','Uzbek');
INSERT INTO IsoLanguagesDes VALUES (456,'fin','Vai');
INSERT INTO IsoLanguagesDes VALUES (457,'fin','Venda');
INSERT INTO IsoLanguagesDes VALUES (458,'fin','Vietnamese');
INSERT INTO IsoLanguagesDes VALUES (459,'fin','Volapük');
INSERT INTO IsoLanguagesDes VALUES (460,'fin','Votic');
INSERT INTO IsoLanguagesDes VALUES (461,'fin','Wakashan languages');
INSERT INTO IsoLanguagesDes VALUES (462,'fin','Walamo');
INSERT INTO IsoLanguagesDes VALUES (463,'fin','Waray');
INSERT INTO IsoLanguagesDes VALUES (464,'fin','Washo');
INSERT INTO IsoLanguagesDes VALUES (465,'fin','Welsh');
INSERT INTO IsoLanguagesDes VALUES (466,'fin','Sorbian languages');
INSERT INTO IsoLanguagesDes VALUES (467,'fin','Walloon');
INSERT INTO IsoLanguagesDes VALUES (468,'fin','Wolof');
INSERT INTO IsoLanguagesDes VALUES (469,'fin','Kalmyk; Oirat');
INSERT INTO IsoLanguagesDes VALUES (470,'fin','Xhosa');
INSERT INTO IsoLanguagesDes VALUES (471,'fin','Yao');
INSERT INTO IsoLanguagesDes VALUES (472,'fin','Yapese');
INSERT INTO IsoLanguagesDes VALUES (473,'fin','Yiddish');
INSERT INTO IsoLanguagesDes VALUES (474,'fin','Yoruba');
INSERT INTO IsoLanguagesDes VALUES (475,'fin','Yupik languages');
INSERT INTO IsoLanguagesDes VALUES (476,'fin','Zapotec');
INSERT INTO IsoLanguagesDes VALUES (477,'fin','Zenaga');
INSERT INTO IsoLanguagesDes VALUES (478,'fin','Zhuang; Chuang');
INSERT INTO IsoLanguagesDes VALUES (479,'fin','Zande languages');
INSERT INTO IsoLanguagesDes VALUES (480,'fin','Zulu');
INSERT INTO IsoLanguagesDes VALUES (481,'fin','Zuni');
INSERT INTO IsoLanguagesDes VALUES (482,'fin','No linguistic content');
INSERT INTO IsoLanguagesDes VALUES (483,'fin','N''Ko');
INSERT INTO IsoLanguagesDes VALUES (484,'fin','Zaza; Dimili; Dimli; Kirdki; Kirmanjki');

INSERT INTO OperationsDes VALUES (0,'fin','Publish');
INSERT INTO OperationsDes VALUES (1,'fin','Download');
INSERT INTO OperationsDes VALUES (2,'fin','Editing');
INSERT INTO OperationsDes VALUES (3,'fin','Notify');
INSERT INTO OperationsDes VALUES (5,'fin','Interactive Map');
INSERT INTO OperationsDes VALUES (6,'fin','Featured');

INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (0,'fin','Unknown');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (1,'fin','Draft');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (2,'fin','Approved');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (3,'fin','Retired');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (4,'fin','Submitted');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (5,'fin','Rejected');

INSERT INTO RegionsDes VALUES (1,'fin','Armenia');
INSERT INTO RegionsDes VALUES (2,'fin','Afghanistan');
INSERT INTO RegionsDes VALUES (3,'fin','Albania');
INSERT INTO RegionsDes VALUES (4,'fin','Algeria');
INSERT INTO RegionsDes VALUES (5,'fin','American Samoa');
INSERT INTO RegionsDes VALUES (6,'fin','Andorra');
INSERT INTO RegionsDes VALUES (7,'fin','Angola');
INSERT INTO RegionsDes VALUES (8,'fin','Antigua and Barbuda');
INSERT INTO RegionsDes VALUES (9,'fin','Argentina');
INSERT INTO RegionsDes VALUES (10,'fin','Australia');
INSERT INTO RegionsDes VALUES (11,'fin','Austria');
INSERT INTO RegionsDes VALUES (12,'fin','Bahamas');
INSERT INTO RegionsDes VALUES (13,'fin','Bahrain');
INSERT INTO RegionsDes VALUES (14,'fin','Barbados');
INSERT INTO RegionsDes VALUES (16,'fin','Bangladesh');
INSERT INTO RegionsDes VALUES (17,'fin','Bermuda');
INSERT INTO RegionsDes VALUES (18,'fin','Bhutan');
INSERT INTO RegionsDes VALUES (19,'fin','Bolivia');
INSERT INTO RegionsDes VALUES (20,'fin','Botswana');
INSERT INTO RegionsDes VALUES (21,'fin','Brazil');
INSERT INTO RegionsDes VALUES (22,'fin','Aruba');
INSERT INTO RegionsDes VALUES (23,'fin','Belize');
INSERT INTO RegionsDes VALUES (24,'fin','British Indian Ocean Ter');
INSERT INTO RegionsDes VALUES (25,'fin','Solomon Islands');
INSERT INTO RegionsDes VALUES (26,'fin','Brunei Darussalam');
INSERT INTO RegionsDes VALUES (27,'fin','Bulgaria');
INSERT INTO RegionsDes VALUES (28,'fin','Myanmar');
INSERT INTO RegionsDes VALUES (29,'fin','Burundi');
INSERT INTO RegionsDes VALUES (30,'fin','Antarctica');
INSERT INTO RegionsDes VALUES (31,'fin','Bouvet Island');
INSERT INTO RegionsDes VALUES (32,'fin','Cameroon');
INSERT INTO RegionsDes VALUES (33,'fin','Canada');
INSERT INTO RegionsDes VALUES (35,'fin','Cape Verde');
INSERT INTO RegionsDes VALUES (36,'fin','Cayman Island');
INSERT INTO RegionsDes VALUES (37,'fin','Central African Republic');
INSERT INTO RegionsDes VALUES (38,'fin','Sri Lanka');
INSERT INTO RegionsDes VALUES (39,'fin','Chad');
INSERT INTO RegionsDes VALUES (40,'fin','Chile');
INSERT INTO RegionsDes VALUES (41,'fin','China, Mainland');
INSERT INTO RegionsDes VALUES (42,'fin','Christmas Island');
INSERT INTO RegionsDes VALUES (43,'fin','Cocos Islands');
INSERT INTO RegionsDes VALUES (44,'fin','Colombia');
INSERT INTO RegionsDes VALUES (45,'fin','Comoros');
INSERT INTO RegionsDes VALUES (46,'fin','Congo, Republic of');
INSERT INTO RegionsDes VALUES (47,'fin','Cook Islands');
INSERT INTO RegionsDes VALUES (48,'fin','Costa Rica');
INSERT INTO RegionsDes VALUES (49,'fin','Cuba');
INSERT INTO RegionsDes VALUES (50,'fin','Cyprus');
INSERT INTO RegionsDes VALUES (52,'fin','Azerbaijan, Republic of');
INSERT INTO RegionsDes VALUES (53,'fin','Benin');
INSERT INTO RegionsDes VALUES (54,'fin','Denmark');
INSERT INTO RegionsDes VALUES (55,'fin','Dominica');
INSERT INTO RegionsDes VALUES (56,'fin','Dominican Republic');
INSERT INTO RegionsDes VALUES (57,'fin','Belarus');
INSERT INTO RegionsDes VALUES (58,'fin','Ecuador');
INSERT INTO RegionsDes VALUES (59,'fin','Egypt');
INSERT INTO RegionsDes VALUES (60,'fin','El Salvador');
INSERT INTO RegionsDes VALUES (61,'fin','Equatorial Guinea');
INSERT INTO RegionsDes VALUES (63,'fin','Estonia');
INSERT INTO RegionsDes VALUES (64,'fin','Faeroe Islands');
INSERT INTO RegionsDes VALUES (65,'fin','Falkland Islands');
INSERT INTO RegionsDes VALUES (66,'fin','Fiji Islands');
INSERT INTO RegionsDes VALUES (67,'fin','Finland');
INSERT INTO RegionsDes VALUES (68,'fin','France');
INSERT INTO RegionsDes VALUES (69,'fin','French Guiana');
INSERT INTO RegionsDes VALUES (70,'fin','French Polynesia');
INSERT INTO RegionsDes VALUES (71,'fin','French South Terr');
INSERT INTO RegionsDes VALUES (72,'fin','Djibouti');
INSERT INTO RegionsDes VALUES (73,'fin','Georgia');
INSERT INTO RegionsDes VALUES (74,'fin','Gabon');
INSERT INTO RegionsDes VALUES (75,'fin','Gambia');
INSERT INTO RegionsDes VALUES (76,'fin','Gaza Strip');
INSERT INTO RegionsDes VALUES (79,'fin','Germany');
INSERT INTO RegionsDes VALUES (80,'fin','Bosnia and Herzegovina');
INSERT INTO RegionsDes VALUES (81,'fin','Ghana');
INSERT INTO RegionsDes VALUES (82,'fin','Gibraltar');
INSERT INTO RegionsDes VALUES (83,'fin','Kiribati');
INSERT INTO RegionsDes VALUES (84,'fin','Greece');
INSERT INTO RegionsDes VALUES (85,'fin','Greenland');
INSERT INTO RegionsDes VALUES (86,'fin','Grenada');
INSERT INTO RegionsDes VALUES (87,'fin','Guadeloupe');
INSERT INTO RegionsDes VALUES (88,'fin','Guam');
INSERT INTO RegionsDes VALUES (89,'fin','Guatemala');
INSERT INTO RegionsDes VALUES (90,'fin','Guinea');
INSERT INTO RegionsDes VALUES (91,'fin','Guyana');
INSERT INTO RegionsDes VALUES (92,'fin','Heard and McDonald Is');
INSERT INTO RegionsDes VALUES (93,'fin','Haiti');
INSERT INTO RegionsDes VALUES (95,'fin','Honduras');
INSERT INTO RegionsDes VALUES (97,'fin','Hungary');
INSERT INTO RegionsDes VALUES (98,'fin','Croatia');
INSERT INTO RegionsDes VALUES (99,'fin','Iceland');
INSERT INTO RegionsDes VALUES (100,'fin','India');
INSERT INTO RegionsDes VALUES (101,'fin','Indonesia');
INSERT INTO RegionsDes VALUES (102,'fin','Iran, Islamic Rep of');
INSERT INTO RegionsDes VALUES (103,'fin','Iraq');
INSERT INTO RegionsDes VALUES (104,'fin','Ireland');
INSERT INTO RegionsDes VALUES (105,'fin','Israel');
INSERT INTO RegionsDes VALUES (106,'fin','Italy');
INSERT INTO RegionsDes VALUES (107,'fin','Ivory Coast');
INSERT INTO RegionsDes VALUES (108,'fin','Kazakhstan');
INSERT INTO RegionsDes VALUES (109,'fin','Jamaica');
INSERT INTO RegionsDes VALUES (110,'fin','Japan');
INSERT INTO RegionsDes VALUES (112,'fin','Jordan');
INSERT INTO RegionsDes VALUES (113,'fin','Kyrgyzstan');
INSERT INTO RegionsDes VALUES (114,'fin','Kenya');
INSERT INTO RegionsDes VALUES (115,'fin','Cambodia');
INSERT INTO RegionsDes VALUES (116,'fin','Korea, Dem People''s Rep');
INSERT INTO RegionsDes VALUES (117,'fin','Korea, Republic of');
INSERT INTO RegionsDes VALUES (118,'fin','Kuwait');
INSERT INTO RegionsDes VALUES (119,'fin','Latvia');
INSERT INTO RegionsDes VALUES (120,'fin','Laos');
INSERT INTO RegionsDes VALUES (121,'fin','Lebanon');
INSERT INTO RegionsDes VALUES (122,'fin','Lesotho');
INSERT INTO RegionsDes VALUES (123,'fin','Liberia');
INSERT INTO RegionsDes VALUES (124,'fin','Libyan Arab Jamahiriya');
INSERT INTO RegionsDes VALUES (125,'fin','Liechtensten');
INSERT INTO RegionsDes VALUES (126,'fin','Lithuania');
INSERT INTO RegionsDes VALUES (127,'fin','Marshall Island');
INSERT INTO RegionsDes VALUES (129,'fin','Madagascar');
INSERT INTO RegionsDes VALUES (130,'fin','Malawi');
INSERT INTO RegionsDes VALUES (131,'fin','Malaysia');
INSERT INTO RegionsDes VALUES (132,'fin','Maldives');
INSERT INTO RegionsDes VALUES (133,'fin','Mali');
INSERT INTO RegionsDes VALUES (134,'fin','Malta');
INSERT INTO RegionsDes VALUES (135,'fin','Martinique');
INSERT INTO RegionsDes VALUES (136,'fin','Mauritania');
INSERT INTO RegionsDes VALUES (137,'fin','Mauritius');
INSERT INTO RegionsDes VALUES (138,'fin','Mexico');
INSERT INTO RegionsDes VALUES (139,'fin','Midway Islands');
INSERT INTO RegionsDes VALUES (140,'fin','Monaco');
INSERT INTO RegionsDes VALUES (141,'fin','Mongolia');
INSERT INTO RegionsDes VALUES (142,'fin','Montserrat');
INSERT INTO RegionsDes VALUES (143,'fin','Morocco');
INSERT INTO RegionsDes VALUES (144,'fin','Mozambique');
INSERT INTO RegionsDes VALUES (145,'fin','Micronesia,Fed States of');
INSERT INTO RegionsDes VALUES (146,'fin','Moldova, Republic of');
INSERT INTO RegionsDes VALUES (147,'fin','Namibia');
INSERT INTO RegionsDes VALUES (148,'fin','Nauru');
INSERT INTO RegionsDes VALUES (149,'fin','Nepal');
INSERT INTO RegionsDes VALUES (150,'fin','Netherlands');
INSERT INTO RegionsDes VALUES (151,'fin','Neth Antilles');
INSERT INTO RegionsDes VALUES (153,'fin','NewCaledonia');
INSERT INTO RegionsDes VALUES (154,'fin','Macedonia');
INSERT INTO RegionsDes VALUES (155,'fin','Vanuatu');
INSERT INTO RegionsDes VALUES (156,'fin','New Zealand');
INSERT INTO RegionsDes VALUES (157,'fin','Nicaragua');
INSERT INTO RegionsDes VALUES (158,'fin','Niger');
INSERT INTO RegionsDes VALUES (159,'fin','Nigeria');
INSERT INTO RegionsDes VALUES (160,'fin','Niue');
INSERT INTO RegionsDes VALUES (161,'fin','Norfolk Island');
INSERT INTO RegionsDes VALUES (162,'fin','Norway');
INSERT INTO RegionsDes VALUES (163,'fin','Northern Mariana Is');
INSERT INTO RegionsDes VALUES (165,'fin','Pakistan');
INSERT INTO RegionsDes VALUES (166,'fin','Panama');
INSERT INTO RegionsDes VALUES (167,'fin','Czech Republic');
INSERT INTO RegionsDes VALUES (168,'fin','Papua New Guinea');
INSERT INTO RegionsDes VALUES (169,'fin','Paraguay');
INSERT INTO RegionsDes VALUES (170,'fin','Peru');
INSERT INTO RegionsDes VALUES (171,'fin','Philippines');
INSERT INTO RegionsDes VALUES (172,'fin','Pitcairn Islands');
INSERT INTO RegionsDes VALUES (173,'fin','Poland');
INSERT INTO RegionsDes VALUES (174,'fin','Portugal');
INSERT INTO RegionsDes VALUES (175,'fin','Guinea-Bissau');
INSERT INTO RegionsDes VALUES (176,'fin','East Timor');
INSERT INTO RegionsDes VALUES (177,'fin','Puerto Rico');
INSERT INTO RegionsDes VALUES (178,'fin','Eritrea');
INSERT INTO RegionsDes VALUES (179,'fin','Qatar');
INSERT INTO RegionsDes VALUES (181,'fin','Zimbabwe');
INSERT INTO RegionsDes VALUES (182,'fin','Reunion');
INSERT INTO RegionsDes VALUES (183,'fin','Romania');
INSERT INTO RegionsDes VALUES (184,'fin','Rwanda');
INSERT INTO RegionsDes VALUES (185,'fin','Russian Federation');
INSERT INTO RegionsDes VALUES (187,'fin','Saint Helena');
INSERT INTO RegionsDes VALUES (188,'fin','Saint Kitts and Nevis');
INSERT INTO RegionsDes VALUES (189,'fin','Saint Lucia');
INSERT INTO RegionsDes VALUES (190,'fin','Saint Pierre & Miquelon');
INSERT INTO RegionsDes VALUES (191,'fin','Saint Vincent/Grenadines');
INSERT INTO RegionsDes VALUES (192,'fin','San Marino');
INSERT INTO RegionsDes VALUES (193,'fin','Sao Tome and Principe');
INSERT INTO RegionsDes VALUES (194,'fin','Saudi Arabia');
INSERT INTO RegionsDes VALUES (195,'fin','Senegal');
INSERT INTO RegionsDes VALUES (196,'fin','Seychelles');
INSERT INTO RegionsDes VALUES (197,'fin','Sierra Leone');
INSERT INTO RegionsDes VALUES (198,'fin','Slovenia');
INSERT INTO RegionsDes VALUES (199,'fin','Slovakia');
INSERT INTO RegionsDes VALUES (200,'fin','Singapore');
INSERT INTO RegionsDes VALUES (201,'fin','Somalia');
INSERT INTO RegionsDes VALUES (202,'fin','South Africa');
INSERT INTO RegionsDes VALUES (203,'fin','Spain');
INSERT INTO RegionsDes VALUES (205,'fin','Western Sahara');
INSERT INTO RegionsDes VALUES (206,'fin','Sudan');
INSERT INTO RegionsDes VALUES (207,'fin','Suriname');
INSERT INTO RegionsDes VALUES (208,'fin','Tajikistan');
INSERT INTO RegionsDes VALUES (209,'fin','Swaziland');
INSERT INTO RegionsDes VALUES (210,'fin','Sweden');
INSERT INTO RegionsDes VALUES (211,'fin','Switzerland');
INSERT INTO RegionsDes VALUES (212,'fin','Syrian Arab Republic');
INSERT INTO RegionsDes VALUES (213,'fin','Turkmenistan');
INSERT INTO RegionsDes VALUES (214,'fin','China, Taiwan Prov of');
INSERT INTO RegionsDes VALUES (215,'fin','Tanzania, United Rep of');
INSERT INTO RegionsDes VALUES (216,'fin','Thailand');
INSERT INTO RegionsDes VALUES (217,'fin','Togo');
INSERT INTO RegionsDes VALUES (218,'fin','Tokelau');
INSERT INTO RegionsDes VALUES (219,'fin','Tonga');
INSERT INTO RegionsDes VALUES (220,'fin','Trinidad and Tobago');
INSERT INTO RegionsDes VALUES (221,'fin','Oman');
INSERT INTO RegionsDes VALUES (222,'fin','Tunisia');
INSERT INTO RegionsDes VALUES (223,'fin','Turkey');
INSERT INTO RegionsDes VALUES (224,'fin','Turks and Caicos Is');
INSERT INTO RegionsDes VALUES (225,'fin','United Arab Emirates');
INSERT INTO RegionsDes VALUES (226,'fin','Uganda');
INSERT INTO RegionsDes VALUES (227,'fin','Tuvalu');
INSERT INTO RegionsDes VALUES (229,'fin','United Kingdom');
INSERT INTO RegionsDes VALUES (230,'fin','Ukraine');
INSERT INTO RegionsDes VALUES (231,'fin','United States of America');
INSERT INTO RegionsDes VALUES (232,'fin','US Minor Outlying Is');
INSERT INTO RegionsDes VALUES (233,'fin','Burkina Faso');
INSERT INTO RegionsDes VALUES (234,'fin','Uruguay');
INSERT INTO RegionsDes VALUES (235,'fin','Uzbekistan');
INSERT INTO RegionsDes VALUES (236,'fin','Venezuela');
INSERT INTO RegionsDes VALUES (237,'fin','Viet Nam');
INSERT INTO RegionsDes VALUES (238,'fin','Ethiopia');
INSERT INTO RegionsDes VALUES (239,'fin','British Virgin Island');
INSERT INTO RegionsDes VALUES (240,'fin','US Virgin Islands');
INSERT INTO RegionsDes VALUES (242,'fin','Wake Island');
INSERT INTO RegionsDes VALUES (243,'fin','Wallis and Futuna Is');
INSERT INTO RegionsDes VALUES (244,'fin','Samoa');
INSERT INTO RegionsDes VALUES (245,'fin','West Bank');
INSERT INTO RegionsDes VALUES (249,'fin','Yemen');
INSERT INTO RegionsDes VALUES (250,'fin','Congo, Dem Republic of');
INSERT INTO RegionsDes VALUES (251,'fin','Zambia');
INSERT INTO RegionsDes VALUES (255,'fin','Belgium');
INSERT INTO RegionsDes VALUES (256,'fin','Luxembourg');
INSERT INTO RegionsDes VALUES (258,'fin','Anguilla');
INSERT INTO RegionsDes VALUES (260,'fin','Svalbard Is');
INSERT INTO RegionsDes VALUES (264,'fin','Isle of Man');
INSERT INTO RegionsDes VALUES (270,'fin','Mayotte');
INSERT INTO RegionsDes VALUES (271,'fin','SouthGeorgia/Sandwich Is');
INSERT INTO RegionsDes VALUES (303,'fin','Western Europe');
INSERT INTO RegionsDes VALUES (307,'fin','Intergvt Author Devpment');
INSERT INTO RegionsDes VALUES (310,'fin','North Western Africa');
INSERT INTO RegionsDes VALUES (311,'fin','Western Africa');
INSERT INTO RegionsDes VALUES (312,'fin','Central Africa');
INSERT INTO RegionsDes VALUES (313,'fin','Eastern Africa');
INSERT INTO RegionsDes VALUES (314,'fin','Southern Africa');
INSERT INTO RegionsDes VALUES (315,'fin','Latin Amer & Caribbean');
INSERT INTO RegionsDes VALUES (316,'fin','Central America');
INSERT INTO RegionsDes VALUES (317,'fin','Caribbean');
INSERT INTO RegionsDes VALUES (318,'fin','South America');
INSERT INTO RegionsDes VALUES (319,'fin','Near East');
INSERT INTO RegionsDes VALUES (320,'fin','Near East in Africa');
INSERT INTO RegionsDes VALUES (321,'fin','Near East in Asia');
INSERT INTO RegionsDes VALUES (322,'fin','Far East');
INSERT INTO RegionsDes VALUES (323,'fin','South Asia');
INSERT INTO RegionsDes VALUES (324,'fin','East & South East Asia');
INSERT INTO RegionsDes VALUES (325,'fin','Near East and North Africa');
INSERT INTO RegionsDes VALUES (334,'fin','Eastern Europe');
INSERT INTO RegionsDes VALUES (335,'fin','Europe');
INSERT INTO RegionsDes VALUES (337,'fin','Asia');
INSERT INTO RegionsDes VALUES (338,'fin','Africa');
INSERT INTO RegionsDes VALUES (348,'fin','Latin America');
INSERT INTO RegionsDes VALUES (370,'fin','Serbia');
INSERT INTO RegionsDes VALUES (371,'fin','Montenegro');
INSERT INTO RegionsDes VALUES (390,'fin','South of Sahara');
INSERT INTO RegionsDes VALUES (421,'fin','North Africa');
INSERT INTO RegionsDes VALUES (427,'fin','Europe, Non-EU Countries');
INSERT INTO RegionsDes VALUES (428,'fin','North America');
INSERT INTO RegionsDes VALUES (469,'fin','USSR, Former Area of');
INSERT INTO RegionsDes VALUES (1008,'fin','Arctic Sea');
INSERT INTO RegionsDes VALUES (1009,'fin','Atlantic, Northwest');
INSERT INTO RegionsDes VALUES (1010,'fin','Atlantic, Northeast');
INSERT INTO RegionsDes VALUES (1011,'fin','Atlantic, Western Central');
INSERT INTO RegionsDes VALUES (1012,'fin','Atlantic, Eastern Central');
INSERT INTO RegionsDes VALUES (1013,'fin','Mediterran and Black Sea');
INSERT INTO RegionsDes VALUES (1014,'fin','Atlantic, Southwest');
INSERT INTO RegionsDes VALUES (1015,'fin','Atlantic, Southeast');
INSERT INTO RegionsDes VALUES (1016,'fin','Atlantic, Antarctic');
INSERT INTO RegionsDes VALUES (1017,'fin','Indian Ocean, Western');
INSERT INTO RegionsDes VALUES (1018,'fin','Indian Ocean, Eastern');
INSERT INTO RegionsDes VALUES (1019,'fin','Indian Ocean, Antarctic');
INSERT INTO RegionsDes VALUES (1020,'fin','Pacific, Northwest');
INSERT INTO RegionsDes VALUES (1021,'fin','Pacific, Northeast');
INSERT INTO RegionsDes VALUES (1022,'fin','Pacific, Western Central');
INSERT INTO RegionsDes VALUES (1023,'fin','Pacific, Eastern Central');
INSERT INTO RegionsDes VALUES (1024,'fin','Pacific, Southwest');
INSERT INTO RegionsDes VALUES (1025,'fin','Pacific, Southeast');
INSERT INTO RegionsDes VALUES (1026,'fin','Pacific, Antarctic');
INSERT INTO RegionsDes VALUES (1220,'fin','All fishing areas');
INSERT INTO RegionsDes VALUES (9999,'fin','World');
