-- ISO 3 letter code migration
INSERT INTO Languages VALUES ('ara','العربية', 'n', 'n');

UPDATE CategoriesDes             SET langid='ara' WHERE langid='ar';
UPDATE IsoLanguagesDes           SET langid='ara' WHERE langid='ar';
UPDATE RegionsDes                SET langid='ara' WHERE langid='ar';
UPDATE GroupsDes                 SET langid='ara' WHERE langid='ar';
UPDATE OperationsDes             SET langid='ara' WHERE langid='ar';
UPDATE StatusValuesDes           SET langid='ara' WHERE langid='ar';
UPDATE CswServerCapabilitiesInfo SET langid='ara' WHERE langid='ar';
DELETE FROM Languages WHERE id='ar';

-- Take care to table ID (related to other loc files)
INSERT INTO CswServerCapabilitiesInfo VALUES (41, 'ara', 'title', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (42, 'ara', 'abstract', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (43, 'ara', 'fees', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (44, 'ara', 'accessConstraints', '');

INSERT INTO CategoriesDes (iddes, langid, label) VALUES (1,'ara','Maps & graphics');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (2,'ara','Datasets');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (3,'ara','Interactive resources');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (4,'ara','Applications');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (5,'ara','Case studies, best practices');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (6,'ara','Conference proceedings');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (7,'ara','Photo');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (8,'ara','Audio/Video');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (9,'ara','Directories');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (10,'ara','Other information resources');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (11,'ara','Z3950 Servers');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (12,'ara','Registers');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (13,'ara','Physical Samples');

INSERT INTO GroupsDes (iddes, langid, label) VALUES (-1,'ara','Guest');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (0,'ara','Intranet');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (1,'ara','All');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (2,'ara','Sample group');

INSERT INTO IsoLanguagesDes VALUES (1,'ara','Afar');
INSERT INTO IsoLanguagesDes VALUES (2,'ara','Abkhazian');
INSERT INTO IsoLanguagesDes VALUES (3,'ara','Achinese');
INSERT INTO IsoLanguagesDes VALUES (4,'ara','Acoli');
INSERT INTO IsoLanguagesDes VALUES (5,'ara','Adangme');
INSERT INTO IsoLanguagesDes VALUES (6,'ara','Adyghe; Adygei');
INSERT INTO IsoLanguagesDes VALUES (7,'ara','Afro-Asiatic (Other)');
INSERT INTO IsoLanguagesDes VALUES (8,'ara','Afrihili');
INSERT INTO IsoLanguagesDes VALUES (9,'ara','Afrikaans');
INSERT INTO IsoLanguagesDes VALUES (10,'ara','Ainu');
INSERT INTO IsoLanguagesDes VALUES (11,'ara','Akan');
INSERT INTO IsoLanguagesDes VALUES (12,'ara','Akkadian');
INSERT INTO IsoLanguagesDes VALUES (13,'ara','Albanian');
INSERT INTO IsoLanguagesDes VALUES (14,'ara','Aleut');
INSERT INTO IsoLanguagesDes VALUES (15,'ara','Algonquian languages');
INSERT INTO IsoLanguagesDes VALUES (16,'ara','Southern Altai');
INSERT INTO IsoLanguagesDes VALUES (17,'ara','Amharic');
INSERT INTO IsoLanguagesDes VALUES (18,'ara','English, Old (ca.450-1100)');
INSERT INTO IsoLanguagesDes VALUES (19,'ara','Angika');
INSERT INTO IsoLanguagesDes VALUES (20,'ara','Apache languages');
INSERT INTO IsoLanguagesDes VALUES (21,'ara','Arabic');
INSERT INTO IsoLanguagesDes VALUES (22,'ara','Aramaic');
INSERT INTO IsoLanguagesDes VALUES (23,'ara','Aragonese');
INSERT INTO IsoLanguagesDes VALUES (24,'ara','Armenian');
INSERT INTO IsoLanguagesDes VALUES (25,'ara','Mapudungun; Mapuche');
INSERT INTO IsoLanguagesDes VALUES (26,'ara','Arapaho');
INSERT INTO IsoLanguagesDes VALUES (27,'ara','Artificial (Other)');
INSERT INTO IsoLanguagesDes VALUES (28,'ara','Arawak');
INSERT INTO IsoLanguagesDes VALUES (29,'ara','Assamese');
INSERT INTO IsoLanguagesDes VALUES (30,'ara','Asturian; Bable');
INSERT INTO IsoLanguagesDes VALUES (31,'ara','Athapascan languages');
INSERT INTO IsoLanguagesDes VALUES (32,'ara','Australian languages');
INSERT INTO IsoLanguagesDes VALUES (33,'ara','Avaric');
INSERT INTO IsoLanguagesDes VALUES (34,'ara','Avestan');
INSERT INTO IsoLanguagesDes VALUES (35,'ara','Awadhi');
INSERT INTO IsoLanguagesDes VALUES (36,'ara','Aymara');
INSERT INTO IsoLanguagesDes VALUES (37,'ara','Azerbaijani');
INSERT INTO IsoLanguagesDes VALUES (38,'ara','Banda languages');
INSERT INTO IsoLanguagesDes VALUES (39,'ara','Bamileke languages');
INSERT INTO IsoLanguagesDes VALUES (40,'ara','Bashkir');
INSERT INTO IsoLanguagesDes VALUES (41,'ara','Baluchi');
INSERT INTO IsoLanguagesDes VALUES (42,'ara','Bambara');
INSERT INTO IsoLanguagesDes VALUES (43,'ara','Balinese');
INSERT INTO IsoLanguagesDes VALUES (44,'ara','Basque');
INSERT INTO IsoLanguagesDes VALUES (45,'ara','Basa');
INSERT INTO IsoLanguagesDes VALUES (46,'ara','Baltic (Other)');
INSERT INTO IsoLanguagesDes VALUES (47,'ara','Beja');
INSERT INTO IsoLanguagesDes VALUES (48,'ara','Belarusian');
INSERT INTO IsoLanguagesDes VALUES (49,'ara','Bemba');
INSERT INTO IsoLanguagesDes VALUES (50,'ara','Bengali');
INSERT INTO IsoLanguagesDes VALUES (51,'ara','Berber (Other)');
INSERT INTO IsoLanguagesDes VALUES (52,'ara','Bhojpuri');
INSERT INTO IsoLanguagesDes VALUES (53,'ara','Bihari');
INSERT INTO IsoLanguagesDes VALUES (54,'ara','Bikol');
INSERT INTO IsoLanguagesDes VALUES (55,'ara','Bini; Edo');
INSERT INTO IsoLanguagesDes VALUES (56,'ara','Bislama');
INSERT INTO IsoLanguagesDes VALUES (57,'ara','Siksika');
INSERT INTO IsoLanguagesDes VALUES (58,'ara','Bantu (Other)');
INSERT INTO IsoLanguagesDes VALUES (59,'ara','Bosnian');
INSERT INTO IsoLanguagesDes VALUES (60,'ara','Braj');
INSERT INTO IsoLanguagesDes VALUES (61,'ara','Breton');
INSERT INTO IsoLanguagesDes VALUES (62,'ara','Batak languages');
INSERT INTO IsoLanguagesDes VALUES (63,'ara','Buriat');
INSERT INTO IsoLanguagesDes VALUES (64,'ara','Buginese');
INSERT INTO IsoLanguagesDes VALUES (65,'ara','Bulgarian');
INSERT INTO IsoLanguagesDes VALUES (66,'ara','Burmese');
INSERT INTO IsoLanguagesDes VALUES (67,'ara','Blin; Bilin');
INSERT INTO IsoLanguagesDes VALUES (68,'ara','Caddo');
INSERT INTO IsoLanguagesDes VALUES (69,'ara','Central American Indian (Other)');
INSERT INTO IsoLanguagesDes VALUES (70,'ara','Galibi Carib');
INSERT INTO IsoLanguagesDes VALUES (71,'ara','Catalan; Valencian');
INSERT INTO IsoLanguagesDes VALUES (72,'ara','Caucasian (Other)on liturgique; vieux bulgare');
INSERT INTO IsoLanguagesDes VALUES (73,'ara','Cebuano');
INSERT INTO IsoLanguagesDes VALUES (74,'ara','Celtic (Other)');
INSERT INTO IsoLanguagesDes VALUES (75,'ara','Chamorro');
INSERT INTO IsoLanguagesDes VALUES (76,'ara','Chibcha');
INSERT INTO IsoLanguagesDes VALUES (77,'ara','Chechen');
INSERT INTO IsoLanguagesDes VALUES (78,'ara','Chagataier)');
INSERT INTO IsoLanguagesDes VALUES (79,'ara','Chinese(Other)');
INSERT INTO IsoLanguagesDes VALUES (80,'ara','Chuukese');
INSERT INTO IsoLanguagesDes VALUES (81,'ara','Mari');
INSERT INTO IsoLanguagesDes VALUES (82,'ara','Chinook jargon');
INSERT INTO IsoLanguagesDes VALUES (83,'ara','Choctaw');
INSERT INTO IsoLanguagesDes VALUES (84,'ara','Chipewyan');
INSERT INTO IsoLanguagesDes VALUES (85,'ara','Cherokee');
INSERT INTO IsoLanguagesDes VALUES (86,'ara','Church Slavic; Old Slavonic; Church Sl');
INSERT INTO IsoLanguagesDes VALUES (87,'ara','Chuvash');
INSERT INTO IsoLanguagesDes VALUES (88,'ara','Cheyenne');
INSERT INTO IsoLanguagesDes VALUES (89,'ara','Chamic languages');
INSERT INTO IsoLanguagesDes VALUES (90,'ara','Coptic');
INSERT INTO IsoLanguagesDes VALUES (91,'ara','Cornish');
INSERT INTO IsoLanguagesDes VALUES (92,'ara','Corsican');
INSERT INTO IsoLanguagesDes VALUES (93,'ara','Creoles and pidgins, English based (Ot');
INSERT INTO IsoLanguagesDes VALUES (94,'ara','Creoles and pidgins, French-based (Oth');
INSERT INTO IsoLanguagesDes VALUES (95,'ara','Creoles and pidgins, Portuguese-based ');
INSERT INTO IsoLanguagesDes VALUES (96,'ara','Cree');
INSERT INTO IsoLanguagesDes VALUES (97,'ara','Crimean Tatar; Crimean Turkish');
INSERT INTO IsoLanguagesDes VALUES (98,'ara','Creoles and pidgins (Other)');
INSERT INTO IsoLanguagesDes VALUES (99,'ara','Kashubian');
INSERT INTO IsoLanguagesDes VALUES (100,'ara','Cushitic (Other)');
INSERT INTO IsoLanguagesDes VALUES (101,'ara','Czech');
INSERT INTO IsoLanguagesDes VALUES (102,'ara','Dakota');
INSERT INTO IsoLanguagesDes VALUES (103,'ara','Danish');
INSERT INTO IsoLanguagesDes VALUES (104,'ara','Dargwa');
INSERT INTO IsoLanguagesDes VALUES (105,'ara','Land Dayak languages');
INSERT INTO IsoLanguagesDes VALUES (106,'ara','Delaware');
INSERT INTO IsoLanguagesDes VALUES (107,'ara','Slave (Athapascan)');
INSERT INTO IsoLanguagesDes VALUES (108,'ara','Dogrib');
INSERT INTO IsoLanguagesDes VALUES (109,'ara','Dinka');
INSERT INTO IsoLanguagesDes VALUES (110,'ara','Divehi; Dhivehi; Maldivian');
INSERT INTO IsoLanguagesDes VALUES (111,'ara','Dogri');
INSERT INTO IsoLanguagesDes VALUES (112,'ara','Dravidian (Other)');
INSERT INTO IsoLanguagesDes VALUES (113,'ara','Lower Sorbian');
INSERT INTO IsoLanguagesDes VALUES (114,'ara','Duala');
INSERT INTO IsoLanguagesDes VALUES (115,'ara','Dutch, Middle (ca.1050-1350)');
INSERT INTO IsoLanguagesDes VALUES (116,'ara','Dutch; Flemish');
INSERT INTO IsoLanguagesDes VALUES (117,'ara','Dyula');
INSERT INTO IsoLanguagesDes VALUES (118,'ara','Dzongkha');
INSERT INTO IsoLanguagesDes VALUES (119,'ara','Efik');
INSERT INTO IsoLanguagesDes VALUES (120,'ara','Egyptian (Ancient)');
INSERT INTO IsoLanguagesDes VALUES (121,'ara','Ekajuk');
INSERT INTO IsoLanguagesDes VALUES (122,'ara','Elamite');
INSERT INTO IsoLanguagesDes VALUES (123,'ara','English');
INSERT INTO IsoLanguagesDes VALUES (124,'ara','English, Middle (1100-1500)');
INSERT INTO IsoLanguagesDes VALUES (125,'ara','Esperanto');
INSERT INTO IsoLanguagesDes VALUES (126,'ara','Estonian');
INSERT INTO IsoLanguagesDes VALUES (127,'ara','Ewe');
INSERT INTO IsoLanguagesDes VALUES (128,'ara','Ewondo');
INSERT INTO IsoLanguagesDes VALUES (129,'ara','Fang');
INSERT INTO IsoLanguagesDes VALUES (130,'ara','Faroese');
INSERT INTO IsoLanguagesDes VALUES (131,'ara','Fanti');
INSERT INTO IsoLanguagesDes VALUES (132,'ara','Fijian');
INSERT INTO IsoLanguagesDes VALUES (133,'ara','Filipino; Pilipino');
INSERT INTO IsoLanguagesDes VALUES (134,'ara','Finnish');
INSERT INTO IsoLanguagesDes VALUES (135,'ara','Finno-Ugrian (Other)');
INSERT INTO IsoLanguagesDes VALUES (136,'ara','Fon');
INSERT INTO IsoLanguagesDes VALUES (137,'ara','French');
INSERT INTO IsoLanguagesDes VALUES (138,'ara','French, Middle (ca.1400-1600)');
INSERT INTO IsoLanguagesDes VALUES (139,'ara','French, Old (842-ca.1400)');
INSERT INTO IsoLanguagesDes VALUES (140,'ara','Northern Frisian');
INSERT INTO IsoLanguagesDes VALUES (141,'ara','Eastern Frisian');
INSERT INTO IsoLanguagesDes VALUES (142,'ara','Western Frisian');
INSERT INTO IsoLanguagesDes VALUES (143,'ara','Fulah');
INSERT INTO IsoLanguagesDes VALUES (144,'ara','Friulian');
INSERT INTO IsoLanguagesDes VALUES (145,'ara','Ga');
INSERT INTO IsoLanguagesDes VALUES (146,'ara','Gayo');
INSERT INTO IsoLanguagesDes VALUES (147,'ara','Gbaya');
INSERT INTO IsoLanguagesDes VALUES (148,'ara','Germanic (Other)');
INSERT INTO IsoLanguagesDes VALUES (149,'ara','Georgian');
INSERT INTO IsoLanguagesDes VALUES (150,'ara','German');
INSERT INTO IsoLanguagesDes VALUES (151,'ara','Geez');
INSERT INTO IsoLanguagesDes VALUES (152,'ara','Gilbertese');
INSERT INTO IsoLanguagesDes VALUES (153,'ara','Gaelic; Scottish Gaelic');
INSERT INTO IsoLanguagesDes VALUES (154,'ara','Irish');
INSERT INTO IsoLanguagesDes VALUES (155,'ara','Galician');
INSERT INTO IsoLanguagesDes VALUES (156,'ara','Manx');
INSERT INTO IsoLanguagesDes VALUES (157,'ara','German, Middle High (ca.1050-1500)');
INSERT INTO IsoLanguagesDes VALUES (158,'ara','German, Old High (ca.750-1050)');
INSERT INTO IsoLanguagesDes VALUES (159,'ara','Gondi');
INSERT INTO IsoLanguagesDes VALUES (160,'ara','Gorontalo');
INSERT INTO IsoLanguagesDes VALUES (161,'ara','Gothicanguage Association)');
INSERT INTO IsoLanguagesDes VALUES (162,'ara','Grebo');
INSERT INTO IsoLanguagesDes VALUES (163,'ara','Greek, Ancient (to 1453)');
INSERT INTO IsoLanguagesDes VALUES (164,'ara','Greek, Modern (1453-)');
INSERT INTO IsoLanguagesDes VALUES (165,'ara','Guarani');
INSERT INTO IsoLanguagesDes VALUES (166,'ara','Swiss German; Alemannic');
INSERT INTO IsoLanguagesDes VALUES (167,'ara','Gujarati');
INSERT INTO IsoLanguagesDes VALUES (168,'ara','Gwich''in');
INSERT INTO IsoLanguagesDes VALUES (169,'ara','Haida');
INSERT INTO IsoLanguagesDes VALUES (170,'ara','Haitian; Haitian Creole');
INSERT INTO IsoLanguagesDes VALUES (171,'ara','Hausa');
INSERT INTO IsoLanguagesDes VALUES (172,'ara','Hawaiian');
INSERT INTO IsoLanguagesDes VALUES (173,'ara','Hebrew');
INSERT INTO IsoLanguagesDes VALUES (174,'ara','Herero');
INSERT INTO IsoLanguagesDes VALUES (175,'ara','Hiligaynon');
INSERT INTO IsoLanguagesDes VALUES (176,'ara','Himachali');
INSERT INTO IsoLanguagesDes VALUES (177,'ara','Hindi');
INSERT INTO IsoLanguagesDes VALUES (178,'ara','Hittite');
INSERT INTO IsoLanguagesDes VALUES (179,'ara','Hmong');
INSERT INTO IsoLanguagesDes VALUES (180,'ara','Hiri Motu');
INSERT INTO IsoLanguagesDes VALUES (181,'ara','Upper Sorbian');
INSERT INTO IsoLanguagesDes VALUES (182,'ara','Hungarian');
INSERT INTO IsoLanguagesDes VALUES (183,'ara','Hupa');
INSERT INTO IsoLanguagesDes VALUES (184,'ara','Iban');
INSERT INTO IsoLanguagesDes VALUES (185,'ara','Igbo');
INSERT INTO IsoLanguagesDes VALUES (186,'ara','Icelandic');
INSERT INTO IsoLanguagesDes VALUES (187,'ara','Ido');
INSERT INTO IsoLanguagesDes VALUES (188,'ara','Sichuan Yi');
INSERT INTO IsoLanguagesDes VALUES (189,'ara','Ijo languages');
INSERT INTO IsoLanguagesDes VALUES (190,'ara','Inuktitut');
INSERT INTO IsoLanguagesDes VALUES (191,'ara','Interlingue');
INSERT INTO IsoLanguagesDes VALUES (192,'ara','Iloko');
INSERT INTO IsoLanguagesDes VALUES (193,'ara','Interlingua (International Auxiliary L');
INSERT INTO IsoLanguagesDes VALUES (194,'ara','Indic (Other)');
INSERT INTO IsoLanguagesDes VALUES (195,'ara','Indonesian');
INSERT INTO IsoLanguagesDes VALUES (196,'ara','Indo-European (Other)');
INSERT INTO IsoLanguagesDes VALUES (197,'ara','Ingush');
INSERT INTO IsoLanguagesDes VALUES (198,'ara','Inupiaq');
INSERT INTO IsoLanguagesDes VALUES (199,'ara','Iranian (Other)');
INSERT INTO IsoLanguagesDes VALUES (200,'ara','Iroquoian languages');
INSERT INTO IsoLanguagesDes VALUES (201,'ara','Italian');
INSERT INTO IsoLanguagesDes VALUES (202,'ara','Javanese');
INSERT INTO IsoLanguagesDes VALUES (203,'ara','Lojban');
INSERT INTO IsoLanguagesDes VALUES (204,'ara','Japanese');
INSERT INTO IsoLanguagesDes VALUES (205,'ara','Judeo-Persian');
INSERT INTO IsoLanguagesDes VALUES (206,'ara','Judeo-Arabic');
INSERT INTO IsoLanguagesDes VALUES (207,'ara','Kara-Kalpak');
INSERT INTO IsoLanguagesDes VALUES (208,'ara','Kabyle');
INSERT INTO IsoLanguagesDes VALUES (209,'ara','Kachin; Jingpho');
INSERT INTO IsoLanguagesDes VALUES (210,'ara','Kalaallisut; Greenlandic');
INSERT INTO IsoLanguagesDes VALUES (211,'ara','Kamba');
INSERT INTO IsoLanguagesDes VALUES (212,'ara','Kannada');
INSERT INTO IsoLanguagesDes VALUES (213,'ara','Karen languages');
INSERT INTO IsoLanguagesDes VALUES (214,'ara','Kashmiri');
INSERT INTO IsoLanguagesDes VALUES (215,'ara','Kanuri');
INSERT INTO IsoLanguagesDes VALUES (216,'ara','Kawi');
INSERT INTO IsoLanguagesDes VALUES (217,'ara','Kazakh');
INSERT INTO IsoLanguagesDes VALUES (218,'ara','Kabardian');
INSERT INTO IsoLanguagesDes VALUES (219,'ara','Khasi');
INSERT INTO IsoLanguagesDes VALUES (220,'ara','Khoisan (Other)');
INSERT INTO IsoLanguagesDes VALUES (221,'ara','Central Khmer');
INSERT INTO IsoLanguagesDes VALUES (222,'ara','Khotanese');
INSERT INTO IsoLanguagesDes VALUES (223,'ara','Kikuyu; Gikuyu');
INSERT INTO IsoLanguagesDes VALUES (224,'ara','Kinyarwanda');
INSERT INTO IsoLanguagesDes VALUES (225,'ara','Kirghiz; Kyrgyz');
INSERT INTO IsoLanguagesDes VALUES (226,'ara','Kimbundu');
INSERT INTO IsoLanguagesDes VALUES (227,'ara','Konkani');
INSERT INTO IsoLanguagesDes VALUES (228,'ara','Komi');
INSERT INTO IsoLanguagesDes VALUES (229,'ara','Kongo');
INSERT INTO IsoLanguagesDes VALUES (230,'ara','Korean');
INSERT INTO IsoLanguagesDes VALUES (231,'ara','Kosraean');
INSERT INTO IsoLanguagesDes VALUES (232,'ara','Kpelle');
INSERT INTO IsoLanguagesDes VALUES (233,'ara','Karachay-Balkar');
INSERT INTO IsoLanguagesDes VALUES (234,'ara','Karelian');
INSERT INTO IsoLanguagesDes VALUES (235,'ara','Kru languages');
INSERT INTO IsoLanguagesDes VALUES (236,'ara','Kurukh');
INSERT INTO IsoLanguagesDes VALUES (237,'ara','Kuanyama; Kwanyama');
INSERT INTO IsoLanguagesDes VALUES (238,'ara','Kumyk');
INSERT INTO IsoLanguagesDes VALUES (239,'ara','Kurdish');
INSERT INTO IsoLanguagesDes VALUES (240,'ara','Kutenai');
INSERT INTO IsoLanguagesDes VALUES (241,'ara','Ladino');
INSERT INTO IsoLanguagesDes VALUES (242,'ara','Lahnda');
INSERT INTO IsoLanguagesDes VALUES (243,'ara','Lamba');
INSERT INTO IsoLanguagesDes VALUES (244,'ara','Lao');
INSERT INTO IsoLanguagesDes VALUES (245,'ara','Latin');
INSERT INTO IsoLanguagesDes VALUES (246,'ara','Latvian');
INSERT INTO IsoLanguagesDes VALUES (247,'ara','Lezghian');
INSERT INTO IsoLanguagesDes VALUES (248,'ara','Limburgan; Limburger; Limburgish');
INSERT INTO IsoLanguagesDes VALUES (249,'ara','Lingala');
INSERT INTO IsoLanguagesDes VALUES (250,'ara','Lithuanian');
INSERT INTO IsoLanguagesDes VALUES (251,'ara','Mongo');
INSERT INTO IsoLanguagesDes VALUES (252,'ara','Lozi');
INSERT INTO IsoLanguagesDes VALUES (253,'ara','Luxembourgish; Letzeburgesch');
INSERT INTO IsoLanguagesDes VALUES (254,'ara','Luba-Lulua');
INSERT INTO IsoLanguagesDes VALUES (255,'ara','Luba-Katangaxon, Low');
INSERT INTO IsoLanguagesDes VALUES (256,'ara','Ganda');
INSERT INTO IsoLanguagesDes VALUES (257,'ara','Luiseno');
INSERT INTO IsoLanguagesDes VALUES (258,'ara','Lunda');
INSERT INTO IsoLanguagesDes VALUES (259,'ara','Luo (Kenya and Tanzania)');
INSERT INTO IsoLanguagesDes VALUES (260,'ara','Lushai');
INSERT INTO IsoLanguagesDes VALUES (261,'ara','Macedonian00E5l');
INSERT INTO IsoLanguagesDes VALUES (262,'ara','Madurese');
INSERT INTO IsoLanguagesDes VALUES (263,'ara','Magahi');
INSERT INTO IsoLanguagesDes VALUES (264,'ara','Marshallese');
INSERT INTO IsoLanguagesDes VALUES (265,'ara','Maithili');
INSERT INTO IsoLanguagesDes VALUES (266,'ara','Makasarl Nepal Bhasa');
INSERT INTO IsoLanguagesDes VALUES (267,'ara','Malayalam');
INSERT INTO IsoLanguagesDes VALUES (268,'ara','Mandingo');
INSERT INTO IsoLanguagesDes VALUES (269,'ara','Maori');
INSERT INTO IsoLanguagesDes VALUES (270,'ara','Austronesian (Other)');
INSERT INTO IsoLanguagesDes VALUES (271,'ara','Marathi');
INSERT INTO IsoLanguagesDes VALUES (272,'ara','Masai');
INSERT INTO IsoLanguagesDes VALUES (273,'ara','Malay');
INSERT INTO IsoLanguagesDes VALUES (274,'ara','Moksha');
INSERT INTO IsoLanguagesDes VALUES (275,'ara','Mandar');
INSERT INTO IsoLanguagesDes VALUES (276,'ara','Mende');
INSERT INTO IsoLanguagesDes VALUES (277,'ara','Irish, Middle (900-1200)');
INSERT INTO IsoLanguagesDes VALUES (278,'ara','Mi''kmaq; Micmac');
INSERT INTO IsoLanguagesDes VALUES (279,'ara','Minangkabau');
INSERT INTO IsoLanguagesDes VALUES (280,'ara','Miscellaneous languages');
INSERT INTO IsoLanguagesDes VALUES (281,'ara','Mon-Khmer (Other)');
INSERT INTO IsoLanguagesDes VALUES (282,'ara','Malagasy');
INSERT INTO IsoLanguagesDes VALUES (283,'ara','Maltese');
INSERT INTO IsoLanguagesDes VALUES (284,'ara','Manchu');
INSERT INTO IsoLanguagesDes VALUES (285,'ara','Manipuri');
INSERT INTO IsoLanguagesDes VALUES (286,'ara','Manobo languages');
INSERT INTO IsoLanguagesDes VALUES (287,'ara','Mohawk');
INSERT INTO IsoLanguagesDes VALUES (288,'ara','Moldavian');
INSERT INTO IsoLanguagesDes VALUES (289,'ara','Mongolian');
INSERT INTO IsoLanguagesDes VALUES (290,'ara','Mossi');
INSERT INTO IsoLanguagesDes VALUES (291,'ara','Multiple languages');
INSERT INTO IsoLanguagesDes VALUES (292,'ara','Munda languages');
INSERT INTO IsoLanguagesDes VALUES (293,'ara','Creek');
INSERT INTO IsoLanguagesDes VALUES (294,'ara','Mirandese');
INSERT INTO IsoLanguagesDes VALUES (295,'ara','Marwari');
INSERT INTO IsoLanguagesDes VALUES (296,'ara','Mayan languages');
INSERT INTO IsoLanguagesDes VALUES (297,'ara','Erzya');
INSERT INTO IsoLanguagesDes VALUES (298,'ara','Nahuatl languages');
INSERT INTO IsoLanguagesDes VALUES (299,'ara','North American Indian');
INSERT INTO IsoLanguagesDes VALUES (300,'ara','Neapolitan');
INSERT INTO IsoLanguagesDes VALUES (301,'ara','Nauru');
INSERT INTO IsoLanguagesDes VALUES (302,'ara','Navajo; Navaho');
INSERT INTO IsoLanguagesDes VALUES (303,'ara','Ndebele, South; South Ndebele');
INSERT INTO IsoLanguagesDes VALUES (304,'ara','Ndebele, North; North Ndebele');
INSERT INTO IsoLanguagesDes VALUES (305,'ara','Ndonga');
INSERT INTO IsoLanguagesDes VALUES (306,'ara','Low German; Low Saxon; German, Low; Sa');
INSERT INTO IsoLanguagesDes VALUES (307,'ara','Nepali');
INSERT INTO IsoLanguagesDes VALUES (308,'ara','Nepal Bhasa; Newari');
INSERT INTO IsoLanguagesDes VALUES (309,'ara','Nias');
INSERT INTO IsoLanguagesDes VALUES (310,'ara','Niger-Kordofanian (Other)');
INSERT INTO IsoLanguagesDes VALUES (311,'ara','Niuean');
INSERT INTO IsoLanguagesDes VALUES (312,'ara','Norwegian Nynorsk; Nynorsk, Norwegian');
INSERT INTO IsoLanguagesDes VALUES (313,'ara','Bokmål, Norwegian; Norwegian Bokmål');
INSERT INTO IsoLanguagesDes VALUES (314,'ara','Nogai');
INSERT INTO IsoLanguagesDes VALUES (315,'ara','Norse, Old');
INSERT INTO IsoLanguagesDes VALUES (316,'ara','Norwegian');
INSERT INTO IsoLanguagesDes VALUES (317,'ara','Pedi; Sepedi; Northern Sotho');
INSERT INTO IsoLanguagesDes VALUES (318,'ara','Nubian languages');
INSERT INTO IsoLanguagesDes VALUES (319,'ara','Classical Newari; Old Newari; Classica');
INSERT INTO IsoLanguagesDes VALUES (320,'ara','Chichewa; Chewa; Nyanja');
INSERT INTO IsoLanguagesDes VALUES (321,'ara','Nyamwezi');
INSERT INTO IsoLanguagesDes VALUES (322,'ara','Nyankole');
INSERT INTO IsoLanguagesDes VALUES (323,'ara','Nyoro');
INSERT INTO IsoLanguagesDes VALUES (324,'ara','Nzima');
INSERT INTO IsoLanguagesDes VALUES (325,'ara','Occitan (post 1500); Provençal');
INSERT INTO IsoLanguagesDes VALUES (326,'ara','Ojibwa');
INSERT INTO IsoLanguagesDes VALUES (327,'ara','Oriya');
INSERT INTO IsoLanguagesDes VALUES (328,'ara','Oromo');
INSERT INTO IsoLanguagesDes VALUES (329,'ara','Osage');
INSERT INTO IsoLanguagesDes VALUES (330,'ara','Ossetian; Ossetic');
INSERT INTO IsoLanguagesDes VALUES (331,'ara','Turkish, Ottoman (1500-1928)');
INSERT INTO IsoLanguagesDes VALUES (332,'ara','Otomian languages');
INSERT INTO IsoLanguagesDes VALUES (333,'ara','Papuan (Other)');
INSERT INTO IsoLanguagesDes VALUES (334,'ara','Pangasinan');
INSERT INTO IsoLanguagesDes VALUES (335,'ara','Pahlavi');
INSERT INTO IsoLanguagesDes VALUES (336,'ara','Pampanga');
INSERT INTO IsoLanguagesDes VALUES (337,'ara','Panjabi; Punjabi');
INSERT INTO IsoLanguagesDes VALUES (338,'ara','Papiamento');
INSERT INTO IsoLanguagesDes VALUES (339,'ara','Palauan');
INSERT INTO IsoLanguagesDes VALUES (340,'ara','Persian, Old (ca.600-400 B.C.)');
INSERT INTO IsoLanguagesDes VALUES (341,'ara','Persian');
INSERT INTO IsoLanguagesDes VALUES (342,'ara','Philippine (Other)');
INSERT INTO IsoLanguagesDes VALUES (343,'ara','Phoenician');
INSERT INTO IsoLanguagesDes VALUES (344,'ara','Pali');
INSERT INTO IsoLanguagesDes VALUES (345,'ara','Polish');
INSERT INTO IsoLanguagesDes VALUES (346,'ara','Pohnpeian');
INSERT INTO IsoLanguagesDes VALUES (347,'ara','Portuguese');
INSERT INTO IsoLanguagesDes VALUES (348,'ara','Prakrit languages');
INSERT INTO IsoLanguagesDes VALUES (349,'ara','Provençal, Old (to 1500)');
INSERT INTO IsoLanguagesDes VALUES (350,'ara','Pushto');
INSERT INTO IsoLanguagesDes VALUES (351,'ara','Reserved for local use');
INSERT INTO IsoLanguagesDes VALUES (352,'ara','Quechua');
INSERT INTO IsoLanguagesDes VALUES (353,'ara','Rajasthani');
INSERT INTO IsoLanguagesDes VALUES (354,'ara','Rapanui');
INSERT INTO IsoLanguagesDes VALUES (355,'ara','Rarotongan; Cook Islands Maori');
INSERT INTO IsoLanguagesDes VALUES (356,'ara','Romance (Other)');
INSERT INTO IsoLanguagesDes VALUES (357,'ara','Romansh');
INSERT INTO IsoLanguagesDes VALUES (358,'ara','Romany');
INSERT INTO IsoLanguagesDes VALUES (359,'ara','Romanian');
INSERT INTO IsoLanguagesDes VALUES (360,'ara','Rundi');
INSERT INTO IsoLanguagesDes VALUES (361,'ara','Aromanian; Arumanian; Macedo-Romanian');
INSERT INTO IsoLanguagesDes VALUES (362,'ara','Russian');
INSERT INTO IsoLanguagesDes VALUES (363,'ara','Sandawe');
INSERT INTO IsoLanguagesDes VALUES (364,'ara','Sango');
INSERT INTO IsoLanguagesDes VALUES (365,'ara','Yakut');
INSERT INTO IsoLanguagesDes VALUES (366,'ara','South American Indian (Other)');
INSERT INTO IsoLanguagesDes VALUES (367,'ara','Salishan languages');
INSERT INTO IsoLanguagesDes VALUES (368,'ara','Samaritan Aramaic');
INSERT INTO IsoLanguagesDes VALUES (369,'ara','Sanskrit');
INSERT INTO IsoLanguagesDes VALUES (370,'ara','Sasak');
INSERT INTO IsoLanguagesDes VALUES (371,'ara','Santali');
INSERT INTO IsoLanguagesDes VALUES (372,'ara','Serbian');
INSERT INTO IsoLanguagesDes VALUES (373,'ara','Sicilian');
INSERT INTO IsoLanguagesDes VALUES (374,'ara','Scots');
INSERT INTO IsoLanguagesDes VALUES (375,'ara','Croatian');
INSERT INTO IsoLanguagesDes VALUES (376,'ara','Selkup');
INSERT INTO IsoLanguagesDes VALUES (377,'ara','Semitic (Other)');
INSERT INTO IsoLanguagesDes VALUES (378,'ara','Irish, Old (to 900)');
INSERT INTO IsoLanguagesDes VALUES (379,'ara','Sign Languages');
INSERT INTO IsoLanguagesDes VALUES (380,'ara','Shan');
INSERT INTO IsoLanguagesDes VALUES (381,'ara','Sidamo');
INSERT INTO IsoLanguagesDes VALUES (382,'ara','Sinhala; Sinhalese');
INSERT INTO IsoLanguagesDes VALUES (383,'ara','Siouan languages');
INSERT INTO IsoLanguagesDes VALUES (384,'ara','Sino-Tibetan (Other)');
INSERT INTO IsoLanguagesDes VALUES (385,'ara','Slavic (Other)');
INSERT INTO IsoLanguagesDes VALUES (386,'ara','Slovak');
INSERT INTO IsoLanguagesDes VALUES (387,'ara','Slovenian');
INSERT INTO IsoLanguagesDes VALUES (388,'ara','Southern Sami');
INSERT INTO IsoLanguagesDes VALUES (389,'ara','Northern Sami');
INSERT INTO IsoLanguagesDes VALUES (390,'ara','Sami languages (Other)');
INSERT INTO IsoLanguagesDes VALUES (391,'ara','Lule Sami');
INSERT INTO IsoLanguagesDes VALUES (392,'ara','Inari Sami');
INSERT INTO IsoLanguagesDes VALUES (393,'ara','Samoan');
INSERT INTO IsoLanguagesDes VALUES (394,'ara','Skolt Sami');
INSERT INTO IsoLanguagesDes VALUES (395,'ara','Shona');
INSERT INTO IsoLanguagesDes VALUES (396,'ara','Sindhi');
INSERT INTO IsoLanguagesDes VALUES (397,'ara','Soninke');
INSERT INTO IsoLanguagesDes VALUES (398,'ara','Sogdian');
INSERT INTO IsoLanguagesDes VALUES (399,'ara','Somali');
INSERT INTO IsoLanguagesDes VALUES (400,'ara','Songhai languages');
INSERT INTO IsoLanguagesDes VALUES (401,'ara','Sotho, Southern');
INSERT INTO IsoLanguagesDes VALUES (402,'ara','Spanish; Castilian');
INSERT INTO IsoLanguagesDes VALUES (403,'ara','Sardinian; Zazaki');
INSERT INTO IsoLanguagesDes VALUES (404,'ara','Sranan Tongo');
INSERT INTO IsoLanguagesDes VALUES (405,'ara','Serer');
INSERT INTO IsoLanguagesDes VALUES (406,'ara','Nilo-Saharan (Other)');
INSERT INTO IsoLanguagesDes VALUES (407,'ara','Swati');
INSERT INTO IsoLanguagesDes VALUES (408,'ara','Sukuma');
INSERT INTO IsoLanguagesDes VALUES (409,'ara','Sundanese');
INSERT INTO IsoLanguagesDes VALUES (410,'ara','Susu');
INSERT INTO IsoLanguagesDes VALUES (411,'ara','Sumerian');
INSERT INTO IsoLanguagesDes VALUES (412,'ara','Swahili');
INSERT INTO IsoLanguagesDes VALUES (413,'ara','Swedish');
INSERT INTO IsoLanguagesDes VALUES (414,'ara','Syriac');
INSERT INTO IsoLanguagesDes VALUES (415,'ara','Tahitian');
INSERT INTO IsoLanguagesDes VALUES (416,'ara','Tai (Other)');
INSERT INTO IsoLanguagesDes VALUES (417,'ara','Tamil');
INSERT INTO IsoLanguagesDes VALUES (418,'ara','Tatar');
INSERT INTO IsoLanguagesDes VALUES (419,'ara','Telugu');
INSERT INTO IsoLanguagesDes VALUES (420,'ara','Timnendere)');
INSERT INTO IsoLanguagesDes VALUES (421,'ara','Tereno');
INSERT INTO IsoLanguagesDes VALUES (422,'ara','Tetum');
INSERT INTO IsoLanguagesDes VALUES (423,'ara','Tajik');
INSERT INTO IsoLanguagesDes VALUES (424,'ara','Tagalog');
INSERT INTO IsoLanguagesDes VALUES (425,'ara','Thai');
INSERT INTO IsoLanguagesDes VALUES (426,'ara','Tibetan');
INSERT INTO IsoLanguagesDes VALUES (427,'ara','Tigre');
INSERT INTO IsoLanguagesDes VALUES (428,'ara','Tigrinya');
INSERT INTO IsoLanguagesDes VALUES (429,'ara','Tiv');
INSERT INTO IsoLanguagesDes VALUES (430,'ara','Tokelau');
INSERT INTO IsoLanguagesDes VALUES (431,'ara','Klingon; tlhIngan-Hol');
INSERT INTO IsoLanguagesDes VALUES (432,'ara','Tlingit');
INSERT INTO IsoLanguagesDes VALUES (433,'ara','Tamashek');
INSERT INTO IsoLanguagesDes VALUES (434,'ara','Tonga (Nyasa)');
INSERT INTO IsoLanguagesDes VALUES (435,'ara','Tonga (Tonga Islands)');
INSERT INTO IsoLanguagesDes VALUES (436,'ara','Tok Pisin');
INSERT INTO IsoLanguagesDes VALUES (437,'ara','Tsimshian');
INSERT INTO IsoLanguagesDes VALUES (438,'ara','Tswana');
INSERT INTO IsoLanguagesDes VALUES (439,'ara','Tsonga');
INSERT INTO IsoLanguagesDes VALUES (440,'ara','Turkmen');
INSERT INTO IsoLanguagesDes VALUES (441,'ara','Tumbuka');
INSERT INTO IsoLanguagesDes VALUES (442,'ara','Tupi languages');
INSERT INTO IsoLanguagesDes VALUES (443,'ara','Turkish');
INSERT INTO IsoLanguagesDes VALUES (444,'ara','Altaic (Other)');
INSERT INTO IsoLanguagesDes VALUES (445,'ara','Tuvalu');
INSERT INTO IsoLanguagesDes VALUES (446,'ara','Twi');
INSERT INTO IsoLanguagesDes VALUES (447,'ara','Tuvinian');
INSERT INTO IsoLanguagesDes VALUES (448,'ara','Udmurt');
INSERT INTO IsoLanguagesDes VALUES (449,'ara','Ugaritic');
INSERT INTO IsoLanguagesDes VALUES (450,'ara','Uighur; Uyghur');
INSERT INTO IsoLanguagesDes VALUES (451,'ara','Ukrainian');
INSERT INTO IsoLanguagesDes VALUES (452,'ara','Umbundu');
INSERT INTO IsoLanguagesDes VALUES (453,'ara','Undetermined');
INSERT INTO IsoLanguagesDes VALUES (454,'ara','Urdu');
INSERT INTO IsoLanguagesDes VALUES (455,'ara','Uzbek');
INSERT INTO IsoLanguagesDes VALUES (456,'ara','Vai');
INSERT INTO IsoLanguagesDes VALUES (457,'ara','Venda');
INSERT INTO IsoLanguagesDes VALUES (458,'ara','Vietnamese');
INSERT INTO IsoLanguagesDes VALUES (459,'ara','Volapük');
INSERT INTO IsoLanguagesDes VALUES (460,'ara','Votic');
INSERT INTO IsoLanguagesDes VALUES (461,'ara','Wakashan languages');
INSERT INTO IsoLanguagesDes VALUES (462,'ara','Walamo');
INSERT INTO IsoLanguagesDes VALUES (463,'ara','Waray');
INSERT INTO IsoLanguagesDes VALUES (464,'ara','Washo');
INSERT INTO IsoLanguagesDes VALUES (465,'ara','Welsh');
INSERT INTO IsoLanguagesDes VALUES (466,'ara','Sorbian languages');
INSERT INTO IsoLanguagesDes VALUES (467,'ara','Walloon');
INSERT INTO IsoLanguagesDes VALUES (468,'ara','Wolof');
INSERT INTO IsoLanguagesDes VALUES (469,'ara','Kalmyk; Oirat');
INSERT INTO IsoLanguagesDes VALUES (470,'ara','Xhosa');
INSERT INTO IsoLanguagesDes VALUES (471,'ara','Yao');
INSERT INTO IsoLanguagesDes VALUES (472,'ara','Yapese');
INSERT INTO IsoLanguagesDes VALUES (473,'ara','Yiddish');
INSERT INTO IsoLanguagesDes VALUES (474,'ara','Yoruba');
INSERT INTO IsoLanguagesDes VALUES (475,'ara','Yupik languages');
INSERT INTO IsoLanguagesDes VALUES (476,'ara','Zapotec');
INSERT INTO IsoLanguagesDes VALUES (477,'ara','Zenaga');
INSERT INTO IsoLanguagesDes VALUES (478,'ara','Zhuang; Chuang');
INSERT INTO IsoLanguagesDes VALUES (479,'ara','Zande languages');
INSERT INTO IsoLanguagesDes VALUES (480,'ara','Zulu');
INSERT INTO IsoLanguagesDes VALUES (481,'ara','Zuni');
INSERT INTO IsoLanguagesDes VALUES (482,'ara','No linguistic content');
INSERT INTO IsoLanguagesDes VALUES (483,'ara','N''Ko');
INSERT INTO IsoLanguagesDes VALUES (484,'ara','Zaza; Dimili; Dimli; Kirdki; Kirmanjki');

INSERT INTO OperationsDes VALUES (0,'ara','Publish');
INSERT INTO OperationsDes VALUES (1,'ara','Download');
INSERT INTO OperationsDes VALUES (2,'ara','Editing');
INSERT INTO OperationsDes VALUES (3,'ara','Notify');
INSERT INTO OperationsDes VALUES (5,'ara','Interactive Map');
INSERT INTO OperationsDes VALUES (6,'ara','Featured');

INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (0,'ara','Unknown');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (1,'ara','Draft');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (2,'ara','Approved');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (3,'ara','Retired');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (4,'ara','Submitted');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (5,'ara','Rejected');

INSERT INTO RegionsDes VALUES (1,'ara','Armenia');
INSERT INTO RegionsDes VALUES (2,'ara','Afghanistan');
INSERT INTO RegionsDes VALUES (3,'ara','Albania');
INSERT INTO RegionsDes VALUES (4,'ara','Algeria');
INSERT INTO RegionsDes VALUES (5,'ara','American Samoa');
INSERT INTO RegionsDes VALUES (6,'ara','Andorra');
INSERT INTO RegionsDes VALUES (7,'ara','Angola');
INSERT INTO RegionsDes VALUES (8,'ara','Antigua and Barbuda');
INSERT INTO RegionsDes VALUES (9,'ara','Argentina');
INSERT INTO RegionsDes VALUES (10,'ara','Australia');
INSERT INTO RegionsDes VALUES (11,'ara','Austria');
INSERT INTO RegionsDes VALUES (12,'ara','Bahamas');
INSERT INTO RegionsDes VALUES (13,'ara','Bahrain');
INSERT INTO RegionsDes VALUES (14,'ara','Barbados');
INSERT INTO RegionsDes VALUES (16,'ara','Bangladesh');
INSERT INTO RegionsDes VALUES (17,'ara','Bermuda');
INSERT INTO RegionsDes VALUES (18,'ara','Bhutan');
INSERT INTO RegionsDes VALUES (19,'ara','Bolivia');
INSERT INTO RegionsDes VALUES (20,'ara','Botswana');
INSERT INTO RegionsDes VALUES (21,'ara','Brazil');
INSERT INTO RegionsDes VALUES (22,'ara','Aruba');
INSERT INTO RegionsDes VALUES (23,'ara','Belize');
INSERT INTO RegionsDes VALUES (24,'ara','British Indian Ocean Ter');
INSERT INTO RegionsDes VALUES (25,'ara','Solomon Islands');
INSERT INTO RegionsDes VALUES (26,'ara','Brunei Darussalam');
INSERT INTO RegionsDes VALUES (27,'ara','Bulgaria');
INSERT INTO RegionsDes VALUES (28,'ara','Myanmar');
INSERT INTO RegionsDes VALUES (29,'ara','Burundi');
INSERT INTO RegionsDes VALUES (30,'ara','Antarctica');
INSERT INTO RegionsDes VALUES (31,'ara','Bouvet Island');
INSERT INTO RegionsDes VALUES (32,'ara','Cameroon');
INSERT INTO RegionsDes VALUES (33,'ara','Canada');
INSERT INTO RegionsDes VALUES (35,'ara','Cape Verde');
INSERT INTO RegionsDes VALUES (36,'ara','Cayman Island');
INSERT INTO RegionsDes VALUES (37,'ara','Central African Republic');
INSERT INTO RegionsDes VALUES (38,'ara','Sri Lanka');
INSERT INTO RegionsDes VALUES (39,'ara','Chad');
INSERT INTO RegionsDes VALUES (40,'ara','Chile');
INSERT INTO RegionsDes VALUES (41,'ara','China, Mainland');
INSERT INTO RegionsDes VALUES (42,'ara','Christmas Island');
INSERT INTO RegionsDes VALUES (43,'ara','Cocos Islands');
INSERT INTO RegionsDes VALUES (44,'ara','Colombia');
INSERT INTO RegionsDes VALUES (45,'ara','Comoros');
INSERT INTO RegionsDes VALUES (46,'ara','Congo, Republic of');
INSERT INTO RegionsDes VALUES (47,'ara','Cook Islands');
INSERT INTO RegionsDes VALUES (48,'ara','Costa Rica');
INSERT INTO RegionsDes VALUES (49,'ara','Cuba');
INSERT INTO RegionsDes VALUES (50,'ara','Cyprus');
INSERT INTO RegionsDes VALUES (52,'ara','Azerbaijan, Republic of');
INSERT INTO RegionsDes VALUES (53,'ara','Benin');
INSERT INTO RegionsDes VALUES (54,'ara','Denmark');
INSERT INTO RegionsDes VALUES (55,'ara','Dominica');
INSERT INTO RegionsDes VALUES (56,'ara','Dominican Republic');
INSERT INTO RegionsDes VALUES (57,'ara','Belarus');
INSERT INTO RegionsDes VALUES (58,'ara','Ecuador');
INSERT INTO RegionsDes VALUES (59,'ara','Egypt');
INSERT INTO RegionsDes VALUES (60,'ara','El Salvador');
INSERT INTO RegionsDes VALUES (61,'ara','Equatorial Guinea');
INSERT INTO RegionsDes VALUES (63,'ara','Estonia');
INSERT INTO RegionsDes VALUES (64,'ara','Faeroe Islands');
INSERT INTO RegionsDes VALUES (65,'ara','Falkland Islands');
INSERT INTO RegionsDes VALUES (66,'ara','Fiji Islands');
INSERT INTO RegionsDes VALUES (67,'ara','Finland');
INSERT INTO RegionsDes VALUES (68,'ara','France');
INSERT INTO RegionsDes VALUES (69,'ara','French Guiana');
INSERT INTO RegionsDes VALUES (70,'ara','French Polynesia');
INSERT INTO RegionsDes VALUES (71,'ara','French South Terr');
INSERT INTO RegionsDes VALUES (72,'ara','Djibouti');
INSERT INTO RegionsDes VALUES (73,'ara','Georgia');
INSERT INTO RegionsDes VALUES (74,'ara','Gabon');
INSERT INTO RegionsDes VALUES (75,'ara','Gambia');
INSERT INTO RegionsDes VALUES (76,'ara','Gaza Strip');
INSERT INTO RegionsDes VALUES (79,'ara','Germany');
INSERT INTO RegionsDes VALUES (80,'ara','Bosnia and Herzegovina');
INSERT INTO RegionsDes VALUES (81,'ara','Ghana');
INSERT INTO RegionsDes VALUES (82,'ara','Gibraltar');
INSERT INTO RegionsDes VALUES (83,'ara','Kiribati');
INSERT INTO RegionsDes VALUES (84,'ara','Greece');
INSERT INTO RegionsDes VALUES (85,'ara','Greenland');
INSERT INTO RegionsDes VALUES (86,'ara','Grenada');
INSERT INTO RegionsDes VALUES (87,'ara','Guadeloupe');
INSERT INTO RegionsDes VALUES (88,'ara','Guam');
INSERT INTO RegionsDes VALUES (89,'ara','Guatemala');
INSERT INTO RegionsDes VALUES (90,'ara','Guinea');
INSERT INTO RegionsDes VALUES (91,'ara','Guyana');
INSERT INTO RegionsDes VALUES (92,'ara','Heard and McDonald Is');
INSERT INTO RegionsDes VALUES (93,'ara','Haiti');
INSERT INTO RegionsDes VALUES (95,'ara','Honduras');
INSERT INTO RegionsDes VALUES (97,'ara','Hungary');
INSERT INTO RegionsDes VALUES (98,'ara','Croatia');
INSERT INTO RegionsDes VALUES (99,'ara','Iceland');
INSERT INTO RegionsDes VALUES (100,'ara','India');
INSERT INTO RegionsDes VALUES (101,'ara','Indonesia');
INSERT INTO RegionsDes VALUES (102,'ara','Iran, Islamic Rep of');
INSERT INTO RegionsDes VALUES (103,'ara','Iraq');
INSERT INTO RegionsDes VALUES (104,'ara','Ireland');
INSERT INTO RegionsDes VALUES (105,'ara','Israel');
INSERT INTO RegionsDes VALUES (106,'ara','Italy');
INSERT INTO RegionsDes VALUES (107,'ara','Ivory Coast');
INSERT INTO RegionsDes VALUES (108,'ara','Kazakhstan');
INSERT INTO RegionsDes VALUES (109,'ara','Jamaica');
INSERT INTO RegionsDes VALUES (110,'ara','Japan');
INSERT INTO RegionsDes VALUES (112,'ara','Jordan');
INSERT INTO RegionsDes VALUES (113,'ara','Kyrgyzstan');
INSERT INTO RegionsDes VALUES (114,'ara','Kenya');
INSERT INTO RegionsDes VALUES (115,'ara','Cambodia');
INSERT INTO RegionsDes VALUES (116,'ara','Korea, Dem People''s Rep');
INSERT INTO RegionsDes VALUES (117,'ara','Korea, Republic of');
INSERT INTO RegionsDes VALUES (118,'ara','Kuwait');
INSERT INTO RegionsDes VALUES (119,'ara','Latvia');
INSERT INTO RegionsDes VALUES (120,'ara','Laos');
INSERT INTO RegionsDes VALUES (121,'ara','Lebanon');
INSERT INTO RegionsDes VALUES (122,'ara','Lesotho');
INSERT INTO RegionsDes VALUES (123,'ara','Liberia');
INSERT INTO RegionsDes VALUES (124,'ara','Libyan Arab Jamahiriya');
INSERT INTO RegionsDes VALUES (125,'ara','Liechtensten');
INSERT INTO RegionsDes VALUES (126,'ara','Lithuania');
INSERT INTO RegionsDes VALUES (127,'ara','Marshall Island');
INSERT INTO RegionsDes VALUES (129,'ara','Madagascar');
INSERT INTO RegionsDes VALUES (130,'ara','Malawi');
INSERT INTO RegionsDes VALUES (131,'ara','Malaysia');
INSERT INTO RegionsDes VALUES (132,'ara','Maldives');
INSERT INTO RegionsDes VALUES (133,'ara','Mali');
INSERT INTO RegionsDes VALUES (134,'ara','Malta');
INSERT INTO RegionsDes VALUES (135,'ara','Martinique');
INSERT INTO RegionsDes VALUES (136,'ara','Mauritania');
INSERT INTO RegionsDes VALUES (137,'ara','Mauritius');
INSERT INTO RegionsDes VALUES (138,'ara','Mexico');
INSERT INTO RegionsDes VALUES (139,'ara','Midway Islands');
INSERT INTO RegionsDes VALUES (140,'ara','Monaco');
INSERT INTO RegionsDes VALUES (141,'ara','Mongolia');
INSERT INTO RegionsDes VALUES (142,'ara','Montserrat');
INSERT INTO RegionsDes VALUES (143,'ara','Morocco');
INSERT INTO RegionsDes VALUES (144,'ara','Mozambique');
INSERT INTO RegionsDes VALUES (145,'ara','Micronesia,Fed States of');
INSERT INTO RegionsDes VALUES (146,'ara','Moldova, Republic of');
INSERT INTO RegionsDes VALUES (147,'ara','Namibia');
INSERT INTO RegionsDes VALUES (148,'ara','Nauru');
INSERT INTO RegionsDes VALUES (149,'ara','Nepal');
INSERT INTO RegionsDes VALUES (150,'ara','Netherlands');
INSERT INTO RegionsDes VALUES (151,'ara','Neth Antilles');
INSERT INTO RegionsDes VALUES (153,'ara','NewCaledonia');
INSERT INTO RegionsDes VALUES (154,'ara','Macedonia');
INSERT INTO RegionsDes VALUES (155,'ara','Vanuatu');
INSERT INTO RegionsDes VALUES (156,'ara','New Zealand');
INSERT INTO RegionsDes VALUES (157,'ara','Nicaragua');
INSERT INTO RegionsDes VALUES (158,'ara','Niger');
INSERT INTO RegionsDes VALUES (159,'ara','Nigeria');
INSERT INTO RegionsDes VALUES (160,'ara','Niue');
INSERT INTO RegionsDes VALUES (161,'ara','Norfolk Island');
INSERT INTO RegionsDes VALUES (162,'ara','Norway');
INSERT INTO RegionsDes VALUES (163,'ara','Northern Mariana Is');
INSERT INTO RegionsDes VALUES (165,'ara','Pakistan');
INSERT INTO RegionsDes VALUES (166,'ara','Panama');
INSERT INTO RegionsDes VALUES (167,'ara','Czech Republic');
INSERT INTO RegionsDes VALUES (168,'ara','Papua New Guinea');
INSERT INTO RegionsDes VALUES (169,'ara','Paraguay');
INSERT INTO RegionsDes VALUES (170,'ara','Peru');
INSERT INTO RegionsDes VALUES (171,'ara','Philippines');
INSERT INTO RegionsDes VALUES (172,'ara','Pitcairn Islands');
INSERT INTO RegionsDes VALUES (173,'ara','Poland');
INSERT INTO RegionsDes VALUES (174,'ara','Portugal');
INSERT INTO RegionsDes VALUES (175,'ara','Guinea-Bissau');
INSERT INTO RegionsDes VALUES (176,'ara','East Timor');
INSERT INTO RegionsDes VALUES (177,'ara','Puerto Rico');
INSERT INTO RegionsDes VALUES (178,'ara','Eritrea');
INSERT INTO RegionsDes VALUES (179,'ara','Qatar');
INSERT INTO RegionsDes VALUES (181,'ara','Zimbabwe');
INSERT INTO RegionsDes VALUES (182,'ara','Reunion');
INSERT INTO RegionsDes VALUES (183,'ara','Romania');
INSERT INTO RegionsDes VALUES (184,'ara','Rwanda');
INSERT INTO RegionsDes VALUES (185,'ara','Russian Federation');
INSERT INTO RegionsDes VALUES (187,'ara','Saint Helena');
INSERT INTO RegionsDes VALUES (188,'ara','Saint Kitts and Nevis');
INSERT INTO RegionsDes VALUES (189,'ara','Saint Lucia');
INSERT INTO RegionsDes VALUES (190,'ara','Saint Pierre & Miquelon');
INSERT INTO RegionsDes VALUES (191,'ara','Saint Vincent/Grenadines');
INSERT INTO RegionsDes VALUES (192,'ara','San Marino');
INSERT INTO RegionsDes VALUES (193,'ara','Sao Tome and Principe');
INSERT INTO RegionsDes VALUES (194,'ara','Saudi Arabia');
INSERT INTO RegionsDes VALUES (195,'ara','Senegal');
INSERT INTO RegionsDes VALUES (196,'ara','Seychelles');
INSERT INTO RegionsDes VALUES (197,'ara','Sierra Leone');
INSERT INTO RegionsDes VALUES (198,'ara','Slovenia');
INSERT INTO RegionsDes VALUES (199,'ara','Slovakia');
INSERT INTO RegionsDes VALUES (200,'ara','Singapore');
INSERT INTO RegionsDes VALUES (201,'ara','Somalia');
INSERT INTO RegionsDes VALUES (202,'ara','South Africa');
INSERT INTO RegionsDes VALUES (203,'ara','Spain');
INSERT INTO RegionsDes VALUES (205,'ara','Western Sahara');
INSERT INTO RegionsDes VALUES (206,'ara','Sudan');
INSERT INTO RegionsDes VALUES (207,'ara','Suriname');
INSERT INTO RegionsDes VALUES (208,'ara','Tajikistan');
INSERT INTO RegionsDes VALUES (209,'ara','Swaziland');
INSERT INTO RegionsDes VALUES (210,'ara','Sweden');
INSERT INTO RegionsDes VALUES (211,'ara','Switzerland');
INSERT INTO RegionsDes VALUES (212,'ara','Syrian Arab Republic');
INSERT INTO RegionsDes VALUES (213,'ara','Turkmenistan');
INSERT INTO RegionsDes VALUES (214,'ara','China, Taiwan Prov of');
INSERT INTO RegionsDes VALUES (215,'ara','Tanzania, United Rep of');
INSERT INTO RegionsDes VALUES (216,'ara','Thailand');
INSERT INTO RegionsDes VALUES (217,'ara','Togo');
INSERT INTO RegionsDes VALUES (218,'ara','Tokelau');
INSERT INTO RegionsDes VALUES (219,'ara','Tonga');
INSERT INTO RegionsDes VALUES (220,'ara','Trinidad and Tobago');
INSERT INTO RegionsDes VALUES (221,'ara','Oman');
INSERT INTO RegionsDes VALUES (222,'ara','Tunisia');
INSERT INTO RegionsDes VALUES (223,'ara','Turkey');
INSERT INTO RegionsDes VALUES (224,'ara','Turks and Caicos Is');
INSERT INTO RegionsDes VALUES (225,'ara','United Arab Emirates');
INSERT INTO RegionsDes VALUES (226,'ara','Uganda');
INSERT INTO RegionsDes VALUES (227,'ara','Tuvalu');
INSERT INTO RegionsDes VALUES (229,'ara','United Kingdom');
INSERT INTO RegionsDes VALUES (230,'ara','Ukraine');
INSERT INTO RegionsDes VALUES (231,'ara','United States of America');
INSERT INTO RegionsDes VALUES (232,'ara','US Minor Outlying Is');
INSERT INTO RegionsDes VALUES (233,'ara','Burkina Faso');
INSERT INTO RegionsDes VALUES (234,'ara','Uruguay');
INSERT INTO RegionsDes VALUES (235,'ara','Uzbekistan');
INSERT INTO RegionsDes VALUES (236,'ara','Venezuela');
INSERT INTO RegionsDes VALUES (237,'ara','Viet Nam');
INSERT INTO RegionsDes VALUES (238,'ara','Ethiopia');
INSERT INTO RegionsDes VALUES (239,'ara','British Virgin Island');
INSERT INTO RegionsDes VALUES (240,'ara','US Virgin Islands');
INSERT INTO RegionsDes VALUES (242,'ara','Wake Island');
INSERT INTO RegionsDes VALUES (243,'ara','Wallis and Futuna Is');
INSERT INTO RegionsDes VALUES (244,'ara','Samoa');
INSERT INTO RegionsDes VALUES (245,'ara','West Bank');
INSERT INTO RegionsDes VALUES (249,'ara','Yemen');
INSERT INTO RegionsDes VALUES (250,'ara','Congo, Dem Republic of');
INSERT INTO RegionsDes VALUES (251,'ara','Zambia');
INSERT INTO RegionsDes VALUES (255,'ara','Belgium');
INSERT INTO RegionsDes VALUES (256,'ara','Luxembourg');
INSERT INTO RegionsDes VALUES (258,'ara','Anguilla');
INSERT INTO RegionsDes VALUES (260,'ara','Svalbard Is');
INSERT INTO RegionsDes VALUES (264,'ara','Isle of Man');
INSERT INTO RegionsDes VALUES (270,'ara','Mayotte');
INSERT INTO RegionsDes VALUES (271,'ara','SouthGeorgia/Sandwich Is');
INSERT INTO RegionsDes VALUES (303,'ara','Western Europe');
INSERT INTO RegionsDes VALUES (307,'ara','Intergvt Author Devpment');
INSERT INTO RegionsDes VALUES (310,'ara','North Western Africa');
INSERT INTO RegionsDes VALUES (311,'ara','Western Africa');
INSERT INTO RegionsDes VALUES (312,'ara','Central Africa');
INSERT INTO RegionsDes VALUES (313,'ara','Eastern Africa');
INSERT INTO RegionsDes VALUES (314,'ara','Southern Africa');
INSERT INTO RegionsDes VALUES (315,'ara','Latin Amer & Caribbean');
INSERT INTO RegionsDes VALUES (316,'ara','Central America');
INSERT INTO RegionsDes VALUES (317,'ara','Caribbean');
INSERT INTO RegionsDes VALUES (318,'ara','South America');
INSERT INTO RegionsDes VALUES (319,'ara','Near East');
INSERT INTO RegionsDes VALUES (320,'ara','Near East in Africa');
INSERT INTO RegionsDes VALUES (321,'ara','Near East in Asia');
INSERT INTO RegionsDes VALUES (322,'ara','Far East');
INSERT INTO RegionsDes VALUES (323,'ara','South Asia');
INSERT INTO RegionsDes VALUES (324,'ara','East & South East Asia');
INSERT INTO RegionsDes VALUES (325,'ara','Near East and North Africa');
INSERT INTO RegionsDes VALUES (334,'ara','Eastern Europe');
INSERT INTO RegionsDes VALUES (335,'ara','Europe');
INSERT INTO RegionsDes VALUES (337,'ara','Asia');
INSERT INTO RegionsDes VALUES (338,'ara','Africa');
INSERT INTO RegionsDes VALUES (348,'ara','Latin America');
INSERT INTO RegionsDes VALUES (370,'ara','Serbia');
INSERT INTO RegionsDes VALUES (371,'ara','Montenegro');
INSERT INTO RegionsDes VALUES (390,'ara','South of Sahara');
INSERT INTO RegionsDes VALUES (421,'ara','North Africa');
INSERT INTO RegionsDes VALUES (427,'ara','Europe, Non-EU Countries');
INSERT INTO RegionsDes VALUES (428,'ara','North America');
INSERT INTO RegionsDes VALUES (469,'ara','USSR, Former Area of');
INSERT INTO RegionsDes VALUES (1008,'ara','Arctic Sea');
INSERT INTO RegionsDes VALUES (1009,'ara','Atlantic, Northwest');
INSERT INTO RegionsDes VALUES (1010,'ara','Atlantic, Northeast');
INSERT INTO RegionsDes VALUES (1011,'ara','Atlantic, Western Central');
INSERT INTO RegionsDes VALUES (1012,'ara','Atlantic, Eastern Central');
INSERT INTO RegionsDes VALUES (1013,'ara','Mediterran and Black Sea');
INSERT INTO RegionsDes VALUES (1014,'ara','Atlantic, Southwest');
INSERT INTO RegionsDes VALUES (1015,'ara','Atlantic, Southeast');
INSERT INTO RegionsDes VALUES (1016,'ara','Atlantic, Antarctic');
INSERT INTO RegionsDes VALUES (1017,'ara','Indian Ocean, Western');
INSERT INTO RegionsDes VALUES (1018,'ara','Indian Ocean, Eastern');
INSERT INTO RegionsDes VALUES (1019,'ara','Indian Ocean, Antarctic');
INSERT INTO RegionsDes VALUES (1020,'ara','Pacific, Northwest');
INSERT INTO RegionsDes VALUES (1021,'ara','Pacific, Northeast');
INSERT INTO RegionsDes VALUES (1022,'ara','Pacific, Western Central');
INSERT INTO RegionsDes VALUES (1023,'ara','Pacific, Eastern Central');
INSERT INTO RegionsDes VALUES (1024,'ara','Pacific, Southwest');
INSERT INTO RegionsDes VALUES (1025,'ara','Pacific, Southeast');
INSERT INTO RegionsDes VALUES (1026,'ara','Pacific, Antarctic');
INSERT INTO RegionsDes VALUES (1220,'ara','All fishing areas');
INSERT INTO RegionsDes VALUES (9999,'ara','World');
