-- ISO 3 letter code migration
INSERT INTO Languages VALUES ('vie','Tiếng Việt', 'n', 'n');

UPDATE CategoriesDes             SET langid='vie' WHERE langid='vi';
UPDATE IsoLanguagesDes           SET langid='vie' WHERE langid='vi';
UPDATE RegionsDes                SET langid='vie' WHERE langid='vi';
UPDATE GroupsDes                 SET langid='vie' WHERE langid='vi';
UPDATE OperationsDes             SET langid='vie' WHERE langid='vi';
UPDATE StatusValuesDes           SET langid='vie' WHERE langid='vi';
UPDATE CswServerCapabilitiesInfo SET langid='vie' WHERE langid='vi';
DELETE FROM Languages WHERE id='vi';

-- Take care to table ID (related to other loc files)
INSERT INTO CswServerCapabilitiesInfo VALUES (45, 'vie', 'title', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (46, 'vie', 'abstract', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (47, 'vie', 'fees', '');
INSERT INTO CswServerCapabilitiesInfo VALUES (48, 'vie', 'accessConstraints', '');

INSERT INTO CategoriesDes (iddes, langid, label) VALUES (1,'vie','Maps & graphics');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (2,'vie','Datasets');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (3,'vie','Interactive resources');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (4,'vie','Applications');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (5,'vie','Case studies, best practices');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (6,'vie','Conference proceedings');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (7,'vie','Photo');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (8,'vie','Audio/Video');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (9,'vie','Directories');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (10,'vie','Other information resources');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (11,'vie','Z3950 Servers');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (12,'vie','Registers');
INSERT INTO CategoriesDes (iddes, langid, label) VALUES (13,'vie','Physical Samples');

INSERT INTO GroupsDes (iddes, langid, label) VALUES (-1,'vie','Guest');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (0,'vie','Intranet');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (1,'vie','All');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (2,'vie','Sample group');

INSERT INTO IsoLanguagesDes VALUES (1,'vie','Afar');
INSERT INTO IsoLanguagesDes VALUES (2,'vie','Abkhazian');
INSERT INTO IsoLanguagesDes VALUES (3,'vie','Achinese');
INSERT INTO IsoLanguagesDes VALUES (4,'vie','Acoli');
INSERT INTO IsoLanguagesDes VALUES (5,'vie','Adangme');
INSERT INTO IsoLanguagesDes VALUES (6,'vie','Adyghe; Adygei');
INSERT INTO IsoLanguagesDes VALUES (7,'vie','Afro-Asiatic (Other)');
INSERT INTO IsoLanguagesDes VALUES (8,'vie','Afrihili');
INSERT INTO IsoLanguagesDes VALUES (9,'vie','Afrikaans');
INSERT INTO IsoLanguagesDes VALUES (10,'vie','Ainu');
INSERT INTO IsoLanguagesDes VALUES (11,'vie','Akan');
INSERT INTO IsoLanguagesDes VALUES (12,'vie','Akkadian');
INSERT INTO IsoLanguagesDes VALUES (13,'vie','Albanian');
INSERT INTO IsoLanguagesDes VALUES (14,'vie','Aleut');
INSERT INTO IsoLanguagesDes VALUES (15,'vie','Algonquian languages');
INSERT INTO IsoLanguagesDes VALUES (16,'vie','Southern Altai');
INSERT INTO IsoLanguagesDes VALUES (17,'vie','Amharic');
INSERT INTO IsoLanguagesDes VALUES (18,'vie','English, Old (ca.450-1100)');
INSERT INTO IsoLanguagesDes VALUES (19,'vie','Angika');
INSERT INTO IsoLanguagesDes VALUES (20,'vie','Apache languages');
INSERT INTO IsoLanguagesDes VALUES (21,'vie','Arabic');
INSERT INTO IsoLanguagesDes VALUES (22,'vie','Aramaic');
INSERT INTO IsoLanguagesDes VALUES (23,'vie','Aragonese');
INSERT INTO IsoLanguagesDes VALUES (24,'vie','Armenian');
INSERT INTO IsoLanguagesDes VALUES (25,'vie','Mapudungun; Mapuche');
INSERT INTO IsoLanguagesDes VALUES (26,'vie','Arapaho');
INSERT INTO IsoLanguagesDes VALUES (27,'vie','Artificial (Other)');
INSERT INTO IsoLanguagesDes VALUES (28,'vie','Arawak');
INSERT INTO IsoLanguagesDes VALUES (29,'vie','Assamese');
INSERT INTO IsoLanguagesDes VALUES (30,'vie','Asturian; Bable');
INSERT INTO IsoLanguagesDes VALUES (31,'vie','Athapascan languages');
INSERT INTO IsoLanguagesDes VALUES (32,'vie','Australian languages');
INSERT INTO IsoLanguagesDes VALUES (33,'vie','Avaric');
INSERT INTO IsoLanguagesDes VALUES (34,'vie','Avestan');
INSERT INTO IsoLanguagesDes VALUES (35,'vie','Awadhi');
INSERT INTO IsoLanguagesDes VALUES (36,'vie','Aymara');
INSERT INTO IsoLanguagesDes VALUES (37,'vie','Azerbaijani');
INSERT INTO IsoLanguagesDes VALUES (38,'vie','Banda languages');
INSERT INTO IsoLanguagesDes VALUES (39,'vie','Bamileke languages');
INSERT INTO IsoLanguagesDes VALUES (40,'vie','Bashkir');
INSERT INTO IsoLanguagesDes VALUES (41,'vie','Baluchi');
INSERT INTO IsoLanguagesDes VALUES (42,'vie','Bambara');
INSERT INTO IsoLanguagesDes VALUES (43,'vie','Balinese');
INSERT INTO IsoLanguagesDes VALUES (44,'vie','Basque');
INSERT INTO IsoLanguagesDes VALUES (45,'vie','Basa');
INSERT INTO IsoLanguagesDes VALUES (46,'vie','Baltic (Other)');
INSERT INTO IsoLanguagesDes VALUES (47,'vie','Beja');
INSERT INTO IsoLanguagesDes VALUES (48,'vie','Belarusian');
INSERT INTO IsoLanguagesDes VALUES (49,'vie','Bemba');
INSERT INTO IsoLanguagesDes VALUES (50,'vie','Bengali');
INSERT INTO IsoLanguagesDes VALUES (51,'vie','Berber (Other)');
INSERT INTO IsoLanguagesDes VALUES (52,'vie','Bhojpuri');
INSERT INTO IsoLanguagesDes VALUES (53,'vie','Bihari');
INSERT INTO IsoLanguagesDes VALUES (54,'vie','Bikol');
INSERT INTO IsoLanguagesDes VALUES (55,'vie','Bini; Edo');
INSERT INTO IsoLanguagesDes VALUES (56,'vie','Bislama');
INSERT INTO IsoLanguagesDes VALUES (57,'vie','Siksika');
INSERT INTO IsoLanguagesDes VALUES (58,'vie','Bantu (Other)');
INSERT INTO IsoLanguagesDes VALUES (59,'vie','Bosnian');
INSERT INTO IsoLanguagesDes VALUES (60,'vie','Braj');
INSERT INTO IsoLanguagesDes VALUES (61,'vie','Breton');
INSERT INTO IsoLanguagesDes VALUES (62,'vie','Batak languages');
INSERT INTO IsoLanguagesDes VALUES (63,'vie','Buriat');
INSERT INTO IsoLanguagesDes VALUES (64,'vie','Buginese');
INSERT INTO IsoLanguagesDes VALUES (65,'vie','Bulgarian');
INSERT INTO IsoLanguagesDes VALUES (66,'vie','Burmese');
INSERT INTO IsoLanguagesDes VALUES (67,'vie','Blin; Bilin');
INSERT INTO IsoLanguagesDes VALUES (68,'vie','Caddo');
INSERT INTO IsoLanguagesDes VALUES (69,'vie','Central American Indian (Other)');
INSERT INTO IsoLanguagesDes VALUES (70,'vie','Galibi Carib');
INSERT INTO IsoLanguagesDes VALUES (71,'vie','Catalan; Valencian');
INSERT INTO IsoLanguagesDes VALUES (72,'vie','Caucasian (Other)on liturgique; vieux bulgare');
INSERT INTO IsoLanguagesDes VALUES (73,'vie','Cebuano');
INSERT INTO IsoLanguagesDes VALUES (74,'vie','Celtic (Other)');
INSERT INTO IsoLanguagesDes VALUES (75,'vie','Chamorro');
INSERT INTO IsoLanguagesDes VALUES (76,'vie','Chibcha');
INSERT INTO IsoLanguagesDes VALUES (77,'vie','Chechen');
INSERT INTO IsoLanguagesDes VALUES (78,'vie','Chagataier)');
INSERT INTO IsoLanguagesDes VALUES (79,'vie','Chinese(Other)');
INSERT INTO IsoLanguagesDes VALUES (80,'vie','Chuukese');
INSERT INTO IsoLanguagesDes VALUES (81,'vie','Mari');
INSERT INTO IsoLanguagesDes VALUES (82,'vie','Chinook jargon');
INSERT INTO IsoLanguagesDes VALUES (83,'vie','Choctaw');
INSERT INTO IsoLanguagesDes VALUES (84,'vie','Chipewyan');
INSERT INTO IsoLanguagesDes VALUES (85,'vie','Cherokee');
INSERT INTO IsoLanguagesDes VALUES (86,'vie','Church Slavic; Old Slavonic; Church Sl');
INSERT INTO IsoLanguagesDes VALUES (87,'vie','Chuvash');
INSERT INTO IsoLanguagesDes VALUES (88,'vie','Cheyenne');
INSERT INTO IsoLanguagesDes VALUES (89,'vie','Chamic languages');
INSERT INTO IsoLanguagesDes VALUES (90,'vie','Coptic');
INSERT INTO IsoLanguagesDes VALUES (91,'vie','Cornish');
INSERT INTO IsoLanguagesDes VALUES (92,'vie','Corsican');
INSERT INTO IsoLanguagesDes VALUES (93,'vie','Creoles and pidgins, English based (Ot');
INSERT INTO IsoLanguagesDes VALUES (94,'vie','Creoles and pidgins, French-based (Oth');
INSERT INTO IsoLanguagesDes VALUES (95,'vie','Creoles and pidgins, Portuguese-based ');
INSERT INTO IsoLanguagesDes VALUES (96,'vie','Cree');
INSERT INTO IsoLanguagesDes VALUES (97,'vie','Crimean Tatar; Crimean Turkish');
INSERT INTO IsoLanguagesDes VALUES (98,'vie','Creoles and pidgins (Other)');
INSERT INTO IsoLanguagesDes VALUES (99,'vie','Kashubian');
INSERT INTO IsoLanguagesDes VALUES (100,'vie','Cushitic (Other)');
INSERT INTO IsoLanguagesDes VALUES (101,'vie','Czech');
INSERT INTO IsoLanguagesDes VALUES (102,'vie','Dakota');
INSERT INTO IsoLanguagesDes VALUES (103,'vie','Danish');
INSERT INTO IsoLanguagesDes VALUES (104,'vie','Dargwa');
INSERT INTO IsoLanguagesDes VALUES (105,'vie','Land Dayak languages');
INSERT INTO IsoLanguagesDes VALUES (106,'vie','Delaware');
INSERT INTO IsoLanguagesDes VALUES (107,'vie','Slave (Athapascan)');
INSERT INTO IsoLanguagesDes VALUES (108,'vie','Dogrib');
INSERT INTO IsoLanguagesDes VALUES (109,'vie','Dinka');
INSERT INTO IsoLanguagesDes VALUES (110,'vie','Divehi; Dhivehi; Maldivian');
INSERT INTO IsoLanguagesDes VALUES (111,'vie','Dogri');
INSERT INTO IsoLanguagesDes VALUES (112,'vie','Dravidian (Other)');
INSERT INTO IsoLanguagesDes VALUES (113,'vie','Lower Sorbian');
INSERT INTO IsoLanguagesDes VALUES (114,'vie','Duala');
INSERT INTO IsoLanguagesDes VALUES (115,'vie','Dutch, Middle (ca.1050-1350)');
INSERT INTO IsoLanguagesDes VALUES (116,'vie','Dutch; Flemish');
INSERT INTO IsoLanguagesDes VALUES (117,'vie','Dyula');
INSERT INTO IsoLanguagesDes VALUES (118,'vie','Dzongkha');
INSERT INTO IsoLanguagesDes VALUES (119,'vie','Efik');
INSERT INTO IsoLanguagesDes VALUES (120,'vie','Egyptian (Ancient)');
INSERT INTO IsoLanguagesDes VALUES (121,'vie','Ekajuk');
INSERT INTO IsoLanguagesDes VALUES (122,'vie','Elamite');
INSERT INTO IsoLanguagesDes VALUES (123,'vie','English');
INSERT INTO IsoLanguagesDes VALUES (124,'vie','English, Middle (1100-1500)');
INSERT INTO IsoLanguagesDes VALUES (125,'vie','Esperanto');
INSERT INTO IsoLanguagesDes VALUES (126,'vie','Estonian');
INSERT INTO IsoLanguagesDes VALUES (127,'vie','Ewe');
INSERT INTO IsoLanguagesDes VALUES (128,'vie','Ewondo');
INSERT INTO IsoLanguagesDes VALUES (129,'vie','Fang');
INSERT INTO IsoLanguagesDes VALUES (130,'vie','Faroese');
INSERT INTO IsoLanguagesDes VALUES (131,'vie','Fanti');
INSERT INTO IsoLanguagesDes VALUES (132,'vie','Fijian');
INSERT INTO IsoLanguagesDes VALUES (133,'vie','Filipino; Pilipino');
INSERT INTO IsoLanguagesDes VALUES (134,'vie','Finnish');
INSERT INTO IsoLanguagesDes VALUES (135,'vie','Finno-Ugrian (Other)');
INSERT INTO IsoLanguagesDes VALUES (136,'vie','Fon');
INSERT INTO IsoLanguagesDes VALUES (137,'vie','French');
INSERT INTO IsoLanguagesDes VALUES (138,'vie','French, Middle (ca.1400-1600)');
INSERT INTO IsoLanguagesDes VALUES (139,'vie','French, Old (842-ca.1400)');
INSERT INTO IsoLanguagesDes VALUES (140,'vie','Northern Frisian');
INSERT INTO IsoLanguagesDes VALUES (141,'vie','Eastern Frisian');
INSERT INTO IsoLanguagesDes VALUES (142,'vie','Western Frisian');
INSERT INTO IsoLanguagesDes VALUES (143,'vie','Fulah');
INSERT INTO IsoLanguagesDes VALUES (144,'vie','Friulian');
INSERT INTO IsoLanguagesDes VALUES (145,'vie','Ga');
INSERT INTO IsoLanguagesDes VALUES (146,'vie','Gayo');
INSERT INTO IsoLanguagesDes VALUES (147,'vie','Gbaya');
INSERT INTO IsoLanguagesDes VALUES (148,'vie','Germanic (Other)');
INSERT INTO IsoLanguagesDes VALUES (149,'vie','Georgian');
INSERT INTO IsoLanguagesDes VALUES (150,'vie','German');
INSERT INTO IsoLanguagesDes VALUES (151,'vie','Geez');
INSERT INTO IsoLanguagesDes VALUES (152,'vie','Gilbertese');
INSERT INTO IsoLanguagesDes VALUES (153,'vie','Gaelic; Scottish Gaelic');
INSERT INTO IsoLanguagesDes VALUES (154,'vie','Irish');
INSERT INTO IsoLanguagesDes VALUES (155,'vie','Galician');
INSERT INTO IsoLanguagesDes VALUES (156,'vie','Manx');
INSERT INTO IsoLanguagesDes VALUES (157,'vie','German, Middle High (ca.1050-1500)');
INSERT INTO IsoLanguagesDes VALUES (158,'vie','German, Old High (ca.750-1050)');
INSERT INTO IsoLanguagesDes VALUES (159,'vie','Gondi');
INSERT INTO IsoLanguagesDes VALUES (160,'vie','Gorontalo');
INSERT INTO IsoLanguagesDes VALUES (161,'vie','Gothicanguage Association)');
INSERT INTO IsoLanguagesDes VALUES (162,'vie','Grebo');
INSERT INTO IsoLanguagesDes VALUES (163,'vie','Greek, Ancient (to 1453)');
INSERT INTO IsoLanguagesDes VALUES (164,'vie','Greek, Modern (1453-)');
INSERT INTO IsoLanguagesDes VALUES (165,'vie','Guarani');
INSERT INTO IsoLanguagesDes VALUES (166,'vie','Swiss German; Alemannic');
INSERT INTO IsoLanguagesDes VALUES (167,'vie','Gujarati');
INSERT INTO IsoLanguagesDes VALUES (168,'vie','Gwich''in');
INSERT INTO IsoLanguagesDes VALUES (169,'vie','Haida');
INSERT INTO IsoLanguagesDes VALUES (170,'vie','Haitian; Haitian Creole');
INSERT INTO IsoLanguagesDes VALUES (171,'vie','Hausa');
INSERT INTO IsoLanguagesDes VALUES (172,'vie','Hawaiian');
INSERT INTO IsoLanguagesDes VALUES (173,'vie','Hebrew');
INSERT INTO IsoLanguagesDes VALUES (174,'vie','Herero');
INSERT INTO IsoLanguagesDes VALUES (175,'vie','Hiligaynon');
INSERT INTO IsoLanguagesDes VALUES (176,'vie','Himachali');
INSERT INTO IsoLanguagesDes VALUES (177,'vie','Hindi');
INSERT INTO IsoLanguagesDes VALUES (178,'vie','Hittite');
INSERT INTO IsoLanguagesDes VALUES (179,'vie','Hmong');
INSERT INTO IsoLanguagesDes VALUES (180,'vie','Hiri Motu');
INSERT INTO IsoLanguagesDes VALUES (181,'vie','Upper Sorbian');
INSERT INTO IsoLanguagesDes VALUES (182,'vie','Hungarian');
INSERT INTO IsoLanguagesDes VALUES (183,'vie','Hupa');
INSERT INTO IsoLanguagesDes VALUES (184,'vie','Iban');
INSERT INTO IsoLanguagesDes VALUES (185,'vie','Igbo');
INSERT INTO IsoLanguagesDes VALUES (186,'vie','Icelandic');
INSERT INTO IsoLanguagesDes VALUES (187,'vie','Ido');
INSERT INTO IsoLanguagesDes VALUES (188,'vie','Sichuan Yi');
INSERT INTO IsoLanguagesDes VALUES (189,'vie','Ijo languages');
INSERT INTO IsoLanguagesDes VALUES (190,'vie','Inuktitut');
INSERT INTO IsoLanguagesDes VALUES (191,'vie','Interlingue');
INSERT INTO IsoLanguagesDes VALUES (192,'vie','Iloko');
INSERT INTO IsoLanguagesDes VALUES (193,'vie','Interlingua (International Auxiliary L');
INSERT INTO IsoLanguagesDes VALUES (194,'vie','Indic (Other)');
INSERT INTO IsoLanguagesDes VALUES (195,'vie','Indonesian');
INSERT INTO IsoLanguagesDes VALUES (196,'vie','Indo-European (Other)');
INSERT INTO IsoLanguagesDes VALUES (197,'vie','Ingush');
INSERT INTO IsoLanguagesDes VALUES (198,'vie','Inupiaq');
INSERT INTO IsoLanguagesDes VALUES (199,'vie','Iranian (Other)');
INSERT INTO IsoLanguagesDes VALUES (200,'vie','Iroquoian languages');
INSERT INTO IsoLanguagesDes VALUES (201,'vie','Italian');
INSERT INTO IsoLanguagesDes VALUES (202,'vie','Javanese');
INSERT INTO IsoLanguagesDes VALUES (203,'vie','Lojban');
INSERT INTO IsoLanguagesDes VALUES (204,'vie','Japanese');
INSERT INTO IsoLanguagesDes VALUES (205,'vie','Judeo-Persian');
INSERT INTO IsoLanguagesDes VALUES (206,'vie','Judeo-Arabic');
INSERT INTO IsoLanguagesDes VALUES (207,'vie','Kara-Kalpak');
INSERT INTO IsoLanguagesDes VALUES (208,'vie','Kabyle');
INSERT INTO IsoLanguagesDes VALUES (209,'vie','Kachin; Jingpho');
INSERT INTO IsoLanguagesDes VALUES (210,'vie','Kalaallisut; Greenlandic');
INSERT INTO IsoLanguagesDes VALUES (211,'vie','Kamba');
INSERT INTO IsoLanguagesDes VALUES (212,'vie','Kannada');
INSERT INTO IsoLanguagesDes VALUES (213,'vie','Karen languages');
INSERT INTO IsoLanguagesDes VALUES (214,'vie','Kashmiri');
INSERT INTO IsoLanguagesDes VALUES (215,'vie','Kanuri');
INSERT INTO IsoLanguagesDes VALUES (216,'vie','Kawi');
INSERT INTO IsoLanguagesDes VALUES (217,'vie','Kazakh');
INSERT INTO IsoLanguagesDes VALUES (218,'vie','Kabardian');
INSERT INTO IsoLanguagesDes VALUES (219,'vie','Khasi');
INSERT INTO IsoLanguagesDes VALUES (220,'vie','Khoisan (Other)');
INSERT INTO IsoLanguagesDes VALUES (221,'vie','Central Khmer');
INSERT INTO IsoLanguagesDes VALUES (222,'vie','Khotanese');
INSERT INTO IsoLanguagesDes VALUES (223,'vie','Kikuyu; Gikuyu');
INSERT INTO IsoLanguagesDes VALUES (224,'vie','Kinyarwanda');
INSERT INTO IsoLanguagesDes VALUES (225,'vie','Kirghiz; Kyrgyz');
INSERT INTO IsoLanguagesDes VALUES (226,'vie','Kimbundu');
INSERT INTO IsoLanguagesDes VALUES (227,'vie','Konkani');
INSERT INTO IsoLanguagesDes VALUES (228,'vie','Komi');
INSERT INTO IsoLanguagesDes VALUES (229,'vie','Kongo');
INSERT INTO IsoLanguagesDes VALUES (230,'vie','Korean');
INSERT INTO IsoLanguagesDes VALUES (231,'vie','Kosraean');
INSERT INTO IsoLanguagesDes VALUES (232,'vie','Kpelle');
INSERT INTO IsoLanguagesDes VALUES (233,'vie','Karachay-Balkar');
INSERT INTO IsoLanguagesDes VALUES (234,'vie','Karelian');
INSERT INTO IsoLanguagesDes VALUES (235,'vie','Kru languages');
INSERT INTO IsoLanguagesDes VALUES (236,'vie','Kurukh');
INSERT INTO IsoLanguagesDes VALUES (237,'vie','Kuanyama; Kwanyama');
INSERT INTO IsoLanguagesDes VALUES (238,'vie','Kumyk');
INSERT INTO IsoLanguagesDes VALUES (239,'vie','Kurdish');
INSERT INTO IsoLanguagesDes VALUES (240,'vie','Kutenai');
INSERT INTO IsoLanguagesDes VALUES (241,'vie','Ladino');
INSERT INTO IsoLanguagesDes VALUES (242,'vie','Lahnda');
INSERT INTO IsoLanguagesDes VALUES (243,'vie','Lamba');
INSERT INTO IsoLanguagesDes VALUES (244,'vie','Lao');
INSERT INTO IsoLanguagesDes VALUES (245,'vie','Latin');
INSERT INTO IsoLanguagesDes VALUES (246,'vie','Latvian');
INSERT INTO IsoLanguagesDes VALUES (247,'vie','Lezghian');
INSERT INTO IsoLanguagesDes VALUES (248,'vie','Limburgan; Limburger; Limburgish');
INSERT INTO IsoLanguagesDes VALUES (249,'vie','Lingala');
INSERT INTO IsoLanguagesDes VALUES (250,'vie','Lithuanian');
INSERT INTO IsoLanguagesDes VALUES (251,'vie','Mongo');
INSERT INTO IsoLanguagesDes VALUES (252,'vie','Lozi');
INSERT INTO IsoLanguagesDes VALUES (253,'vie','Luxembourgish; Letzeburgesch');
INSERT INTO IsoLanguagesDes VALUES (254,'vie','Luba-Lulua');
INSERT INTO IsoLanguagesDes VALUES (255,'vie','Luba-Katangaxon, Low');
INSERT INTO IsoLanguagesDes VALUES (256,'vie','Ganda');
INSERT INTO IsoLanguagesDes VALUES (257,'vie','Luiseno');
INSERT INTO IsoLanguagesDes VALUES (258,'vie','Lunda');
INSERT INTO IsoLanguagesDes VALUES (259,'vie','Luo (Kenya and Tanzania)');
INSERT INTO IsoLanguagesDes VALUES (260,'vie','Lushai');
INSERT INTO IsoLanguagesDes VALUES (261,'vie','Macedonian00E5l');
INSERT INTO IsoLanguagesDes VALUES (262,'vie','Madurese');
INSERT INTO IsoLanguagesDes VALUES (263,'vie','Magahi');
INSERT INTO IsoLanguagesDes VALUES (264,'vie','Marshallese');
INSERT INTO IsoLanguagesDes VALUES (265,'vie','Maithili');
INSERT INTO IsoLanguagesDes VALUES (266,'vie','Makasarl Nepal Bhasa');
INSERT INTO IsoLanguagesDes VALUES (267,'vie','Malayalam');
INSERT INTO IsoLanguagesDes VALUES (268,'vie','Mandingo');
INSERT INTO IsoLanguagesDes VALUES (269,'vie','Maori');
INSERT INTO IsoLanguagesDes VALUES (270,'vie','Austronesian (Other)');
INSERT INTO IsoLanguagesDes VALUES (271,'vie','Marathi');
INSERT INTO IsoLanguagesDes VALUES (272,'vie','Masai');
INSERT INTO IsoLanguagesDes VALUES (273,'vie','Malay');
INSERT INTO IsoLanguagesDes VALUES (274,'vie','Moksha');
INSERT INTO IsoLanguagesDes VALUES (275,'vie','Mandar');
INSERT INTO IsoLanguagesDes VALUES (276,'vie','Mende');
INSERT INTO IsoLanguagesDes VALUES (277,'vie','Irish, Middle (900-1200)');
INSERT INTO IsoLanguagesDes VALUES (278,'vie','Mi''kmaq; Micmac');
INSERT INTO IsoLanguagesDes VALUES (279,'vie','Minangkabau');
INSERT INTO IsoLanguagesDes VALUES (280,'vie','Miscellaneous languages');
INSERT INTO IsoLanguagesDes VALUES (281,'vie','Mon-Khmer (Other)');
INSERT INTO IsoLanguagesDes VALUES (282,'vie','Malagasy');
INSERT INTO IsoLanguagesDes VALUES (283,'vie','Maltese');
INSERT INTO IsoLanguagesDes VALUES (284,'vie','Manchu');
INSERT INTO IsoLanguagesDes VALUES (285,'vie','Manipuri');
INSERT INTO IsoLanguagesDes VALUES (286,'vie','Manobo languages');
INSERT INTO IsoLanguagesDes VALUES (287,'vie','Mohawk');
INSERT INTO IsoLanguagesDes VALUES (288,'vie','Moldavian');
INSERT INTO IsoLanguagesDes VALUES (289,'vie','Mongolian');
INSERT INTO IsoLanguagesDes VALUES (290,'vie','Mossi');
INSERT INTO IsoLanguagesDes VALUES (291,'vie','Multiple languages');
INSERT INTO IsoLanguagesDes VALUES (292,'vie','Munda languages');
INSERT INTO IsoLanguagesDes VALUES (293,'vie','Creek');
INSERT INTO IsoLanguagesDes VALUES (294,'vie','Mirandese');
INSERT INTO IsoLanguagesDes VALUES (295,'vie','Marwari');
INSERT INTO IsoLanguagesDes VALUES (296,'vie','Mayan languages');
INSERT INTO IsoLanguagesDes VALUES (297,'vie','Erzya');
INSERT INTO IsoLanguagesDes VALUES (298,'vie','Nahuatl languages');
INSERT INTO IsoLanguagesDes VALUES (299,'vie','North American Indian');
INSERT INTO IsoLanguagesDes VALUES (300,'vie','Neapolitan');
INSERT INTO IsoLanguagesDes VALUES (301,'vie','Nauru');
INSERT INTO IsoLanguagesDes VALUES (302,'vie','Navajo; Navaho');
INSERT INTO IsoLanguagesDes VALUES (303,'vie','Ndebele, South; South Ndebele');
INSERT INTO IsoLanguagesDes VALUES (304,'vie','Ndebele, North; North Ndebele');
INSERT INTO IsoLanguagesDes VALUES (305,'vie','Ndonga');
INSERT INTO IsoLanguagesDes VALUES (306,'vie','Low German; Low Saxon; German, Low; Sa');
INSERT INTO IsoLanguagesDes VALUES (307,'vie','Nepali');
INSERT INTO IsoLanguagesDes VALUES (308,'vie','Nepal Bhasa; Newari');
INSERT INTO IsoLanguagesDes VALUES (309,'vie','Nias');
INSERT INTO IsoLanguagesDes VALUES (310,'vie','Niger-Kordofanian (Other)');
INSERT INTO IsoLanguagesDes VALUES (311,'vie','Niuean');
INSERT INTO IsoLanguagesDes VALUES (312,'vie','Norwegian Nynorsk; Nynorsk, Norwegian');
INSERT INTO IsoLanguagesDes VALUES (313,'vie','Bokmål, Norwegian; Norwegian Bokmål');
INSERT INTO IsoLanguagesDes VALUES (314,'vie','Nogai');
INSERT INTO IsoLanguagesDes VALUES (315,'vie','Norse, Old');
INSERT INTO IsoLanguagesDes VALUES (316,'vie','Norwegian');
INSERT INTO IsoLanguagesDes VALUES (317,'vie','Pedi; Sepedi; Northern Sotho');
INSERT INTO IsoLanguagesDes VALUES (318,'vie','Nubian languages');
INSERT INTO IsoLanguagesDes VALUES (319,'vie','Classical Newari; Old Newari; Classica');
INSERT INTO IsoLanguagesDes VALUES (320,'vie','Chichewa; Chewa; Nyanja');
INSERT INTO IsoLanguagesDes VALUES (321,'vie','Nyamwezi');
INSERT INTO IsoLanguagesDes VALUES (322,'vie','Nyankole');
INSERT INTO IsoLanguagesDes VALUES (323,'vie','Nyoro');
INSERT INTO IsoLanguagesDes VALUES (324,'vie','Nzima');
INSERT INTO IsoLanguagesDes VALUES (325,'vie','Occitan (post 1500); Provençal');
INSERT INTO IsoLanguagesDes VALUES (326,'vie','Ojibwa');
INSERT INTO IsoLanguagesDes VALUES (327,'vie','Oriya');
INSERT INTO IsoLanguagesDes VALUES (328,'vie','Oromo');
INSERT INTO IsoLanguagesDes VALUES (329,'vie','Osage');
INSERT INTO IsoLanguagesDes VALUES (330,'vie','Ossetian; Ossetic');
INSERT INTO IsoLanguagesDes VALUES (331,'vie','Turkish, Ottoman (1500-1928)');
INSERT INTO IsoLanguagesDes VALUES (332,'vie','Otomian languages');
INSERT INTO IsoLanguagesDes VALUES (333,'vie','Papuan (Other)');
INSERT INTO IsoLanguagesDes VALUES (334,'vie','Pangasinan');
INSERT INTO IsoLanguagesDes VALUES (335,'vie','Pahlavi');
INSERT INTO IsoLanguagesDes VALUES (336,'vie','Pampanga');
INSERT INTO IsoLanguagesDes VALUES (337,'vie','Panjabi; Punjabi');
INSERT INTO IsoLanguagesDes VALUES (338,'vie','Papiamento');
INSERT INTO IsoLanguagesDes VALUES (339,'vie','Palauan');
INSERT INTO IsoLanguagesDes VALUES (340,'vie','Persian, Old (ca.600-400 B.C.)');
INSERT INTO IsoLanguagesDes VALUES (341,'vie','Persian');
INSERT INTO IsoLanguagesDes VALUES (342,'vie','Philippine (Other)');
INSERT INTO IsoLanguagesDes VALUES (343,'vie','Phoenician');
INSERT INTO IsoLanguagesDes VALUES (344,'vie','Pali');
INSERT INTO IsoLanguagesDes VALUES (345,'vie','Polish');
INSERT INTO IsoLanguagesDes VALUES (346,'vie','Pohnpeian');
INSERT INTO IsoLanguagesDes VALUES (347,'vie','Portuguese');
INSERT INTO IsoLanguagesDes VALUES (348,'vie','Prakrit languages');
INSERT INTO IsoLanguagesDes VALUES (349,'vie','Provençal, Old (to 1500)');
INSERT INTO IsoLanguagesDes VALUES (350,'vie','Pushto');
INSERT INTO IsoLanguagesDes VALUES (351,'vie','Reserved for local use');
INSERT INTO IsoLanguagesDes VALUES (352,'vie','Quechua');
INSERT INTO IsoLanguagesDes VALUES (353,'vie','Rajasthani');
INSERT INTO IsoLanguagesDes VALUES (354,'vie','Rapanui');
INSERT INTO IsoLanguagesDes VALUES (355,'vie','Rarotongan; Cook Islands Maori');
INSERT INTO IsoLanguagesDes VALUES (356,'vie','Romance (Other)');
INSERT INTO IsoLanguagesDes VALUES (357,'vie','Romansh');
INSERT INTO IsoLanguagesDes VALUES (358,'vie','Romany');
INSERT INTO IsoLanguagesDes VALUES (359,'vie','Romanian');
INSERT INTO IsoLanguagesDes VALUES (360,'vie','Rundi');
INSERT INTO IsoLanguagesDes VALUES (361,'vie','Aromanian; Arumanian; Macedo-Romanian');
INSERT INTO IsoLanguagesDes VALUES (362,'vie','Russian');
INSERT INTO IsoLanguagesDes VALUES (363,'vie','Sandawe');
INSERT INTO IsoLanguagesDes VALUES (364,'vie','Sango');
INSERT INTO IsoLanguagesDes VALUES (365,'vie','Yakut');
INSERT INTO IsoLanguagesDes VALUES (366,'vie','South American Indian (Other)');
INSERT INTO IsoLanguagesDes VALUES (367,'vie','Salishan languages');
INSERT INTO IsoLanguagesDes VALUES (368,'vie','Samaritan Aramaic');
INSERT INTO IsoLanguagesDes VALUES (369,'vie','Sanskrit');
INSERT INTO IsoLanguagesDes VALUES (370,'vie','Sasak');
INSERT INTO IsoLanguagesDes VALUES (371,'vie','Santali');
INSERT INTO IsoLanguagesDes VALUES (372,'vie','Serbian');
INSERT INTO IsoLanguagesDes VALUES (373,'vie','Sicilian');
INSERT INTO IsoLanguagesDes VALUES (374,'vie','Scots');
INSERT INTO IsoLanguagesDes VALUES (375,'vie','Croatian');
INSERT INTO IsoLanguagesDes VALUES (376,'vie','Selkup');
INSERT INTO IsoLanguagesDes VALUES (377,'vie','Semitic (Other)');
INSERT INTO IsoLanguagesDes VALUES (378,'vie','Irish, Old (to 900)');
INSERT INTO IsoLanguagesDes VALUES (379,'vie','Sign Languages');
INSERT INTO IsoLanguagesDes VALUES (380,'vie','Shan');
INSERT INTO IsoLanguagesDes VALUES (381,'vie','Sidamo');
INSERT INTO IsoLanguagesDes VALUES (382,'vie','Sinhala; Sinhalese');
INSERT INTO IsoLanguagesDes VALUES (383,'vie','Siouan languages');
INSERT INTO IsoLanguagesDes VALUES (384,'vie','Sino-Tibetan (Other)');
INSERT INTO IsoLanguagesDes VALUES (385,'vie','Slavic (Other)');
INSERT INTO IsoLanguagesDes VALUES (386,'vie','Slovak');
INSERT INTO IsoLanguagesDes VALUES (387,'vie','Slovenian');
INSERT INTO IsoLanguagesDes VALUES (388,'vie','Southern Sami');
INSERT INTO IsoLanguagesDes VALUES (389,'vie','Northern Sami');
INSERT INTO IsoLanguagesDes VALUES (390,'vie','Sami languages (Other)');
INSERT INTO IsoLanguagesDes VALUES (391,'vie','Lule Sami');
INSERT INTO IsoLanguagesDes VALUES (392,'vie','Inari Sami');
INSERT INTO IsoLanguagesDes VALUES (393,'vie','Samoan');
INSERT INTO IsoLanguagesDes VALUES (394,'vie','Skolt Sami');
INSERT INTO IsoLanguagesDes VALUES (395,'vie','Shona');
INSERT INTO IsoLanguagesDes VALUES (396,'vie','Sindhi');
INSERT INTO IsoLanguagesDes VALUES (397,'vie','Soninke');
INSERT INTO IsoLanguagesDes VALUES (398,'vie','Sogdian');
INSERT INTO IsoLanguagesDes VALUES (399,'vie','Somali');
INSERT INTO IsoLanguagesDes VALUES (400,'vie','Songhai languages');
INSERT INTO IsoLanguagesDes VALUES (401,'vie','Sotho, Southern');
INSERT INTO IsoLanguagesDes VALUES (402,'vie','Spanish; Castilian');
INSERT INTO IsoLanguagesDes VALUES (403,'vie','Sardinian; Zazaki');
INSERT INTO IsoLanguagesDes VALUES (404,'vie','Sranan Tongo');
INSERT INTO IsoLanguagesDes VALUES (405,'vie','Serer');
INSERT INTO IsoLanguagesDes VALUES (406,'vie','Nilo-Saharan (Other)');
INSERT INTO IsoLanguagesDes VALUES (407,'vie','Swati');
INSERT INTO IsoLanguagesDes VALUES (408,'vie','Sukuma');
INSERT INTO IsoLanguagesDes VALUES (409,'vie','Sundanese');
INSERT INTO IsoLanguagesDes VALUES (410,'vie','Susu');
INSERT INTO IsoLanguagesDes VALUES (411,'vie','Sumerian');
INSERT INTO IsoLanguagesDes VALUES (412,'vie','Swahili');
INSERT INTO IsoLanguagesDes VALUES (413,'vie','Swedish');
INSERT INTO IsoLanguagesDes VALUES (414,'vie','Syriac');
INSERT INTO IsoLanguagesDes VALUES (415,'vie','Tahitian');
INSERT INTO IsoLanguagesDes VALUES (416,'vie','Tai (Other)');
INSERT INTO IsoLanguagesDes VALUES (417,'vie','Tamil');
INSERT INTO IsoLanguagesDes VALUES (418,'vie','Tatar');
INSERT INTO IsoLanguagesDes VALUES (419,'vie','Telugu');
INSERT INTO IsoLanguagesDes VALUES (420,'vie','Timnendere)');
INSERT INTO IsoLanguagesDes VALUES (421,'vie','Tereno');
INSERT INTO IsoLanguagesDes VALUES (422,'vie','Tetum');
INSERT INTO IsoLanguagesDes VALUES (423,'vie','Tajik');
INSERT INTO IsoLanguagesDes VALUES (424,'vie','Tagalog');
INSERT INTO IsoLanguagesDes VALUES (425,'vie','Thai');
INSERT INTO IsoLanguagesDes VALUES (426,'vie','Tibetan');
INSERT INTO IsoLanguagesDes VALUES (427,'vie','Tigre');
INSERT INTO IsoLanguagesDes VALUES (428,'vie','Tigrinya');
INSERT INTO IsoLanguagesDes VALUES (429,'vie','Tiv');
INSERT INTO IsoLanguagesDes VALUES (430,'vie','Tokelau');
INSERT INTO IsoLanguagesDes VALUES (431,'vie','Klingon; tlhIngan-Hol');
INSERT INTO IsoLanguagesDes VALUES (432,'vie','Tlingit');
INSERT INTO IsoLanguagesDes VALUES (433,'vie','Tamashek');
INSERT INTO IsoLanguagesDes VALUES (434,'vie','Tonga (Nyasa)');
INSERT INTO IsoLanguagesDes VALUES (435,'vie','Tonga (Tonga Islands)');
INSERT INTO IsoLanguagesDes VALUES (436,'vie','Tok Pisin');
INSERT INTO IsoLanguagesDes VALUES (437,'vie','Tsimshian');
INSERT INTO IsoLanguagesDes VALUES (438,'vie','Tswana');
INSERT INTO IsoLanguagesDes VALUES (439,'vie','Tsonga');
INSERT INTO IsoLanguagesDes VALUES (440,'vie','Turkmen');
INSERT INTO IsoLanguagesDes VALUES (441,'vie','Tumbuka');
INSERT INTO IsoLanguagesDes VALUES (442,'vie','Tupi languages');
INSERT INTO IsoLanguagesDes VALUES (443,'vie','Turkish');
INSERT INTO IsoLanguagesDes VALUES (444,'vie','Altaic (Other)');
INSERT INTO IsoLanguagesDes VALUES (445,'vie','Tuvalu');
INSERT INTO IsoLanguagesDes VALUES (446,'vie','Twi');
INSERT INTO IsoLanguagesDes VALUES (447,'vie','Tuvinian');
INSERT INTO IsoLanguagesDes VALUES (448,'vie','Udmurt');
INSERT INTO IsoLanguagesDes VALUES (449,'vie','Ugaritic');
INSERT INTO IsoLanguagesDes VALUES (450,'vie','Uighur; Uyghur');
INSERT INTO IsoLanguagesDes VALUES (451,'vie','Ukrainian');
INSERT INTO IsoLanguagesDes VALUES (452,'vie','Umbundu');
INSERT INTO IsoLanguagesDes VALUES (453,'vie','Undetermined');
INSERT INTO IsoLanguagesDes VALUES (454,'vie','Urdu');
INSERT INTO IsoLanguagesDes VALUES (455,'vie','Uzbek');
INSERT INTO IsoLanguagesDes VALUES (456,'vie','Vai');
INSERT INTO IsoLanguagesDes VALUES (457,'vie','Venda');
INSERT INTO IsoLanguagesDes VALUES (458,'vie','Vietnamese');
INSERT INTO IsoLanguagesDes VALUES (459,'vie','Volapük');
INSERT INTO IsoLanguagesDes VALUES (460,'vie','Votic');
INSERT INTO IsoLanguagesDes VALUES (461,'vie','Wakashan languages');
INSERT INTO IsoLanguagesDes VALUES (462,'vie','Walamo');
INSERT INTO IsoLanguagesDes VALUES (463,'vie','Waray');
INSERT INTO IsoLanguagesDes VALUES (464,'vie','Washo');
INSERT INTO IsoLanguagesDes VALUES (465,'vie','Welsh');
INSERT INTO IsoLanguagesDes VALUES (466,'vie','Sorbian languages');
INSERT INTO IsoLanguagesDes VALUES (467,'vie','Walloon');
INSERT INTO IsoLanguagesDes VALUES (468,'vie','Wolof');
INSERT INTO IsoLanguagesDes VALUES (469,'vie','Kalmyk; Oirat');
INSERT INTO IsoLanguagesDes VALUES (470,'vie','Xhosa');
INSERT INTO IsoLanguagesDes VALUES (471,'vie','Yao');
INSERT INTO IsoLanguagesDes VALUES (472,'vie','Yapese');
INSERT INTO IsoLanguagesDes VALUES (473,'vie','Yiddish');
INSERT INTO IsoLanguagesDes VALUES (474,'vie','Yoruba');
INSERT INTO IsoLanguagesDes VALUES (475,'vie','Yupik languages');
INSERT INTO IsoLanguagesDes VALUES (476,'vie','Zapotec');
INSERT INTO IsoLanguagesDes VALUES (477,'vie','Zenaga');
INSERT INTO IsoLanguagesDes VALUES (478,'vie','Zhuang; Chuang');
INSERT INTO IsoLanguagesDes VALUES (479,'vie','Zande languages');
INSERT INTO IsoLanguagesDes VALUES (480,'vie','Zulu');
INSERT INTO IsoLanguagesDes VALUES (481,'vie','Zuni');
INSERT INTO IsoLanguagesDes VALUES (482,'vie','No linguistic content');
INSERT INTO IsoLanguagesDes VALUES (483,'vie','N''Ko');
INSERT INTO IsoLanguagesDes VALUES (484,'vie','Zaza; Dimili; Dimli; Kirdki; Kirmanjki');

INSERT INTO OperationsDes VALUES (0,'vie','Publish');
INSERT INTO OperationsDes VALUES (1,'vie','Download');
INSERT INTO OperationsDes VALUES (2,'vie','Editing');
INSERT INTO OperationsDes VALUES (3,'vie','Notify');
INSERT INTO OperationsDes VALUES (5,'vie','Interactive Map');
INSERT INTO OperationsDes VALUES (6,'vie','Featured');

INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (0,'vie','Unknown');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (1,'vie','Draft');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (2,'vie','Approved');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (3,'vie','Retired');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (4,'vie','Submitted');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (5,'vie','Rejected');

INSERT INTO RegionsDes VALUES (1,'vie','Armenia');
INSERT INTO RegionsDes VALUES (2,'vie','Afghanistan');
INSERT INTO RegionsDes VALUES (3,'vie','Albania');
INSERT INTO RegionsDes VALUES (4,'vie','Algeria');
INSERT INTO RegionsDes VALUES (5,'vie','American Samoa');
INSERT INTO RegionsDes VALUES (6,'vie','Andorra');
INSERT INTO RegionsDes VALUES (7,'vie','Angola');
INSERT INTO RegionsDes VALUES (8,'vie','Antigua and Barbuda');
INSERT INTO RegionsDes VALUES (9,'vie','Argentina');
INSERT INTO RegionsDes VALUES (10,'vie','Australia');
INSERT INTO RegionsDes VALUES (11,'vie','Austria');
INSERT INTO RegionsDes VALUES (12,'vie','Bahamas');
INSERT INTO RegionsDes VALUES (13,'vie','Bahrain');
INSERT INTO RegionsDes VALUES (14,'vie','Barbados');
INSERT INTO RegionsDes VALUES (16,'vie','Bangladesh');
INSERT INTO RegionsDes VALUES (17,'vie','Bermuda');
INSERT INTO RegionsDes VALUES (18,'vie','Bhutan');
INSERT INTO RegionsDes VALUES (19,'vie','Bolivia');
INSERT INTO RegionsDes VALUES (20,'vie','Botswana');
INSERT INTO RegionsDes VALUES (21,'vie','Brazil');
INSERT INTO RegionsDes VALUES (22,'vie','Aruba');
INSERT INTO RegionsDes VALUES (23,'vie','Belize');
INSERT INTO RegionsDes VALUES (24,'vie','British Indian Ocean Ter');
INSERT INTO RegionsDes VALUES (25,'vie','Solomon Islands');
INSERT INTO RegionsDes VALUES (26,'vie','Brunei Darussalam');
INSERT INTO RegionsDes VALUES (27,'vie','Bulgaria');
INSERT INTO RegionsDes VALUES (28,'vie','Myanmar');
INSERT INTO RegionsDes VALUES (29,'vie','Burundi');
INSERT INTO RegionsDes VALUES (30,'vie','Antarctica');
INSERT INTO RegionsDes VALUES (31,'vie','Bouvet Island');
INSERT INTO RegionsDes VALUES (32,'vie','Cameroon');
INSERT INTO RegionsDes VALUES (33,'vie','Canada');
INSERT INTO RegionsDes VALUES (35,'vie','Cape Verde');
INSERT INTO RegionsDes VALUES (36,'vie','Cayman Island');
INSERT INTO RegionsDes VALUES (37,'vie','Central African Republic');
INSERT INTO RegionsDes VALUES (38,'vie','Sri Lanka');
INSERT INTO RegionsDes VALUES (39,'vie','Chad');
INSERT INTO RegionsDes VALUES (40,'vie','Chile');
INSERT INTO RegionsDes VALUES (41,'vie','China, Mainland');
INSERT INTO RegionsDes VALUES (42,'vie','Christmas Island');
INSERT INTO RegionsDes VALUES (43,'vie','Cocos Islands');
INSERT INTO RegionsDes VALUES (44,'vie','Colombia');
INSERT INTO RegionsDes VALUES (45,'vie','Comoros');
INSERT INTO RegionsDes VALUES (46,'vie','Congo, Republic of');
INSERT INTO RegionsDes VALUES (47,'vie','Cook Islands');
INSERT INTO RegionsDes VALUES (48,'vie','Costa Rica');
INSERT INTO RegionsDes VALUES (49,'vie','Cuba');
INSERT INTO RegionsDes VALUES (50,'vie','Cyprus');
INSERT INTO RegionsDes VALUES (52,'vie','Azerbaijan, Republic of');
INSERT INTO RegionsDes VALUES (53,'vie','Benin');
INSERT INTO RegionsDes VALUES (54,'vie','Denmark');
INSERT INTO RegionsDes VALUES (55,'vie','Dominica');
INSERT INTO RegionsDes VALUES (56,'vie','Dominican Republic');
INSERT INTO RegionsDes VALUES (57,'vie','Belarus');
INSERT INTO RegionsDes VALUES (58,'vie','Ecuador');
INSERT INTO RegionsDes VALUES (59,'vie','Egypt');
INSERT INTO RegionsDes VALUES (60,'vie','El Salvador');
INSERT INTO RegionsDes VALUES (61,'vie','Equatorial Guinea');
INSERT INTO RegionsDes VALUES (63,'vie','Estonia');
INSERT INTO RegionsDes VALUES (64,'vie','Faeroe Islands');
INSERT INTO RegionsDes VALUES (65,'vie','Falkland Islands');
INSERT INTO RegionsDes VALUES (66,'vie','Fiji Islands');
INSERT INTO RegionsDes VALUES (67,'vie','Finland');
INSERT INTO RegionsDes VALUES (68,'vie','France');
INSERT INTO RegionsDes VALUES (69,'vie','French Guiana');
INSERT INTO RegionsDes VALUES (70,'vie','French Polynesia');
INSERT INTO RegionsDes VALUES (71,'vie','French South Terr');
INSERT INTO RegionsDes VALUES (72,'vie','Djibouti');
INSERT INTO RegionsDes VALUES (73,'vie','Georgia');
INSERT INTO RegionsDes VALUES (74,'vie','Gabon');
INSERT INTO RegionsDes VALUES (75,'vie','Gambia');
INSERT INTO RegionsDes VALUES (76,'vie','Gaza Strip');
INSERT INTO RegionsDes VALUES (79,'vie','Germany');
INSERT INTO RegionsDes VALUES (80,'vie','Bosnia and Herzegovina');
INSERT INTO RegionsDes VALUES (81,'vie','Ghana');
INSERT INTO RegionsDes VALUES (82,'vie','Gibraltar');
INSERT INTO RegionsDes VALUES (83,'vie','Kiribati');
INSERT INTO RegionsDes VALUES (84,'vie','Greece');
INSERT INTO RegionsDes VALUES (85,'vie','Greenland');
INSERT INTO RegionsDes VALUES (86,'vie','Grenada');
INSERT INTO RegionsDes VALUES (87,'vie','Guadeloupe');
INSERT INTO RegionsDes VALUES (88,'vie','Guam');
INSERT INTO RegionsDes VALUES (89,'vie','Guatemala');
INSERT INTO RegionsDes VALUES (90,'vie','Guinea');
INSERT INTO RegionsDes VALUES (91,'vie','Guyana');
INSERT INTO RegionsDes VALUES (92,'vie','Heard and McDonald Is');
INSERT INTO RegionsDes VALUES (93,'vie','Haiti');
INSERT INTO RegionsDes VALUES (95,'vie','Honduras');
INSERT INTO RegionsDes VALUES (97,'vie','Hungary');
INSERT INTO RegionsDes VALUES (98,'vie','Croatia');
INSERT INTO RegionsDes VALUES (99,'vie','Iceland');
INSERT INTO RegionsDes VALUES (100,'vie','India');
INSERT INTO RegionsDes VALUES (101,'vie','Indonesia');
INSERT INTO RegionsDes VALUES (102,'vie','Iran, Islamic Rep of');
INSERT INTO RegionsDes VALUES (103,'vie','Iraq');
INSERT INTO RegionsDes VALUES (104,'vie','Ireland');
INSERT INTO RegionsDes VALUES (105,'vie','Israel');
INSERT INTO RegionsDes VALUES (106,'vie','Italy');
INSERT INTO RegionsDes VALUES (107,'vie','Ivory Coast');
INSERT INTO RegionsDes VALUES (108,'vie','Kazakhstan');
INSERT INTO RegionsDes VALUES (109,'vie','Jamaica');
INSERT INTO RegionsDes VALUES (110,'vie','Japan');
INSERT INTO RegionsDes VALUES (112,'vie','Jordan');
INSERT INTO RegionsDes VALUES (113,'vie','Kyrgyzstan');
INSERT INTO RegionsDes VALUES (114,'vie','Kenya');
INSERT INTO RegionsDes VALUES (115,'vie','Cambodia');
INSERT INTO RegionsDes VALUES (116,'vie','Korea, Dem People''s Rep');
INSERT INTO RegionsDes VALUES (117,'vie','Korea, Republic of');
INSERT INTO RegionsDes VALUES (118,'vie','Kuwait');
INSERT INTO RegionsDes VALUES (119,'vie','Latvia');
INSERT INTO RegionsDes VALUES (120,'vie','Laos');
INSERT INTO RegionsDes VALUES (121,'vie','Lebanon');
INSERT INTO RegionsDes VALUES (122,'vie','Lesotho');
INSERT INTO RegionsDes VALUES (123,'vie','Liberia');
INSERT INTO RegionsDes VALUES (124,'vie','Libyan Arab Jamahiriya');
INSERT INTO RegionsDes VALUES (125,'vie','Liechtensten');
INSERT INTO RegionsDes VALUES (126,'vie','Lithuania');
INSERT INTO RegionsDes VALUES (127,'vie','Marshall Island');
INSERT INTO RegionsDes VALUES (129,'vie','Madagascar');
INSERT INTO RegionsDes VALUES (130,'vie','Malawi');
INSERT INTO RegionsDes VALUES (131,'vie','Malaysia');
INSERT INTO RegionsDes VALUES (132,'vie','Maldives');
INSERT INTO RegionsDes VALUES (133,'vie','Mali');
INSERT INTO RegionsDes VALUES (134,'vie','Malta');
INSERT INTO RegionsDes VALUES (135,'vie','Martinique');
INSERT INTO RegionsDes VALUES (136,'vie','Mauritania');
INSERT INTO RegionsDes VALUES (137,'vie','Mauritius');
INSERT INTO RegionsDes VALUES (138,'vie','Mexico');
INSERT INTO RegionsDes VALUES (139,'vie','Midway Islands');
INSERT INTO RegionsDes VALUES (140,'vie','Monaco');
INSERT INTO RegionsDes VALUES (141,'vie','Mongolia');
INSERT INTO RegionsDes VALUES (142,'vie','Montserrat');
INSERT INTO RegionsDes VALUES (143,'vie','Morocco');
INSERT INTO RegionsDes VALUES (144,'vie','Mozambique');
INSERT INTO RegionsDes VALUES (145,'vie','Micronesia,Fed States of');
INSERT INTO RegionsDes VALUES (146,'vie','Moldova, Republic of');
INSERT INTO RegionsDes VALUES (147,'vie','Namibia');
INSERT INTO RegionsDes VALUES (148,'vie','Nauru');
INSERT INTO RegionsDes VALUES (149,'vie','Nepal');
INSERT INTO RegionsDes VALUES (150,'vie','Netherlands');
INSERT INTO RegionsDes VALUES (151,'vie','Neth Antilles');
INSERT INTO RegionsDes VALUES (153,'vie','NewCaledonia');
INSERT INTO RegionsDes VALUES (154,'vie','Macedonia');
INSERT INTO RegionsDes VALUES (155,'vie','Vanuatu');
INSERT INTO RegionsDes VALUES (156,'vie','New Zealand');
INSERT INTO RegionsDes VALUES (157,'vie','Nicaragua');
INSERT INTO RegionsDes VALUES (158,'vie','Niger');
INSERT INTO RegionsDes VALUES (159,'vie','Nigeria');
INSERT INTO RegionsDes VALUES (160,'vie','Niue');
INSERT INTO RegionsDes VALUES (161,'vie','Norfolk Island');
INSERT INTO RegionsDes VALUES (162,'vie','Norway');
INSERT INTO RegionsDes VALUES (163,'vie','Northern Mariana Is');
INSERT INTO RegionsDes VALUES (165,'vie','Pakistan');
INSERT INTO RegionsDes VALUES (166,'vie','Panama');
INSERT INTO RegionsDes VALUES (167,'vie','Czech Republic');
INSERT INTO RegionsDes VALUES (168,'vie','Papua New Guinea');
INSERT INTO RegionsDes VALUES (169,'vie','Paraguay');
INSERT INTO RegionsDes VALUES (170,'vie','Peru');
INSERT INTO RegionsDes VALUES (171,'vie','Philippines');
INSERT INTO RegionsDes VALUES (172,'vie','Pitcairn Islands');
INSERT INTO RegionsDes VALUES (173,'vie','Poland');
INSERT INTO RegionsDes VALUES (174,'vie','Portugal');
INSERT INTO RegionsDes VALUES (175,'vie','Guinea-Bissau');
INSERT INTO RegionsDes VALUES (176,'vie','East Timor');
INSERT INTO RegionsDes VALUES (177,'vie','Puerto Rico');
INSERT INTO RegionsDes VALUES (178,'vie','Eritrea');
INSERT INTO RegionsDes VALUES (179,'vie','Qatar');
INSERT INTO RegionsDes VALUES (181,'vie','Zimbabwe');
INSERT INTO RegionsDes VALUES (182,'vie','Reunion');
INSERT INTO RegionsDes VALUES (183,'vie','Romania');
INSERT INTO RegionsDes VALUES (184,'vie','Rwanda');
INSERT INTO RegionsDes VALUES (185,'vie','Russian Federation');
INSERT INTO RegionsDes VALUES (187,'vie','Saint Helena');
INSERT INTO RegionsDes VALUES (188,'vie','Saint Kitts and Nevis');
INSERT INTO RegionsDes VALUES (189,'vie','Saint Lucia');
INSERT INTO RegionsDes VALUES (190,'vie','Saint Pierre & Miquelon');
INSERT INTO RegionsDes VALUES (191,'vie','Saint Vincent/Grenadines');
INSERT INTO RegionsDes VALUES (192,'vie','San Marino');
INSERT INTO RegionsDes VALUES (193,'vie','Sao Tome and Principe');
INSERT INTO RegionsDes VALUES (194,'vie','Saudi Arabia');
INSERT INTO RegionsDes VALUES (195,'vie','Senegal');
INSERT INTO RegionsDes VALUES (196,'vie','Seychelles');
INSERT INTO RegionsDes VALUES (197,'vie','Sierra Leone');
INSERT INTO RegionsDes VALUES (198,'vie','Slovenia');
INSERT INTO RegionsDes VALUES (199,'vie','Slovakia');
INSERT INTO RegionsDes VALUES (200,'vie','Singapore');
INSERT INTO RegionsDes VALUES (201,'vie','Somalia');
INSERT INTO RegionsDes VALUES (202,'vie','South Africa');
INSERT INTO RegionsDes VALUES (203,'vie','Spain');
INSERT INTO RegionsDes VALUES (205,'vie','Western Sahara');
INSERT INTO RegionsDes VALUES (206,'vie','Sudan');
INSERT INTO RegionsDes VALUES (207,'vie','Suriname');
INSERT INTO RegionsDes VALUES (208,'vie','Tajikistan');
INSERT INTO RegionsDes VALUES (209,'vie','Swaziland');
INSERT INTO RegionsDes VALUES (210,'vie','Sweden');
INSERT INTO RegionsDes VALUES (211,'vie','Switzerland');
INSERT INTO RegionsDes VALUES (212,'vie','Syrian Arab Republic');
INSERT INTO RegionsDes VALUES (213,'vie','Turkmenistan');
INSERT INTO RegionsDes VALUES (214,'vie','China, Taiwan Prov of');
INSERT INTO RegionsDes VALUES (215,'vie','Tanzania, United Rep of');
INSERT INTO RegionsDes VALUES (216,'vie','Thailand');
INSERT INTO RegionsDes VALUES (217,'vie','Togo');
INSERT INTO RegionsDes VALUES (218,'vie','Tokelau');
INSERT INTO RegionsDes VALUES (219,'vie','Tonga');
INSERT INTO RegionsDes VALUES (220,'vie','Trinidad and Tobago');
INSERT INTO RegionsDes VALUES (221,'vie','Oman');
INSERT INTO RegionsDes VALUES (222,'vie','Tunisia');
INSERT INTO RegionsDes VALUES (223,'vie','Turkey');
INSERT INTO RegionsDes VALUES (224,'vie','Turks and Caicos Is');
INSERT INTO RegionsDes VALUES (225,'vie','United Arab Emirates');
INSERT INTO RegionsDes VALUES (226,'vie','Uganda');
INSERT INTO RegionsDes VALUES (227,'vie','Tuvalu');
INSERT INTO RegionsDes VALUES (229,'vie','United Kingdom');
INSERT INTO RegionsDes VALUES (230,'vie','Ukraine');
INSERT INTO RegionsDes VALUES (231,'vie','United States of America');
INSERT INTO RegionsDes VALUES (232,'vie','US Minor Outlying Is');
INSERT INTO RegionsDes VALUES (233,'vie','Burkina Faso');
INSERT INTO RegionsDes VALUES (234,'vie','Uruguay');
INSERT INTO RegionsDes VALUES (235,'vie','Uzbekistan');
INSERT INTO RegionsDes VALUES (236,'vie','Venezuela');
INSERT INTO RegionsDes VALUES (237,'vie','Viet Nam');
INSERT INTO RegionsDes VALUES (238,'vie','Ethiopia');
INSERT INTO RegionsDes VALUES (239,'vie','British Virgin Island');
INSERT INTO RegionsDes VALUES (240,'vie','US Virgin Islands');
INSERT INTO RegionsDes VALUES (242,'vie','Wake Island');
INSERT INTO RegionsDes VALUES (243,'vie','Wallis and Futuna Is');
INSERT INTO RegionsDes VALUES (244,'vie','Samoa');
INSERT INTO RegionsDes VALUES (245,'vie','West Bank');
INSERT INTO RegionsDes VALUES (249,'vie','Yemen');
INSERT INTO RegionsDes VALUES (250,'vie','Congo, Dem Republic of');
INSERT INTO RegionsDes VALUES (251,'vie','Zambia');
INSERT INTO RegionsDes VALUES (255,'vie','Belgium');
INSERT INTO RegionsDes VALUES (256,'vie','Luxembourg');
INSERT INTO RegionsDes VALUES (258,'vie','Anguilla');
INSERT INTO RegionsDes VALUES (260,'vie','Svalbard Is');
INSERT INTO RegionsDes VALUES (264,'vie','Isle of Man');
INSERT INTO RegionsDes VALUES (270,'vie','Mayotte');
INSERT INTO RegionsDes VALUES (271,'vie','SouthGeorgia/Sandwich Is');
INSERT INTO RegionsDes VALUES (303,'vie','Western Europe');
INSERT INTO RegionsDes VALUES (307,'vie','Intergvt Author Devpment');
INSERT INTO RegionsDes VALUES (310,'vie','North Western Africa');
INSERT INTO RegionsDes VALUES (311,'vie','Western Africa');
INSERT INTO RegionsDes VALUES (312,'vie','Central Africa');
INSERT INTO RegionsDes VALUES (313,'vie','Eastern Africa');
INSERT INTO RegionsDes VALUES (314,'vie','Southern Africa');
INSERT INTO RegionsDes VALUES (315,'vie','Latin Amer & Caribbean');
INSERT INTO RegionsDes VALUES (316,'vie','Central America');
INSERT INTO RegionsDes VALUES (317,'vie','Caribbean');
INSERT INTO RegionsDes VALUES (318,'vie','South America');
INSERT INTO RegionsDes VALUES (319,'vie','Near East');
INSERT INTO RegionsDes VALUES (320,'vie','Near East in Africa');
INSERT INTO RegionsDes VALUES (321,'vie','Near East in Asia');
INSERT INTO RegionsDes VALUES (322,'vie','Far East');
INSERT INTO RegionsDes VALUES (323,'vie','South Asia');
INSERT INTO RegionsDes VALUES (324,'vie','East & South East Asia');
INSERT INTO RegionsDes VALUES (325,'vie','Near East and North Africa');
INSERT INTO RegionsDes VALUES (334,'vie','Eastern Europe');
INSERT INTO RegionsDes VALUES (335,'vie','Europe');
INSERT INTO RegionsDes VALUES (337,'vie','Asia');
INSERT INTO RegionsDes VALUES (338,'vie','Africa');
INSERT INTO RegionsDes VALUES (348,'vie','Latin America');
INSERT INTO RegionsDes VALUES (370,'vie','Serbia');
INSERT INTO RegionsDes VALUES (371,'vie','Montenegro');
INSERT INTO RegionsDes VALUES (390,'vie','South of Sahara');
INSERT INTO RegionsDes VALUES (421,'vie','North Africa');
INSERT INTO RegionsDes VALUES (427,'vie','Europe, Non-EU Countries');
INSERT INTO RegionsDes VALUES (428,'vie','North America');
INSERT INTO RegionsDes VALUES (469,'vie','USSR, Former Area of');
INSERT INTO RegionsDes VALUES (1008,'vie','Arctic Sea');
INSERT INTO RegionsDes VALUES (1009,'vie','Atlantic, Northwest');
INSERT INTO RegionsDes VALUES (1010,'vie','Atlantic, Northeast');
INSERT INTO RegionsDes VALUES (1011,'vie','Atlantic, Western Central');
INSERT INTO RegionsDes VALUES (1012,'vie','Atlantic, Eastern Central');
INSERT INTO RegionsDes VALUES (1013,'vie','Mediterran and Black Sea');
INSERT INTO RegionsDes VALUES (1014,'vie','Atlantic, Southwest');
INSERT INTO RegionsDes VALUES (1015,'vie','Atlantic, Southeast');
INSERT INTO RegionsDes VALUES (1016,'vie','Atlantic, Antarctic');
INSERT INTO RegionsDes VALUES (1017,'vie','Indian Ocean, Western');
INSERT INTO RegionsDes VALUES (1018,'vie','Indian Ocean, Eastern');
INSERT INTO RegionsDes VALUES (1019,'vie','Indian Ocean, Antarctic');
INSERT INTO RegionsDes VALUES (1020,'vie','Pacific, Northwest');
INSERT INTO RegionsDes VALUES (1021,'vie','Pacific, Northeast');
INSERT INTO RegionsDes VALUES (1022,'vie','Pacific, Western Central');
INSERT INTO RegionsDes VALUES (1023,'vie','Pacific, Eastern Central');
INSERT INTO RegionsDes VALUES (1024,'vie','Pacific, Southwest');
INSERT INTO RegionsDes VALUES (1025,'vie','Pacific, Southeast');
INSERT INTO RegionsDes VALUES (1026,'vie','Pacific, Antarctic');
INSERT INTO RegionsDes VALUES (1220,'vie','All fishing areas');
INSERT INTO RegionsDes VALUES (9999,'vie','World');
