--liquibase formatted sql
--changeset francois:00004
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM Languages WHERE id = 'arm';

INSERT INTO Languages (id, name, isinspire) VALUES ('arm','հայերեն', 'n');

INSERT INTO GroupsDes (iddes, langid, label) VALUES (-1,'arm','Guest');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (0,'arm','Intranet');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (1,'arm','All');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (2,'arm','Sample group');

INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (1,'arm','Afar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (2,'arm','Abkhazian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (3,'arm','Achinese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (4,'arm','Acoli');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (5,'arm','Adangme');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (6,'arm','Adyghe; Adygei');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (7,'arm','Afro-Asiatic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (8,'arm','Afrihili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (9,'arm','Afrikaans');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (10,'arm','Ainu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (11,'arm','Akan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (12,'arm','Akkadian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (13,'arm','Albanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (14,'arm','Aleut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (15,'arm','Algonquian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (16,'arm','Southern Altai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (17,'arm','Amharic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (18,'arm','English, Old (ca.450-1100)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (19,'arm','Angika');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (20,'arm','Apache languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (21,'arm','Arabic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (22,'arm','Aramaic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (23,'arm','Aragonese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (24,'arm','Armenian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (25,'arm','Mapudungun; Mapuche');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (26,'arm','Arapaho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (27,'arm','Artificial (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (28,'arm','Arawak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (29,'arm','Assamese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (30,'arm','Asturian; Bable');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (31,'arm','Athapascan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (32,'arm','Australian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (33,'arm','Avaric');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (34,'arm','Avestan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (35,'arm','Awadhi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (36,'arm','Aymara');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (37,'arm','Azerbaijani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (38,'arm','Banda languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (39,'arm','Bamileke languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (40,'arm','Bashkir');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (41,'arm','Baluchi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (42,'arm','Bambara');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (43,'arm','Balinese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (44,'arm','Basque');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (45,'arm','Basa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (46,'arm','Baltic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (47,'arm','Beja');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (48,'arm','Belarusian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (49,'arm','Bemba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (50,'arm','Bengali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (51,'arm','Berber (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (52,'arm','Bhojpuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (53,'arm','Bihari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (54,'arm','Bikol');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (55,'arm','Bini; Edo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (56,'arm','Bislama');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (57,'arm','Siksika');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (58,'arm','Bantu (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (59,'arm','Bosnian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (60,'arm','Braj');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (61,'arm','Breton');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (62,'arm','Batak languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (63,'arm','Buriat');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (64,'arm','Buginese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (65,'arm','Bulgarian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (66,'arm','Burmese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (67,'arm','Blin; Bilin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (68,'arm','Caddo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (69,'arm','Central American Indian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (70,'arm','Galibi Carib');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (71,'arm','Catalan; Valencian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (72,'arm','Caucasian (Other)on liturgique; vieux bulgare');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (73,'arm','Cebuano');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (74,'arm','Celtic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (75,'arm','Chamorro');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (76,'arm','Chibcha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (77,'arm','Chechen');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (78,'arm','Chagataier)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (79,'arm','Chinese(Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (80,'arm','Chuukese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (81,'arm','Mari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (82,'arm','Chinook jargon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (83,'arm','Choctaw');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (84,'arm','Chipewyan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (85,'arm','Cherokee');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (86,'arm','Church Slavic; Old Slavonic; Church Sl');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (87,'arm','Chuvash');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (88,'arm','Cheyenne');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (89,'arm','Chamic languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (90,'arm','Coptic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (91,'arm','Cornish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (92,'arm','Corsican');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (93,'arm','Creoles and pidgins, English based (Ot');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (94,'arm','Creoles and pidgins, French-based (Oth');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (95,'arm','Creoles and pidgins, Portuguese-based ');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (96,'arm','Cree');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (97,'arm','Crimean Tatar; Crimean Turkish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (98,'arm','Creoles and pidgins (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (99,'arm','Kashubian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (100,'arm','Cushitic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (101,'arm','Czech');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (102,'arm','Dakota');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (103,'arm','Danish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (104,'arm','Dargwa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (105,'arm','Land Dayak languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (106,'arm','Delaware');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (107,'arm','Slave (Athapascan)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (108,'arm','Dogrib');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (109,'arm','Dinka');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (110,'arm','Divehi; Dhivehi; Maldivian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (111,'arm','Dogri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (112,'arm','Dravidian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (113,'arm','Lower Sorbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (114,'arm','Duala');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (115,'arm','Dutch, Middle (ca.1050-1350)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (116,'arm','Dutch; Flemish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (117,'arm','Dyula');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (118,'arm','Dzongkha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (119,'arm','Efik');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (120,'arm','Egyptian (Ancient)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (121,'arm','Ekajuk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (122,'arm','Elamite');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (123,'arm','English');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (124,'arm','English, Middle (1100-1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (125,'arm','Esperanto');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (126,'arm','Estonian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (127,'arm','Ewe');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (128,'arm','Ewondo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (129,'arm','Fang');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (130,'arm','Faroese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (131,'arm','Fanti');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (132,'arm','Fijian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (133,'arm','Filipino; Pilipino');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (134,'arm','Finnish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (135,'arm','Finno-Ugrian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (136,'arm','Fon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (137,'arm','French');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (138,'arm','French, Middle (ca.1400-1600)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (139,'arm','French, Old (842-ca.1400)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (140,'arm','Northern Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (141,'arm','Eastern Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (142,'arm','Western Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (143,'arm','Fulah');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (144,'arm','Friulian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (145,'arm','Ga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (146,'arm','Gayo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (147,'arm','Gbaya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (148,'arm','Germanic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (149,'arm','Georgian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (150,'arm','German');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (151,'arm','Geez');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (152,'arm','Gilbertese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (153,'arm','Gaelic; Scottish Gaelic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (154,'arm','Irish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (155,'arm','Galician');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (156,'arm','Manx');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (157,'arm','German, Middle High (ca.1050-1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (158,'arm','German, Old High (ca.750-1050)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (159,'arm','Gondi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (160,'arm','Gorontalo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (161,'arm','Gothicanguage Association)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (162,'arm','Grebo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (163,'arm','Greek, Ancient (to 1453)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (164,'arm','Greek, Modern (1453-)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (165,'arm','Guarani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (166,'arm','Swiss German; Alemannic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (167,'arm','Gujarati');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (168,'arm','Gwich''in');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (169,'arm','Haida');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (170,'arm','Haitian; Haitian Creole');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (171,'arm','Hausa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (172,'arm','Hawaiian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (173,'arm','Hebrew');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (174,'arm','Herero');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (175,'arm','Hiligaynon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (176,'arm','Himachali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (177,'arm','Hindi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (178,'arm','Hittite');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (179,'arm','Hmong');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (180,'arm','Hiri Motu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (181,'arm','Upper Sorbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (182,'arm','Hungarian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (183,'arm','Hupa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (184,'arm','Iban');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (185,'arm','Igbo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (186,'arm','Icelandic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (187,'arm','Ido');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (188,'arm','Sichuan Yi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (189,'arm','Ijo languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (190,'arm','Inuktitut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (191,'arm','Interlingue');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (192,'arm','Iloko');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (193,'arm','Interlingua (International Auxiliary L');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (194,'arm','Indic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (195,'arm','Indonesian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (196,'arm','Indo-European (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (197,'arm','Ingush');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (198,'arm','Inupiaq');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (199,'arm','Iranian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (200,'arm','Iroquoian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (201,'arm','Italian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (202,'arm','Javanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (203,'arm','Lojban');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (204,'arm','Japanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (205,'arm','Judeo-Persian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (206,'arm','Judeo-Arabic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (207,'arm','Kara-Kalpak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (208,'arm','Kabyle');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (209,'arm','Kachin; Jingpho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (210,'arm','Kalaallisut; Greenlandic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (211,'arm','Kamba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (212,'arm','Kannada');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (213,'arm','Karen languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (214,'arm','Kashmiri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (215,'arm','Kanuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (216,'arm','Kawi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (217,'arm','Kazakh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (218,'arm','Kabardian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (219,'arm','Khasi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (220,'arm','Khoisan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (221,'arm','Central Khmer');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (222,'arm','Khotanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (223,'arm','Kikuyu; Gikuyu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (224,'arm','Kinyarwanda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (225,'arm','Kirghiz; Kyrgyz');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (226,'arm','Kimbundu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (227,'arm','Konkani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (228,'arm','Komi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (229,'arm','Kongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (230,'arm','Korean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (231,'arm','Kosraean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (232,'arm','Kpelle');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (233,'arm','Karachay-Balkar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (234,'arm','Karelian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (235,'arm','Kru languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (236,'arm','Kurukh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (237,'arm','Kuanyama; Kwanyama');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (238,'arm','Kumyk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (239,'arm','Kurdish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (240,'arm','Kutenai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (241,'arm','Ladino');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (242,'arm','Lahnda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (243,'arm','Lamba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (244,'arm','Lao');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (245,'arm','Latin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (246,'arm','Latvian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (247,'arm','Lezghian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (248,'arm','Limburgan; Limburger; Limburgish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (249,'arm','Lingala');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (250,'arm','Lithuanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (251,'arm','Mongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (252,'arm','Lozi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (253,'arm','Luxembourgish; Letzeburgesch');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (254,'arm','Luba-Lulua');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (255,'arm','Luba-Katangaxon, Low');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (256,'arm','Ganda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (257,'arm','Luiseno');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (258,'arm','Lunda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (259,'arm','Luo (Kenya and Tanzania)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (260,'arm','Lushai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (261,'arm','Macedonian00E5l');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (262,'arm','Madurese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (263,'arm','Magahi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (264,'arm','Marshallese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (265,'arm','Maithili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (266,'arm','Makasarl Nepal Bhasa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (267,'arm','Malayalam');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (268,'arm','Mandingo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (269,'arm','Maori');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (270,'arm','Austronesian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (271,'arm','Marathi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (272,'arm','Masai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (273,'arm','Malay');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (274,'arm','Moksha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (275,'arm','Mandar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (276,'arm','Mende');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (277,'arm','Irish, Middle (900-1200)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (278,'arm','Mi''kmaq; Micmac');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (279,'arm','Minangkabau');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (280,'arm','Miscellaneous languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (281,'arm','Mon-Khmer (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (282,'arm','Malagasy');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (283,'arm','Maltese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (284,'arm','Manchu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (285,'arm','Manipuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (286,'arm','Manobo languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (287,'arm','Mohawk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (288,'arm','Moldavian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (289,'arm','Mongolian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (290,'arm','Mossi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (291,'arm','Multiple languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (292,'arm','Munda languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (293,'arm','Creek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (294,'arm','Mirandese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (295,'arm','Marwari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (296,'arm','Mayan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (297,'arm','Erzya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (298,'arm','Nahuatl languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (299,'arm','North American Indian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (300,'arm','Neapolitan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (301,'arm','Nauru');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (302,'arm','Navajo; Navaho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (303,'arm','Ndebele, South; South Ndebele');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (304,'arm','Ndebele, North; North Ndebele');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (305,'arm','Ndonga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (306,'arm','Low German; Low Saxon; German, Low; Sa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (307,'arm','Nepali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (308,'arm','Nepal Bhasa; Newari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (309,'arm','Nias');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (310,'arm','Niger-Kordofanian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (311,'arm','Niuean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (312,'arm','Norwegian Nynorsk; Nynorsk, Norwegian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (313,'arm','Bokmål, Norwegian; Norwegian Bokmål');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (314,'arm','Nogai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (315,'arm','Norse, Old');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (316,'arm','Norwegian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (317,'arm','Pedi; Sepedi; Northern Sotho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (318,'arm','Nubian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (319,'arm','Classical Newari; Old Newari; Classica');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (320,'arm','Chichewa; Chewa; Nyanja');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (321,'arm','Nyamwezi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (322,'arm','Nyankole');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (323,'arm','Nyoro');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (324,'arm','Nzima');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (325,'arm','Occitan (post 1500); Provençal');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (326,'arm','Ojibwa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (327,'arm','Oriya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (328,'arm','Oromo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (329,'arm','Osage');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (330,'arm','Ossetian; Ossetic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (331,'arm','Turkish, Ottoman (1500-1928)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (332,'arm','Otomian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (333,'arm','Papuan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (334,'arm','Pangasinan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (335,'arm','Pahlavi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (336,'arm','Pampanga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (337,'arm','Panjabi; Punjabi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (338,'arm','Papiamento');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (339,'arm','Palauan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (340,'arm','Persian, Old (ca.600-400 B.C.)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (341,'arm','Persian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (342,'arm','Philippine (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (343,'arm','Phoenician');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (344,'arm','Pali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (345,'arm','Polish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (346,'arm','Pohnpeian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (347,'arm','Portuguese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (348,'arm','Prakrit languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (349,'arm','Provençal, Old (to 1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (350,'arm','Pushto');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (351,'arm','Reserved for local use');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (352,'arm','Quechua');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (353,'arm','Rajasthani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (354,'arm','Rapanui');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (355,'arm','Rarotongan; Cook Islands Maori');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (356,'arm','Romance (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (357,'arm','Romansh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (358,'arm','Romany');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (359,'arm','Romanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (360,'arm','Rundi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (361,'arm','Aromanian; Arumanian; Macedo-Romanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (362,'arm','Russian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (363,'arm','Sandawe');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (364,'arm','Sango');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (365,'arm','Yakut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (366,'arm','South American Indian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (367,'arm','Salishan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (368,'arm','Samaritan Aramaic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (369,'arm','Sanskrit');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (370,'arm','Sasak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (371,'arm','Santali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (372,'arm','Serbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (373,'arm','Sicilian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (374,'arm','Scots');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (375,'arm','Croatian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (376,'arm','Selkup');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (377,'arm','Semitic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (378,'arm','Irish, Old (to 900)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (379,'arm','Sign Languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (380,'arm','Shan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (381,'arm','Sidamo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (382,'arm','Sinhala; Sinhalese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (383,'arm','Siouan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (384,'arm','Sino-Tibetan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (385,'arm','Slavic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (386,'arm','Slovak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (387,'arm','Slovenian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (388,'arm','Southern Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (389,'arm','Northern Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (390,'arm','Sami languages (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (391,'arm','Lule Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (392,'arm','Inari Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (393,'arm','Samoan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (394,'arm','Skolt Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (395,'arm','Shona');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (396,'arm','Sindhi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (397,'arm','Soninke');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (398,'arm','Sogdian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (399,'arm','Somali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (400,'arm','Songhai languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (401,'arm','Sotho, Southern');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (402,'arm','Spanish; Castilian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (403,'arm','Sardinian; Zazaki');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (404,'arm','Sranan Tongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (405,'arm','Serer');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (406,'arm','Nilo-Saharan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (407,'arm','Swati');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (408,'arm','Sukuma');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (409,'arm','Sundanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (410,'arm','Susu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (411,'arm','Sumerian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (412,'arm','Swahili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (413,'arm','Swedish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (414,'arm','Syriac');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (415,'arm','Tahitian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (416,'arm','Tai (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (417,'arm','Tamil');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (418,'arm','Tatar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (419,'arm','Telugu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (420,'arm','Timnendere)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (421,'arm','Tereno');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (422,'arm','Tetum');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (423,'arm','Tajik');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (424,'arm','Tagalog');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (425,'arm','Thai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (426,'arm','Tibetan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (427,'arm','Tigre');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (428,'arm','Tigrinya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (429,'arm','Tiv');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (430,'arm','Tokelau');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (431,'arm','Klingon; tlhIngan-Hol');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (432,'arm','Tlingit');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (433,'arm','Tamashek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (434,'arm','Tonga (Nyasa)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (435,'arm','Tonga (Tonga Islands)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (436,'arm','Tok Pisin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (437,'arm','Tsimshian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (438,'arm','Tswana');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (439,'arm','Tsonga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (440,'arm','Turkmen');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (441,'arm','Tumbuka');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (442,'arm','Tupi languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (443,'arm','Turkish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (444,'arm','Altaic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (445,'arm','Tuvalu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (446,'arm','Twi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (447,'arm','Tuvinian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (448,'arm','Udmurt');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (449,'arm','Ugaritic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (450,'arm','Uighur; Uyghur');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (451,'arm','Ukrainian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (452,'arm','Umbundu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (453,'arm','Undetermined');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (454,'arm','Urdu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (455,'arm','Uzbek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (456,'arm','Vai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (457,'arm','Venda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (458,'arm','Vietnamese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (459,'arm','Volapük');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (460,'arm','Votic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (461,'arm','Wakashan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (462,'arm','Walamo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (463,'arm','Waray');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (464,'arm','Washo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (465,'arm','Welsh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (466,'arm','Sorbian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (467,'arm','Walloon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (468,'arm','Wolof');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (469,'arm','Kalmyk; Oirat');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (470,'arm','Xhosa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (471,'arm','Yao');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (472,'arm','Yapese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (473,'arm','Yiddish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (474,'arm','Yoruba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (475,'arm','Yupik languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (476,'arm','Zapotec');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (477,'arm','Zenaga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (478,'arm','Zhuang; Chuang');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (479,'arm','Zande languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (480,'arm','Zulu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (481,'arm','Zuni');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (482,'arm','No linguistic content');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (483,'arm','N''Ko');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (484,'arm','Zaza; Dimili; Dimli; Kirdki; Kirmanjki');

INSERT INTO OperationsDes  (iddes, langid, label) VALUES (0,'arm','Publish');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (1,'arm','Download');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (2,'arm','Editing');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (3,'arm','Notify');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (5,'arm','Interactive Map');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (6,'arm','Featured');

INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (0,'arm','Unknown');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (1,'arm','Draft');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (2,'arm','Approved');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (3,'arm','Retired');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (4,'arm','Submitted');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (5,'arm','Rejected');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (50,'arm','Record created.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (51,'arm','Record updated.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (52,'arm','Attachment {{h.currentStatus}} added.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (53,'arm','Attachment {{h.previousStatus}} deleted.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (54,'arm','Owner changed from {{h.previousStatus}} to {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (55,'arm','Group owner changed from {{h.previousStatus}} to {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (56,'arm','Privileges updated.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (57,'arm','Category changed. Now categories are {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (58,'arm','Validation triggered. Exit status is now {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (59,'arm','Status changed from {{h.previousStatus}} to {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (60,'arm','Record updated by process {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (61,'arm','Record deleted.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (62,'arm','Record imported.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (63,'arm','Record restored.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (100,'arm','DOI creation request');


INSERT INTO SelectionsDes (iddes, langid, label) VALUES (0,'arm','Preferred records');
INSERT INTO SelectionsDes (iddes, langid, label) VALUES (1,'arm','Watch list');

INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (-1,'arm', 'Average');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (0,'arm', 'Completeness#Is the information on this page complete enough to know what you can expect from this dataset?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (1,'arm', 'Discoverability#Was it easy to find this information page?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (2,'arm', 'Readability#Was it easy to read and understand the contents of this page?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (3,'arm', 'Data quality#Does the dataset contain the information you expected, the dataset has enough accuracy, the data is valid/up-to-date?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (4,'arm', 'Service quality#The dataset is provided as a service or mediatype that is easy to work with?');
