--liquibase formatted sql
--changeset francois:00005
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM Languages WHERE id = 'aze';

INSERT INTO Languages (id, name, isinspire) VALUES ('aze','Azərbaycan dili', 'n');

INSERT INTO GroupsDes (iddes, langid, label) VALUES (-1,'aze','Guest');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (0,'aze','Intranet');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (1,'aze','All');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (2,'aze','Sample group');

INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (1,'aze','Afar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (2,'aze','Abkhazian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (3,'aze','Achinese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (4,'aze','Acoli');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (5,'aze','Adangme');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (6,'aze','Adyghe; Adygei');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (7,'aze','Afro-Asiatic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (8,'aze','Afrihili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (9,'aze','Afrikaans');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (10,'aze','Ainu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (11,'aze','Akan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (12,'aze','Akkadian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (13,'aze','Albanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (14,'aze','Aleut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (15,'aze','Algonquian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (16,'aze','Southern Altai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (17,'aze','Amharic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (18,'aze','English, Old (ca.450-1100)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (19,'aze','Angika');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (20,'aze','Apache languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (21,'aze','Arabic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (22,'aze','Aramaic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (23,'aze','Aragonese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (24,'aze','Armenian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (25,'aze','Mapudungun; Mapuche');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (26,'aze','Arapaho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (27,'aze','Artificial (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (28,'aze','Arawak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (29,'aze','Assamese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (30,'aze','Asturian; Bable');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (31,'aze','Athapascan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (32,'aze','Australian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (33,'aze','Avaric');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (34,'aze','Avestan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (35,'aze','Awadhi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (36,'aze','Aymara');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (37,'aze','Azerbaijani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (38,'aze','Banda languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (39,'aze','Bamileke languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (40,'aze','Bashkir');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (41,'aze','Baluchi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (42,'aze','Bambara');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (43,'aze','Balinese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (44,'aze','Basque');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (45,'aze','Basa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (46,'aze','Baltic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (47,'aze','Beja');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (48,'aze','Belarusian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (49,'aze','Bemba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (50,'aze','Bengali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (51,'aze','Berber (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (52,'aze','Bhojpuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (53,'aze','Bihari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (54,'aze','Bikol');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (55,'aze','Bini; Edo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (56,'aze','Bislama');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (57,'aze','Siksika');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (58,'aze','Bantu (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (59,'aze','Bosnian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (60,'aze','Braj');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (61,'aze','Breton');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (62,'aze','Batak languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (63,'aze','Buriat');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (64,'aze','Buginese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (65,'aze','Bulgarian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (66,'aze','Burmese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (67,'aze','Blin; Bilin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (68,'aze','Caddo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (69,'aze','Central American Indian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (70,'aze','Galibi Carib');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (71,'aze','Catalan; Valencian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (72,'aze','Caucasian (Other)on liturgique; vieux bulgare');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (73,'aze','Cebuano');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (74,'aze','Celtic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (75,'aze','Chamorro');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (76,'aze','Chibcha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (77,'aze','Chechen');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (78,'aze','Chagataier)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (79,'aze','Chinese(Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (80,'aze','Chuukese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (81,'aze','Mari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (82,'aze','Chinook jargon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (83,'aze','Choctaw');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (84,'aze','Chipewyan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (85,'aze','Cherokee');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (86,'aze','Church Slavic; Old Slavonic; Church Sl');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (87,'aze','Chuvash');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (88,'aze','Cheyenne');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (89,'aze','Chamic languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (90,'aze','Coptic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (91,'aze','Cornish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (92,'aze','Corsican');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (93,'aze','Creoles and pidgins, English based (Ot');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (94,'aze','Creoles and pidgins, French-based (Oth');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (95,'aze','Creoles and pidgins, Portuguese-based ');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (96,'aze','Cree');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (97,'aze','Crimean Tatar; Crimean Turkish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (98,'aze','Creoles and pidgins (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (99,'aze','Kashubian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (100,'aze','Cushitic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (101,'aze','Czech');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (102,'aze','Dakota');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (103,'aze','Danish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (104,'aze','Dargwa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (105,'aze','Land Dayak languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (106,'aze','Delaware');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (107,'aze','Slave (Athapascan)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (108,'aze','Dogrib');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (109,'aze','Dinka');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (110,'aze','Divehi; Dhivehi; Maldivian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (111,'aze','Dogri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (112,'aze','Dravidian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (113,'aze','Lower Sorbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (114,'aze','Duala');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (115,'aze','Dutch, Middle (ca.1050-1350)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (116,'aze','Dutch; Flemish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (117,'aze','Dyula');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (118,'aze','Dzongkha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (119,'aze','Efik');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (120,'aze','Egyptian (Ancient)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (121,'aze','Ekajuk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (122,'aze','Elamite');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (123,'aze','English');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (124,'aze','English, Middle (1100-1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (125,'aze','Esperanto');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (126,'aze','Estonian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (127,'aze','Ewe');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (128,'aze','Ewondo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (129,'aze','Fang');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (130,'aze','Faroese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (131,'aze','Fanti');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (132,'aze','Fijian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (133,'aze','Filipino; Pilipino');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (134,'aze','Finnish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (135,'aze','Finno-Ugrian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (136,'aze','Fon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (137,'aze','French');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (138,'aze','French, Middle (ca.1400-1600)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (139,'aze','French, Old (842-ca.1400)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (140,'aze','Northern Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (141,'aze','Eastern Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (142,'aze','Western Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (143,'aze','Fulah');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (144,'aze','Friulian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (145,'aze','Ga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (146,'aze','Gayo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (147,'aze','Gbaya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (148,'aze','Germanic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (149,'aze','Georgian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (150,'aze','German');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (151,'aze','Geez');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (152,'aze','Gilbertese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (153,'aze','Gaelic; Scottish Gaelic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (154,'aze','Irish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (155,'aze','Galician');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (156,'aze','Manx');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (157,'aze','German, Middle High (ca.1050-1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (158,'aze','German, Old High (ca.750-1050)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (159,'aze','Gondi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (160,'aze','Gorontalo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (161,'aze','Gothicanguage Association)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (162,'aze','Grebo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (163,'aze','Greek, Ancient (to 1453)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (164,'aze','Greek, Modern (1453-)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (165,'aze','Guarani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (166,'aze','Swiss German; Alemannic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (167,'aze','Gujarati');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (168,'aze','Gwich''in');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (169,'aze','Haida');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (170,'aze','Haitian; Haitian Creole');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (171,'aze','Hausa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (172,'aze','Hawaiian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (173,'aze','Hebrew');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (174,'aze','Herero');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (175,'aze','Hiligaynon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (176,'aze','Himachali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (177,'aze','Hindi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (178,'aze','Hittite');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (179,'aze','Hmong');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (180,'aze','Hiri Motu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (181,'aze','Upper Sorbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (182,'aze','Hungarian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (183,'aze','Hupa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (184,'aze','Iban');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (185,'aze','Igbo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (186,'aze','Icelandic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (187,'aze','Ido');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (188,'aze','Sichuan Yi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (189,'aze','Ijo languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (190,'aze','Inuktitut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (191,'aze','Interlingue');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (192,'aze','Iloko');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (193,'aze','Interlingua (International Auxiliary L');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (194,'aze','Indic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (195,'aze','Indonesian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (196,'aze','Indo-European (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (197,'aze','Ingush');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (198,'aze','Inupiaq');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (199,'aze','Iranian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (200,'aze','Iroquoian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (201,'aze','Italian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (202,'aze','Javanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (203,'aze','Lojban');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (204,'aze','Japanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (205,'aze','Judeo-Persian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (206,'aze','Judeo-Arabic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (207,'aze','Kara-Kalpak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (208,'aze','Kabyle');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (209,'aze','Kachin; Jingpho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (210,'aze','Kalaallisut; Greenlandic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (211,'aze','Kamba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (212,'aze','Kannada');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (213,'aze','Karen languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (214,'aze','Kashmiri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (215,'aze','Kanuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (216,'aze','Kawi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (217,'aze','Kazakh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (218,'aze','Kabardian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (219,'aze','Khasi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (220,'aze','Khoisan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (221,'aze','Central Khmer');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (222,'aze','Khotanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (223,'aze','Kikuyu; Gikuyu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (224,'aze','Kinyarwanda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (225,'aze','Kirghiz; Kyrgyz');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (226,'aze','Kimbundu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (227,'aze','Konkani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (228,'aze','Komi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (229,'aze','Kongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (230,'aze','Korean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (231,'aze','Kosraean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (232,'aze','Kpelle');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (233,'aze','Karachay-Balkar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (234,'aze','Karelian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (235,'aze','Kru languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (236,'aze','Kurukh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (237,'aze','Kuanyama; Kwanyama');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (238,'aze','Kumyk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (239,'aze','Kurdish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (240,'aze','Kutenai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (241,'aze','Ladino');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (242,'aze','Lahnda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (243,'aze','Lamba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (244,'aze','Lao');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (245,'aze','Latin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (246,'aze','Latvian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (247,'aze','Lezghian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (248,'aze','Limburgan; Limburger; Limburgish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (249,'aze','Lingala');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (250,'aze','Lithuanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (251,'aze','Mongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (252,'aze','Lozi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (253,'aze','Luxembourgish; Letzeburgesch');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (254,'aze','Luba-Lulua');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (255,'aze','Luba-Katangaxon, Low');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (256,'aze','Ganda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (257,'aze','Luiseno');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (258,'aze','Lunda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (259,'aze','Luo (Kenya and Tanzania)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (260,'aze','Lushai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (261,'aze','Macedonian00E5l');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (262,'aze','Madurese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (263,'aze','Magahi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (264,'aze','Marshallese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (265,'aze','Maithili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (266,'aze','Makasarl Nepal Bhasa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (267,'aze','Malayalam');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (268,'aze','Mandingo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (269,'aze','Maori');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (270,'aze','Austronesian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (271,'aze','Marathi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (272,'aze','Masai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (273,'aze','Malay');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (274,'aze','Moksha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (275,'aze','Mandar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (276,'aze','Mende');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (277,'aze','Irish, Middle (900-1200)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (278,'aze','Mi''kmaq; Micmac');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (279,'aze','Minangkabau');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (280,'aze','Miscellaneous languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (281,'aze','Mon-Khmer (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (282,'aze','Malagasy');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (283,'aze','Maltese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (284,'aze','Manchu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (285,'aze','Manipuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (286,'aze','Manobo languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (287,'aze','Mohawk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (288,'aze','Moldavian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (289,'aze','Mongolian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (290,'aze','Mossi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (291,'aze','Multiple languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (292,'aze','Munda languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (293,'aze','Creek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (294,'aze','Mirandese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (295,'aze','Marwari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (296,'aze','Mayan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (297,'aze','Erzya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (298,'aze','Nahuatl languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (299,'aze','North American Indian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (300,'aze','Neapolitan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (301,'aze','Nauru');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (302,'aze','Navajo; Navaho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (303,'aze','Ndebele, South; South Ndebele');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (304,'aze','Ndebele, North; North Ndebele');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (305,'aze','Ndonga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (306,'aze','Low German; Low Saxon; German, Low; Sa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (307,'aze','Nepali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (308,'aze','Nepal Bhasa; Newari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (309,'aze','Nias');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (310,'aze','Niger-Kordofanian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (311,'aze','Niuean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (312,'aze','Norwegian Nynorsk; Nynorsk, Norwegian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (313,'aze','Bokmål, Norwegian; Norwegian Bokmål');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (314,'aze','Nogai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (315,'aze','Norse, Old');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (316,'aze','Norwegian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (317,'aze','Pedi; Sepedi; Northern Sotho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (318,'aze','Nubian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (319,'aze','Classical Newari; Old Newari; Classica');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (320,'aze','Chichewa; Chewa; Nyanja');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (321,'aze','Nyamwezi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (322,'aze','Nyankole');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (323,'aze','Nyoro');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (324,'aze','Nzima');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (325,'aze','Occitan (post 1500); Provençal');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (326,'aze','Ojibwa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (327,'aze','Oriya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (328,'aze','Oromo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (329,'aze','Osage');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (330,'aze','Ossetian; Ossetic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (331,'aze','Turkish, Ottoman (1500-1928)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (332,'aze','Otomian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (333,'aze','Papuan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (334,'aze','Pangasinan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (335,'aze','Pahlavi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (336,'aze','Pampanga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (337,'aze','Panjabi; Punjabi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (338,'aze','Papiamento');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (339,'aze','Palauan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (340,'aze','Persian, Old (ca.600-400 B.C.)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (341,'aze','Persian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (342,'aze','Philippine (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (343,'aze','Phoenician');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (344,'aze','Pali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (345,'aze','Polish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (346,'aze','Pohnpeian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (347,'aze','Portuguese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (348,'aze','Prakrit languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (349,'aze','Provençal, Old (to 1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (350,'aze','Pushto');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (351,'aze','Reserved for local use');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (352,'aze','Quechua');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (353,'aze','Rajasthani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (354,'aze','Rapanui');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (355,'aze','Rarotongan; Cook Islands Maori');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (356,'aze','Romance (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (357,'aze','Romansh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (358,'aze','Romany');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (359,'aze','Romanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (360,'aze','Rundi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (361,'aze','Aromanian; Arumanian; Macedo-Romanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (362,'aze','Russian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (363,'aze','Sandawe');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (364,'aze','Sango');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (365,'aze','Yakut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (366,'aze','South American Indian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (367,'aze','Salishan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (368,'aze','Samaritan Aramaic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (369,'aze','Sanskrit');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (370,'aze','Sasak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (371,'aze','Santali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (372,'aze','Serbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (373,'aze','Sicilian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (374,'aze','Scots');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (375,'aze','Croatian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (376,'aze','Selkup');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (377,'aze','Semitic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (378,'aze','Irish, Old (to 900)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (379,'aze','Sign Languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (380,'aze','Shan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (381,'aze','Sidamo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (382,'aze','Sinhala; Sinhalese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (383,'aze','Siouan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (384,'aze','Sino-Tibetan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (385,'aze','Slavic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (386,'aze','Slovak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (387,'aze','Slovenian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (388,'aze','Southern Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (389,'aze','Northern Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (390,'aze','Sami languages (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (391,'aze','Lule Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (392,'aze','Inari Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (393,'aze','Samoan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (394,'aze','Skolt Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (395,'aze','Shona');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (396,'aze','Sindhi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (397,'aze','Soninke');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (398,'aze','Sogdian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (399,'aze','Somali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (400,'aze','Songhai languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (401,'aze','Sotho, Southern');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (402,'aze','Spanish; Castilian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (403,'aze','Sardinian; Zazaki');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (404,'aze','Sranan Tongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (405,'aze','Serer');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (406,'aze','Nilo-Saharan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (407,'aze','Swati');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (408,'aze','Sukuma');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (409,'aze','Sundanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (410,'aze','Susu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (411,'aze','Sumerian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (412,'aze','Swahili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (413,'aze','Swedish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (414,'aze','Syriac');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (415,'aze','Tahitian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (416,'aze','Tai (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (417,'aze','Tamil');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (418,'aze','Tatar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (419,'aze','Telugu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (420,'aze','Timnendere)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (421,'aze','Tereno');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (422,'aze','Tetum');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (423,'aze','Tajik');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (424,'aze','Tagalog');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (425,'aze','Thai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (426,'aze','Tibetan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (427,'aze','Tigre');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (428,'aze','Tigrinya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (429,'aze','Tiv');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (430,'aze','Tokelau');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (431,'aze','Klingon; tlhIngan-Hol');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (432,'aze','Tlingit');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (433,'aze','Tamashek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (434,'aze','Tonga (Nyasa)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (435,'aze','Tonga (Tonga Islands)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (436,'aze','Tok Pisin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (437,'aze','Tsimshian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (438,'aze','Tswana');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (439,'aze','Tsonga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (440,'aze','Turkmen');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (441,'aze','Tumbuka');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (442,'aze','Tupi languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (443,'aze','Turkish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (444,'aze','Altaic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (445,'aze','Tuvalu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (446,'aze','Twi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (447,'aze','Tuvinian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (448,'aze','Udmurt');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (449,'aze','Ugaritic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (450,'aze','Uighur; Uyghur');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (451,'aze','Ukrainian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (452,'aze','Umbundu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (453,'aze','Undetermined');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (454,'aze','Urdu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (455,'aze','Uzbek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (456,'aze','Vai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (457,'aze','Venda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (458,'aze','Vietnamese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (459,'aze','Volapük');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (460,'aze','Votic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (461,'aze','Wakashan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (462,'aze','Walamo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (463,'aze','Waray');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (464,'aze','Washo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (465,'aze','Welsh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (466,'aze','Sorbian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (467,'aze','Walloon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (468,'aze','Wolof');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (469,'aze','Kalmyk; Oirat');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (470,'aze','Xhosa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (471,'aze','Yao');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (472,'aze','Yapese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (473,'aze','Yiddish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (474,'aze','Yoruba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (475,'aze','Yupik languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (476,'aze','Zapotec');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (477,'aze','Zenaga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (478,'aze','Zhuang; Chuang');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (479,'aze','Zande languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (480,'aze','Zulu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (481,'aze','Zuni');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (482,'aze','No linguistic content');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (483,'aze','N''Ko');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (484,'aze','Zaza; Dimili; Dimli; Kirdki; Kirmanjki');

INSERT INTO OperationsDes  (iddes, langid, label) VALUES (0,'aze','Publish');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (1,'aze','Download');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (2,'aze','Editing');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (3,'aze','Notify');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (5,'aze','Interactive Map');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (6,'aze','Featured');

INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (0,'aze','Unknown');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (1,'aze','Draft');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (2,'aze','Approved');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (3,'aze','Retired');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (4,'aze','Submitted');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (5,'aze','Rejected');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (50,'aze','Record created.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (51,'aze','Record updated.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (52,'aze','Attachment {{h.currentStatus}} added.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (53,'aze','Attachment {{h.previousStatus}} deleted.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (54,'aze','Owner changed from {{h.previousStatus}} to {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (55,'aze','Group owner changed from {{h.previousStatus}} to {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (56,'aze','Privileges updated.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (57,'aze','Category changed. Now categories are {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (58,'aze','Validation triggered. Exit status is now {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (59,'aze','Status changed from {{h.previousStatus}} to {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (60,'aze','Record updated by process {{h.currentStatus}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (61,'aze','Record deleted.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (62,'aze','Record imported.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (63,'aze','Record restored.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (100,'aze','DOI creation request');


INSERT INTO SelectionsDes (iddes, langid, label) VALUES (0,'aze','Preferred records');
INSERT INTO SelectionsDes (iddes, langid, label) VALUES (1,'aze','Watch list');

INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (-1,'aze', 'Average');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (0,'aze', 'Completeness#Is the information on this page complete enough to know what you can expect from this dataset?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (1,'aze', 'Discoverability#Was it easy to find this information page?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (2,'aze', 'Readability#Was it easy to read and understand the contents of this page?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (3,'aze', 'Data quality#Does the dataset contain the information you expected, the dataset has enough accuracy, the data is valid/up-to-date?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (4,'aze', 'Service quality#The dataset is provided as a service or mediatype that is easy to work with?');
