--liquibase formatted sql
--changeset francois:00017
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM Languages WHERE id = 'pol';

INSERT INTO Languages (id, name, isinspire) VALUES ('pol','Polski', 'n');

INSERT INTO GroupsDes (iddes, langid, label) VALUES (-1,'pol','Gość');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (0,'pol','Intranet');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (1,'pol','Wszyscy');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (2,'pol','Przykładowa grupa');

INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (1,'pol','Afar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (2,'pol','Abkhazian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (3,'pol','Achinese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (4,'pol','Acoli');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (5,'pol','Adangme');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (6,'pol','Adyghe; Adygei');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (7,'pol','Afro-Asiatic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (8,'pol','Afrihili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (9,'pol','Afrikaans');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (10,'pol','Ainu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (11,'pol','Akan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (12,'pol','Akkadian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (13,'pol','Albanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (14,'pol','Aleut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (15,'pol','Algonquian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (16,'pol','Southern Altai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (17,'pol','Amharic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (18,'pol','English, Old (ca.450-1100)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (19,'pol','Angika');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (20,'pol','Apache languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (21,'pol','Arabic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (22,'pol','Aramaic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (23,'pol','Aragonese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (24,'pol','Armenian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (25,'pol','Mapudungun; Mapuche');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (26,'pol','Arapaho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (27,'pol','Artificial (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (28,'pol','Arawak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (29,'pol','Assamese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (30,'pol','Asturian; Bable');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (31,'pol','Athapascan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (32,'pol','Australian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (33,'pol','Avaric');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (34,'pol','Avestan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (35,'pol','Awadhi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (36,'pol','Aymara');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (37,'pol','Azerbaijani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (38,'pol','Banda languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (39,'pol','Bamileke languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (40,'pol','Bashkir');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (41,'pol','Baluchi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (42,'pol','Bambara');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (43,'pol','Balinese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (44,'pol','Basque');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (45,'pol','Basa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (46,'pol','Baltic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (47,'pol','Beja');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (48,'pol','Belarusian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (49,'pol','Bemba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (50,'pol','Bengali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (51,'pol','Berber (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (52,'pol','Bhojpuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (53,'pol','Bihari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (54,'pol','Bikol');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (55,'pol','Bini; Edo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (56,'pol','Bislama');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (57,'pol','Siksika');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (58,'pol','Bantu (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (59,'pol','Bosnian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (60,'pol','Braj');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (61,'pol','Breton');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (62,'pol','Batak languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (63,'pol','Buriat');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (64,'pol','Buginese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (65,'pol','Bulgarian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (66,'pol','Burmese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (67,'pol','Blin; Bilin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (68,'pol','Caddo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (69,'pol','Central American Indian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (70,'pol','Galibi Carib');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (71,'pol','Catalan; Valencian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (72,'pol','Caucasian (Other)on liturgique; vieux bulgare');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (73,'pol','Cebuano');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (74,'pol','Celtic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (75,'pol','Chamorro');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (76,'pol','Chibcha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (77,'pol','Chechen');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (78,'pol','Chagataier)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (79,'pol','Chinese(Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (80,'pol','Chuukese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (81,'pol','Mari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (82,'pol','Chinook jargon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (83,'pol','Choctaw');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (84,'pol','Chipewyan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (85,'pol','Cherokee');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (86,'pol','Church Slavic; Old Slavonic; Church Sl');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (87,'pol','Chuvash');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (88,'pol','Cheyenne');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (89,'pol','Chamic languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (90,'pol','Coptic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (91,'pol','Cornish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (92,'pol','Corsican');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (93,'pol','Creoles and pidgins, English based (Ot');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (94,'pol','Creoles and pidgins, French-based (Oth');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (95,'pol','Creoles and pidgins, Portuguese-based ');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (96,'pol','Cree');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (97,'pol','Crimean Tatar; Crimean Turkish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (98,'pol','Creoles and pidgins (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (99,'pol','Kashubian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (100,'pol','Cushitic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (101,'pol','Czech');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (102,'pol','Dakota');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (103,'pol','Danish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (104,'pol','Dargwa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (105,'pol','Land Dayak languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (106,'pol','Delaware');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (107,'pol','Slave (Athapascan)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (108,'pol','Dogrib');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (109,'pol','Dinka');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (110,'pol','Divehi; Dhivehi; Maldivian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (111,'pol','Dogri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (112,'pol','Dravidian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (113,'pol','Lower Sorbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (114,'pol','Duala');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (115,'pol','Dutch, Middle (ca.1050-1350)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (116,'pol','Dutch; Flemish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (117,'pol','Dyula');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (118,'pol','Dzongkha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (119,'pol','Efik');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (120,'pol','Egyptian (Ancient)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (121,'pol','Ekajuk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (122,'pol','Elamite');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (123,'pol','English');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (124,'pol','English, Middle (1100-1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (125,'pol','Esperanto');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (126,'pol','Estonian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (127,'pol','Ewe');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (128,'pol','Ewondo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (129,'pol','Fang');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (130,'pol','Faroese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (131,'pol','Fanti');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (132,'pol','Fijian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (133,'pol','Filipino; Pilipino');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (134,'pol','Finnish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (135,'pol','Finno-Ugrian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (136,'pol','Fon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (137,'pol','French');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (138,'pol','French, Middle (ca.1400-1600)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (139,'pol','French, Old (842-ca.1400)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (140,'pol','Northern Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (141,'pol','Eastern Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (142,'pol','Western Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (143,'pol','Fulah');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (144,'pol','Friulian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (145,'pol','Ga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (146,'pol','Gayo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (147,'pol','Gbaya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (148,'pol','Germanic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (149,'pol','Georgian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (150,'pol','German');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (151,'pol','Geez');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (152,'pol','Gilbertese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (153,'pol','Gaelic; Scottish Gaelic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (154,'pol','Irish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (155,'pol','Galician');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (156,'pol','Manx');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (157,'pol','German, Middle High (ca.1050-1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (158,'pol','German, Old High (ca.750-1050)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (159,'pol','Gondi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (160,'pol','Gorontalo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (161,'pol','Gothicanguage Association)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (162,'pol','Grebo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (163,'pol','Greek, Ancient (to 1453)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (164,'pol','Greek, Modern (1453-)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (165,'pol','Guarani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (166,'pol','Swiss German; Alemannic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (167,'pol','Gujarati');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (168,'pol','Gwich''in');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (169,'pol','Haida');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (170,'pol','Haitian; Haitian Creole');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (171,'pol','Hausa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (172,'pol','Hawaiian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (173,'pol','Hebrew');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (174,'pol','Herero');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (175,'pol','Hiligaynon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (176,'pol','Himachali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (177,'pol','Hindi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (178,'pol','Hittite');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (179,'pol','Hmong');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (180,'pol','Hiri Motu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (181,'pol','Upper Sorbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (182,'pol','Hungarian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (183,'pol','Hupa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (184,'pol','Iban');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (185,'pol','Igbo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (186,'pol','Icelandic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (187,'pol','Ido');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (188,'pol','Sichuan Yi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (189,'pol','Ijo languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (190,'pol','Inuktitut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (191,'pol','Interlingue');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (192,'pol','Iloko');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (193,'pol','Interlingua (International Auxiliary L');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (194,'pol','Indic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (195,'pol','Indonesian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (196,'pol','Indo-European (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (197,'pol','Ingush');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (198,'pol','Inupiaq');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (199,'pol','Iranian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (200,'pol','Iroquoian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (201,'pol','Italian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (202,'pol','Javanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (203,'pol','Lojban');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (204,'pol','Japanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (205,'pol','Judeo-Persian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (206,'pol','Judeo-Arabic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (207,'pol','Kara-Kalpak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (208,'pol','Kabyle');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (209,'pol','Kachin; Jingpho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (210,'pol','Kalaallisut; Greenlandic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (211,'pol','Kamba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (212,'pol','Kannada');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (213,'pol','Karen languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (214,'pol','Kashmiri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (215,'pol','Kanuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (216,'pol','Kawi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (217,'pol','Kazakh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (218,'pol','Kabardian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (219,'pol','Khasi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (220,'pol','Khoisan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (221,'pol','Central Khmer');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (222,'pol','Khotanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (223,'pol','Kikuyu; Gikuyu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (224,'pol','Kinyarwanda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (225,'pol','Kirghiz; Kyrgyz');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (226,'pol','Kimbundu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (227,'pol','Konkani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (228,'pol','Komi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (229,'pol','Kongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (230,'pol','Korean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (231,'pol','Kosraean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (232,'pol','Kpelle');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (233,'pol','Karachay-Balkar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (234,'pol','Karelian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (235,'pol','Kru languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (236,'pol','Kurukh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (237,'pol','Kuanyama; Kwanyama');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (238,'pol','Kumyk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (239,'pol','Kurdish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (240,'pol','Kutenai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (241,'pol','Ladino');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (242,'pol','Lahnda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (243,'pol','Lamba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (244,'pol','Lao');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (245,'pol','Latin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (246,'pol','Latvian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (247,'pol','Lezghian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (248,'pol','Limburgan; Limburger; Limburgish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (249,'pol','Lingala');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (250,'pol','Lithuanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (251,'pol','Mongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (252,'pol','Lozi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (253,'pol','Luxembourgish; Letzeburgesch');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (254,'pol','Luba-Lulua');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (255,'pol','Luba-Katangaxon, Low');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (256,'pol','Ganda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (257,'pol','Luiseno');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (258,'pol','Lunda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (259,'pol','Luo (Kenya and Tanzania)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (260,'pol','Lushai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (261,'pol','Macedonian00E5l');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (262,'pol','Madurese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (263,'pol','Magahi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (264,'pol','Marshallese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (265,'pol','Maithili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (266,'pol','Makasarl Nepal Bhasa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (267,'pol','Malayalam');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (268,'pol','Mandingo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (269,'pol','Maori');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (270,'pol','Austronesian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (271,'pol','Marathi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (272,'pol','Masai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (273,'pol','Malay');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (274,'pol','Moksha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (275,'pol','Mandar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (276,'pol','Mende');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (277,'pol','Irish, Middle (900-1200)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (278,'pol','Mi''kmaq; Micmac');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (279,'pol','Minangkabau');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (280,'pol','Miscellaneous languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (281,'pol','Mon-Khmer (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (282,'pol','Malagasy');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (283,'pol','Maltese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (284,'pol','Manchu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (285,'pol','Manipuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (286,'pol','Manobo languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (287,'pol','Mohawk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (288,'pol','Moldavian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (289,'pol','Mongolian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (290,'pol','Mossi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (291,'pol','Multiple languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (292,'pol','Munda languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (293,'pol','Creek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (294,'pol','Mirandese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (295,'pol','Marwari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (296,'pol','Mayan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (297,'pol','Erzya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (298,'pol','Nahuatl languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (299,'pol','North American Indian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (300,'pol','Neapolitan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (301,'pol','Nauru');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (302,'pol','Navajo; Navaho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (303,'pol','Ndebele, South; South Ndebele');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (304,'pol','Ndebele, North; North Ndebele');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (305,'pol','Ndonga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (306,'pol','Low German; Low Saxon; German, Low; Sa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (307,'pol','Nepali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (308,'pol','Nepal Bhasa; Newari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (309,'pol','Nias');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (310,'pol','Niger-Kordofanian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (311,'pol','Niuean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (312,'pol','Norwegian Nynorsk; Nynorsk, Norwegian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (313,'pol','Bokmål, Norwegian; Norwegian Bokmål');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (314,'pol','Nogai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (315,'pol','Norse, Old');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (316,'pol','Norwegian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (317,'pol','Pedi; Sepedi; Northern Sotho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (318,'pol','Nubian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (319,'pol','Classical Newari; Old Newari; Classica');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (320,'pol','Chichewa; Chewa; Nyanja');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (321,'pol','Nyamwezi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (322,'pol','Nyankole');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (323,'pol','Nyoro');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (324,'pol','Nzima');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (325,'pol','Occitan (post 1500); Provençal');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (326,'pol','Ojibwa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (327,'pol','Oriya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (328,'pol','Oromo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (329,'pol','Osage');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (330,'pol','Ossetian; Ossetic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (331,'pol','Turkish, Ottoman (1500-1928)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (332,'pol','Otomian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (333,'pol','Papuan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (334,'pol','Pangasinan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (335,'pol','Pahlavi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (336,'pol','Pampanga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (337,'pol','Panjabi; Punjabi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (338,'pol','Papiamento');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (339,'pol','Palauan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (340,'pol','Persian, Old (ca.600-400 B.C.)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (341,'pol','Persian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (342,'pol','Philippine (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (343,'pol','Phoenician');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (344,'pol','Pali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (345,'pol','Polish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (346,'pol','Pohnpeian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (347,'pol','Portuguese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (348,'pol','Prakrit languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (349,'pol','Provençal, Old (to 1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (350,'pol','Pushto');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (351,'pol','Reserved for local use');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (352,'pol','Quechua');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (353,'pol','Rajasthani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (354,'pol','Rapanui');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (355,'pol','Rarotongan; Cook Islands Maori');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (356,'pol','Romance (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (357,'pol','Romansh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (358,'pol','Romany');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (359,'pol','Romanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (360,'pol','Rundi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (361,'pol','Aromanian; Arumanian; Macedo-Romanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (362,'pol','Russian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (363,'pol','Sandawe');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (364,'pol','Sango');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (365,'pol','Yakut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (366,'pol','South American Indian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (367,'pol','Salishan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (368,'pol','Samaritan Aramaic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (369,'pol','Sanskrit');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (370,'pol','Sasak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (371,'pol','Santali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (372,'pol','Serbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (373,'pol','Sicilian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (374,'pol','Scots');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (375,'pol','Croatian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (376,'pol','Selkup');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (377,'pol','Semitic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (378,'pol','Irish, Old (to 900)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (379,'pol','Sign Languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (380,'pol','Shan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (381,'pol','Sidamo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (382,'pol','Sinhala; Sinhalese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (383,'pol','Siouan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (384,'pol','Sino-Tibetan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (385,'pol','Slavic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (386,'pol','Slovak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (387,'pol','Slovenian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (388,'pol','Southern Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (389,'pol','Northern Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (390,'pol','Sami languages (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (391,'pol','Lule Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (392,'pol','Inari Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (393,'pol','Samoan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (394,'pol','Skolt Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (395,'pol','Shona');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (396,'pol','Sindhi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (397,'pol','Soninke');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (398,'pol','Sogdian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (399,'pol','Somali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (400,'pol','Songhai languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (401,'pol','Sotho, Southern');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (402,'pol','Spanish; Castilian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (403,'pol','Sardinian; Zazaki');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (404,'pol','Sranan Tongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (405,'pol','Serer');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (406,'pol','Nilo-Saharan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (407,'pol','Swati');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (408,'pol','Sukuma');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (409,'pol','Sundanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (410,'pol','Susu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (411,'pol','Sumerian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (412,'pol','Swahili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (413,'pol','Swedish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (414,'pol','Syriac');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (415,'pol','Tahitian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (416,'pol','Tai (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (417,'pol','Tamil');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (418,'pol','Tatar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (419,'pol','Telugu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (420,'pol','Timnendere)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (421,'pol','Tereno');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (422,'pol','Tetum');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (423,'pol','Tajik');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (424,'pol','Tagalog');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (425,'pol','Thai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (426,'pol','Tibetan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (427,'pol','Tigre');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (428,'pol','Tigrinya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (429,'pol','Tiv');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (430,'pol','Tokelau');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (431,'pol','Klingon; tlhIngan-Hol');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (432,'pol','Tlingit');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (433,'pol','Tamashek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (434,'pol','Tonga (Nyasa)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (435,'pol','Tonga (Tonga Islands)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (436,'pol','Tok Pisin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (437,'pol','Tsimshian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (438,'pol','Tswana');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (439,'pol','Tsonga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (440,'pol','Turkmen');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (441,'pol','Tumbuka');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (442,'pol','Tupi languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (443,'pol','Turkish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (444,'pol','Altaic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (445,'pol','Tuvalu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (446,'pol','Twi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (447,'pol','Tuvinian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (448,'pol','Udmurt');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (449,'pol','Ugaritic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (450,'pol','Uighur; Uyghur');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (451,'pol','Ukrainian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (452,'pol','Umbundu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (453,'pol','Undetermined');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (454,'pol','Urdu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (455,'pol','Uzbek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (456,'pol','Vai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (457,'pol','Venda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (458,'pol','Vietnamese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (459,'pol','Volapük');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (460,'pol','Votic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (461,'pol','Wakashan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (462,'pol','Walamo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (463,'pol','Waray');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (464,'pol','Washo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (465,'pol','Welsh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (466,'pol','Sorbian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (467,'pol','Walloon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (468,'pol','Wolof');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (469,'pol','Kalmyk; Oirat');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (470,'pol','Xhosa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (471,'pol','Yao');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (472,'pol','Yapese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (473,'pol','Yiddish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (474,'pol','Yoruba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (475,'pol','Yupik languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (476,'pol','Zapotec');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (477,'pol','Zenaga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (478,'pol','Zhuang; Chuang');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (479,'pol','Zande languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (480,'pol','Zulu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (481,'pol','Zuni');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (482,'pol','No linguistic content');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (483,'pol','N''Ko');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (484,'pol','Zaza; Dimili; Dimli; Kirdki; Kirmanjki');

INSERT INTO OperationsDes  (iddes, langid, label) VALUES (0,'pol','Publikacja');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (1,'pol','Pobieranie');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (2,'pol','Edycja');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (3,'pol','Powiadamianie');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (5,'pol','Mapy interaktywne');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (6,'pol','Wyróżnione');

INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (0,'pol','Nieznany');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (1,'pol','Draft');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (2,'pol','Zaaprobowana');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (3,'pol','Porzucone');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (4,'pol','Załadowane');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (5,'pol','Odrzucone');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (50,'pol','Record created.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (51,'pol','Record updated.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (52,'pol','Attachment {{h.item1}} added.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (53,'pol','Attachment {{h.item1}} deleted.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (54,'pol','Owner changed from {{h.item1}} to {{h.item2}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (55,'pol','Group owner changed from {{h.item1}} to {{h.item2}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (56,'pol','Privileges updated.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (57,'pol','Category changed. Now categories are {{h.item1}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (58,'pol','Validation triggered. Exit status is now {{h.item1}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (59,'pol','Status changed from {{h.item1}} to {{h.item2}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (60,'pol','Record updated by process {{h.item1}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (61,'pol','Record deleted.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (62,'pol','Record imported.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (63,'pol','Record restored.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (100,'pol','DOI creation requested.');


INSERT INTO SelectionsDes (iddes, langid, label) VALUES (0,'pol','Preferred records');
INSERT INTO SelectionsDes (iddes, langid, label) VALUES (1,'pol','Watch list');


INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (-1,'pol', 'Average');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (0,'pol', 'Completeness#Is the information on this page complete enough to know what you can expect from this dataset?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (1,'pol', 'Discoverability#Was it easy to find this information page?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (2,'pol', 'Readability#Was it easy to read and understand the contents of this page?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (3,'pol', 'Data quality#Does the dataset contain the information you expected, the dataset has enough accuracy, the data is valid/up-to-date?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (4,'pol', 'Service quality#The dataset is provided as a service or mediatype that is easy to work with?');
