--liquibase formatted sql
--changeset francois:00022
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM Languages WHERE id = 'spa';

INSERT INTO Languages (id, name, isinspire) VALUES ('spa','español', 'y');

INSERT INTO GroupsDes (iddes, langid, label) VALUES (-1,'spa','Guest');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (0,'spa','Intranet');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (1,'spa','Todos');
INSERT INTO GroupsDes (iddes, langid, label) VALUES (2,'spa','Grupo de ejemplo');

INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (1,'spa','Afar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (2,'spa','Abkhazian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (3,'spa','Achinese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (4,'spa','Acoli');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (5,'spa','Adangme');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (6,'spa','Adyghe; Adygei');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (7,'spa','Afro-Asiatic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (8,'spa','Afrihili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (9,'spa','Afrikaans');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (10,'spa','Ainu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (11,'spa','Akan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (12,'spa','Akkadian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (13,'spa','Albanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (14,'spa','Aleut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (15,'spa','Algonquian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (16,'spa','Southern Altai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (17,'spa','Amharic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (18,'spa','English, Old (ca.450-1100)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (19,'spa','Angika');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (20,'spa','Apache languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (21,'spa','Arabic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (22,'spa','Aramaic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (23,'spa','Aragonese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (24,'spa','Armenian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (25,'spa','Mapudungun; Mapuche');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (26,'spa','Arapaho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (27,'spa','Artificial (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (28,'spa','Arawak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (29,'spa','Assamese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (30,'spa','Asturian; Bable');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (31,'spa','Athapascan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (32,'spa','Australian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (33,'spa','Avaric');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (34,'spa','Avestan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (35,'spa','Awadhi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (36,'spa','Aymara');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (37,'spa','Azerbaijani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (38,'spa','Banda languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (39,'spa','Bamileke languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (40,'spa','Bashkir');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (41,'spa','Baluchi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (42,'spa','Bambara');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (43,'spa','Balinese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (44,'spa','Basque');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (45,'spa','Basa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (46,'spa','Baltic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (47,'spa','Beja');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (48,'spa','Belarusian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (49,'spa','Bemba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (50,'spa','Bengali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (51,'spa','Berber (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (52,'spa','Bhojpuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (53,'spa','Bihari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (54,'spa','Bikol');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (55,'spa','Bini; Edo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (56,'spa','Bislama');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (57,'spa','Siksika');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (58,'spa','Bantu (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (59,'spa','Bosnian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (60,'spa','Braj');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (61,'spa','Breton');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (62,'spa','Batak languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (63,'spa','Buriat');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (64,'spa','Buginese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (65,'spa','Bulgarian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (66,'spa','Burmese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (67,'spa','Blin; Bilin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (68,'spa','Caddo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (69,'spa','Central American Indian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (70,'spa','Galibi Carib');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (71,'spa','Catalan; Valencian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (72,'spa','Caucasian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (73,'spa','Cebuano');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (74,'spa','Celtic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (75,'spa','Chamorro');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (76,'spa','Chibcha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (77,'spa','Chechenher)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (78,'spa','Chagataier)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (79,'spa','Chinese(Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (80,'spa','Chuukese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (81,'spa','Mari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (82,'spa','Chinook jargon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (83,'spa','Choctaw');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (84,'spa','Chipewyan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (85,'spa','Cherokee');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (86,'spa','Church Slavic; Old Slavonic; Church Sl');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (87,'spa','Chuvash');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (88,'spa','Cheyenne');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (89,'spa','Chamic languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (90,'spa','Coptic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (91,'spa','Cornish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (92,'spa','Corsican');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (93,'spa','Creoles and pidgins, English based (Ot');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (94,'spa','Creoles and pidgins, French-based (Oth');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (95,'spa','Creoles and pidgins, Portuguese-based ');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (96,'spa','Cree');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (97,'spa','Crimean Tatar; Crimean Turkish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (98,'spa','Creoles and pidgins (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (99,'spa','Kashubian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (100,'spa','Cushitic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (101,'spa','Czech');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (102,'spa','Dakota');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (103,'spa','Danish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (104,'spa','Dargwa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (105,'spa','Land Dayak languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (106,'spa','Delaware');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (107,'spa','Slave (Athapascan)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (108,'spa','Dogrib');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (109,'spa','Dinka');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (110,'spa','Divehi; Dhivehi; Maldivian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (111,'spa','Dogri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (112,'spa','Dravidian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (113,'spa','Lower Sorbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (114,'spa','Duala');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (115,'spa','Dutch, Middle (ca.1050-1350)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (116,'spa','Dutch; Flemish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (117,'spa','Dyula');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (118,'spa','Dzongkha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (119,'spa','Efik');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (120,'spa','Egyptian (Ancient)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (121,'spa','Ekajuk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (122,'spa','Elamite');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (123,'spa','English');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (124,'spa','English, Middle (1100-1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (125,'spa','Esperanto');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (126,'spa','Estonian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (127,'spa','Ewe');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (128,'spa','Ewondo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (129,'spa','Fang');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (130,'spa','Faroese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (131,'spa','Fanti');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (132,'spa','Fijian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (133,'spa','Filipino; Pilipino');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (134,'spa','Finnish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (135,'spa','Finno-Ugrian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (136,'spa','Fon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (137,'spa','French');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (138,'spa','French, Middle (ca.1400-1600)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (139,'spa','French, Old (842-ca.1400)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (140,'spa','Northern Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (141,'spa','Eastern Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (142,'spa','Western Frisian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (143,'spa','Fulah');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (144,'spa','Friulian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (145,'spa','Ga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (146,'spa','Gayo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (147,'spa','Gbaya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (148,'spa','Germanic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (149,'spa','Georgian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (150,'spa','German');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (151,'spa','Geez');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (152,'spa','Gilbertese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (153,'spa','Gaelic; Scottish Gaelic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (154,'spa','Irish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (155,'spa','Galician');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (156,'spa','Manx');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (157,'spa','German, Middle High (ca.1050-1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (158,'spa','German, Old High (ca.750-1050)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (159,'spa','Gondi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (160,'spa','Gorontalo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (161,'spa','Gothictionale)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (162,'spa','Grebo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (163,'spa','Greek, Ancient (to 1453)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (164,'spa','Greek, Modern (1453-)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (165,'spa','Guarani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (166,'spa','Swiss German; Alemannic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (167,'spa','Gujarati');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (168,'spa','Gwich''in');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (169,'spa','Haida');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (170,'spa','Haitian; Haitian Creole');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (171,'spa','Hausa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (172,'spa','Hawaiian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (173,'spa','Hebrew');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (174,'spa','Herero');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (175,'spa','Hiligaynon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (176,'spa','Himachali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (177,'spa','Hindi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (178,'spa','Hittite');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (179,'spa','Hmong');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (180,'spa','Hiri Motu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (181,'spa','Upper Sorbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (182,'spa','Hungarian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (183,'spa','Hupa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (184,'spa','Iban');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (185,'spa','Igbo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (186,'spa','Icelandic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (187,'spa','Ido');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (188,'spa','Sichuan Yi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (189,'spa','Ijo languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (190,'spa','Inuktitut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (191,'spa','Interlingue');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (192,'spa','Iloko');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (193,'spa','Interlingua (International Auxiliary L');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (194,'spa','Indic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (195,'spa','Indonesian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (196,'spa','Indo-European (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (197,'spa','Ingush');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (198,'spa','Inupiaq');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (199,'spa','Iranian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (200,'spa','Iroquoian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (201,'spa','Italian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (202,'spa','Javanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (203,'spa','Lojban');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (204,'spa','Japanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (205,'spa','Judeo-Persian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (206,'spa','Judeo-Arabic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (207,'spa','Kara-Kalpak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (208,'spa','Kabyle');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (209,'spa','Kachin; Jingpho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (210,'spa','Kalaallisut; Greenlandic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (211,'spa','Kamba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (212,'spa','Kannada');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (213,'spa','Karen languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (214,'spa','Kashmiri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (215,'spa','Kanuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (216,'spa','Kawi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (217,'spa','Kazakh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (218,'spa','Kabardian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (219,'spa','Khasi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (220,'spa','Khoisan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (221,'spa','Central Khmer');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (222,'spa','Khotanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (223,'spa','Kikuyu; Gikuyu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (224,'spa','Kinyarwanda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (225,'spa','Kirghiz; Kyrgyz');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (226,'spa','Kimbundu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (227,'spa','Konkani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (228,'spa','Komi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (229,'spa','Kongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (230,'spa','Korean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (231,'spa','Kosraean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (232,'spa','Kpelle');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (233,'spa','Karachay-Balkar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (234,'spa','Karelian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (235,'spa','Kru languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (236,'spa','Kurukh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (237,'spa','Kuanyama; Kwanyama');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (238,'spa','Kumyk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (239,'spa','Kurdish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (240,'spa','Kutenai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (241,'spa','Ladino');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (242,'spa','Lahnda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (243,'spa','Lamba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (244,'spa','Lao');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (245,'spa','Latin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (246,'spa','Latvian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (247,'spa','Lezghian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (248,'spa','Limburgan; Limburger; Limburgish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (249,'spa','Lingala');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (250,'spa','Lithuanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (251,'spa','Mongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (252,'spa','Lozi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (253,'spa','Luxembourgish; Letzeburgesch');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (254,'spa','Luba-Lulua');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (255,'spa','Luba-Katangaxon, Low');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (256,'spa','Ganda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (257,'spa','Luiseno');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (258,'spa','Lunda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (259,'spa','Luo (Kenya and Tanzania)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (260,'spa','Lushai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (261,'spa','Macedonian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (262,'spa','Madurese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (263,'spa','Magahi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (264,'spa','Marshallese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (265,'spa','Maithili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (266,'spa','Makasar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (267,'spa','Malayalam');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (268,'spa','Mandingo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (269,'spa','Maori');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (270,'spa','Austronesian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (271,'spa','Marathil');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (272,'spa','Masai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (273,'spa','Malay');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (274,'spa','Moksha');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (275,'spa','Mandar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (276,'spa','Mende');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (277,'spa','Irish, Middle (900-1200)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (278,'spa','Mi''kmaq; Micmac');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (279,'spa','Minangkabau');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (280,'spa','Miscellaneous languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (281,'spa','Mon-Khmer (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (282,'spa','Malagasy');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (283,'spa','Maltese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (284,'spa','Manchu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (285,'spa','Manipuri');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (286,'spa','Manobo languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (287,'spa','Mohawk');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (288,'spa','Moldavian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (289,'spa','Mongolian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (290,'spa','Mossi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (291,'spa','Multiple languages)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (292,'spa','Munda languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (293,'spa','Creek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (294,'spa','Mirandese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (295,'spa','Marwari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (296,'spa','Mayan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (297,'spa','Erzya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (298,'spa','Nahuatl languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (299,'spa','North American Indian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (300,'spa','Neapolitan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (301,'spa','Nauru');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (302,'spa','Navajo; Navaho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (303,'spa','Ndebele, South; South Ndebele');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (304,'spa','Ndebele, North; North Ndebele');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (305,'spa','Ndonga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (306,'spa','Low German; Low Saxon; German, Low; Sa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (307,'spa','Nepali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (308,'spa','Nepal Bhasa; Newari');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (309,'spa','Nias');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (310,'spa','Niger-Kordofanian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (311,'spa','Niuean');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (312,'spa','Norwegian Nynorsk; Nynorsk, Norwegian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (313,'spa','Bokmål, Norwegian; Norwegian Bokmål');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (314,'spa','Nogai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (315,'spa','Norse, Old');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (316,'spa','Norwegian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (317,'spa','Pedi; Sepedi; Northern Sotho');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (318,'spa','Nubian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (319,'spa','Classical Newari; Old Newari; Classica');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (320,'spa','Chichewa; Chewa; Nyanja');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (321,'spa','Nyamwezi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (322,'spa','Nyankole');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (323,'spa','Nyoro');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (324,'spa','Nzima');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (325,'spa','Occitan (post 1500); Provençal');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (326,'spa','Ojibwa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (327,'spa','Oriya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (328,'spa','Oromo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (329,'spa','Osage');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (330,'spa','Ossetian; Ossetic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (331,'spa','Turkish, Ottoman (1500-1928)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (332,'spa','Otomian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (333,'spa','Papuan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (334,'spa','Pangasinan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (335,'spa','Pahlavi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (336,'spa','Pampanga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (337,'spa','Panjabi; Punjabi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (338,'spa','Papiamento');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (339,'spa','Palauan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (340,'spa','Persian, Old (ca.600-400 B.C.)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (341,'spa','Persian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (342,'spa','Philippine (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (343,'spa','Phoenician');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (344,'spa','Pali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (345,'spa','Polish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (346,'spa','Pohnpeian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (347,'spa','Portuguese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (348,'spa','Prakrit languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (349,'spa','Provençal, Old (to 1500)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (350,'spa','Pushto');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (351,'spa','Reserved for local use');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (352,'spa','Quechua');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (353,'spa','Rajasthani');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (354,'spa','Rapanui');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (355,'spa','Rarotongan; Cook Islands Maori');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (356,'spa','Romance (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (357,'spa','Romansh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (358,'spa','Romany');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (359,'spa','Romanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (360,'spa','Rundi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (361,'spa','Aromanian; Arumanian; Macedo-Romanian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (362,'spa','Russian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (363,'spa','Sandawe');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (364,'spa','Sango');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (365,'spa','Yakut');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (366,'spa','South American Indian (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (367,'spa','Salishan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (368,'spa','Samaritan Aramaic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (369,'spa','Sanskrit');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (370,'spa','Sasak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (371,'spa','Santali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (372,'spa','Serbian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (373,'spa','Sicilian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (374,'spa','Scots');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (375,'spa','Croatian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (376,'spa','Selkup');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (377,'spa','Semitic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (378,'spa','Irish, Old (to 900)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (379,'spa','Sign Languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (380,'spa','Shan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (381,'spa','Sidamo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (382,'spa','Sinhala; Sinhalese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (383,'spa','Siouan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (384,'spa','Sino-Tibetan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (385,'spa','Slavic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (386,'spa','Slovak');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (387,'spa','Slovenian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (388,'spa','Southern Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (389,'spa','Northern Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (390,'spa','Sami languages (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (391,'spa','Lule Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (392,'spa','Inari Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (393,'spa','Samoan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (394,'spa','Skolt Sami');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (395,'spa','Shona');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (396,'spa','Sindhi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (397,'spa','Soninke');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (398,'spa','Sogdian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (399,'spa','Somali');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (400,'spa','Songhai languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (401,'spa','Sotho, Southern');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (402,'spa','Spanish; Castilian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (403,'spa','Sardinian; Zazaki');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (404,'spa','Sranan Tongo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (405,'spa','Serer');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (406,'spa','Nilo-Saharan (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (407,'spa','Swati');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (408,'spa','Sukuma');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (409,'spa','Sundanese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (410,'spa','Susu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (411,'spa','Sumerian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (412,'spa','Swahili');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (413,'spa','Swedish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (414,'spa','Syriac');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (415,'spa','Tahitianre)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (416,'spa','Tai (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (417,'spa','Tamil');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (418,'spa','Tatar');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (419,'spa','Telugu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (420,'spa','Timne');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (421,'spa','Tereno');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (422,'spa','Tetum');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (423,'spa','Tajik');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (424,'spa','Tagalog');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (425,'spa','Thai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (426,'spa','Tibetan');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (427,'spa','Tigre');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (428,'spa','Tigrinya');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (429,'spa','Tiv');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (430,'spa','Tokelau');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (431,'spa','Klingon; tlhIngan-Hol');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (432,'spa','Tlingit');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (433,'spa','Tamashek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (434,'spa','Tonga (Nyasa)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (435,'spa','Tonga (Tonga Islands)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (436,'spa','Tok Pisin');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (437,'spa','Tsimshian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (438,'spa','Tswana');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (439,'spa','Tsonga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (440,'spa','Turkmen');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (441,'spa','Tumbuka');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (442,'spa','Tupi languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (443,'spa','Turkish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (444,'spa','Altaic (Other)');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (445,'spa','Tuvalu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (446,'spa','Twi');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (447,'spa','Tuvinian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (448,'spa','Udmurt');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (449,'spa','Ugaritic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (450,'spa','Uighur; Uyghur');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (451,'spa','Ukrainian');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (452,'spa','Umbundu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (453,'spa','Undetermined');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (454,'spa','Urdu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (455,'spa','Uzbek');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (456,'spa','Vai');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (457,'spa','Venda');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (458,'spa','Vietnamese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (459,'spa','Volapük');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (460,'spa','Votic');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (461,'spa','Wakashan languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (462,'spa','Walamo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (463,'spa','Waray');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (464,'spa','Washo');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (465,'spa','Welsh');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (466,'spa','Sorbian languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (467,'spa','Walloon');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (468,'spa','Wolof');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (469,'spa','Kalmyk; Oirat');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (470,'spa','Xhosa');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (471,'spa','Yao');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (472,'spa','Yapese');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (473,'spa','Yiddish');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (474,'spa','Yoruba');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (475,'spa','Yupik languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (476,'spa','Zapotec');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (477,'spa','Zenaga');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (478,'spa','Zhuang; Chuang');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (479,'spa','Zande languages');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (480,'spa','Zulu');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (481,'spa','Zuni');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (482,'spa','No linguistic content');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (483,'spa','N''Ko');
INSERT INTO IsoLanguagesDes  (iddes, langid, label) VALUES (484,'spa','Zaza; Dimili; Dimli; Kirdki; Kirmanjki');

INSERT INTO OperationsDes  (iddes, langid, label) VALUES (0,'spa','Publicar');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (1,'spa','Descargar');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (2,'spa','Editar');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (3,'spa','Notificar');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (5,'spa','Mapa interactivo');
INSERT INTO OperationsDes  (iddes, langid, label) VALUES (6,'spa','Featured');

INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (0,'spa','Unknown');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (1,'spa','Borrador');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (2,'spa','Aprobado');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (3,'spa','Retirado');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (4,'spa','Enviado');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (5,'spa','Rechazado');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (50,'spa','Record created.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (51,'spa','Record updated.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (52,'spa','Attachment {{h.item1}} added.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (53,'spa','Attachment {{h.item1}} deleted.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (54,'spa','Owner changed from {{h.item1}} to {{h.item2}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (55,'spa','Group owner changed from {{h.item1}} to {{h.item2}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (56,'spa','Privileges updated.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (57,'spa','Category changed. Now categories are {{h.item1}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (58,'spa','Validation triggered. Exit status is now {{h.item1}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (59,'spa','Status changed from {{h.item1}} to {{h.item2}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (60,'spa','Record updated by process {{h.item1}}.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (61,'spa','Record deleted.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (62,'spa','Record imported.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (63,'spa','Record restored.');
INSERT INTO StatusValuesDes  (iddes, langid, label) VALUES (100,'spa','DOI creation requested.');

INSERT INTO SelectionsDes (iddes, langid, label) VALUES (0,'spa','Preferred records');
INSERT INTO SelectionsDes (iddes, langid, label) VALUES (1,'spa','Watch list');

INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (-1,'spa', 'Average');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (0,'spa', 'Completeness#Is the information on this page complete enough to know what you can expect from this dataset?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (1,'spa', 'Discoverability#Was it easy to find this information page?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (2,'spa', 'Readability#Was it easy to read and understand the contents of this page?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (3,'spa', 'Data quality#Does the dataset contain the information you expected, the dataset has enough accuracy, the data is valid/up-to-date?');
INSERT INTO GUF_RatingCriteriaDes (iddes, langid, label) VALUES (4,'spa', 'Service quality#The dataset is provided as a service or mediatype that is easy to work with?');
