opendal.scheme=${OPENDAL_SCHEME:#{null}}
opendal.root=${OPENDAL_ROOT:/}

# S3 or other service options
opendal.endpoint=${OPENDAL_ENDPOINT:#{null}}
opendal.bucket=${OPENDAL_BUCKET:#{null}}
opendal.access_key_id=${OPENDAL_ACCESS_KEY_ID:#{null}}
opendal.secret_access_key=${OPENDAL_SECRET_ACCESS_KEY:#{null}}
opendal.region=${OPENDAL_REGION:#{null}}
opendal.username=${OPENDAL_USERNAME:#{null}}
opendal.password=${OPENDAL_PASSWORD:#{null}}
